-- =============================================================================
-- 40 Hadith Nawawi — Hadith 27: "Righteousness (birr) is good character"
-- Target collection: public.hadith_collections.id = 2  /  position = 27
-- Idempotent guard on (collection, position). All 11 content languages.
-- Includes both narrations: an-Nawwas (Muslim) and Wabisa (Ahmad/ad-Darimi).
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Righteousness is good character',
  'La piété génère le noble caractère',
  'البر حسن الخلق',
  'Frömmigkeit ist guter Charakter',
  'Vroomheid is goed karakter',
  'İyilik güzel ahlaktır',
  'Kebajikan adalah akhlak yang baik',
  'نیکی حسنِ اخلاق ہے',
  'সৎকর্ম হলো সচ্চরিত্র',
  'Kebajikan ialah akhlak yang baik',
  'Благочестие — это благой нрав',
  -- arabic_text (both narrations)
  'عَنِ النَّوَّاسِ بْنِ سَمْعَانَ رَضِيَ اللَّهُ عَنْهُ عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ: «الْبِرُّ حُسْنُ الْخُلُقِ، وَالْإِثْمُ مَا حَاكَ فِي نَفْسِكَ وَكَرِهْتَ أَنْ يَطَّلِعَ عَلَيْهِ النَّاسُ». رَوَاهُ مُسْلِمٌ. وَعَنْ وَابِصَةَ بْنِ مَعْبَدٍ رَضِيَ اللَّهُ عَنْهُ قَالَ: أَتَيْتُ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَقَالَ: «جِئْتَ تَسْأَلُ عَنِ الْبِرِّ؟» قُلْتُ: نَعَمْ. قَالَ: «اسْتَفْتِ قَلْبَكَ؛ الْبِرُّ مَا اطْمَأَنَّتْ إِلَيْهِ النَّفْسُ وَاطْمَأَنَّ إِلَيْهِ الْقَلْبُ، وَالْإِثْمُ مَا حَاكَ فِي النَّفْسِ وَتَرَدَّدَ فِي الصَّدْرِ، وَإِنْ أَفْتَاكَ النَّاسُ وَأَفْتَوْكَ»',
  -- transcription
  'ʿani n-Nawwāsi bni Samʿāna raḍiya Llāhu ʿanhu ʿani n-Nabiyyi ṣalla Llāhu ʿalayhi wa-sallama qāla: al-birru ḥusnu l-khuluqi, wa-l-ithmu mā ḥāka fī nafsika wa-karihta an yaṭṭaliʿa ʿalayhi n-nāsu. rawāhu Muslimun. wa-ʿan Wābiṣata bni Maʿbadin raḍiya Llāhu ʿanhu qāla: ataytu Rasūla Llāhi ṣalla Llāhu ʿalayhi wa-sallama fa-qāla: jiʾta tasʾalu ʿani l-birri? qultu: naʿam. qāla: istafti qalbaka; al-birru mā ṭmaʾannat ilayhi n-nafsu wa-ṭmaʾanna ilayhi l-qalbu, wa-l-ithmu mā ḥāka fi n-nafsi wa-taraddada fi ṣ-ṣadri, wa-in aftāka n-nāsu wa-aftawka.',
  'ʿani n-Nawwâsi bni Samʿâna (radia Llâhou ʿanhou) ʿani n-Nabiyyi (salla Llâhou ʿalayhi wa sallam) qâla : al-birrou housnou l-khouluqi, wa l-ithmou mâ hâka fî nafsika wa karihta an yattaliʿa ʿalayhi n-nâsou. rawâhou Mouslimoun. wa ʿan Wâbisata bni Maʿbadin (radia Llâhou ʿanhou) qâla : ataytou Rassôla Llâhi (salla Llâhou ʿalayhi wa sallam) fa-qâla : jiʾta tasʾalou ʿani l-birri ? qoultou : naʿam. qâla : istafti qalbaka ; al-birrou mâ tmaʾannat ilayhi n-nafsou wa tmaʾanna ilayhi l-qalbou, wa l-ithmou mâ hâka fi n-nafsi wa taraddada fi s-sadri, wa in aftâka n-nâsou wa aftawka.',
  'ʿani n-Nawwāsi bni Samʿāna (radiya Llāhu ʿanhu) ʿani n-Nabijji (salla Llāhu ʿalaihi wa-sallam) qāla: al-birru husnu l-chuluqi, wa-l-ithmu mā hāka fī nafsika wa-karihta an jattaliʿa ʿalaihi n-nāsu. rawāhu Muslimun. wa-ʿan Wābisata bni Maʿbadin (radiya Llāhu ʿanhu) qāla: ataitu Rasūla Llāhi (salla Llāhu ʿalaihi wa-sallam) fa-qāla: dschiʾta tasʾalu ʿani l-birri? qultu: naʿam. qāla: istafti qalbaka; al-birru mā tmaʾannat ilaihi n-nafsu wa-tmaʾanna ilaihi l-qalbu, wa-l-ithmu mā hāka fi n-nafsi wa-taraddada fi s-sadri, wa-in aftāka n-nāsu wa-aftauka.',
  'ʿani n-Nawwaasi bni Samʿaana (radia Llaahoe ʿanhoe) ʿani n-Nabijji (salla Llaahoe ʿalaihi wa-sallam) qaala: al-birroe hoesnoe l-choeloeqi, wa-l-ithmoe maa haaka fie nafsika wa-karihta an jattaliʿa ʿalaihi n-naasoe. rawaahoe Moeslimoen. wa-ʿan Waabisata bni Maʿbadin (radia Llaahoe ʿanhoe) qaala: ataitoe Rasoela Llaahi (salla Llaahoe ʿalaihi wa-sallam) fa-qaala: dzjiʾta tasʾaloe ʿani l-birri? qoeltoe: naʿam. qaala: istafti qalbaka; al-birroe maa tmaʾannat ilaihi n-nafsoe wa-tmaʾanna ilaihi l-qalboe, wa-l-ithmoe maa haaka fi n-nafsi wa-taraddada fi s-sadri, wa-in aftaaka n-naasoe wa-aftauka.',
  'an Nevvâs ibn Semʿân''dan (radıyallâhu anh), Nebî''den (s.a.v.) rivayetle buyurdu: el-birru husnu''l-huluk, ve''l-ismu mâ hâke fî nefsike ve kerihte en yattaliʿa aleyhi''n-nâs. Müslim rivayet etti. Ve Vâbisa ibn Maʿbed''den (radıyallâhu anh): Resûlullah''a (s.a.v.) geldim, buyurdu: birri sormaya mı geldin? Evet, dedim. Buyurdu: kalbine danış; birr, nefsin ve kalbin kendisine yatıştığı şeydir; ism (günah) ise, nefiste tereddüt uyandıran ve göğüste şüphe doğuran şeydir, insanlar sana fetva verseler de.',
  'an an-Nawwas bin Samʿan (radhiyallahu ʿanhu), dari Nabi (shallallahu ʿalaihi wa sallam) bersabda: al-birru husnul-khuluq, wal-itsmu ma haka fi nafsika wa karihta an yaththaliʿa ʿalaihin-nas. Diriwayatkan oleh Muslim. Dan dari Wabishah bin Maʿbad (radhiyallahu ʿanhu) berkata: aku mendatangi Rasulullah (shallallahu ʿalaihi wa sallam), lalu beliau bersabda: engkau datang untuk bertanya tentang kebajikan? Aku menjawab: ya. Beliau bersabda: mintalah fatwa kepada hatimu; kebajikan adalah apa yang menenangkan jiwa dan menenangkan hati, dan dosa adalah apa yang mengganjal di jiwa dan meragukan di dada, meskipun orang-orang memberimu fatwa.',
  'نواس بن سمعان رضی اللہ عنہ سے، نبی صلی اللہ علیہ وسلم سے روایت ہے کہ آپ نے فرمایا: البِرُّ حُسنُ الخُلُقِ، وَالاِثمُ ما حاکَ فی نَفسِکَ وَکَرِہتَ اَن یَطَّلِعَ عَلَیہِ النّاسُ۔ اسے مسلم نے روایت کیا۔ اور وابصہ بن معبد رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: میں رسول اللہ صلی اللہ علیہ وسلم کے پاس آیا تو آپ نے فرمایا: تم نیکی کے بارے میں پوچھنے آئے ہو؟ میں نے کہا: جی ہاں۔ فرمایا: اپنے دل سے فتویٰ پوچھو؛ نیکی وہ ہے جس پر نفس مطمئن ہو اور دل کو سکون ملے، اور گناہ وہ ہے جو دل میں کھٹکے اور سینے میں تردد پیدا کرے، اگرچہ لوگ تمہیں فتویٰ دیں۔',
  'নাওয়াস ইবনে সামআন (রাদিয়াল্লাহু আনহু) থেকে, নবী (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) থেকে বর্ণিত, তিনি বলেছেন: আল-বিররু হুসনুল খুলুক, ওয়াল ইসমু মা হাকা ফী নাফসিকা ওয়া কারিহতা আন ইয়াত্তালিআ আলাইহিন নাস। মুসলিম এটি বর্ণনা করেছেন। আর ওয়াবিসা ইবনে মাবাদ (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: আমি রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম)-এর নিকট এলাম, তিনি বললেন: তুমি কি সৎকর্ম সম্পর্কে জিজ্ঞাসা করতে এসেছ? আমি বললাম: হ্যাঁ। তিনি বললেন: তোমার অন্তরের কাছে ফতোয়া চাও; সৎকর্ম হলো যাতে অন্তর প্রশান্তি পায় ও হৃদয় স্বস্তি পায়, আর পাপ হলো যা অন্তরে খটকা লাগায় ও বুকে দ্বিধা সৃষ্টি করে, যদিও মানুষ তোমাকে ফতোয়া দেয়।',
  'an an-Nawwas bin Samʿan (radhiallahu ʿanhu), daripada Nabi (sallallahu ʿalaihi wa sallam) bersabda: al-birru husnul-khuluq, wal-itsmu ma haka fi nafsika wa karihta an yaththaliʿa ʿalaihin-nas. Diriwayatkan oleh Muslim. Dan daripada Wabisah bin Maʿbad (radhiallahu ʿanhu) berkata: aku mendatangi Rasulullah (sallallahu ʿalaihi wa sallam), lalu baginda bersabda: engkau datang untuk bertanya tentang kebajikan? Aku menjawab: ya. Baginda bersabda: mintalah fatwa kepada hatimu; kebajikan ialah apa yang menenangkan jiwa dan menenangkan hati, dan dosa ialah apa yang mengganjal di jiwa dan meragukan di dada, walaupun orang ramai memberimu fatwa.',
  'От ан-Навваса ибн Самана (да будет доволен им Аллах), от Пророка ﷺ передаётся, что он сказал: аль-бирру хусну ль-хулюк, валь-исму ма хака фи нафсика ва карихта ан яттали‘а ‘аляйхи н-нас. Передал Муслим. И от Вабисы ибн Мабада (да будет доволен им Аллах) передаётся: я пришёл к Посланнику Аллаха ﷺ, и он сказал: ты пришёл спросить о благочестии? Я сказал: да. Он сказал: спроси своё сердце; благочестие — это то, к чему успокаивается душа и успокаивается сердце, а грех — это то, что тревожит душу и колеблется в груди, даже если люди дадут тебе фетву.',
  -- translation
  'On the authority of an-Nawwas ibn Samʿan (may Allah be pleased with him), from the Prophet ﷺ, who said: "Righteousness (birr) is good character, and sin is what wavers in your soul and which you dislike people to discover about you." Reported by Muslim. And on the authority of Wabisa ibn Maʿbad (may Allah be pleased with him), who said: I came to the Messenger of Allah ﷺ and he said: "You have come to ask about righteousness?" I said: "Yes." He said: "Consult your heart. Righteousness is that with which the soul is at ease and the heart is at peace; and sin is that which wavers in the soul and causes hesitation in the breast, even if people give you their opinion (fatwa) again and again."',
  'D''après An-Nawwâs ibn Samʿân (qu''Allah l''agrée), le Prophète ﷺ a dit : « La piété (birr) consiste en la bonne moralité, et le péché est ce qui trouble ton âme et qu''il te répugne que les gens découvrent en toi. » Rapporté par Muslim. Et d''après Wâbisa ibn Maʿbad (qu''Allah l''agrée) : Je me rendis auprès de l''Envoyé d''Allah ﷺ et il me dit : « Tu es venu m''interroger sur la piété ? » Je dis : « Oui. » Il dit : « Consulte ton cœur : la piété est ce dans quoi l''âme et le cœur trouvent leur quiétude ; et le péché est ce qui tourmente l''âme et met la poitrine dans l''hésitation, quoique les gens te donnent leur avis (fatwa) et insistent dessus. »',
  'Nach an-Nawwas ibn Samʿan (möge Allah mit ihm zufrieden sein), vom Propheten ﷺ, der sagte: „Die Frömmigkeit (Birr) ist guter Charakter, und die Sünde ist das, was in deiner Seele schwankt und von dem es dir zuwider ist, dass die Menschen es an dir entdecken." Überliefert von Muslim. Und nach Wabisa ibn Maʿbad (möge Allah mit ihm zufrieden sein): Ich kam zum Gesandten Allahs ﷺ und er sagte: „Du bist gekommen, um nach der Frömmigkeit zu fragen?" Ich sagte: „Ja." Er sagte: „Befrage dein Herz. Die Frömmigkeit ist das, womit die Seele zur Ruhe kommt und das Herz Frieden findet; und die Sünde ist das, was in der Seele schwankt und in der Brust Zögern verursacht, auch wenn die Menschen dir immer wieder ihre Meinung (Fatwa) geben."',
  'Op gezag van an-Nawwas ibn Samʿan (moge Allah tevreden met hem zijn), van de Profeet ﷺ, die zei: „De vroomheid (birr) is goed karakter, en de zonde is wat in je ziel weifelt en waarvan het je tegenstaat dat de mensen het bij jou ontdekken." Overgeleverd door Muslim. En op gezag van Wabisa ibn Maʿbad (moge Allah tevreden met hem zijn): Ik kwam bij de Boodschapper van Allah ﷺ en hij zei: „Je bent gekomen om naar de vroomheid te vragen?" Ik zei: „Ja." Hij zei: „Raadpleeg je hart. De vroomheid is dat waarmee de ziel gerust is en het hart vrede vindt; en de zonde is dat wat in de ziel weifelt en in de borst aarzeling veroorzaakt, ook al geven de mensen je telkens weer hun oordeel (fatwa)."',
  'Nevvâs ibn Semʿân''dan (Allah ondan razı olsun), Nebî''den ﷺ rivayetle buyurdu: „İyilik (birr) güzel ahlaktır; günah ise nefsinde tereddüt uyandıran ve insanların senin hakkında bilmesinden hoşlanmadığın şeydir." Müslim rivayet etti. Vâbisa ibn Maʿbed''den (Allah ondan razı olsun): Resûlullah''a ﷺ geldim, buyurdu: „İyiliği sormaya mı geldin?" „Evet" dedim. Buyurdu: „Kalbine danış. İyilik, nefsin ve kalbin kendisine yatıştığı şeydir; günah ise nefiste tereddüt uyandıran ve göğüste şüphe doğuran şeydir, insanlar sana defalarca fetva verseler de."',
  'Dari an-Nawwas bin Samʿan (semoga Allah meridhainya), dari Nabi ﷺ, beliau bersabda: "Kebajikan (birr) adalah akhlak yang baik, dan dosa adalah apa yang mengganjal dalam jiwamu dan engkau tidak suka orang-orang mengetahuinya darimu." Diriwayatkan oleh Muslim. Dan dari Wabishah bin Maʿbad (semoga Allah meridhainya), ia berkata: Aku mendatangi Rasulullah ﷺ, lalu beliau bersabda: "Engkau datang untuk bertanya tentang kebajikan?" Aku menjawab: "Ya." Beliau bersabda: "Mintalah fatwa kepada hatimu. Kebajikan adalah apa yang menenangkan jiwa dan menenangkan hati; dan dosa adalah apa yang mengganjal dalam jiwa dan meragukan dalam dada, meskipun orang-orang memberimu fatwa berulang kali."',
  'نواس بن سمعان رضی اللہ عنہ سے، نبی ﷺ سے روایت ہے کہ آپ نے فرمایا: ”نیکی (بِرّ) حسنِ اخلاق ہے، اور گناہ وہ ہے جو تیرے دل میں کھٹکے اور تو ناپسند کرے کہ لوگ اس پر مطلع ہوں۔“ اسے مسلم نے روایت کیا۔ اور وابصہ بن معبد رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: میں رسول اللہ ﷺ کے پاس آیا تو آپ نے فرمایا: ”تم نیکی کے بارے میں پوچھنے آئے ہو؟“ میں نے کہا: ”جی ہاں۔“ فرمایا: ”اپنے دل سے فتویٰ پوچھو۔ نیکی وہ ہے جس پر نفس مطمئن ہو اور دل کو سکون ملے؛ اور گناہ وہ ہے جو نفس میں کھٹکے اور سینے میں تردد پیدا کرے، اگرچہ لوگ تمہیں بار بار فتویٰ دیں۔“',
  'নাওয়াস ইবনে সামআন (রাদিয়াল্লাহু আনহু) থেকে, নবী ﷺ থেকে বর্ণিত, তিনি বলেছেন: "সৎকর্ম (বির্র) হলো সচ্চরিত্র, আর পাপ হলো যা তোমার অন্তরে খটকা লাগায় এবং তুমি অপছন্দ করো যে মানুষ তা সম্পর্কে অবগত হোক।" মুসলিম এটি বর্ণনা করেছেন। আর ওয়াবিসা ইবনে মাবাদ (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: আমি রাসূলুল্লাহ ﷺ-এর নিকট এলাম, তিনি বললেন: "তুমি কি সৎকর্ম সম্পর্কে জিজ্ঞাসা করতে এসেছ?" আমি বললাম: "হ্যাঁ।" তিনি বললেন: "তোমার অন্তরের কাছে ফতোয়া চাও। সৎকর্ম হলো যাতে আত্মা প্রশান্তি পায় ও হৃদয় স্বস্তি পায়; আর পাপ হলো যা আত্মায় খটকা লাগায় ও বুকে দ্বিধা সৃষ্টি করে, যদিও মানুষ তোমাকে বারবার ফতোয়া দেয়।"',
  'Daripada an-Nawwas bin Samʿan (semoga Allah meredainya), daripada Nabi ﷺ, baginda bersabda: "Kebajikan (birr) ialah akhlak yang baik, dan dosa ialah apa yang mengganjal dalam jiwamu dan engkau tidak suka orang ramai mengetahuinya daripadamu." Diriwayatkan oleh Muslim. Dan daripada Wabisah bin Maʿbad (semoga Allah meredainya), dia berkata: Aku mendatangi Rasulullah ﷺ, lalu baginda bersabda: "Engkau datang untuk bertanya tentang kebajikan?" Aku menjawab: "Ya." Baginda bersabda: "Mintalah fatwa kepada hatimu. Kebajikan ialah apa yang menenangkan jiwa dan menenangkan hati; dan dosa ialah apa yang mengganjal dalam jiwa dan meragukan dalam dada, walaupun orang ramai memberimu fatwa berulang kali."',
  'От ан-Навваса ибн Самана (да будет доволен им Аллах), от Пророка ﷺ, который сказал: «Благочестие (бирр) — это благой нрав, а грех — это то, что колеблется в твоей душе и что тебе неприятно, чтобы люди обнаружили это в тебе». Передал Муслим. И от Вабисы ибн Мабада (да будет доволен им Аллах): Я пришёл к Посланнику Аллаха ﷺ, и он сказал: «Ты пришёл спросить о благочестии?» Я сказал: «Да». Он сказал: «Спроси своё сердце. Благочестие — это то, к чему успокаивается душа и успокаивается сердце; а грех — это то, что тревожит душу и колеблется в груди, даже если люди дают тебе фетву снова и снова».',
  -- reference
  'Hasan/Sahih — the first narration reported by Muslim (4/1980, no. 2553); the second by Ahmad (4/228) and ad-Darimi (2/2533) with a good chain (graded hasan)',
  'Hasan/Sahih — la première version rapportée par Muslim (4/1980, n°2553) ; la seconde par Ahmad (4/228) et ad-Dârimî (2/2533) avec une bonne chaîne (hasan)',
  'حديث حسن/صحيح، رواه الأول مسلم (٤/١٩٨٠) (رقم ٢٥٥٣)، والثاني أحمد (٤/٢٢٨) والدارمي (٢/٢٥٣٣) بإسناد حسن',
  'Hasan/Sahih — die erste Überlieferung von Muslim (4/1980, Nr. 2553); die zweite von Ahmad (4/228) und ad-Darimi (2/2533) mit guter Kette (hasan)',
  'Hasan/Sahih — de eerste overlevering door Muslim (4/1980, nr. 2553); de tweede door Ahmad (4/228) en ad-Darimi (2/2533) met een goede keten (hasan)',
  'Hasen/Sahih — ilk rivayet Müslim (4/1980, no. 2553); ikincisi Ahmed (4/228) ve Dârimî (2/2533) tarafından hasen senedle rivayet edilmiştir',
  'Hasan/Sahih — riwayat pertama oleh Muslim (4/1980, no. 2553); yang kedua oleh Ahmad (4/228) dan ad-Darimi (2/2533) dengan sanad hasan',
  'حسن/صحیح حدیث — پہلی روایت مسلم (۴/۱۹۸۰، نمبر ۲۵۵۳)؛ دوسری احمد (۴/۲۲۸) اور دارمی (۲/۲۵۳۳) نے حسن سند سے روایت کی',
  'হাসান/সহীহ হাদীস — প্রথম বর্ণনা মুসলিম (৪/১৯৮০, নং ২৫৫৩); দ্বিতীয়টি আহমাদ (৪/২২৮) ও দারিমী (২/২৫৩৩) হাসান সনদে বর্ণনা করেছেন',
  'Hasan/Sahih — riwayat pertama oleh Muslim (4/1980, no. 2553); yang kedua oleh Ahmad (4/228) dan ad-Darimi (2/2533) dengan sanad hasan',
  'Хасан/сахих — первая версия передана Муслимом (4/1980, № 2553); вторая — Ахмадом (4/228) и ад-Дарими (2/2533) с хорошим иснадом (хасан)',
  -- tafsir
  '• The merit of good character, which the Prophet ﷺ made equivalent to righteousness (birr).\n• The sign by which one knows that something is a sin is that it troubles the conscience and the soul does not find ease in it.\n• The believer is one who dislikes that people become aware of his faults, unlike the corrupt person who does not care.\n• The discernment (firasa) of the Prophet ﷺ, who, before Wabisa said anything, preceded him with the words: "You have come to ask about righteousness."\n• The permissibility of referring the ruling on a matter to the tranquil soul, which detests evil and loves good.\n• A person should consult his own soul rather than rely solely on the verdicts of common people, for some of those without religious knowledge may give him a verdict that his soul struggles to accept; in such a case he defers to the judgement of his conscience.\n• Where independent reasoning (ijtihad) to seek the truth is possible, it should not be forsaken in favour of blind imitation (taqlid); the Prophet ﷺ said: "even if people give you their verdict (fatwa) and insist upon it."',
  '• Le mérite de la bonne moralité, que le Prophète ﷺ a rendue équivalente à la piété (birr).\n• Le repère qui permet de savoir qu''une chose est un péché, c''est qu''elle tourmente la conscience et que l''âme n''y trouve pas sa quiétude.\n• Le croyant est celui qui n''aime pas que les gens soient au courant de ses défauts, contrairement au libertin qui ne s''en soucie pas.\n• La physiognomonie (firâsa) du Prophète ﷺ qui, avant que Wâbisa ne lui dise quoi que ce soit, l''a devancé par cette parole : « Tu es venu m''interroger sur la piété. »\n• La possibilité de déférer le jugement d''une chose à l''âme rassérénée qui déteste le mal et aime le bien.\n• À l''homme de consulter son âme sans s''en remettre aux fatwas du commun des gens, car certains d''entre eux, sans savoir religieux, peuvent lui donner une réponse que son âme a du mal à accepter ; dans ce cas, il s''en remet au jugement de sa conscience.\n• Quand l''effort d''interprétation (ijtihad) pour rechercher la vérité est possible, on ne doit pas s''en passer au profit du conformisme (taqlîd) ; le Prophète ﷺ a dit : « quoique les gens te donnent leur avis (fatwa) et insistent dessus ».',
  '• فضل حسن الخلق، حيث جعله النبي صلى الله عليه وسلم معادلاً للبر.\n• العلامة التي يُعرف بها أن الشيء إثم هي أن يحيك في النفس ولا تطمئن إليه.\n• المؤمن هو الذي يكره أن يطّلع الناس على عيوبه، بخلاف الفاجر الذي لا يبالي.\n• فراسة النبي صلى الله عليه وسلم، الذي سبق وابصة بقوله قبل أن يقول له شيئاً: «جئت تسأل عن البر».\n• جواز رد الحكم في الشيء إلى النفس المطمئنة التي تكره الشر وتحب الخير.\n• على المرء أن يستفتي نفسه ولا يكتفي بفتاوى عامة الناس، فإن بعضهم ممن لا علم له قد يفتيه بما لا تطمئن إليه نفسه، وحينئذ يرجع إلى حكم ضميره.\n• إذا أمكن الاجتهاد في طلب الحق فلا ينبغي تركه إلى التقليد، فقد قال النبي صلى الله عليه وسلم: «وإن أفتاك الناس وأفتوك».',
  '• Der Vorzug des guten Charakters, den der Prophet ﷺ der Frömmigkeit (Birr) gleichsetzte.\n• Das Zeichen, an dem man erkennt, dass etwas eine Sünde ist: dass es das Gewissen beunruhigt und die Seele darin keine Ruhe findet.\n• Der Gläubige ist derjenige, dem es zuwider ist, dass die Menschen seine Fehler erfahren, im Gegensatz zum Lasterhaften, dem es gleichgültig ist.\n• Die Scharfsicht (Firasa) des Propheten ﷺ, der Wabisa, bevor dieser etwas sagte, mit den Worten zuvorkam: „Du bist gekommen, um nach der Frömmigkeit zu fragen."\n• Die Zulässigkeit, das Urteil über eine Sache der ruhigen Seele zu überlassen, die das Böse verabscheut und das Gute liebt.\n• Der Mensch soll seine eigene Seele befragen und sich nicht allein auf die Rechtsauskünfte des gemeinen Volkes verlassen, denn manche ohne religiöses Wissen geben ihm vielleicht eine Antwort, die seine Seele schwer annimmt; in diesem Fall folgt er dem Urteil seines Gewissens.\n• Wo eigenständige Urteilsfindung (Idschtihad) zur Wahrheitssuche möglich ist, sollte sie nicht zugunsten blinder Nachahmung (Taqlid) aufgegeben werden; der Prophet ﷺ sagte: „auch wenn die Menschen dir ihre Auskunft (Fatwa) geben und darauf bestehen."',
  '• De verdienste van het goede karakter, dat de Profeet ﷺ gelijkstelde aan de vroomheid (birr).\n• Het teken waaraan men herkent dat iets een zonde is: dat het het geweten verontrust en de ziel er geen rust in vindt.\n• De gelovige is degene die het tegenstaat dat de mensen zijn gebreken te weten komen, in tegenstelling tot de losbandige die er niet om geeft.\n• Het scherpe inzicht (firasa) van de Profeet ﷺ, die Wabisa, voordat deze iets zei, voorging met de woorden: „Je bent gekomen om naar de vroomheid te vragen."\n• De toelaatbaarheid om het oordeel over een zaak over te laten aan de geruste ziel die het kwaad verafschuwt en het goede liefheeft.\n• De mens moet zijn eigen ziel raadplegen en niet uitsluitend vertrouwen op de uitspraken van het gewone volk, want sommigen zonder religieuze kennis geven hem misschien een antwoord dat zijn ziel moeilijk aanvaardt; in dat geval volgt hij het oordeel van zijn geweten.\n• Waar zelfstandige redenering (ijtihad) om de waarheid te zoeken mogelijk is, mag deze niet worden opgegeven ten gunste van blinde navolging (taqlid); de Profeet ﷺ zei: „ook al geven de mensen je hun oordeel (fatwa) en houden zij erop aan."',
  '• Güzel ahlakın fazileti; Peygamber ﷺ onu birre (iyiliğe) denk kılmıştır.\n• Bir şeyin günah olduğunu gösteren işaret: nefiste tereddüt uyandırması ve nefsin ona yatışmamasıdır.\n• Mümin, insanların ayıplarına muttali olmasından hoşlanmayan kimsedir; aldırmayan fâcirin aksine.\n• Peygamber''in ﷺ firaseti; Vâbisa bir şey söylemeden önce ona: „İyiliği sormaya mı geldin?" diyerek öne geçmiştir.\n• Bir şeyin hükmünü, kötülükten hoşlanmayan ve hayrı seven mutmain nefse havale etmenin câizliği.\n• Kişi nefsine danışmalı, yalnızca avamın fetvalarına dayanmamalıdır; zira ilmi olmayan bazıları ona, nefsinin kabul etmekte zorlandığı bir cevap verebilir; o zaman vicdanının hükmüne döner.\n• Hakkı aramada içtihat mümkünse, taklit uğruna terk edilmemelidir; Peygamber ﷺ: „insanlar sana fetva verseler de" buyurmuştur.',
  '• Keutamaan akhlak yang baik, yang Nabi ﷺ jadikan setara dengan kebajikan (birr).\n• Tanda yang dengannya diketahui bahwa sesuatu itu dosa adalah ia mengganjal di hati dan jiwa tidak tenang terhadapnya.\n• Seorang mukmin adalah orang yang tidak suka orang-orang mengetahui aibnya, berbeda dengan orang fajir yang tidak peduli.\n• Firasat Nabi ﷺ, yang sebelum Wabishah mengatakan sesuatu, beliau mendahuluinya dengan ucapan: "Engkau datang untuk bertanya tentang kebajikan."\n• Bolehnya mengembalikan hukum suatu perkara kepada jiwa yang tenang yang membenci keburukan dan mencintai kebaikan.\n• Hendaklah seseorang meminta fatwa kepada jiwanya dan tidak hanya bersandar pada fatwa orang awam, karena sebagian mereka yang tidak berilmu mungkin memberinya jawaban yang sulit diterima jiwanya; dalam keadaan demikian ia kembali kepada hukum hati nuraninya.\n• Apabila ijtihad untuk mencari kebenaran memungkinkan, hendaknya tidak ditinggalkan demi taklid; Nabi ﷺ bersabda: "meskipun orang-orang memberimu fatwa dan mendesakmu."',
  '• حسنِ اخلاق کی فضیلت، جسے نبی ﷺ نے نیکی (بِرّ) کے برابر قرار دیا۔\n• کسی چیز کے گناہ ہونے کی پہچان یہ ہے کہ وہ دل میں کھٹکے اور نفس اس پر مطمئن نہ ہو۔\n• مومن وہ ہے جو ناپسند کرتا ہے کہ لوگ اس کے عیبوں سے واقف ہوں، اس فاجر کے برعکس جو پروا نہیں کرتا۔\n• نبی ﷺ کی فراست، جنہوں نے وابصہ کے کچھ کہنے سے پہلے ہی فرما دیا: ”تم نیکی کے بارے میں پوچھنے آئے ہو۔“\n• کسی چیز کے حکم کو اس مطمئن نفس کے سپرد کرنے کا جواز جو برائی کو ناپسند اور بھلائی کو پسند کرتی ہے۔\n• آدمی کو اپنے نفس سے فتویٰ پوچھنا چاہیے اور صرف عام لوگوں کے فتووں پر اکتفا نہیں کرنا چاہیے، کیونکہ ان میں سے بعض بے علم لوگ اسے ایسا جواب دے سکتے ہیں جسے اس کا نفس قبول کرنے میں دشواری محسوس کرے؛ ایسی صورت میں وہ اپنے ضمیر کے فیصلے کی طرف رجوع کرے۔\n• جب حق کی تلاش میں اجتہاد ممکن ہو تو اسے تقلید کے بدلے چھوڑنا نہیں چاہیے؛ نبی ﷺ نے فرمایا: ”اگرچہ لوگ تمہیں فتویٰ دیں اور اصرار کریں۔“',
  '• সচ্চরিত্রের ফজিলত, যাকে নবী ﷺ সৎকর্মের (বির্র) সমতুল্য করেছেন।\n• কোনো বিষয় পাপ হওয়ার নিদর্শন হলো তা অন্তরে খটকা লাগায় ও আত্মা তাতে প্রশান্তি পায় না।\n• মুমিন হলো সে যে অপছন্দ করে যে মানুষ তার দোষ সম্পর্কে অবগত হোক, পাপাচারীর বিপরীতে যে পরোয়া করে না।\n• নবী ﷺ-এর অন্তর্দৃষ্টি (ফিরাসা), যিনি ওয়াবিসা কিছু বলার আগেই বলে দিলেন: "তুমি কি সৎকর্ম সম্পর্কে জিজ্ঞাসা করতে এসেছ?"\n• কোনো বিষয়ের বিধান সেই প্রশান্ত আত্মার কাছে সোপর্দ করার বৈধতা যা মন্দকে অপছন্দ করে ও কল্যাণকে ভালোবাসে।\n• মানুষের উচিত নিজের আত্মার কাছে ফতোয়া চাওয়া এবং কেবল সাধারণ মানুষের ফতোয়ার উপর নির্ভর না করা, কারণ তাদের মধ্যে কিছু জ্ঞানহীন ব্যক্তি তাকে এমন উত্তর দিতে পারে যা তার আত্মা গ্রহণ করতে কষ্ট পায়; এমন অবস্থায় সে তার বিবেকের রায়ের দিকে ফিরে যায়।\n• যখন সত্য অন্বেষণে ইজতিহাদ সম্ভব, তখন তা তাকলিদের পরিবর্তে ত্যাগ করা উচিত নয়; নবী ﷺ বলেছেন: "যদিও মানুষ তোমাকে ফতোয়া দেয় ও জোর দেয়।"',
  '• Kelebihan akhlak yang baik, yang Nabi ﷺ jadikan setara dengan kebajikan (birr).\n• Tanda yang dengannya diketahui bahawa sesuatu itu dosa ialah ia mengganjal di hati dan jiwa tidak tenang terhadapnya.\n• Seorang mukmin ialah orang yang tidak suka orang ramai mengetahui aibnya, berbeza dengan orang fajir yang tidak peduli.\n• Firasat Nabi ﷺ, yang sebelum Wabisah mengatakan sesuatu, baginda mendahuluinya dengan ucapan: "Engkau datang untuk bertanya tentang kebajikan."\n• Harusnya mengembalikan hukum sesuatu perkara kepada jiwa yang tenang yang membenci keburukan dan mencintai kebaikan.\n• Hendaklah seseorang meminta fatwa kepada jiwanya dan tidak hanya bersandar pada fatwa orang awam, kerana sebahagian mereka yang tidak berilmu mungkin memberinya jawapan yang sukar diterima jiwanya; dalam keadaan demikian dia kembali kepada hukum hati nuraninya.\n• Apabila ijtihad untuk mencari kebenaran memungkinkan, hendaknya ia tidak ditinggalkan demi taklid; Nabi ﷺ bersabda: "walaupun orang ramai memberimu fatwa dan mendesakmu."',
  '• Достоинство благого нрава, который Пророк ﷺ приравнял к благочестию (бирр).\n• Признак, по которому узнают, что нечто является грехом: оно тревожит совесть, и душа не находит в нём покоя.\n• Верующий — это тот, кому неприятно, чтобы люди узнали о его недостатках, в отличие от нечестивца, которому всё равно.\n• Проницательность (фираса) Пророка ﷺ, который, прежде чем Вабиса что-либо сказал, опередил его словами: «Ты пришёл спросить о благочестии».\n• Дозволенность передавать суждение о чём-либо успокоенной душе, которая ненавидит зло и любит добро.\n• Человеку следует спрашивать собственную душу, а не полагаться лишь на фетвы простых людей, ибо некоторые из них, не имеющие религиозного знания, могут дать ему ответ, который его душа с трудом принимает; в таком случае он обращается к суждению своей совести.\n• Когда возможно самостоятельное усердие (иджтихад) в поиске истины, его не следует оставлять ради слепого подражания (таклид); Пророк ﷺ сказал: «даже если люди дадут тебе фетву и будут настаивать на ней».',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-27-Nawawi-Psalmodie-Arabe.mp3',
  5,
  27
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 27
);
