-- =============================================================================
-- 40 Hadith Nawawi — Hadith 29: "The deeds that admit to Paradise / gates of good"
-- Target collection: public.hadith_collections.id = 2  /  position = 29
-- Idempotent guard on (collection, position). All 11 content languages.
-- tafsir_* intentionally left NULL (no commentary provided for this hadith).
-- Arabic cleaned: بملا ذلك -> بمِلاكِ ذلك، وإنما -> وإنّا.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'The deeds that lead to Paradise',
  'Ce qui fait entrer au paradis',
  'ما يدخل الجنة',
  'Was ins Paradies führt',
  'Wat naar het Paradijs leidt',
  'Cennete götüren ameller',
  'Amal yang memasukkan ke surga',
  'جنت میں داخل کرنے والے اعمال',
  'যা জান্নাতে প্রবেশ করায়',
  'Amalan yang memasukkan ke syurga',
  'То, что вводит в Рай',
  -- arabic_text (cleaned)
  'عَنْ مُعَاذِ بْنِ جَبَلٍ رَضِيَ اللَّهُ عَنْهُ قَالَ: قُلْتُ: يَا رَسُولَ اللَّهِ، أَخْبِرْنِي بِعَمَلٍ يُدْخِلُنِي الْجَنَّةَ وَيُبَاعِدُنِي عَنِ النَّارِ. قَالَ: «لَقَدْ سَأَلْتَ عَنْ عَظِيمٍ، وَإِنَّهُ لَيَسِيرٌ عَلَى مَنْ يَسَّرَهُ اللَّهُ عَلَيْهِ: تَعْبُدُ اللَّهَ لَا تُشْرِكُ بِهِ شَيْئًا، وَتُقِيمُ الصَّلَاةَ، وَتُؤْتِي الزَّكَاةَ، وَتَصُومُ رَمَضَانَ، وَتَحُجُّ الْبَيْتَ». ثُمَّ قَالَ: «أَلَا أَدُلُّكَ عَلَى أَبْوَابِ الْخَيْرِ؟ الصَّوْمُ جُنَّةٌ، وَالصَّدَقَةُ تُطْفِئُ الْخَطِيئَةَ كَمَا يُطْفِئُ الْمَاءُ النَّارَ، وَصَلَاةُ الرَّجُلِ فِي جَوْفِ اللَّيْلِ». ثُمَّ تَلَا: {تَتَجَافَى جُنُوبُهُمْ عَنِ الْمَضَاجِعِ} حَتَّى بَلَغَ {يَعْمَلُونَ}. ثُمَّ قَالَ: «أَلَا أُخْبِرُكَ بِرَأْسِ الْأَمْرِ وَعَمُودِهِ وَذِرْوَةِ سَنَامِهِ؟» قُلْتُ: بَلَى يَا رَسُولَ اللَّهِ. قَالَ: «رَأْسُ الْأَمْرِ الْإِسْلَامُ، وَعَمُودُهُ الصَّلَاةُ، وَذِرْوَةُ سَنَامِهِ الْجِهَادُ». ثُمَّ قَالَ: «أَلَا أُخْبِرُكَ بِمِلَاكِ ذَلِكَ كُلِّهِ؟» فَقُلْتُ: بَلَى يَا رَسُولَ اللَّهِ. فَأَخَذَ بِلِسَانِهِ وَقَالَ: «كُفَّ عَلَيْكَ هَذَا». قُلْتُ: يَا نَبِيَّ اللَّهِ، وَإِنَّا لَمُؤَاخَذُونَ بِمَا نَتَكَلَّمُ بِهِ؟ فَقَالَ: «ثَكِلَتْكَ أُمُّكَ، وَهَلْ يَكُبُّ النَّاسَ فِي النَّارِ عَلَى وُجُوهِهِمْ — أَوْ قَالَ: عَلَى مَنَاخِرِهِمْ — إِلَّا حَصَائِدُ أَلْسِنَتِهِمْ؟»',
  -- transcription
  'ʿan Muʿādhi bni Jabalin raḍiya Llāhu ʿanhu qāla: qultu: yā Rasūla Llāhi, akhbirnī bi-ʿamalin yudkhilunī l-jannata wa-yubāʿidunī ʿani n-nāri. qāla: laqad saʾalta ʿan ʿaẓīmin, wa-innahu la-yasīrun ʿalā man yassarahu Llāhu ʿalayhi: taʿbudu Llāha lā tushriku bihi shayʾan, wa-tuqīmu ṣ-ṣalāta, wa-tuʾtī z-zakāta, wa-taṣūmu Ramaḍāna, wa-taḥujju l-bayta. thumma qāla: alā adulluka ʿalā abwābi l-khayri? aṣ-ṣawmu junnatun, wa-ṣ-ṣadaqatu tuṭfiʾu l-khaṭīʾata kamā yuṭfiʾu l-māʾu n-nāra, wa-ṣalātu r-rajuli fī jawfi l-layli. thumma talā: {tatajāfā junūbuhum ʿani l-maḍājiʿi} ḥattā balagha {yaʿmalūna}. thumma qāla: alā ukhbiruka bi-raʾsi l-amri wa-ʿamūdihi wa-dhirwati sanāmihi? qultu: balā yā Rasūla Llāhi. qāla: raʾsu l-amri l-islāmu, wa-ʿamūduhu ṣ-ṣalātu, wa-dhirwatu sanāmihi l-jihādu. thumma qāla: alā ukhbiruka bi-milāki dhālika kullihi? fa-qultu: balā yā Rasūla Llāhi. fa-akhadha bi-lisānihi wa-qāla: kuffa ʿalayka hādhā. qultu: yā Nabiyya Llāhi, wa-innā la-muʾākhadhūna bimā natakallamu bihi? fa-qāla: thakilatka ummuka, wa-hal yakubbu n-nāsa fi n-nāri ʿalā wujūhihim — aw qāla: ʿalā manākhirihim — illā ḥaṣāʾidu alsinatihim?',
  'ʿan Mouʿâdhi bni Jabalin (radia Llâhou ʿanhou) qâla : qoultou : yâ Rassôla Llâhi, akhbirnî bi-ʿamalin youdkhilounî l-jannata wa youbâʿidounî ʿani n-nâri. qâla : laqad saʾalta ʿan ʿazîmin, wa innahou la-yasîroun ʿalâ man yassarahou Llâhou ʿalayhi : taʿboudou Llâha lâ touchrikou bihi chayʾan, wa touqîmou s-salâta, wa touʾtî z-zakâta, wa tasôumou Ramadâna, wa tahoujjou l-bayta. thoumma qâla : alâ adoullouka ʿalâ abwâbi l-khayri ? as-sawmou jounnatoun, wa s-sadaqatou toutfiʾou l-khatîʾata kamâ youtfiʾou l-mâʾou n-nâra, wa salâtou r-rajouli fî jawfi l-layli. thoumma talâ : {tatajâfâ jounôubouhoum ʿani l-madâjiʿi} hattâ balagha {yaʿmalôuna}. thoumma qâla : alâ oukhbirouka bi-raʾsi l-amri wa ʿamôudihi wa dhirwati sanâmihi ? qoultou : balâ yâ Rassôla Llâhi. qâla : raʾsou l-amri l-islâmou, wa ʿamôudouhou s-salâtou, wa dhirwatou sanâmihi l-jihâdou. thoumma qâla : alâ oukhbirouka bi-milâki dhâlika koullihi ? fa-qoultou : balâ yâ Rassôla Llâhi. fa-akhadha bi-lisânihi wa qâla : kouffa ʿalayka hâdhâ. qoultou : yâ Nabiyya Llâhi, wa innâ la-mouʾâkhadhôuna bimâ natakallamou bihi ? fa-qâla : thakilatka oummouka, wa hal yakoubbou n-nâsa fi n-nâri ʿalâ woujôuhihim — aw qâla : ʿalâ manâkhirihim — illâ hasâʾidou alsinatihim ?',
  'ʿan Muʿādhi bni Dschabalin (radiya Llāhu ʿanhu) qāla: qultu: jā Rasūla Llāhi, achbirnī bi-ʿamalin judchilunī l-dschannata wa-jubāʿidunī ʿani n-nāri. qāla: laqad saʾalta ʿan ʿazīmin, wa-innahu la-jasīrun ʿalā man jassarahu Llāhu ʿalaihi: taʿbudu Llāha lā tuschriku bihi schaiʾan, wa-tuqīmu s-salāta, wa-tuʾtī z-zakāta, wa-tasūmu Ramadāna, wa-tahudschdschu l-baita. thumma qāla: alā adulluka ʿalā abwābi l-chairi? as-saumu dschunnatun, wa-s-sadaqatu tutfiʾu l-chatīʾata kamā jutfiʾu l-māʾu n-nāra, wa-salātu r-radschuli fī dschaufi l-laili. thumma talā: {tatadschāfā dschunūbuhum ʿani l-madādschiʿi} hattā balagha {jaʿmalūna}. thumma qāla: alā uchbiruka bi-raʾsi l-amri wa-ʿamūdihi wa-dhirwati sanāmihi? qultu: balā jā Rasūla Llāhi. qāla: raʾsu l-amri l-islāmu, wa-ʿamūduhu s-salātu, wa-dhirwatu sanāmihi l-dschihādu. thumma qāla: alā uchbiruka bi-milāki dhālika kullihi? fa-qultu: balā jā Rasūla Llāhi. fa-achadha bi-lisānihi wa-qāla: kuffa ʿalaika hādhā. qultu: jā Nabijja Llāhi, wa-innā la-muʾāchadhūna bimā natakallamu bihi? fa-qāla: thakilatka ummuka, wa-hal jakubbu n-nāsa fi n-nāri ʿalā wudschūhihim — au qāla: ʿalā manāchirihim — illā hasāʾidu alsinatihim?',
  'ʿan Moeʿaadhi bni Dzjabalin (radia Llaahoe ʿanhoe) qaala: qoeltoe: jaa Rasoela Llaahi, achbirnie bi-ʿamalin joedchiloenie l-dzjannata wa-joebaaʿidoenie ʿani n-naari. qaala: laqad saʾalta ʿan ʿaziemin, wa-innahoe la-jasieroen ʿalaa man jassarahoe Llaahoe ʿalaihi: taʿboedoe Llaaha laa toesjrikoe bihi sjaiʾan, wa-toeqiemoe s-salaata, wa-toeʾtie z-zakaata, wa-tasoemoe Ramadaana, wa-tahoedzjdzjoe l-baita. thoemma qaala: alaa adoelloeka ʿalaa abwaabi l-chairi? as-saumoe dzjoennatoen, wa-s-sadaqatoe toetfiʾoe l-chatieʾata kamaa joetfiʾoe l-maaʾoe n-naara, wa-salaatoe r-radzjoeli fie dzjaufi l-laili. thoemma talaa: {tatadzjaafaa dzjoenoeboehoem ʿani l-madaadzjiʿi} hattaa balagha {jaʿmaloena}. thoemma qaala: alaa oechbiroeka bi-raʾsi l-amri wa-ʿamoedihi wa-dhirwati sanaamihi? qoeltoe: balaa jaa Rasoela Llaahi. qaala: raʾsoe l-amri l-islaamoe, wa-ʿamoedoehoe s-salaatoe, wa-dhirwatoe sanaamihi l-dzjihaadoe. thoemma qaala: alaa oechbiroeka bi-milaaki dhaalika koellihi? fa-qoeltoe: balaa jaa Rasoela Llaahi. fa-achadha bi-lisaanihi wa-qaala: koeffa ʿalaika haadhaa. qoeltoe: jaa Nabijja Llaahi, wa-innaa la-moeʾaachadhoena bimaa natakallamoe bihi? fa-qaala: thakilatka oemmoeka, wa-hal jakoebboe n-naasa fi n-naari ʿalaa woedzjoehihim — au qaala: ʿalaa manaachirihim — illaa hasaaʾidoe alsinatihim?',
  'an Muâz ibn Cebel''den (radıyallâhu anh) rivayetle dedi ki: dedim ki: yâ Resûlallah, beni cennete sokacak ve ateşten uzaklaştıracak bir amel söyle. Buyurdu: büyük bir şey sordun, ama Allah''ın kolaylaştırdığı kimseye o kolaydır: Allah''a hiçbir şeyi ortak koşmadan ibadet edersin, namazı kılarsın, zekâtı verirsin, Ramazan orucunu tutarsın ve Beyt''i haccedersin. Sonra buyurdu: sana hayır kapılarını göstereyim mi? Oruç bir kalkandır, sadaka suyun ateşi söndürdüğü gibi günahı söndürür, ve kişinin gecenin bir vaktinde kıldığı namaz. Sonra şu âyeti okudu: {Yanları yataklarından uzaklaşır} ve {yapmakta olduklarına} kadar (okudu). Sonra buyurdu: sana işin başını, direğini ve zirvesini haber vereyim mi? Dedim: evet, yâ Resûlallah. Buyurdu: işin başı İslâm, direği namaz, zirvesi de cihaddır. Sonra buyurdu: sana bütün bunların özünü (dayanağını) haber vereyim mi? Dedim: evet, yâ Resûlallah. Dilini tuttu ve: şunu tut (kontrol et), buyurdu. Dedim: yâ Nebiyyallah, söylediklerimizden hesaba mı çekileceğiz? Buyurdu: anan seni yitirsin (kaybetsin)! İnsanları yüzüstü — yahut: burunları üstü — ateşe atan, dillerinin biçtiklerinden başka nedir ki?',
  'an Muʿadz bin Jabal (radhiyallahu ʿanhu) berkata: aku berkata: wahai Rasulullah, beritahukan aku suatu amal yang memasukkanku ke surga dan menjauhkanku dari neraka. Beliau bersabda: sungguh engkau bertanya tentang perkara yang besar, namun ia mudah bagi siapa yang Allah mudahkan atasnya: engkau menyembah Allah tanpa menyekutukan-Nya dengan sesuatu apa pun, mendirikan shalat, menunaikan zakat, berpuasa Ramadhan, dan berhaji ke Baitullah. Lalu beliau bersabda: maukah aku tunjukkan kepadamu pintu-pintu kebaikan? Puasa adalah perisai, sedekah memadamkan dosa sebagaimana air memadamkan api, dan shalat seseorang di tengah malam. Lalu beliau membaca: {lambung mereka jauh dari tempat tidur} hingga sampai {yang mereka kerjakan}. Lalu beliau bersabda: maukah aku beritahukan kepadamu pokok perkara, tiangnya, dan puncaknya? Aku menjawab: ya, wahai Rasulullah. Beliau bersabda: pokok perkara adalah Islam, tiangnya adalah shalat, dan puncaknya adalah jihad. Lalu beliau bersabda: maukah aku beritahukan kepadamu kunci dari semua itu? Aku menjawab: ya, wahai Rasulullah. Beliau memegang lidahnya dan bersabda: tahanlah ini olehmu. Aku berkata: wahai Nabi Allah, apakah kami akan dihukum karena apa yang kami ucapkan? Beliau bersabda: semoga ibumu kehilanganmu! Bukankah yang menjerumuskan manusia ke dalam neraka dengan wajah mereka — atau beliau berkata: dengan hidung mereka — hanyalah hasil (tuaian) lidah mereka?',
  'معاذ بن جبل رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: میں نے عرض کیا: یا رسول اللہ! مجھے کوئی ایسا عمل بتائیے جو مجھے جنت میں داخل کرے اور جہنم سے دور رکھے۔ آپ نے فرمایا: تم نے ایک بڑی چیز کے بارے میں پوچھا، اور یہ اس کے لیے آسان ہے جس پر اللہ آسان کر دے: تم اللہ کی عبادت کرو اور اس کے ساتھ کسی کو شریک نہ کرو، نماز قائم کرو، زکوٰۃ ادا کرو، رمضان کے روزے رکھو اور بیت اللہ کا حج کرو۔ پھر فرمایا: کیا میں تمہیں خیر کے دروازے نہ بتاؤں؟ روزہ ڈھال ہے، صدقہ گناہ کو ایسے بجھا دیتا ہے جیسے پانی آگ کو بجھاتا ہے، اور آدمی کی رات کے درمیانی حصے کی نماز۔ پھر آپ نے یہ آیت تلاوت کی: {ان کے پہلو بستروں سے جدا رہتے ہیں} یہاں تک کہ {یعملون} تک پہنچے۔ پھر فرمایا: کیا میں تمہیں اس سارے معاملے کی جڑ، اس کا ستون اور اس کی چوٹی نہ بتاؤں؟ میں نے کہا: ضرور، یا رسول اللہ! فرمایا: معاملے کی جڑ اسلام ہے، اس کا ستون نماز ہے، اور اس کی چوٹی جہاد ہے۔ پھر فرمایا: کیا میں تمہیں اس سب کی اصل (کلید) نہ بتاؤں؟ میں نے کہا: ضرور، یا رسول اللہ! آپ نے اپنی زبان پکڑی اور فرمایا: اسے روکے رکھو۔ میں نے کہا: یا نبی اللہ! کیا ہم اس پر بھی پکڑے جائیں گے جو ہم بولتے ہیں؟ آپ نے فرمایا: تیری ماں تجھے گم پائے! لوگوں کو ان کے چہروں کے بل — یا فرمایا: ان کے نتھنوں کے بل — جہنم میں ان کی زبانوں کی کاٹی ہوئی فصل کے سوا اور کیا گراتا ہے؟',
  'মুআয ইবনে জাবাল (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: আমি বললাম: হে আল্লাহর রাসূল! আমাকে এমন একটি আমল বলুন যা আমাকে জান্নাতে প্রবেশ করায় এবং জাহান্নাম থেকে দূরে রাখে। তিনি বললেন: তুমি এক মহান বিষয় সম্পর্কে জিজ্ঞাসা করেছ, আর তা সহজ তার জন্য যাকে আল্লাহ সহজ করে দেন: তুমি আল্লাহর ইবাদত করবে ও তাঁর সাথে কাউকে শরিক করবে না, সালাত কায়েম করবে, যাকাত দেবে, রমজানের সিয়াম পালন করবে এবং বাইতুল্লাহর হজ করবে। অতঃপর তিনি বললেন: আমি কি তোমাকে কল্যাণের দরজাসমূহ দেখিয়ে দেব না? সিয়াম ঢাল, সদকা পাপ নিভিয়ে দেয় যেমন পানি আগুন নিভায়, এবং রাতের মধ্যভাগে মানুষের সালাত। অতঃপর তিনি তিলাওয়াত করলেন: {তাদের পার্শ্ব বিছানা থেকে আলাদা থাকে} যতক্ষণ না {ইয়ামালূন} পর্যন্ত পৌঁছলেন। অতঃপর তিনি বললেন: আমি কি তোমাকে বিষয়টির মূল, এর স্তম্ভ ও এর শীর্ষচূড়া বলে দেব না? আমি বললাম: অবশ্যই, হে আল্লাহর রাসূল! তিনি বললেন: বিষয়টির মূল হলো ইসলাম, এর স্তম্ভ হলো সালাত, আর এর শীর্ষচূড়া হলো জিহাদ। অতঃপর তিনি বললেন: আমি কি তোমাকে এ সবকিছুর মূল চাবিকাঠি বলে দেব না? আমি বললাম: অবশ্যই, হে আল্লাহর রাসূল! তিনি তাঁর জিহ্বা ধরে বললেন: এটিকে সংযত রাখো। আমি বললাম: হে আল্লাহর নবী! আমরা যা বলি তার জন্যও কি আমাদের পাকড়াও করা হবে? তিনি বললেন: তোমার মা তোমাকে হারাক! মানুষকে তাদের মুখের ওপর — অথবা তিনি বললেন: তাদের নাকের ওপর — জাহান্নামে তাদের জিহ্বার ফসল ছাড়া আর কী নিক্ষেপ করে?',
  'an Muʿadz bin Jabal (radhiallahu ʿanhu) berkata: aku berkata: wahai Rasulullah, beritahukanlah aku suatu amal yang memasukkanku ke syurga dan menjauhkanku dari neraka. Baginda bersabda: sungguh engkau bertanya tentang perkara yang besar, namun ia mudah bagi sesiapa yang Allah mudahkan atasnya: engkau menyembah Allah tanpa menyekutukan-Nya dengan sesuatu apa pun, mendirikan solat, menunaikan zakat, berpuasa Ramadan, dan mengerjakan haji ke Baitullah. Lalu baginda bersabda: mahukah aku tunjukkan kepadamu pintu-pintu kebaikan? Puasa adalah perisai, sedekah memadamkan dosa sebagaimana air memadamkan api, dan solat seseorang di tengah malam. Lalu baginda membaca: {lambung mereka jauh dari tempat tidur} sehingga sampai {yang mereka kerjakan}. Lalu baginda bersabda: mahukah aku beritahukan kepadamu pokok perkara, tiangnya, dan puncaknya? Aku menjawab: ya, wahai Rasulullah. Baginda bersabda: pokok perkara ialah Islam, tiangnya ialah solat, dan puncaknya ialah jihad. Lalu baginda bersabda: mahukah aku beritahukan kepadamu kunci semua itu? Aku menjawab: ya, wahai Rasulullah. Baginda memegang lidahnya dan bersabda: tahanlah ini olehmu. Aku berkata: wahai Nabi Allah, adakah kami akan dihukum kerana apa yang kami ucapkan? Baginda bersabda: semoga ibumu kehilanganmu! Bukankah yang mencampakkan manusia ke dalam neraka dengan wajah mereka — atau baginda berkata: dengan hidung mereka — hanyalah hasil (tuaian) lidah mereka?',
  'От Муаза ибн Джабаля (да будет доволен им Аллах) передаётся: я сказал: о Посланник Аллаха, укажи мне деяние, которое введёт меня в Рай и отдалит от Огня. Он сказал: ты спросил о великом, но это легко для того, кому Аллах облегчит: поклоняйся Аллаху, не придавая Ему ничего в сотоварищи, совершай молитву, давай закят, постись в Рамадан и соверши хадж к Дому. Затем сказал: не указать ли тебе на врата блага? Пост — щит; милостыня гасит грех, как вода гасит огонь; и молитва человека среди ночи. Затем он прочёл: {Бока их сторонятся лож} пока не дошёл до {то, что они совершали}. Затем сказал: не сообщить ли тебе о главе дела, его опоре и его вершине? Я сказал: да, о Посланник Аллаха. Он сказал: глава дела — ислам, его опора — молитва, а вершина его — джихад. Затем сказал: не сообщить ли тебе об основе всего этого? Я сказал: да, о Посланник Аллаха. Он взял свой язык и сказал: удерживай это. Я сказал: о Пророк Аллаха, неужели мы будем спрошены за то, что говорим? Он сказал: да лишится тебя твоя мать! Разве ввергает людей в Огонь на их лицах — или он сказал: на их ноздрях — что-либо, кроме жатвы их языков?',
  -- translation
  'On the authority of Muʿadh ibn Jabal (may Allah be pleased with him), who said: I said: "O Messenger of Allah, tell me of a deed that will admit me to Paradise and keep me far from the Fire." He said: "You have asked about a great matter, yet it is easy for whomever Allah makes it easy: you worship Allah without associating anything with Him, you establish the prayer, you give the zakat, you fast Ramadan, and you make the pilgrimage to the House." Then he said: "Shall I show you the gates of good? Fasting is a shield; charity extinguishes sin as water extinguishes fire; and a man''s prayer in the depth of the night." Then he recited: {Their sides forsake their beds…} until he reached {…what they used to do} (32:16-17). Then he said: "Shall I tell you of the head of the matter, its pillar, and its highest peak?" I said: "Of course, O Messenger of Allah." He said: "The head of the matter is Islam, its pillar is the prayer, and its highest peak is jihad." Then he said: "Shall I tell you the mainstay of all that?" I said: "Of course, O Messenger of Allah." He took hold of his tongue and said: "Restrain this." I said: "O Prophet of Allah, are we to be held to account for what we say?" He said: "May your mother be bereaved of you! Is there anything that casts people into the Fire on their faces — or he said: on their noses — other than the harvests of their tongues?"',
  'D''après Muʿâdh ibn Jabal (qu''Allah l''agrée), qui a dit : Je dis : « Ô Envoyé d''Allah, indique-moi une œuvre qui me fera entrer au Paradis et m''éloignera du Feu. » Il dit : « Tu as interrogé sur une affaire énorme, qui est pourtant aisée pour qui Allah la rend aisée : tu adores Allah sans rien Lui associer, tu accomplis la prière, tu acquittes la zakât, tu jeûnes le Ramadan et tu fais le pèlerinage à la Maison. » Puis il ajouta : « Veux-tu que je t''indique les portes du bien ? Le jeûne est un rempart ; l''aumône éteint le péché comme l''eau éteint le feu ; et la prière de l''homme au cœur de la nuit. » Puis il récita : {Ils s''arrachent de leurs lits…} jusqu''à {…ce qu''ils faisaient} (32:16-17). Puis il dit : « Veux-tu que je t''indique la tête de l''affaire, son pilier et son sommet ? » Je dis : « Bien sûr, ô Envoyé d''Allah. » Il dit : « La tête de l''affaire, c''est l''Islam ; son pilier, c''est la prière ; et son sommet, c''est le jihâd. » Puis il dit : « Veux-tu que je t''indique le pivot de tout cela ? » Je dis : « Bien sûr, ô Envoyé d''Allah. » Il saisit sa langue et dit : « Retiens ceci. » Je dis : « Ô Prophète d''Allah, serons-nous tenus pour responsables de ce que nous disons ? » Il dit : « Que ta mère te perde ! Qu''est-ce qui précipite les gens dans le Feu sur leurs visages — ou il dit : sur leurs narines — si ce n''est les moissons de leurs langues ? »',
  'Nach Muʿadh ibn Jabal (möge Allah mit ihm zufrieden sein), der sagte: Ich sagte: „O Gesandter Allahs, nenne mir eine Tat, die mich ins Paradies eintreten lässt und mich vom Feuer fernhält." Er sagte: „Du hast nach einer gewaltigen Sache gefragt, doch sie ist leicht für den, dem Allah sie leicht macht: du dienst Allah, ohne Ihm etwas beizugesellen, verrichtest das Gebet, gibst die Zakat, fastest im Ramadan und vollziehst die Pilgerfahrt zum Hause." Dann sagte er: „Soll ich dir die Tore des Guten zeigen? Das Fasten ist ein Schild; die Almosen löschen die Sünde, wie Wasser das Feuer löscht; und das Gebet des Mannes mitten in der Nacht." Dann rezitierte er: {Ihre Seiten meiden die Lager…} bis er erreichte {…was sie zu tun pflegten} (32:16-17). Dann sagte er: „Soll ich dir das Haupt der Angelegenheit, ihre Säule und ihren höchsten Gipfel nennen?" Ich sagte: „Gewiss, o Gesandter Allahs." Er sagte: „Das Haupt der Angelegenheit ist der Islam, ihre Säule ist das Gebet, und ihr höchster Gipfel ist der Dschihad." Dann sagte er: „Soll ich dir die Grundlage all dessen nennen?" Ich sagte: „Gewiss, o Gesandter Allahs." Er ergriff seine Zunge und sagte: „Halte diese im Zaum." Ich sagte: „O Prophet Allahs, werden wir für das zur Rechenschaft gezogen, was wir sagen?" Er sagte: „Möge deine Mutter dich verlieren! Wirft etwas die Menschen ins Feuer auf ihre Gesichter — oder er sagte: auf ihre Nasen — anderes als die Ernten ihrer Zungen?"',
  'Op gezag van Muʿadh ibn Jabal (moge Allah tevreden met hem zijn), die zei: Ik zei: „O Boodschapper van Allah, noem mij een daad die mij het Paradijs binnenleidt en mij ver van het Vuur houdt." Hij zei: „Je hebt naar een geweldige zaak gevraagd, doch zij is gemakkelijk voor wie Allah haar gemakkelijk maakt: je aanbidt Allah zonder iets aan Hem toe te kennen, je verricht het gebed, je geeft de zakat, je vast in de Ramadan en je verricht de bedevaart naar het Huis." Toen zei hij: „Zal ik je de poorten van het goede tonen? Het vasten is een schild; de aalmoes dooft de zonde zoals water het vuur dooft; en het gebed van de man in het holst van de nacht." Toen reciteerde hij: {Hun zijden mijden de rustplaatsen…} totdat hij bereikte {…wat zij plachten te doen} (32:16-17). Toen zei hij: „Zal ik je het hoofd van de zaak, haar zuil en haar hoogste top noemen?" Ik zei: „Zeker, o Boodschapper van Allah." Hij zei: „Het hoofd van de zaak is de islam, haar zuil is het gebed, en haar hoogste top is de jihad." Toen zei hij: „Zal ik je de spil van dit alles noemen?" Ik zei: „Zeker, o Boodschapper van Allah." Hij greep zijn tong en zei: „Beheers deze." Ik zei: „O Profeet van Allah, worden wij ter verantwoording geroepen voor wat wij zeggen?" Hij zei: „Moge je moeder je verliezen! Werpt iets de mensen in het Vuur op hun gezichten — of hij zei: op hun neuzen — anders dan de oogsten van hun tongen?"',
  'Muâz ibn Cebel''den (Allah ondan razı olsun) rivayet edildiğine göre şöyle dedi: Dedim ki: „Yâ Resûlallah, beni cennete sokacak ve ateşten uzaklaştıracak bir amel söyle." Buyurdu: „Büyük bir şey sordun, ama Allah''ın kolaylaştırdığı kimseye o kolaydır: Allah''a hiçbir şeyi ortak koşmadan ibadet edersin, namazı kılarsın, zekâtı verirsin, Ramazan orucunu tutarsın ve Beyt''i haccedersin." Sonra buyurdu: „Sana hayır kapılarını göstereyim mi? Oruç bir kalkandır; sadaka suyun ateşi söndürdüğü gibi günahı söndürür; ve kişinin gecenin bir vaktinde kıldığı namaz." Sonra şu âyeti okudu: {Yanları yataklarından uzaklaşır…} ve {yapmakta olduklarına} kadar (okudu) (32:16-17). Sonra buyurdu: „Sana işin başını, direğini ve zirvesini haber vereyim mi?" Dedim: „Evet, yâ Resûlallah." Buyurdu: „İşin başı İslâm, direği namaz, zirvesi de cihaddır." Sonra buyurdu: „Sana bütün bunların dayanağını haber vereyim mi?" Dedim: „Evet, yâ Resûlallah." Dilini tuttu ve buyurdu: „Şunu tut." Dedim: „Yâ Nebiyyallah, söylediklerimizden hesaba mı çekileceğiz?" Buyurdu: „Anan seni yitirsin! İnsanları yüzüstü — yahut: burunları üstü — ateşe atan, dillerinin biçtiklerinden başka nedir?"',
  'Dari Muʿadz bin Jabal (semoga Allah meridhainya), ia berkata: Aku berkata: "Wahai Rasulullah, beritahukan kepadaku suatu amal yang memasukkanku ke surga dan menjauhkanku dari neraka." Beliau bersabda: "Sungguh engkau bertanya tentang perkara yang besar, namun ia mudah bagi siapa yang Allah mudahkan atasnya: engkau menyembah Allah tanpa menyekutukan-Nya dengan sesuatu apa pun, mendirikan shalat, menunaikan zakat, berpuasa Ramadhan, dan berhaji ke Baitullah." Lalu beliau bersabda: "Maukah aku tunjukkan kepadamu pintu-pintu kebaikan? Puasa adalah perisai; sedekah memadamkan dosa sebagaimana air memadamkan api; dan shalat seseorang di tengah malam." Lalu beliau membaca: {Lambung mereka jauh dari tempat tidur…} hingga sampai {…yang mereka kerjakan} (32:16-17). Lalu beliau bersabda: "Maukah aku beritahukan kepadamu pokok perkara, tiangnya, dan puncaknya?" Aku menjawab: "Tentu, wahai Rasulullah." Beliau bersabda: "Pokok perkara adalah Islam, tiangnya adalah shalat, dan puncaknya adalah jihad." Lalu beliau bersabda: "Maukah aku beritahukan kepadamu kunci semua itu?" Aku menjawab: "Tentu, wahai Rasulullah." Beliau memegang lidahnya dan bersabda: "Tahanlah ini olehmu." Aku berkata: "Wahai Nabi Allah, apakah kami akan dihukum karena apa yang kami ucapkan?" Beliau bersabda: "Semoga ibumu kehilanganmu! Bukankah yang menjerumuskan manusia ke dalam neraka dengan wajah mereka — atau beliau berkata: dengan hidung mereka — hanyalah hasil (tuaian) lidah mereka?"',
  'معاذ بن جبل رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: میں نے عرض کیا: ”یا رسول اللہ! مجھے کوئی ایسا عمل بتائیے جو مجھے جنت میں داخل کرے اور جہنم سے دور رکھے۔“ آپ نے فرمایا: ”تم نے ایک بڑی چیز کے بارے میں پوچھا، اور یہ اس کے لیے آسان ہے جس پر اللہ آسان کر دے: تم اللہ کی عبادت کرو اور اس کے ساتھ کسی کو شریک نہ کرو، نماز قائم کرو، زکوٰۃ ادا کرو، رمضان کے روزے رکھو اور بیت اللہ کا حج کرو۔“ پھر فرمایا: ”کیا میں تمہیں خیر کے دروازے نہ بتاؤں؟ روزہ ڈھال ہے؛ صدقہ گناہ کو ایسے بجھا دیتا ہے جیسے پانی آگ کو بجھاتا ہے؛ اور آدمی کی رات کے درمیانی حصے کی نماز۔“ پھر آپ نے یہ آیت تلاوت کی: {ان کے پہلو بستروں سے جدا رہتے ہیں…} یہاں تک کہ {…یعملون} تک پہنچے (۳۲:۱۶-۱۷)۔ پھر فرمایا: ”کیا میں تمہیں معاملے کی جڑ، اس کا ستون اور اس کی چوٹی نہ بتاؤں؟“ میں نے کہا: ”ضرور، یا رسول اللہ!“ فرمایا: ”معاملے کی جڑ اسلام ہے، اس کا ستون نماز ہے، اور اس کی چوٹی جہاد ہے۔“ پھر فرمایا: ”کیا میں تمہیں اس سب کی اصل (کلید) نہ بتاؤں؟“ میں نے کہا: ”ضرور، یا رسول اللہ!“ آپ نے اپنی زبان پکڑی اور فرمایا: ”اسے روکے رکھو۔“ میں نے کہا: ”یا نبی اللہ! کیا ہم اس پر بھی پکڑے جائیں گے جو ہم بولتے ہیں؟“ آپ نے فرمایا: ”تیری ماں تجھے گم پائے! لوگوں کو ان کے چہروں کے بل — یا فرمایا: ان کے نتھنوں کے بل — جہنم میں ان کی زبانوں کی کاٹی ہوئی فصل کے سوا اور کیا گراتا ہے؟“',
  'মুআয ইবনে জাবাল (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: আমি বললাম: "হে আল্লাহর রাসূল! আমাকে এমন একটি আমল বলুন যা আমাকে জান্নাতে প্রবেশ করায় এবং জাহান্নাম থেকে দূরে রাখে।" তিনি বললেন: "তুমি এক মহান বিষয় সম্পর্কে জিজ্ঞাসা করেছ, আর তা সহজ তার জন্য যাকে আল্লাহ সহজ করে দেন: তুমি আল্লাহর ইবাদত করবে ও তাঁর সাথে কাউকে শরিক করবে না, সালাত কায়েম করবে, যাকাত দেবে, রমজানের সিয়াম পালন করবে এবং বাইতুল্লাহর হজ করবে।" অতঃপর তিনি বললেন: "আমি কি তোমাকে কল্যাণের দরজাসমূহ দেখিয়ে দেব না? সিয়াম ঢাল; সদকা পাপ নিভিয়ে দেয় যেমন পানি আগুন নিভায়; এবং রাতের মধ্যভাগে মানুষের সালাত।" অতঃপর তিনি তিলাওয়াত করলেন: {তাদের পার্শ্ব বিছানা থেকে আলাদা থাকে…} যতক্ষণ না {…ইয়ামালূন} পর্যন্ত পৌঁছলেন (৩২:১৬-১৭)। অতঃপর তিনি বললেন: "আমি কি তোমাকে বিষয়টির মূল, এর স্তম্ভ ও এর শীর্ষচূড়া বলে দেব না?" আমি বললাম: "অবশ্যই, হে আল্লাহর রাসূল!" তিনি বললেন: "বিষয়টির মূল হলো ইসলাম, এর স্তম্ভ হলো সালাত, আর এর শীর্ষচূড়া হলো জিহাদ।" অতঃপর তিনি বললেন: "আমি কি তোমাকে এ সবকিছুর মূল চাবিকাঠি বলে দেব না?" আমি বললাম: "অবশ্যই, হে আল্লাহর রাসূল!" তিনি তাঁর জিহ্বা ধরে বললেন: "এটিকে সংযত রাখো।" আমি বললাম: "হে আল্লাহর নবী! আমরা যা বলি তার জন্যও কি আমাদের পাকড়াও করা হবে?" তিনি বললেন: "তোমার মা তোমাকে হারাক! মানুষকে তাদের মুখের ওপর — অথবা তিনি বললেন: তাদের নাকের ওপর — জাহান্নামে তাদের জিহ্বার ফসল ছাড়া আর কী নিক্ষেপ করে?"',
  'Daripada Muʿadz bin Jabal (semoga Allah meredainya), dia berkata: Aku berkata: "Wahai Rasulullah, beritahukanlah kepadaku suatu amal yang memasukkanku ke syurga dan menjauhkanku dari neraka." Baginda bersabda: "Sungguh engkau bertanya tentang perkara yang besar, namun ia mudah bagi sesiapa yang Allah mudahkan atasnya: engkau menyembah Allah tanpa menyekutukan-Nya dengan sesuatu apa pun, mendirikan solat, menunaikan zakat, berpuasa Ramadan, dan mengerjakan haji ke Baitullah." Lalu baginda bersabda: "Mahukah aku tunjukkan kepadamu pintu-pintu kebaikan? Puasa adalah perisai; sedekah memadamkan dosa sebagaimana air memadamkan api; dan solat seseorang di tengah malam." Lalu baginda membaca: {Lambung mereka jauh dari tempat tidur…} sehingga sampai {…yang mereka kerjakan} (32:16-17). Lalu baginda bersabda: "Mahukah aku beritahukan kepadamu pokok perkara, tiangnya, dan puncaknya?" Aku menjawab: "Tentu, wahai Rasulullah." Baginda bersabda: "Pokok perkara ialah Islam, tiangnya ialah solat, dan puncaknya ialah jihad." Lalu baginda bersabda: "Mahukah aku beritahukan kepadamu kunci semua itu?" Aku menjawab: "Tentu, wahai Rasulullah." Baginda memegang lidahnya dan bersabda: "Tahanlah ini olehmu." Aku berkata: "Wahai Nabi Allah, adakah kami akan dihukum kerana apa yang kami ucapkan?" Baginda bersabda: "Semoga ibumu kehilanganmu! Bukankah yang mencampakkan manusia ke dalam neraka dengan wajah mereka — atau baginda berkata: dengan hidung mereka — hanyalah hasil (tuaian) lidah mereka?"',
  'От Муаза ибн Джабаля (да будет доволен им Аллах), который сказал: Я сказал: «О Посланник Аллаха, укажи мне деяние, которое введёт меня в Рай и отдалит от Огня». Он сказал: «Ты спросил о великом, но это легко для того, кому Аллах облегчит: ты поклоняешься Аллаху, не придавая Ему ничего в сотоварищи, совершаешь молитву, даёшь закят, постишься в Рамадан и совершаешь хадж к Дому». Затем он сказал: «Не указать ли тебе на врата блага? Пост — щит; милостыня гасит грех, как вода гасит огонь; и молитва человека среди ночи». Затем он прочёл: {Бока их сторонятся лож…} пока не дошёл до {…то, что они совершали} (32:16-17). Затем сказал: «Не сообщить ли тебе о главе дела, его опоре и его наивысшей вершине?» Я сказал: «Конечно, о Посланник Аллаха». Он сказал: «Глава дела — ислам, его опора — молитва, а наивысшая вершина — джихад». Затем сказал: «Не сообщить ли тебе об основе всего этого?» Я сказал: «Конечно, о Посланник Аллаха». Он взял свой язык и сказал: «Удерживай это». Я сказал: «О Пророк Аллаха, неужели мы будем спрошены за то, что говорим?» Он сказал: «Да лишится тебя твоя мать! Разве ввергает людей в Огонь на их лицах — или он сказал: на их ноздрях — что-либо, кроме жатвы их языков?»',
  -- reference
  'Hasan — reported by at-Tirmidhi (no. 2616, who said hasan sahih), an-Nasaʾi (no. 11394), Ibn Majah (no. 3973), and Ahmad (5/231, 236-237, 245); graded hasan in al-Irwaʾ (2/139)',
  'Hadith hasan rapporté par at-Tirmidhî (n°2616, qui l''a déclaré hasan sahih), an-Nasâʾî (n°11394), Ibn Mâja (n°3973) et Ahmad (5/231, 236-237, 245) ; déclaré hasan dans al-Irwâʾ (2/139)',
  'حديث حسن، رواه الترمذي (رقم ٢٦١٦ وقال: حسن صحيح) والنسائي (رقم ١١٣٩٤) وابن ماجه (رقم ٣٩٧٣) وأحمد (٥/٢٣١، ٢٣٦-٢٣٧، ٢٤٥)، وحُسِّن في الإرواء (٢/١٣٩)',
  'Hasan — überliefert von at-Tirmidhi (Nr. 2616, der es hasan sahih nannte), an-Nasaʾi (Nr. 11394), Ibn Madscha (Nr. 3973) und Ahmad (5/231, 236-237, 245); als hasan eingestuft in al-Irwaʾ (2/139)',
  'Hasan — overgeleverd door at-Tirmidhi (nr. 2616, die het hasan sahih noemde), an-Nasaʾi (nr. 11394), Ibn Madja (nr. 3973) en Ahmad (5/231, 236-237, 245); als hasan beoordeeld in al-Irwaʾ (2/139)',
  'Hasen — Tirmizî (no. 2616, hasen-sahih dedi), Nesâî (no. 11394), İbn Mâce (no. 3973) ve Ahmed (5/231, 236-237, 245) rivayet etmiştir; el-İrvâ''da (2/139) hasen sayılmıştır',
  'Hadis hasan, diriwayatkan oleh at-Tirmidzi (no. 2616, ia berkata hasan sahih), an-Nasaʾi (no. 11394), Ibnu Majah (no. 3973), dan Ahmad (5/231, 236-237, 245); dinilai hasan dalam al-Irwaʾ (2/139)',
  'حسن حدیث، اسے ترمذی (نمبر ۲۶۱۶، اور کہا: حسن صحیح)، نسائی (نمبر ۱۱۳۹۴)، ابن ماجہ (نمبر ۳۹۷۳) اور احمد (۵/۲۳۱، ۲۳۶-۲۳۷، ۲۴۵) نے روایت کیا؛ الارواء (۲/۱۳۹) میں حسن قرار دیا گیا',
  'হাসান হাদীস — তিরমিযী (নং ২৬১৬, তিনি বলেছেন হাসান সহীহ), নাসাঈ (নং ১১৩৯৪), ইবনে মাজাহ (নং ৩৯৭৩) ও আহমাদ (৫/২৩১, ২৩৬-২৩৭, ২৪৫) বর্ণনা করেছেন; আল-ইরওয়ায় (২/১৩৯) হাসান বলা হয়েছে',
  'Hadis hasan, diriwayatkan oleh at-Tirmizi (no. 2616, dia berkata hasan sahih), an-Nasaʾi (no. 11394), Ibnu Majah (no. 3973), dan Ahmad (5/231, 236-237, 245); dinilai hasan dalam al-Irwaʾ (2/139)',
  'Хороший (хасан) хадис, передали ат-Тирмизи (№ 2616, назвал его хасан сахих), ан-Насаи (№ 11394), Ибн Маджа (№ 3973) и Ахмад (5/231, 236-237, 245); назван хасаном в «аль-Ирва» (2/139)',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-29-Nawawi-Psalmodie-Arabe.mp3',
  5,
  29
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 29
);
