-- =============================================================================
-- 40 Hadith Nawawi — Hadith 24: "Prohibition of injustice" (hadith qudsi)
-- Target collection: public.hadith_collections.id = 2  /  position = 24
-- Idempotent guard on (collection, position). All 11 content languages.
-- tafsir_* intentionally left NULL (no commentary provided for this hadith).
-- Arabic cleaned: أولكمم -> أوّلكم، أخركم -> آخركم، restored المخيط/البحر.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'The absolute prohibition of injustice',
  'L''interdiction absolue de l''injustice',
  'تحريم الظلم',
  'Das absolute Verbot der Ungerechtigkeit',
  'Het absolute verbod op onrecht',
  'Zulmün kesin yasaklanması',
  'Pengharaman kezaliman secara mutlak',
  'ظلم کی قطعی ممانعت',
  'যুলম সম্পূর্ণরূপে নিষিদ্ধ',
  'Pengharaman kezaliman secara mutlak',
  'Полный запрет несправедливости',
  -- arabic_text (cleaned)
  'عَنْ أَبِي ذَرٍّ الْغِفَارِيِّ رَضِيَ اللَّهُ عَنْهُ عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فِيمَا يَرْوِيهِ عَنْ رَبِّهِ تَبَارَكَ وَتَعَالَى أَنَّهُ قَالَ: «يَا عِبَادِي، إِنِّي حَرَّمْتُ الظُّلْمَ عَلَى نَفْسِي وَجَعَلْتُهُ بَيْنَكُمْ مُحَرَّمًا فَلَا تَظَالَمُوا. يَا عِبَادِي، كُلُّكُمْ ضَالٌّ إِلَّا مَنْ هَدَيْتُهُ فَاسْتَهْدُونِي أَهْدِكُمْ. يَا عِبَادِي، كُلُّكُمْ جَائِعٌ إِلَّا مَنْ أَطْعَمْتُهُ فَاسْتَطْعِمُونِي أُطْعِمْكُمْ. يَا عِبَادِي، كُلُّكُمْ عَارٍ إِلَّا مَنْ كَسَوْتُهُ فَاسْتَكْسُونِي أَكْسُكُمْ. يَا عِبَادِي، إِنَّكُمْ تُخْطِئُونَ بِاللَّيْلِ وَالنَّهَارِ وَأَنَا أَغْفِرُ الذُّنُوبَ جَمِيعًا فَاسْتَغْفِرُونِي أَغْفِرْ لَكُمْ. يَا عِبَادِي، إِنَّكُمْ لَنْ تَبْلُغُوا ضَرِّي فَتَضُرُّونِي وَلَنْ تَبْلُغُوا نَفْعِي فَتَنْفَعُونِي. يَا عِبَادِي، لَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَإِنْسَكُمْ وَجِنَّكُمْ كَانُوا عَلَى أَتْقَى قَلْبِ رَجُلٍ وَاحِدٍ مِنْكُمْ مَا زَادَ ذَلِكَ فِي مُلْكِي شَيْئًا. يَا عِبَادِي، لَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَإِنْسَكُمْ وَجِنَّكُمْ كَانُوا عَلَى أَفْجَرِ قَلْبِ رَجُلٍ وَاحِدٍ مِنْكُمْ مَا نَقَصَ ذَلِكَ مِنْ مُلْكِي شَيْئًا. يَا عِبَادِي، لَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَإِنْسَكُمْ وَجِنَّكُمْ قَامُوا فِي صَعِيدٍ وَاحِدٍ فَسَأَلُونِي فَأَعْطَيْتُ كُلَّ وَاحِدٍ مَسْأَلَتَهُ مَا نَقَصَ ذَلِكَ مِمَّا عِنْدِي إِلَّا كَمَا يَنْقُصُ الْمِخْيَطُ إِذَا أُدْخِلَ الْبَحْرَ. يَا عِبَادِي، إِنَّمَا هِيَ أَعْمَالُكُمْ أُحْصِيهَا لَكُمْ ثُمَّ أُوَفِّيكُمْ إِيَّاهَا، فَمَنْ وَجَدَ خَيْرًا فَلْيَحْمَدِ اللَّهَ، وَمَنْ وَجَدَ غَيْرَ ذَلِكَ فَلَا يَلُومَنَّ إِلَّا نَفْسَهُ»',
  -- transcription
  'ʿan Abī Dharrin al-Ghifāriyyi raḍiya Llāhu ʿanhu ʿani n-Nabiyyi ṣalla Llāhu ʿalayhi wa-sallama fīmā yarwīhi ʿan Rabbihi tabāraka wa-taʿālā annahu qāla: yā ʿibādī, innī ḥarramtu ẓ-ẓulma ʿalā nafsī wa-jaʿaltuhu baynakum muḥarraman fa-lā taẓālamū. yā ʿibādī, kullukum ḍāllun illā man hadaytuhu fa-stahdūnī ahdikum. yā ʿibādī, kullukum jāʾiʿun illā man aṭʿamtuhu fa-staṭʿimūnī uṭʿimkum. yā ʿibādī, kullukum ʿārin illā man kasawtuhu fa-staksūnī aksukum. yā ʿibādī, innakum tukhṭiʾūna bi-l-layli wa-n-nahāri wa-anā aghfiru dh-dhunūba jamīʿan fa-staghfirūnī aghfir lakum. yā ʿibādī, innakum lan tablughū ḍarrī fa-taḍurrūnī wa-lan tablughū nafʿī fa-tanfaʿūnī. yā ʿibādī, law anna awwalakum wa-ākhirakum wa-insakum wa-jinnakum kānū ʿalā atqā qalbi rajulin wāḥidin minkum mā zāda dhālika fī mulkī shayʾan. yā ʿibādī, law anna awwalakum wa-ākhirakum wa-insakum wa-jinnakum kānū ʿalā afjari qalbi rajulin wāḥidin minkum mā naqaṣa dhālika min mulkī shayʾan. yā ʿibādī, law anna awwalakum wa-ākhirakum wa-insakum wa-jinnakum qāmū fī ṣaʿīdin wāḥidin fa-saʾalūnī fa-aʿṭaytu kulla wāḥidin masʾalatahu mā naqaṣa dhālika mimmā ʿindī illā kamā yanquṣu l-mikhyaṭu idhā udkhila l-baḥra. yā ʿibādī, innamā hiya aʿmālukum uḥṣīhā lakum thumma uwaffīkum iyyāhā, fa-man wajada khayran fa-l-yaḥmadi Llāha, wa-man wajada ghayra dhālika fa-lā yalūmanna illā nafsahu.',
  'ʿan Abî Dharrin al-Ghifârî (radia Llâhou ʿanhou) ʿani n-Nabiyyi (salla Llâhou ʿalayhi wa sallam) fîmâ yarwîhi ʿan Rabbihi tabâraka wa taʿâlâ annahou qâla : yâ ʿibâdî, innî harramtou z-zoulma ʿalâ nafsî wa jaʿaltouhou baynakoum mouharraman fa-lâ tazâlamô. yâ ʿibâdî, koulloukoum dâlloun illâ man hadaytouhou fa-stahdôunî ahdikoum. yâ ʿibâdî, koulloukoum jâʾiʿoun illâ man atʿamtouhou fa-statʿimôunî outʿimkoum. yâ ʿibâdî, koulloukoum ʿârin illâ man kasawtouhou fa-staksôunî aksoukoum. yâ ʿibâdî, innakoum toukhtiʾôuna bi-l-layli wa n-nahâri wa anâ aghfirou dh-dhounôuba jamîʿan fa-staghfirôunî aghfir lakoum. yâ ʿibâdî, innakoum lan tabloughô darrî fa-tadourrôunî wa lan tabloughô nafʿî fa-tanfaʿôunî. yâ ʿibâdî, law anna awwalakoum wa âkhirakoum wa insakoum wa jinnakoum kânô ʿalâ atqâ qalbi rajoulin wâhidin minkoum mâ zâda dhâlika fî moulkî chayʾan. yâ ʿibâdî, law anna awwalakoum wa âkhirakoum wa insakoum wa jinnakoum kânô ʿalâ afjari qalbi rajoulin wâhidin minkoum mâ naqasa dhâlika min moulkî chayʾan. yâ ʿibâdî, law anna awwalakoum wa âkhirakoum wa insakoum wa jinnakoum qâmô fî saʿîdin wâhidin fa-saʾalôunî fa-aʿtaytou koulla wâhidin masʾalatahou mâ naqasa dhâlika mimmâ ʿindî illâ kamâ yanqousou l-mikhyatou idhâ oudkhila l-bahra. yâ ʿibâdî, innamâ hiya aʿmâloukoum ouhsîhâ lakoum thoumma ouwaffîkoum iyyâhâ, fa-man wajada khayran fa-l-yahmadi Llâha, wa man wajada ghayra dhâlika fa-lâ yaloumanna illâ nafsahou.',
  'ʿan Abī Dharrin al-Ghifārijji (radiya Llāhu ʿanhu) ʿani n-Nabijji (salla Llāhu ʿalaihi wa-sallam) fīmā jarwīhi ʿan Rabbihi tabāraka wa-taʿālā annahu qāla: jā ʿibādī, innī harramtu z-zulma ʿalā nafsī wa-dschaʿaltuhu bainakum muharraman fa-lā tazālamū. jā ʿibādī, kullukum dāllun illā man hadaituhu fa-stahdūnī ahdikum. jā ʿibādī, kullukum dschāʾiʿun illā man atʿamtuhu fa-statʿimūnī utʿimkum. jā ʿibādī, kullukum ʿārin illā man kasautuhu fa-staksūnī aksukum. jā ʿibādī, innakum tuchtiʾūna bi-l-laili wa-n-nahāri wa-anā aghfiru dh-dhunūba dschamīʿan fa-staghfirūnī aghfir lakum. jā ʿibādī, innakum lan tablughū darrī fa-tadurrūnī wa-lan tablughū nafʿī fa-tanfaʿūnī. jā ʿibādī, lau anna awwalakum wa-āchirakum wa-insakum wa-dschinnakum kānū ʿalā atqā qalbi radschulin wāhidin minkum mā zāda dhālika fī mulkī schaiʾan. jā ʿibādī, lau anna awwalakum wa-āchirakum wa-insakum wa-dschinnakum kānū ʿalā afdschari qalbi radschulin wāhidin minkum mā naqasa dhālika min mulkī schaiʾan. jā ʿibādī, lau anna awwalakum wa-āchirakum wa-insakum wa-dschinnakum qāmū fī saʿīdin wāhidin fa-saʾalūnī fa-aʿtaitu kulla wāhidin masʾalatahu mā naqasa dhālika mimmā ʿindī illā kamā janqusu l-michjatu idhā udchila l-bahra. jā ʿibādī, innamā hija aʿmālukum uhsīhā lakum thumma uwaffīkum ijjāhā, fa-man wadschada chairan fa-l-jahmadi Llāha, wa-man wadschada ghaira dhālika fa-lā jalūmanna illā nafsahu.',
  'ʿan Abie Dharrin al-Ghifaarijji (radia Llaahoe ʿanhoe) ʿani n-Nabijji (salla Llaahoe ʿalaihi wa-sallam) fiemaa jarwiehi ʿan Rabbihi tabaaraka wa-taʿaalaa annahoe qaala: jaa ʿibaadie, innie harramtoe z-zoelma ʿalaa nafsie wa-dzjaʿaltoehoe bainakoem moeharraman fa-laa tazaalamoe. jaa ʿibaadie, koelloekoem daalloen illaa man hadaitoehoe fa-stahdoenie ahdikoem. jaa ʿibaadie, koelloekoem dzjaaʾiʿoen illaa man atʿamtoehoe fa-statʿimoenie oetʿimkoem. jaa ʿibaadie, koelloekoem ʿaarin illaa man kasautoehoe fa-staksoenie aksoekoem. jaa ʿibaadie, innakoem toechtiʾoena bi-l-laili wa-n-nahaari wa-anaa aghfiroe dh-dhoenoeba dzjamieʿan fa-staghfiroenie aghfir lakoem. jaa ʿibaadie, innakoem lan tabloeghoe darrie fa-tadoerroenie wa-lan tabloeghoe nafʿie fa-tanfaʿoenie. jaa ʿibaadie, lau anna awwalakoem wa-aachirakoem wa-insakoem wa-dzjinnakoem kaanoe ʿalaa atqaa qalbi radzjoelin waahidin minkoem maa zaada dhaalika fie moelkie sjaiʾan. jaa ʿibaadie, lau anna awwalakoem wa-aachirakoem wa-insakoem wa-dzjinnakoem kaanoe ʿalaa afdzjari qalbi radzjoelin waahidin minkoem maa naqasa dhaalika min moelkie sjaiʾan. jaa ʿibaadie, lau anna awwalakoem wa-aachirakoem wa-insakoem wa-dzjinnakoem qaamoe fie saʿiedin waahidin fa-saʾaloenie fa-aʿtaitoe koella waahidin masʾalatahoe maa naqasa dhaalika mimmaa ʿindie illaa kamaa janqoesoe l-michjatoe idhaa oedchila l-bahra. jaa ʿibaadie, innamaa hija aʿmaaloekoem oehsiehaa lakoem thoemma oewaffiekoem ijjaahaa, fa-man wadzjada chairan fa-l-jahmadi Llaaha, wa-man wadzjada ghaira dhaalika fa-laa jaloemanna illaa nafsahoe.',
  'an Ebî Zer el-Gıfârî (radıyallâhu anh), ani''n-Nebiyyi (s.a.v.) fîmâ yervîhi an Rabbihî tebâreke ve teâlâ ennehû kâle: yâ ibâdî, innî harramtu''z-zulme alâ nefsî ve cealtuhû beyneküm muharramen fe-lâ tezâlemû. yâ ibâdî, küllüküm dâllun illâ men hedeytuhû fe''stehdûnî ehdiküm. yâ ibâdî, küllüküm câiʿun illâ men atʿamtuhû fe''statʿimûnî utʿimküm. yâ ibâdî, küllüküm ârin illâ men kesevtuhû fe''steksûnî eksüküm. yâ ibâdî, inneküm tuhtiûne bi''l-leyli ve''n-nehâri ve enâ agfiru''z-zünûbe cemîʿan fe''stagfirûnî agfir leküm. yâ ibâdî, inneküm len teblugû darrî fe-tedurrûnî ve len teblugû nefʿî fe-tenfeʿûnî. yâ ibâdî, lev enne evveleküm ve âhireküm ve inseküm ve cinneküm kânû alâ etkâ kalbi raculin vâhidin minküm mâ zâde zâlike fî mülkî şeyʾen. yâ ibâdî, lev enne evveleküm ve âhireküm ve inseküm ve cinneküm kânû alâ efceri kalbi raculin vâhidin minküm mâ nekasa zâlike min mülkî şeyʾen. yâ ibâdî, lev enne evveleküm ve âhireküm ve inseküm ve cinneküm kâmû fî saʿîdin vâhidin fe-seelûnî fe-aʿtaytu külle vâhidin mesʾeletehû mâ nekasa zâlike mimmâ indî illâ kemâ yenkusu''l-mihyatu izâ udhile''l-bahra. yâ ibâdî, innemâ hiye aʿmâlüküm uhsîhâ leküm summe uveffîküm iyyâhâ, fe-men vecede hayran fe''l-yahmedi''llâhe, ve men vecede gayra zâlike fe-lâ yelûmenne illâ nefsehû.',
  'an Abi Dzarrin al-Ghifari (radhiyallahu ʿanhu) ʿanin-Nabiyyi (shallallahu ʿalaihi wa sallam) fima yarwihi ʿan Rabbihi tabaraka wa taʿala annahu qala: ya ʿibadi, inni harramtuzh-zhulma ʿala nafsi wa jaʿaltuhu bainakum muharraman fala tazhalamu. ya ʿibadi, kullukum dhallun illa man hadaituhu fastahduni ahdikum. ya ʿibadi, kullukum jaʾiʿun illa man athʿamtuhu fastathʿimuni uthʿimkum. ya ʿibadi, kullukum ʿarin illa man kasautuhu fastaksuni aksukum. ya ʿibadi, innakum tukhthiʾuna bil-laili wan-nahari wa ana aghfirudz-dzunuba jamiʿan fastaghfiruni aghfir lakum. ya ʿibadi, innakum lan tablughu dharri fatadhurruni wa lan tablughu nafʿi fatanfaʿuni. ya ʿibadi, lau anna awwalakum wa akhirakum wa insakum wa jinnakum kanu ʿala atqa qalbi rajulin wahidin minkum ma zada dzalika fi mulki syaiʾan. ya ʿibadi, lau anna awwalakum wa akhirakum wa insakum wa jinnakum kanu ʿala afjari qalbi rajulin wahidin minkum ma naqasha dzalika min mulki syaiʾan. ya ʿibadi, lau anna awwalakum wa akhirakum wa insakum wa jinnakum qamu fi shaʿidin wahidin fasaʾaluni faʾaʿthaitu kulla wahidin masʾalatahu ma naqasha dzalika mimma ʿindi illa kama yanqushul-mikhyathu idza udkhilal-bahra. ya ʿibadi, innama hiya aʿmalukum uhshiha lakum tsumma uwaffikum iyyaha, faman wajada khairan falyahmadillaha, wa man wajada ghaira dzalika fala yalumanna illa nafsahu.',
  'یا عِبادِی، اِنّی حَرَّمتُ الظُّلمَ عَلٰی نَفسی وَجَعَلتُہُ بَینَکُم مُحَرَّمًا فَلا تَظالَمُوا۔ یا عِبادِی، کُلُّکُم ضالٌّ اِلّا مَن ہَدَیتُہُ فَاستَہدُونی اَہدِکُم۔ یا عِبادِی، کُلُّکُم جائِعٌ اِلّا مَن اَطعَمتُہُ فَاستَطعِمُونی اُطعِمکُم۔ یا عِبادِی، کُلُّکُم عارٍ اِلّا مَن کَسَوتُہُ فَاستَکسُونی اَکسُکُم۔ یا عِبادِی، اِنَّکُم تُخطِئُونَ بِاللَّیلِ وَالنَّہارِ وَاَنا اَغفِرُ الذُّنُوبَ جَمیعًا فَاستَغفِرُونی اَغفِر لَکُم۔ یا عِبادِی، اِنَّکُم لَن تَبلُغُوا ضَرّی فَتَضُرُّونی وَلَن تَبلُغُوا نَفعی فَتَنفَعُونی۔ یا عِبادِی، لَو اَنَّ اَوَّلَکُم وَآخِرَکُم وَاِنسَکُم وَجِنَّکُم کانُوا عَلٰی اَتقٰی قَلبِ رَجُلٍ واحِدٍ مِنکُم ما زادَ ذٰلِکَ فی مُلکی شَیئًا۔ یا عِبادِی، لَو اَنَّ اَوَّلَکُم وَآخِرَکُم وَاِنسَکُم وَجِنَّکُم کانُوا عَلٰی اَفجَرِ قَلبِ رَجُلٍ واحِدٍ مِنکُم ما نَقَصَ ذٰلِکَ مِن مُلکی شَیئًا۔ یا عِبادِی، لَو اَنَّ اَوَّلَکُم وَآخِرَکُم وَاِنسَکُم وَجِنَّکُم قامُوا فی صَعیدٍ واحِدٍ فَسَاَلُونی فَاَعطَیتُ کُلَّ واحِدٍ مَسئَلَتَہُ ما نَقَصَ ذٰلِکَ مِمّا عِندی اِلّا کَما یَنقُصُ المِخیَطُ اِذا اُدخِلَ البَحرَ۔ یا عِبادِی، اِنَّما ہِیَ اَعمالُکُم اُحصیہا لَکُم ثُمَّ اُوَفّیکُم اِیّاہا، فَمَن وَجَدَ خَیرًا فَلیَحمَدِ اللہَ، وَمَن وَجَدَ غَیرَ ذٰلِکَ فَلا یَلُومَنَّ اِلّا نَفسَہُ۔',
  'ইয়া ইবাদী, ইন্নী হাররামতুয যুলমা আলা নাফসী ওয়া জাআলতুহু বাইনাকুম মুহাররামান ফালা তাযালামূ। ইয়া ইবাদী, কুল্লুকুম দাল্লুন ইল্লা মান হাদাইতুহু ফাসতাহদূনী আহদিকুম। ইয়া ইবাদী, কুল্লুকুম জাইউন ইল্লা মান আতআমতুহু ফাসতাতইমূনী উতইমকুম। ইয়া ইবাদী, কুল্লুকুম আরিন ইল্লা মান কাসাওতুহু ফাসতাকসূনী আকসুকুম। ইয়া ইবাদী, ইন্নাকুম তুখতিঊনা বিল্লাইলি ওয়ান্নাহারি ওয়া আনা আগফিরুয যুনূবা জামীআন ফাসতাগফিরূনী আগফির লাকুম। ইয়া ইবাদী, ইন্নাকুম লান তাবলুগূ দাররী ফাতাদুররূনী ওয়া লান তাবলুগূ নাফঈ ফাতানফাঊনী। ইয়া ইবাদী, লাও আন্না আওয়ালাকুম ওয়া আখিরাকুম ওয়া ইনসাকুম ওয়া জিন্নাকুম কানূ আলা আতকা কালবি রাজুলিন ওয়াহিদিন মিনকুম মা যাদা যালিকা ফী মুলকী শাইআন। ইয়া ইবাদী, লাও আন্না আওয়ালাকুম ওয়া আখিরাকুম ওয়া ইনসাকুম ওয়া জিন্নাকুম কানূ আলা আফজারি কালবি রাজুলিন ওয়াহিদিন মিনকুম মা নাকাসা যালিকা মিন মুলকী শাইআন। ইয়া ইবাদী, লাও আন্না আওয়ালাকুম ওয়া আখিরাকুম ওয়া ইনসাকুম ওয়া জিন্নাকুম কামূ ফী সাঈদিন ওয়াহিদিন ফাসাআলূনী ফাআতাইতু কুল্লা ওয়াহিদিন মাসআলাতাহু মা নাকাসা যালিকা মিম্মা ইন্দী ইল্লা কামা ইয়ানকুসুল মিখইয়াতু ইযা উদখিলাল বাহরা। ইয়া ইবাদী, ইন্নামা হিয়া আমালুকুম উহসীহা লাকুম সুম্মা উওয়াফফীকুম ইয়্যাহা, ফামান ওয়াজাদা খাইরান ফালইয়াহমাদিল্লাহা, ওয়া মান ওয়াজাদা গাইরা যালিকা ফালা ইয়ালূমান্না ইল্লা নাফসাহু।',
  'an Abi Dzarrin al-Ghifari (radhiallahu ʿanhu) ʿanin-Nabiyyi (sallallahu ʿalaihi wa sallam) fima yarwihi ʿan Rabbihi tabaraka wa taʿala annahu qala: ya ʿibadi, inni harramtuz-zulma ʿala nafsi wa jaʿaltuhu bainakum muharraman fala tazalamu. ya ʿibadi, kullukum dollun illa man hadaituhu fastahduni ahdikum. ya ʿibadi, kullukum jaʾiʿun illa man atʿamtuhu fastatʿimuni utʿimkum. ya ʿibadi, kullukum ʿarin illa man kasautuhu fastaksuni aksukum. ya ʿibadi, innakum tukhtiʾuna bil-laili wan-nahari wa ana aghfiruz-zunuba jamiʿan fastaghfiruni aghfir lakum. ya ʿibadi, innakum lan tablughu dorri fatadurruni wa lan tablughu nafʿi fatanfaʿuni. ya ʿibadi, lau anna awwalakum wa akhirakum wa insakum wa jinnakum kanu ʿala atqa qalbi rajulin wahidin minkum ma zada zalika fi mulki syaiʾan. ya ʿibadi, lau anna awwalakum wa akhirakum wa insakum wa jinnakum kanu ʿala afjari qalbi rajulin wahidin minkum ma naqasa zalika min mulki syaiʾan. ya ʿibadi, lau anna awwalakum wa akhirakum wa insakum wa jinnakum qamu fi soʿidin wahidin fasaʾaluni faʾaʿtaitu kulla wahidin masʾalatahu ma naqasa zalika mimma ʿindi illa kama yanqusul-mikhyatu iza udkhilal-bahra. ya ʿibadi, innama hiya aʿmalukum uhsiha lakum tsumma uwaffikum iyyaha, faman wajada khairan falyahmadillaha, wa man wajada ghaira zalika fala yalumanna illa nafsahu.',
  'ан Аби Зарр аль-Гифари (радыйаллаху анху), ани н-Набийи (саллаллаху алейхи ва саллам) фима ярвихи ан Раббихи табарака ва таʿаля аннаху каля: я ибади, инни харрамту з-зульма аля нафси ва джаальтуху байнакум мухарраман фа-ля тазаламу. я ибади, куллюкум даллюн илля ман хадайтуху фа-стахдуни ахдикум. я ибади, куллюкум джаиʿун илля ман атʿамтуху фа-статʿимуни утʿимкум. я ибади, куллюкум арин илля ман касавтуху фа-стаксуни аксукум. я ибади, иннакум тухтиʾуна би-ль-ляйли ва-н-нахари ва ана агфиру з-зунуба джамиʿан фа-стагфируни агфир лякум. я ибади, иннакум лян таблугу дарри фа-тадурруни ва лян таблугу нафʿи фа-танфаʿуни. я ибади, ляу анна аввалякум ва ахиракум ва инсакум ва джиннакум кану аля атка кальби раджулин вахидин минкум ма зада залика фи мульки шайʾан. я ибади, ляу анна аввалякум ва ахиракум ва инсакум ва джиннакум кану аля афджари кальби раджулин вахидин минкум ма накаса залика мин мульки шайʾан. я ибади, ляу анна аввалякум ва ахиракум ва инсакум ва джиннакум каму фи саʿидин вахидин фа-саʾалуни фа-аʿтайту кулля вахидин масʾалятаху ма накаса залика мимма инди илля кама янкусу ль-михйату иза удхиля ль-бахра. я ибади, иннама хийа аʿмалюкум ухсиха лякум сумма уваффикум иййаха, фа-ман ваджада хайран фа-ль-яхмади Ллаха, ва ман ваджада гайра залика фа-ля ялуманна илля нафсаху.',
  -- translation
  'On the authority of Abu Dharr al-Ghifari (may Allah be pleased with him), from the Prophet ﷺ, in what he related from his Lord, Blessed and Exalted, that He said: "O My servants, I have forbidden injustice for Myself and made it forbidden among you, so do not wrong one another. O My servants, all of you are astray except those I have guided, so ask Me for guidance and I will guide you. O My servants, all of you are hungry except those I have fed, so ask Me for food and I will feed you. O My servants, all of you are naked except those I have clothed, so ask Me for clothing and I will clothe you. O My servants, you sin by night and by day, and I forgive all sins, so ask My forgiveness and I will forgive you. O My servants, you will never reach the point of harming Me so as to harm Me, nor the point of benefiting Me so as to benefit Me. O My servants, were the first of you and the last of you, the humans of you and the jinn of you, to be as pious as the most pious heart of any one man among you, that would not increase My dominion in anything. O My servants, were the first of you and the last of you, the humans of you and the jinn of you, to be as wicked as the most wicked heart of any one man among you, that would not decrease My dominion in anything. O My servants, were the first of you and the last of you, the humans of you and the jinn of you, to stand on one plain and ask of Me, and were I to give each one what he asked, that would not decrease what I have any more than a needle decreases the sea when dipped into it. O My servants, these are only your deeds which I record for you, then I repay you for them in full. So whoever finds good, let him praise Allah; and whoever finds otherwise, let him blame none but himself."',
  'D''après Abû Dharr al-Ghifârî (qu''Allah l''agrée), le Prophète ﷺ, rapportant les paroles de son Seigneur, Béni et Très-Haut, a dit : « Ô Mes serviteurs, Je Me suis interdit l''injustice à Moi-même et Je l''ai rendue interdite entre vous : ne soyez donc pas injustes les uns envers les autres. Ô Mes serviteurs, vous êtes tous égarés sauf ceux que J''ai guidés ; demandez-Moi donc de vous guider et Je le ferai. Ô Mes serviteurs, vous êtes tous affamés sauf ceux que J''ai nourris ; demandez-Moi votre nourriture et Je vous la donnerai. Ô Mes serviteurs, vous êtes tous nus sauf ceux que J''ai vêtus ; demandez-Moi de vous vêtir et Je le ferai. Ô Mes serviteurs, vous commettez des fautes la nuit et le jour, et c''est Moi qui pardonne toutes les fautes ; demandez Mon pardon et Je vous pardonnerai. Ô Mes serviteurs, vous ne sauriez atteindre le pouvoir de Me nuire pour Me nuire, ni celui de M''être utile pour M''être utile. Ô Mes serviteurs, si les premiers et les derniers d''entre vous, les hommes et les djinns parmi vous, avaient le cœur du plus pieux d''entre vous, cela n''ajouterait rien à Mon Royaume. Ô Mes serviteurs, si les premiers et les derniers d''entre vous, les hommes et les djinns parmi vous, avaient le cœur du plus impie d''entre vous, cela ne diminuerait en rien Mon Royaume. Ô Mes serviteurs, si les premiers et les derniers d''entre vous, les hommes et les djinns parmi vous, se tenaient sur une même plaine et Me demandaient, et que Je donnais à chacun ce qu''il demande, cela ne diminuerait en rien ce que J''ai, pas plus qu''une aiguille plongée dans la mer ne la diminue. Ô Mes serviteurs, ce ne sont que vos actions que Je compte pour vous, puis Je vous les rétribue pleinement. Que celui qui trouve le bien loue Allah, et que celui qui trouve autre chose ne s''en prenne qu''à lui-même. »',
  'Nach Abu Dharr al-Ghifari (möge Allah mit ihm zufrieden sein), vom Propheten ﷺ, in dem, was er von seinem Herrn, dem Gesegneten und Erhabenen, überliefert, dass Er sagte: „O Meine Diener, Ich habe Mir selbst die Ungerechtigkeit verboten und sie unter euch verboten gemacht, so tut einander kein Unrecht. O Meine Diener, ihr alle seid irregehend außer denen, die Ich rechtgeleitet habe, so bittet Mich um Rechtleitung, und Ich leite euch recht. O Meine Diener, ihr alle seid hungrig außer denen, die Ich gespeist habe, so bittet Mich um Speise, und Ich speise euch. O Meine Diener, ihr alle seid nackt außer denen, die Ich gekleidet habe, so bittet Mich um Kleidung, und Ich kleide euch. O Meine Diener, ihr sündigt bei Nacht und bei Tag, und Ich vergebe alle Sünden, so bittet Mich um Vergebung, und Ich vergebe euch. O Meine Diener, ihr werdet Mir niemals schaden können, um Mir zu schaden, noch Mir nützen können, um Mir zu nützen. O Meine Diener, wären die Ersten von euch und die Letzten von euch, die Menschen von euch und die Dschinn von euch, so fromm wie das frommste Herz eines einzigen Mannes unter euch, das würde Meine Herrschaft um nichts vermehren. O Meine Diener, wären die Ersten von euch und die Letzten von euch, die Menschen von euch und die Dschinn von euch, so verdorben wie das verdorbenste Herz eines einzigen Mannes unter euch, das würde Meine Herrschaft um nichts mindern. O Meine Diener, würden die Ersten von euch und die Letzten von euch, die Menschen von euch und die Dschinn von euch, auf einer Ebene stehen und Mich bitten, und würde Ich jedem geben, worum er bittet, das würde das, was Ich habe, nicht mehr mindern, als eine Nadel das Meer mindert, wenn sie hineingetaucht wird. O Meine Diener, dies sind nur eure Taten, die Ich für euch verzeichne und für die Ich euch dann voll vergelte. Wer also Gutes findet, der lobe Allah; und wer anderes findet, der tadle nur sich selbst."',
  'Op gezag van Abu Dharr al-Ghifari (moge Allah tevreden met hem zijn), van de Profeet ﷺ, in wat hij overlevert van zijn Heer, de Gezegende en Verhevene, dat Hij zei: „O Mijn dienaren, Ik heb Mijzelf het onrecht verboden en het onder jullie verboden gemaakt, dus doe elkaar geen onrecht. O Mijn dienaren, jullie zijn allen dwalend behalve wie Ik heb geleid, dus vraag Mij om leiding en Ik zal jullie leiden. O Mijn dienaren, jullie zijn allen hongerig behalve wie Ik heb gevoed, dus vraag Mij om voedsel en Ik zal jullie voeden. O Mijn dienaren, jullie zijn allen naakt behalve wie Ik heb gekleed, dus vraag Mij om kleding en Ik zal jullie kleden. O Mijn dienaren, jullie zondigen bij nacht en bij dag, en Ik vergeef alle zonden, dus vraag Mij om vergeving en Ik zal jullie vergeven. O Mijn dienaren, jullie zullen Mij nooit kunnen schaden om Mij te schaden, noch Mij kunnen baten om Mij te baten. O Mijn dienaren, als de eersten van jullie en de laatsten van jullie, de mensen van jullie en de djinn van jullie, zo vroom waren als het vroomste hart van één man onder jullie, dan zou dat Mijn heerschappij in niets vermeerderen. O Mijn dienaren, als de eersten van jullie en de laatsten van jullie, de mensen van jullie en de djinn van jullie, zo slecht waren als het slechtste hart van één man onder jullie, dan zou dat Mijn heerschappij in niets verminderen. O Mijn dienaren, als de eersten van jullie en de laatsten van jullie, de mensen van jullie en de djinn van jullie, op één vlakte zouden staan en Mij zouden vragen, en Ik aan ieder zou geven wat hij vroeg, dan zou dat wat Ik heb niet meer verminderen dan een naald de zee vermindert wanneer zij erin wordt gedompeld. O Mijn dienaren, dit zijn slechts jullie daden die Ik voor jullie optel, waarna Ik jullie ze volledig vergeld. Wie dus het goede vindt, laat hem Allah prijzen; en wie iets anders vindt, laat hem niemand dan zichzelf verwijten."',
  'Ebû Zer el-Gıfârî''den (Allah ondan razı olsun), Nebî''nin ﷺ Rabbi Tebâreke ve Teâlâ''dan rivayet ettiğine göre buyurdu ki: „Ey kullarım! Ben zulmü kendime haram kıldım ve onu aranızda da haram kıldım; öyleyse birbirinize zulmetmeyin. Ey kullarım! Hidayet ettiklerim dışında hepiniz sapkınsınız; benden hidayet isteyin, size hidayet edeyim. Ey kullarım! Doyurduklarım dışında hepiniz açsınız; benden yiyecek isteyin, sizi doyurayım. Ey kullarım! Giydirdiklerim dışında hepiniz çıplaksınız; benden giyecek isteyin, sizi giydireyim. Ey kullarım! Siz gece gündüz hata edersiniz, ben ise bütün günahları bağışlarım; benden bağışlanma dileyin, sizi bağışlayayım. Ey kullarım! Bana zarar verecek dereceye ulaşamazsınız ki bana zarar veresiniz, bana fayda verecek dereceye de ulaşamazsınız ki bana fayda veresiniz. Ey kullarım! Eğer önceki ve sonraki, insan ve cinleriniz, sizden en takvâlı bir adamın kalbi üzere olsalardı, bu mülkümde hiçbir şey artırmazdı. Ey kullarım! Eğer önceki ve sonraki, insan ve cinleriniz, sizden en günahkâr bir adamın kalbi üzere olsalardı, bu mülkümden hiçbir şey eksiltmezdi. Ey kullarım! Eğer önceki ve sonraki, insan ve cinleriniz bir düzlükte durup benden isteseler ve ben her birine isteğini versem, bu, iğnenin denize daldırıldığında onu eksilttiği kadar bile yanımdakini eksiltmezdi. Ey kullarım! Onlar ancak sizin amellerinizdir; onları sizin için sayar, sonra karşılığını tam veririm. Kim hayır bulursa Allah''a hamdetsin, kim de bundan başkasını bulursa kendinden başkasını kınamasın."',
  'Dari Abu Dzarr al-Ghifari (semoga Allah meridhainya), dari Nabi ﷺ tentang apa yang beliau riwayatkan dari Rabbnya Tabaraka wa Taʿala, bahwa Dia berfirman: "Wahai hamba-hamba-Ku! Sesungguhnya Aku mengharamkan kezaliman atas diri-Ku dan Aku menjadikannya haram di antara kalian, maka janganlah kalian saling menzalimi. Wahai hamba-hamba-Ku! Kalian semua sesat kecuali yang Aku beri petunjuk, maka mintalah petunjuk kepada-Ku niscaya Aku memberi kalian petunjuk. Wahai hamba-hamba-Ku! Kalian semua lapar kecuali yang Aku beri makan, maka mintalah makan kepada-Ku niscaya Aku memberi kalian makan. Wahai hamba-hamba-Ku! Kalian semua telanjang kecuali yang Aku beri pakaian, maka mintalah pakaian kepada-Ku niscaya Aku memberi kalian pakaian. Wahai hamba-hamba-Ku! Sesungguhnya kalian berbuat dosa di malam dan siang hari, dan Aku mengampuni segala dosa, maka mintalah ampun kepada-Ku niscaya Aku mengampuni kalian. Wahai hamba-hamba-Ku! Sesungguhnya kalian tidak akan mampu mendatangkan mudarat untuk memudaratkan-Ku, dan tidak akan mampu mendatangkan manfaat untuk memberi manfaat kepada-Ku. Wahai hamba-hamba-Ku! Seandainya orang pertama dan terakhir dari kalian, manusia dan jin dari kalian, berada di atas hati orang yang paling bertakwa di antara kalian, hal itu tidak menambah kerajaan-Ku sedikit pun. Wahai hamba-hamba-Ku! Seandainya orang pertama dan terakhir dari kalian, manusia dan jin dari kalian, berada di atas hati orang yang paling durhaka di antara kalian, hal itu tidak mengurangi kerajaan-Ku sedikit pun. Wahai hamba-hamba-Ku! Seandainya orang pertama dan terakhir dari kalian, manusia dan jin dari kalian, berdiri di satu tanah lapang lalu meminta kepada-Ku, kemudian Aku memberi setiap orang permintaannya, hal itu tidak mengurangi apa yang ada pada-Ku kecuali seperti berkurangnya jarum apabila dicelupkan ke laut. Wahai hamba-hamba-Ku! Sesungguhnya itu hanyalah amal-amal kalian yang Aku hitung untuk kalian, kemudian Aku memberikan balasannya secara penuh. Maka barangsiapa mendapati kebaikan hendaklah ia memuji Allah, dan barangsiapa mendapati selain itu janganlah ia mencela kecuali dirinya sendiri."',
  'ابو ذر الغفاری رضی اللہ عنہ سے، نبی ﷺ سے روایت ہے، اس میں جو آپ اپنے رب تبارک و تعالیٰ سے روایت کرتے ہیں کہ اس نے فرمایا: ”اے میرے بندو! میں نے ظلم کو اپنے اوپر حرام کر لیا ہے اور تمہارے درمیان بھی اسے حرام کیا ہے، پس ایک دوسرے پر ظلم نہ کرو۔ اے میرے بندو! تم سب گمراہ ہو سوائے اس کے جسے میں ہدایت دوں، پس مجھ سے ہدایت مانگو میں تمہیں ہدایت دوں گا۔ اے میرے بندو! تم سب بھوکے ہو سوائے اس کے جسے میں کھلاؤں، پس مجھ سے کھانا مانگو میں تمہیں کھلاؤں گا۔ اے میرے بندو! تم سب ننگے ہو سوائے اس کے جسے میں پہناؤں، پس مجھ سے لباس مانگو میں تمہیں پہناؤں گا۔ اے میرے بندو! تم رات اور دن خطائیں کرتے ہو اور میں تمام گناہ بخشتا ہوں، پس مجھ سے بخشش مانگو میں تمہیں بخش دوں گا۔ اے میرے بندو! تم میرے نقصان تک نہیں پہنچ سکتے کہ مجھے نقصان پہنچاؤ، اور نہ میرے نفع تک پہنچ سکتے ہو کہ مجھے نفع پہنچاؤ۔ اے میرے بندو! اگر تمہارے اگلے اور پچھلے، تمہارے انسان اور جن سب تم میں سب سے زیادہ پرہیزگار آدمی کے دل پر ہو جائیں تو اس سے میری بادشاہی میں کچھ اضافہ نہ ہوگا۔ اے میرے بندو! اگر تمہارے اگلے اور پچھلے، تمہارے انسان اور جن سب تم میں سب سے زیادہ بدکار آدمی کے دل پر ہو جائیں تو اس سے میری بادشاہی میں کچھ کمی نہ ہوگی۔ اے میرے بندو! اگر تمہارے اگلے اور پچھلے، تمہارے انسان اور جن ایک ہی میدان میں کھڑے ہو کر مجھ سے مانگیں اور میں ہر ایک کو اس کا سوال دے دوں تو اس سے میرے پاس جو کچھ ہے اس میں اتنی بھی کمی نہ ہوگی جتنی سوئی کو سمندر میں ڈبو کر نکالنے سے ہوتی ہے۔ اے میرے بندو! یہ تو صرف تمہارے اعمال ہیں جنہیں میں تمہارے لیے شمار کرتا ہوں پھر تمہیں ان کا پورا بدلہ دیتا ہوں؛ پس جو بھلائی پائے وہ اللہ کی حمد کرے، اور جو اس کے سوا کچھ پائے وہ اپنے سوا کسی کو ملامت نہ کرے۔“',
  'আবু যার আল-গিফারী (রাদিয়াল্লাহু আনহু) থেকে, নবী ﷺ থেকে বর্ণিত, তিনি যা তাঁর রব তাবারাকা ওয়া তাআলা থেকে বর্ণনা করেন যে তিনি বলেছেন: "হে আমার বান্দারা! আমি যুলমকে নিজের উপর হারাম করেছি এবং তোমাদের মধ্যেও তা হারাম করেছি, সুতরাং একে অপরের প্রতি যুলম করো না। হে আমার বান্দারা! তোমরা সবাই পথভ্রষ্ট, কেবল তাকে ছাড়া যাকে আমি হিদায়াত দিই; সুতরাং আমার কাছে হিদায়াত চাও, আমি তোমাদের হিদায়াত দেব। হে আমার বান্দারা! তোমরা সবাই ক্ষুধার্ত, কেবল তাকে ছাড়া যাকে আমি খাওয়াই; সুতরাং আমার কাছে খাবার চাও, আমি তোমাদের খাওয়াব। হে আমার বান্দারা! তোমরা সবাই উলঙ্গ, কেবল তাকে ছাড়া যাকে আমি পরিধান করাই; সুতরাং আমার কাছে পোশাক চাও, আমি তোমাদের পরিধান করাব। হে আমার বান্দারা! তোমরা রাত ও দিন ভুল করো, আর আমি সমস্ত গুনাহ ক্ষমা করি; সুতরাং আমার কাছে ক্ষমা চাও, আমি তোমাদের ক্ষমা করব। হে আমার বান্দারা! তোমরা আমার ক্ষতি করার সামর্থ্যে পৌঁছাতে পারবে না যে আমার ক্ষতি করবে, আর আমার উপকার করার সামর্থ্যেও পৌঁছাতে পারবে না যে আমার উপকার করবে। হে আমার বান্দারা! যদি তোমাদের প্রথম ও শেষ, তোমাদের মানুষ ও জিন সকলে তোমাদের মধ্যে সবচেয়ে মুত্তাকী ব্যক্তির অন্তরের মতো হয়ে যায়, তবে তা আমার রাজত্বে কিছুই বৃদ্ধি করবে না। হে আমার বান্দারা! যদি তোমাদের প্রথম ও শেষ, তোমাদের মানুষ ও জিন সকলে তোমাদের মধ্যে সবচেয়ে পাপিষ্ঠ ব্যক্তির অন্তরের মতো হয়ে যায়, তবে তা আমার রাজত্বে কিছুই হ্রাস করবে না। হে আমার বান্দারা! যদি তোমাদের প্রথম ও শেষ, তোমাদের মানুষ ও জিন এক ময়দানে দাঁড়িয়ে আমার কাছে চায় এবং আমি প্রত্যেককে তার চাওয়া দিয়ে দিই, তবে তা আমার কাছে যা আছে তা থেকে ততটুকুও হ্রাস করবে না যতটুকু সুই সমুদ্রে ডুবিয়ে নিলে হ্রাস পায়। হে আমার বান্দারা! এগুলো তো কেবল তোমাদের আমল, যা আমি তোমাদের জন্য গণনা করি, অতঃপর তোমাদের তার পূর্ণ প্রতিদান দিই; সুতরাং যে কল্যাণ পায় সে যেন আল্লাহর প্রশংসা করে, আর যে এর ভিন্ন কিছু পায় সে যেন নিজেকে ছাড়া কাউকে দোষ না দেয়।"',
  'Daripada Abu Dzarr al-Ghifari (semoga Allah meredainya), daripada Nabi ﷺ tentang apa yang baginda riwayatkan daripada Tuhannya Tabaraka wa Taʿala, bahawa Dia berfirman: "Wahai hamba-hamba-Ku! Sesungguhnya Aku mengharamkan kezaliman atas diri-Ku dan Aku menjadikannya haram di antara kamu, maka janganlah kamu saling menzalimi. Wahai hamba-hamba-Ku! Kamu semua sesat kecuali yang Aku beri petunjuk, maka mintalah petunjuk kepada-Ku nescaya Aku memberi kamu petunjuk. Wahai hamba-hamba-Ku! Kamu semua lapar kecuali yang Aku beri makan, maka mintalah makan kepada-Ku nescaya Aku memberi kamu makan. Wahai hamba-hamba-Ku! Kamu semua telanjang kecuali yang Aku beri pakaian, maka mintalah pakaian kepada-Ku nescaya Aku memberi kamu pakaian. Wahai hamba-hamba-Ku! Sesungguhnya kamu berbuat dosa pada malam dan siang hari, dan Aku mengampuni segala dosa, maka mintalah ampun kepada-Ku nescaya Aku mengampuni kamu. Wahai hamba-hamba-Ku! Sesungguhnya kamu tidak akan mampu mendatangkan mudarat untuk memudaratkan-Ku, dan tidak akan mampu mendatangkan manfaat untuk memberi manfaat kepada-Ku. Wahai hamba-hamba-Ku! Seandainya orang pertama dan terakhir daripada kamu, manusia dan jin daripada kamu, berada di atas hati orang yang paling bertakwa di antara kamu, hal itu tidak menambah kerajaan-Ku sedikit pun. Wahai hamba-hamba-Ku! Seandainya orang pertama dan terakhir daripada kamu, manusia dan jin daripada kamu, berada di atas hati orang yang paling derhaka di antara kamu, hal itu tidak mengurangi kerajaan-Ku sedikit pun. Wahai hamba-hamba-Ku! Seandainya orang pertama dan terakhir daripada kamu, manusia dan jin daripada kamu, berdiri di satu tanah lapang lalu meminta kepada-Ku, kemudian Aku memberi setiap orang permintaannya, hal itu tidak mengurangi apa yang ada pada-Ku melainkan seperti berkurangnya jarum apabila dicelupkan ke laut. Wahai hamba-hamba-Ku! Sesungguhnya itu hanyalah amal-amal kamu yang Aku hitung untuk kamu, kemudian Aku berikan balasannya secara penuh. Maka sesiapa yang mendapati kebaikan hendaklah dia memuji Allah, dan sesiapa yang mendapati selain itu janganlah dia mencela melainkan dirinya sendiri."',
  'Со слов Абу Зарра аль-Гифари (да будет доволен им Аллах), от Пророка ﷺ, в том, что он передаёт от своего Господа, Благословенного и Всевышнего, что Он сказал: «О рабы Мои! Поистине, Я запретил несправедливость Самому Себе и сделал её запретной между вами, так не притесняйте же друг друга. О рабы Мои! Все вы заблудшие, кроме тех, кого Я повёл прямым путём, так просите же у Меня прямого пути, и Я поведу вас. О рабы Мои! Все вы голодны, кроме тех, кого Я накормил, так просите же у Меня пропитания, и Я накормлю вас. О рабы Мои! Все вы наги, кроме тех, кого Я одел, так просите же у Меня одеяния, и Я одену вас. О рабы Мои! Поистине, вы грешите ночью и днём, а Я прощаю все грехи, так просите же у Меня прощения, и Я прощу вас. О рабы Мои! Вы никогда не сможете причинить Мне вред, чтобы навредить Мне, и не сможете принести Мне пользу, чтобы принести Мне выгоду. О рабы Мои! Если бы первые и последние из вас, люди и джинны из вас, обладали сердцем самого богобоязненного из вас, это нисколько не увеличило бы Моего владычества. О рабы Мои! Если бы первые и последние из вас, люди и джинны из вас, обладали сердцем самого нечестивого из вас, это нисколько не уменьшило бы Моего владычества. О рабы Мои! Если бы первые и последние из вас, люди и джинны из вас, встали на одной равнине и попросили у Меня, и Я дал бы каждому то, что он просил, это уменьшило бы то, что у Меня, не больше, чем уменьшается море, когда в него погружают иглу. О рабы Мои! Поистине, это лишь ваши деяния, которые Я подсчитываю для вас, а затем сполна воздаю вам за них. Так пусть тот, кто обрёл благо, восхвалит Аллаха, а тот, кто обрёл иное, пусть не винит никого, кроме самого себя».',
  -- reference
  'Sahih — reported by Muslim (no. 2577)',
  'Hadith authentique rapporté par Muslim (n°2577)',
  'حديث صحيح، رواه مسلم (رقم ٢٥٧٧)',
  'Sahih — überliefert von Muslim (Nr. 2577)',
  'Sahih — overgeleverd door Muslim (nr. 2577)',
  'Sahih — Müslim (no. 2577) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 2577)',
  'صحیح حدیث، اسے مسلم (نمبر ۲۵۷۷) نے روایت کیا',
  'সহীহ হাদীস — মুসলিম (নং ২৫৭৭) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 2577)',
  'Достоверный хадис, передал Муслим (№ 2577)',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-24-Nawawi-Psalmodie-Arabe.mp3',
  5,
  24
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 24
);
