-- =============================================================================
-- 40 Hadith Nawawi — Hadith 38: "Nearness to Allah and His love (hadith of the awliya)"
-- Target collection: public.hadith_collections.id = 2  /  position = 38
-- Idempotent guard on (collection, position). All 11 content languages.
-- tafsir_* intentionally left NULL (no commentary provided for this hadith).
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Nearness to Allah and His love',
  'L''adoration, moyen de se rapprocher d''Allah et d''en être aimé',
  'العبادة وسيلة القرب والمحبة',
  'Nähe zu Allah und Seine Liebe',
  'Nabijheid tot Allah en Zijn liefde',
  'Allah''a yakınlık ve O''nun sevgisi',
  'Kedekatan dengan Allah dan cinta-Nya',
  'اللہ کا قرب اور اس کی محبت',
  'আল্লাহর নৈকট্য ও তাঁর ভালোবাসা',
  'Kedekatan dengan Allah dan cinta-Nya',
  'Близость к Аллаху и Его любовь',
  -- arabic_text
  'عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللَّهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «إِنَّ اللَّهَ تَعَالَى قَالَ: مَنْ عَادَى لِي وَلِيًّا فَقَدْ آذَنْتُهُ بِالْحَرْبِ، وَمَا تَقَرَّبَ إِلَيَّ عَبْدِي بِشَيْءٍ أَحَبَّ إِلَيَّ مِمَّا افْتَرَضْتُهُ عَلَيْهِ، وَلَا يَزَالُ عَبْدِي يَتَقَرَّبُ إِلَيَّ بِالنَّوَافِلِ حَتَّى أُحِبَّهُ، فَإِذَا أَحْبَبْتُهُ كُنْتُ سَمْعَهُ الَّذِي يَسْمَعُ بِهِ، وَبَصَرَهُ الَّذِي يُبْصِرُ بِهِ، وَيَدَهُ الَّتِي يَبْطِشُ بِهَا، وَرِجْلَهُ الَّتِي يَمْشِي بِهَا، وَلَئِنْ سَأَلَنِي لَأُعْطِيَنَّهُ، وَلَئِنِ اسْتَعَاذَنِي لَأُعِيذَنَّهُ»',
  -- transcription
  'ʿan Abī Hurayrata raḍiya Llāhu ʿanhu qāla: qāla Rasūlu Llāhi ṣalla Llāhu ʿalayhi wa-sallama: inna Llāha taʿālā qāla: man ʿādā lī waliyyan fa-qad ādhantuhu bi-l-ḥarbi, wa-mā taqarraba ilayya ʿabdī bi-shayʾin aḥabba ilayya mimma ftaraḍtuhu ʿalayhi, wa-lā yazālu ʿabdī yataqarrabu ilayya bi-n-nawāfili ḥattā uḥibbahu, fa-idhā aḥbabtuhu kuntu samʿahu lladhī yasmaʿu bihi, wa-baṣarahu lladhī yubṣiru bihi, wa-yadahu llatī yabṭishu bihā, wa-rijlahu llatī yamshī bihā, wa-la-in saʾalanī la-uʿṭiyannahu, wa-la-ini staʿādhanī la-uʿīdhannahu.',
  'ʿan Abî Hourayrata (radia Llâhou ʿanhou) qâla : qâla Rassôlou Llâhi (salla Llâhou ʿalayhi wa sallam) : inna Llâha taʿâlâ qâla : man ʿâdâ lî waliyyan fa-qad âdhantouhou bi-l-harbi, wa mâ taqarraba ilayya ʿabdî bi-chayʾin ahabba ilayya mimma ftaradtouhou ʿalayhi, wa lâ yazâlou ʿabdî yataqarrabou ilayya bi-n-nawâfili hattâ ouhibbahou, fa-idhâ ahbabtouhou kountou samʿahou lladhî yasmaʿou bihi, wa basarahou lladhî youbsirou bihi, wa yadahou llatî yabtichou bihâ, wa rijlahou llatî yamchî bihâ, wa la-in saʾalanî la-ouʿtiyannahou, wa la-ini staʿâdhanî la-ouʿîdhannahou.',
  'ʿan Abī Hurairata (radiya Llāhu ʿanhu) qāla: qāla Rasūlu Llāhi (salla Llāhu ʿalaihi wa-sallam): inna Llāha taʿālā qāla: man ʿādā lī walijjan fa-qad ādhantuhu bi-l-harbi, wa-mā taqarraba ilajja ʿabdī bi-schaiʾin ahabba ilajja mimma ftaradtuhu ʿalaihi, wa-lā jazālu ʿabdī jataqarrabu ilajja bi-n-nawāfili hattā uhibbahu, fa-idhā ahbabtuhu kuntu samʿahu lladhī jasmaʿu bihi, wa-basarahu lladhī jubsiru bihi, wa-jadahu llatī jabtischu bihā, wa-ridschlahu llatī jamschī bihā, wa-la-in saʾalanī la-uʿtijannahu, wa-la-ini staʿādhanī la-uʿīdhannahu.',
  'ʿan Abie Hoerairata (radia Llaahoe ʿanhoe) qaala: qaala Rasoeloe Llaahi (salla Llaahoe ʿalaihi wa-sallam): inna Llaaha taʿaalaa qaala: man ʿaadaa lie walijjan fa-qad aadhantoehoe bi-l-harbi, wa-maa taqarraba ilajja ʿabdie bi-sjaiʾin ahabba ilajja mimma ftaradtoehoe ʿalaihi, wa-laa jazaaloe ʿabdie jataqarraboe ilajja bi-n-nawaafili hattaa oehibbahoe, fa-idhaa ahbabtoehoe koentoe samʿahoe lladhie jasmaʿoe bihi, wa-basarahoe lladhie joebsiroe bihi, wa-jadahoe llatie jabtisjoe bihaa, wa-ridzjlahoe llatie jamsjie bihaa, wa-la-in saʾalanie la-oeʿtijannahoe, wa-la-ini staʿaadhanie la-oeʿiedhannahoe.',
  'an Ebû Hüreyre''den (radıyallâhu anh) rivayetle dedi ki: Resûlullah (s.a.v.) şöyle buyurdu: Allah Teâlâ buyurdu ki: kim benim bir velîme düşmanlık ederse, ona savaş ilan ederim. Kulum, kendisine farz kıldığım şeylerden daha sevimli bir şeyle bana yaklaşmaz. Kulum nafilelerle bana yaklaşmaya devam eder, ta ki onu severim. Onu sevdiğimde, işiten kulağı, gören gözü, tutan eli, yürüyen ayağı olurum. Benden bir şey isterse mutlaka veririm, bana sığınırsa mutlaka onu korurum.',
  'an Abi Hurairah (radhiyallahu ʿanhu) berkata: Rasulullah (shallallahu ʿalaihi wa sallam) bersabda: Allah Taʿala berfirman: barangsiapa memusuhi seorang wali-Ku, maka sungguh Aku menyatakan perang terhadapnya. Tidaklah hamba-Ku mendekatkan diri kepada-Ku dengan sesuatu yang lebih Aku cintai daripada apa yang Aku wajibkan atasnya. Hamba-Ku senantiasa mendekatkan diri kepada-Ku dengan amalan-amalan sunnah hingga Aku mencintainya. Apabila Aku mencintainya, jadilah Aku pendengarannya yang ia gunakan untuk mendengar, penglihatannya yang ia gunakan untuk melihat, tangannya yang ia gunakan untuk memegang, dan kakinya yang ia gunakan untuk berjalan. Jika ia meminta kepada-Ku, pasti Aku memberinya, dan jika ia memohon perlindungan kepada-Ku, pasti Aku melindunginya.',
  'ابو ہریرہ رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: اللہ تعالیٰ نے فرمایا: جو میرے کسی ولی سے دشمنی کرے، میں اس کے خلاف اعلانِ جنگ کرتا ہوں۔ میرا بندہ مجھ سے ان چیزوں سے زیادہ محبوب کسی چیز کے ذریعے قریب نہیں ہوتا جو میں نے اس پر فرض کی ہیں۔ اور میرا بندہ نوافل کے ذریعے میرے قریب ہوتا رہتا ہے یہاں تک کہ میں اس سے محبت کرنے لگتا ہوں۔ پس جب میں اس سے محبت کرتا ہوں تو میں اس کا کان بن جاتا ہوں جس سے وہ سنتا ہے، اس کی آنکھ جس سے وہ دیکھتا ہے، اس کا ہاتھ جس سے وہ پکڑتا ہے، اور اس کا پاؤں جس سے وہ چلتا ہے۔ اور اگر وہ مجھ سے مانگے تو میں ضرور اسے دوں گا، اور اگر وہ میری پناہ مانگے تو میں ضرور اسے پناہ دوں گا۔',
  'আবু হুরায়রা (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) বলেছেন: আল্লাহ তাআলা বলেছেন: যে আমার কোনো ওলীর সাথে শত্রুতা করে, আমি তার বিরুদ্ধে যুদ্ধ ঘোষণা করি। আমার বান্দা আমার নৈকট্য লাভ করে এমন কিছু দিয়ে যা আমার নিকট তার চেয়ে অধিক প্রিয় নয় যা আমি তার ওপর ফরজ করেছি। আর আমার বান্দা নফল আমলের মাধ্যমে আমার নৈকট্য লাভ করতে থাকে যতক্ষণ না আমি তাকে ভালোবেসে ফেলি। অতঃপর যখন আমি তাকে ভালোবাসি, তখন আমি তার কান হয়ে যাই যা দিয়ে সে শোনে, তার চোখ যা দিয়ে সে দেখে, তার হাত যা দিয়ে সে ধরে, এবং তার পা যা দিয়ে সে হাঁটে। আর সে যদি আমার কাছে চায় আমি অবশ্যই তাকে দেব, আর যদি সে আমার আশ্রয় চায় আমি অবশ্যই তাকে আশ্রয় দেব।',
  'an Abi Hurairah (radhiallahu ʿanhu) berkata: Rasulullah (sallallahu ʿalaihi wa sallam) bersabda: Allah Taʿala berfirman: sesiapa yang memusuhi seorang wali-Ku, maka sungguh Aku mengisytiharkan perang terhadapnya. Tidaklah hamba-Ku mendekatkan diri kepada-Ku dengan sesuatu yang lebih Aku cintai daripada apa yang Aku wajibkan ke atasnya. Hamba-Ku sentiasa mendekatkan diri kepada-Ku dengan amalan-amalan sunat sehingga Aku mencintainya. Apabila Aku mencintainya, jadilah Aku pendengarannya yang dia gunakan untuk mendengar, penglihatannya yang dia gunakan untuk melihat, tangannya yang dia gunakan untuk memegang, dan kakinya yang dia gunakan untuk berjalan. Jika dia meminta kepada-Ku, pasti Aku memberinya, dan jika dia memohon perlindungan kepada-Ku, pasti Aku melindunginya.',
  'От Аби Хурайры (да будет доволен им Аллах) передаётся: Посланник Аллаха ﷺ сказал: Аллах Всевышний сказал: кто враждует с тем, кто близок Мне (вали), тому Я объявляю войну. Раб Мой не приближается ко Мне ничем более любимым для Меня, чем то, что Я вменил ему в обязанность. И раб Мой непрестанно приближается ко Мне дополнительными деяниями (нафиля), пока Я не полюблю его. А когда Я полюблю его, Я становлюсь его слухом, которым он слышит, его зрением, которым он видит, его рукой, которой он хватает, и его ногой, которой он ходит. И если он попросит Меня, Я непременно дам ему, а если он прибегнет ко Мне за защитой, Я непременно защищу его.',
  -- translation
  'On the authority of Abu Hurayra (may Allah be pleased with him), the Messenger of Allah ﷺ said: "Allah, the Exalted, said: ''Whoever shows enmity to a friend (wali) of Mine, I declare war upon him. My servant draws not near to Me with anything more beloved to Me than what I have made obligatory upon him. And My servant continues to draw near to Me with voluntary (nafl) deeds until I love him. And when I love him, I am his hearing with which he hears, his sight with which he sees, his hand with which he grasps, and his foot with which he walks. Were he to ask Me, I would surely give him; and were he to seek refuge in Me, I would surely grant him refuge.''"',
  'D''après Abû Hurayra (qu''Allah l''agrée), l''Envoyé d''Allah ﷺ a dit : « Allah le Très-Haut a dit : "Quiconque est l''ennemi d''un Allié (walî) à Moi, Je lui déclare la guerre. Mon serviteur ne s''approche de Moi par rien qui Me soit plus aimable que ce que Je lui ai imposé. Et Mon serviteur ne cesse de s''approcher de Moi par les œuvres surérogatoires jusqu''à ce que Je l''aime. Et lorsque Je l''aime, Je suis son ouïe par laquelle il entend, sa vue par laquelle il voit, sa main par laquelle il saisit, et son pied par lequel il marche. S''il Me demande, Je lui donne certainement ; et s''il cherche refuge auprès de Moi, Je le lui accorde certainement." »',
  'Nach Abu Hurayra (möge Allah mit ihm zufrieden sein) sagte der Gesandte Allahs ﷺ: „Allah, der Erhabene, sprach: ''Wer einem Meiner Nahestehenden (Wali) Feindschaft erweist, dem erkläre Ich den Krieg. Mein Diener nähert sich Mir mit nichts, das Mir lieber wäre als das, was Ich ihm zur Pflicht gemacht habe. Und Mein Diener hört nicht auf, sich Mir durch freiwillige (Nafl-)Werke zu nähern, bis Ich ihn liebe. Und wenn Ich ihn liebe, bin Ich sein Gehör, mit dem er hört, sein Augenlicht, mit dem er sieht, seine Hand, mit der er zugreift, und sein Fuß, mit dem er geht. Und wenn er Mich bittet, gebe Ich ihm gewiss; und wenn er bei Mir Zuflucht sucht, gewähre Ich ihm gewiss Zuflucht.''"',
  'Op gezag van Abu Hurayra (moge Allah tevreden met hem zijn) zei de Boodschapper van Allah ﷺ: „Allah, de Verhevene, zei: ''Wie vijandschap toont jegens een naaste vriend (wali) van Mij, hem verklaar Ik de oorlog. Mijn dienaar nadert Mij met niets dat Mij liefer is dan wat Ik hem verplicht heb gesteld. En Mijn dienaar blijft Mij naderen met vrijwillige (nafl-)daden totdat Ik hem liefheb. En wanneer Ik hem liefheb, ben Ik zijn gehoor waarmee hij hoort, zijn gezicht waarmee hij ziet, zijn hand waarmee hij grijpt, en zijn voet waarmee hij loopt. En als hij Mij vraagt, geef Ik hem zeker; en als hij toevlucht bij Mij zoekt, verleen Ik hem zeker toevlucht.''"',
  'Ebû Hüreyre''den (Allah ondan razı olsun) rivayet edildiğine göre Resûlullah ﷺ şöyle buyurdu: „Allah Teâlâ buyurdu ki: ''Kim Benim bir velîme düşmanlık ederse, ona savaş ilan ederim. Kulum, kendisine farz kıldığım şeylerden daha sevimli bir şeyle Bana yaklaşmaz. Kulum nafilelerle Bana yaklaşmaya devam eder, ta ki onu severim. Onu sevdiğimde, işiten kulağı, gören gözü, tutan eli ve yürüyen ayağı olurum. Benden bir şey isterse mutlaka veririm, Bana sığınırsa mutlaka onu korurum.''"',
  'Dari Abu Hurairah (semoga Allah meridhainya), Rasulullah ﷺ bersabda: "Allah Taʿala berfirman: ''Barangsiapa memusuhi seorang wali-Ku, maka sungguh Aku menyatakan perang terhadapnya. Tidaklah hamba-Ku mendekatkan diri kepada-Ku dengan sesuatu yang lebih Aku cintai daripada apa yang Aku wajibkan atasnya. Hamba-Ku senantiasa mendekatkan diri kepada-Ku dengan amalan-amalan sunnah hingga Aku mencintainya. Apabila Aku mencintainya, jadilah Aku pendengarannya yang ia gunakan untuk mendengar, penglihatannya yang ia gunakan untuk melihat, tangannya yang ia gunakan untuk memegang, dan kakinya yang ia gunakan untuk berjalan. Jika ia meminta kepada-Ku, pasti Aku memberinya; dan jika ia memohon perlindungan kepada-Ku, pasti Aku melindunginya.''"',
  'ابو ہریرہ رضی اللہ عنہ سے روایت ہے کہ رسول اللہ ﷺ نے فرمایا: ”اللہ تعالیٰ نے فرمایا: جو میرے کسی ولی سے دشمنی کرے، میں اس کے خلاف اعلانِ جنگ کرتا ہوں۔ میرا بندہ مجھ سے ان چیزوں سے زیادہ محبوب کسی چیز کے ذریعے قریب نہیں ہوتا جو میں نے اس پر فرض کی ہیں۔ اور میرا بندہ نوافل کے ذریعے میرے قریب ہوتا رہتا ہے یہاں تک کہ میں اس سے محبت کرنے لگتا ہوں۔ پس جب میں اس سے محبت کرتا ہوں تو میں اس کا کان بن جاتا ہوں جس سے وہ سنتا ہے، اس کی آنکھ جس سے وہ دیکھتا ہے، اس کا ہاتھ جس سے وہ پکڑتا ہے، اور اس کا پاؤں جس سے وہ چلتا ہے۔ اور اگر وہ مجھ سے مانگے تو میں ضرور اسے دوں گا، اور اگر وہ میری پناہ مانگے تو میں ضرور اسے پناہ دوں گا۔“',
  'আবু হুরায়রা (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, রাসূলুল্লাহ ﷺ বলেছেন: "আল্লাহ তাআলা বলেছেন: ''যে আমার কোনো ওলীর সাথে শত্রুতা করে, আমি তার বিরুদ্ধে যুদ্ধ ঘোষণা করি। আমার বান্দা আমার নৈকট্য লাভ করে এমন কিছু দিয়ে যা আমার নিকট তার চেয়ে অধিক প্রিয় নয় যা আমি তার ওপর ফরজ করেছি। আর আমার বান্দা নফল আমলের মাধ্যমে আমার নৈকট্য লাভ করতে থাকে যতক্ষণ না আমি তাকে ভালোবেসে ফেলি। অতঃপর যখন আমি তাকে ভালোবাসি, তখন আমি তার কান হয়ে যাই যা দিয়ে সে শোনে, তার চোখ যা দিয়ে সে দেখে, তার হাত যা দিয়ে সে ধরে, এবং তার পা যা দিয়ে সে হাঁটে। আর সে যদি আমার কাছে চায় আমি অবশ্যই তাকে দেব; আর যদি সে আমার আশ্রয় চায় আমি অবশ্যই তাকে আশ্রয় দেব।''"',
  'Daripada Abu Hurairah (semoga Allah meredainya), Rasulullah ﷺ bersabda: "Allah Taʿala berfirman: ''Sesiapa yang memusuhi seorang wali-Ku, maka sungguh Aku mengisytiharkan perang terhadapnya. Tidaklah hamba-Ku mendekatkan diri kepada-Ku dengan sesuatu yang lebih Aku cintai daripada apa yang Aku wajibkan ke atasnya. Hamba-Ku sentiasa mendekatkan diri kepada-Ku dengan amalan-amalan sunat sehingga Aku mencintainya. Apabila Aku mencintainya, jadilah Aku pendengarannya yang dia gunakan untuk mendengar, penglihatannya yang dia gunakan untuk melihat, tangannya yang dia gunakan untuk memegang, dan kakinya yang dia gunakan untuk berjalan. Jika dia meminta kepada-Ku, pasti Aku memberinya; dan jika dia memohon perlindungan kepada-Ku, pasti Aku melindunginya.''"',
  'Со слов Абу Хурайры (да будет доволен им Аллах) Посланник Аллаха ﷺ сказал: «Аллах Всевышний сказал: ''Кто враждует с близким Мне (вали), тому Я объявляю войну. Раб Мой не приближается ко Мне ничем более любимым для Меня, чем то, что Я вменил ему в обязанность. И раб Мой непрестанно приближается ко Мне дополнительными деяниями, пока Я не полюблю его. А когда Я полюблю его, Я становлюсь его слухом, которым он слышит, его зрением, которым он видит, его рукой, которой он хватает, и его ногой, которой он ходит. И если он попросит Меня, Я непременно дам ему; а если прибегнет ко Мне за защитой, Я непременно защищу его.''»',
  -- reference
  'Sahih — reported by Al-Bukhari (no. 6502)',
  'Hadith authentique rapporté par Al-Bukhari (n°6502)',
  'حديث صحيح، رواه البخاري (رقم ٦٥٠٢)',
  'Sahih — überliefert von Al-Bukhari (Nr. 6502)',
  'Sahih — overgeleverd door Al-Bukhari (nr. 6502)',
  'Sahih — Buhârî (no. 6502) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (no. 6502)',
  'صحیح حدیث، اسے بخاری (نمبر ۶۵۰۲) نے روایت کیا',
  'সহীহ হাদীস — বুখারী (নং ৬৫০২) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (no. 6502)',
  'Достоверный хадис, передал аль-Бухари (№ 6502)',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-38-Nawawi-Psalmodie-Arabe.mp3',
  5,
  38
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 38
);
