-- =============================================================================
-- 40 Hadith Nawawi — Hadith 36: "Relieving a believer's distress; gathering for the Qur'an"
-- Target collection: public.hadith_collections.id = 2  /  position = 36
-- Idempotent guard on (collection, position). All 11 content languages.
-- tafsir_* intentionally left NULL (no commentary provided for this hadith).
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Relieving hardship and gathering for the Qur''an',
  'L''incitation à œuvrer salutairement',
  'فضل الاجتماع على تلاوة القرآن والذكر',
  'Not lindern und sich für den Qur''an versammeln',
  'Nood verlichten en samenkomen voor de Koran',
  'Sıkıntı gidermek ve Kur''an için toplanmak',
  'Melapangkan kesusahan dan berkumpul membaca Al-Qur''an',
  'تکلیف دور کرنا اور قرآن کے لیے جمع ہونا',
  'কষ্ট লাঘব ও কুরআন তিলাওয়াতে সমবেত হওয়া',
  'Melapangkan kesusahan dan berkumpul membaca Al-Qur''an',
  'Облегчение тягот и собрание ради Корана',
  -- arabic_text
  'عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللَّهُ عَنْهُ عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ: «مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ، وَمَنْ يَسَّرَ عَلَى مُعْسِرٍ يَسَّرَ اللَّهُ عَلَيْهِ فِي الدُّنْيَا وَالْآخِرَةِ، وَمَنْ سَتَرَ مُسْلِمًا سَتَرَهُ اللَّهُ فِي الدُّنْيَا وَالْآخِرَةِ، وَاللَّهُ فِي عَوْنِ الْعَبْدِ مَا كَانَ الْعَبْدُ فِي عَوْنِ أَخِيهِ، وَمَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ، وَمَا اجْتَمَعَ قَوْمٌ فِي بَيْتٍ مِنْ بُيُوتِ اللَّهِ يَتْلُونَ كِتَابَ اللَّهِ وَيَتَدَارَسُونَهُ بَيْنَهُمْ إِلَّا نَزَلَتْ عَلَيْهِمُ السَّكِينَةُ، وَغَشِيَتْهُمُ الرَّحْمَةُ، وَحَفَّتْهُمُ الْمَلَائِكَةُ، وَذَكَرَهُمُ اللَّهُ فِيمَنْ عِنْدَهُ، وَمَنْ أَبْطَأَ بِهِ عَمَلُهُ لَمْ يُسْرِعْ بِهِ نَسَبُهُ»',
  -- transcription
  'ʿan Abī Hurayrata raḍiya Llāhu ʿanhu ʿani n-Nabiyyi ṣalla Llāhu ʿalayhi wa-sallama qāla: man naffasa ʿan muʾminin kurbatan min kurabi d-dunyā naffasa Llāhu ʿanhu kurbatan min kurabi yawmi l-qiyāmati, wa-man yassara ʿalā muʿsirin yassara Llāhu ʿalayhi fi d-dunyā wa-l-ākhirati, wa-man satara musliman satarahu Llāhu fi d-dunyā wa-l-ākhirati, wa-Llāhu fī ʿawni l-ʿabdi mā kāna l-ʿabdu fī ʿawni akhīhi, wa-man salaka ṭarīqan yaltamisu fīhi ʿilman sahhala Llāhu lahu bihi ṭarīqan ila l-jannati, wa-mā jtamaʿa qawmun fī baytin min buyūti Llāhi yatlūna kitāba Llāhi wa-yatadārasūnahu baynahum illā nazalat ʿalayhimu s-sakīnatu, wa-ghashiyat-humu r-raḥmatu, wa-ḥaffat-humu l-malāʾikatu, wa-dhakarahumu Llāhu fīman ʿindahu, wa-man abṭaʾa bihi ʿamaluhu lam yusriʿ bihi nasabuhu.',
  'ʿan Abî Hourayrata (radia Llâhou ʿanhou) ʿani n-Nabiyyi (salla Llâhou ʿalayhi wa sallam) qâla : man naffasa ʿan mouʾminin kourbatan min kourabi d-dounyâ naffasa Llâhou ʿanhou kourbatan min kourabi yawmi l-qiyâmati, wa man yassara ʿalâ mouʿsirin yassara Llâhou ʿalayhi fi d-dounyâ wa l-âkhirati, wa man satara mousliman satarahou Llâhou fi d-dounyâ wa l-âkhirati, wa Llâhou fî ʿawni l-ʿabdi mâ kâna l-ʿabdou fî ʿawni akhîhi, wa man salaka tarîqan yaltamisou fîhi ʿilman sahhala Llâhou lahou bihi tarîqan ila l-jannati, wa mâ jtamaʿa qawmoun fî baytin min bouyôuti Llâhi yatlôuna kitâba Llâhi wa yatadârasôunahou baynahoum illâ nazalat ʿalayhimou s-sakînatou, wa ghachiyat-houmou r-rahmatou, wa haffat-houmou l-malâʾikatou, wa dhakarahoumou Llâhou fîman ʿindahou, wa man abtaʾa bihi ʿamalouhou lam yousriʿ bihi nasabouhou.',
  'ʿan Abī Hurairata (radiya Llāhu ʿanhu) ʿani n-Nabijji (salla Llāhu ʿalaihi wa-sallam) qāla: man naffasa ʿan muʾminin kurbatan min kurabi d-dunjā naffasa Llāhu ʿanhu kurbatan min kurabi jaumi l-qijāmati, wa-man jassara ʿalā muʿsirin jassara Llāhu ʿalaihi fi d-dunjā wa-l-āchirati, wa-man satara musliman satarahu Llāhu fi d-dunjā wa-l-āchirati, wa-Llāhu fī ʿauni l-ʿabdi mā kāna l-ʿabdu fī ʿauni achīhi, wa-man salaka tarīqan jaltamisu fīhi ʿilman sahhala Llāhu lahu bihi tarīqan ila l-dschannati, wa-mā dschtamaʿa qaumun fī baitin min bujūti Llāhi jatlūna kitāba Llāhi wa-jatadārasūnahu bainahum illā nazalat ʿalaihimu s-sakīnatu, wa-ghaschijat-humu r-rahmatu, wa-haffat-humu l-malāʾikatu, wa-dhakarahumu Llāhu fīman ʿindahu, wa-man abtaʾa bihi ʿamaluhu lam jusriʿ bihi nasabuhu.',
  'ʿan Abie Hoerairata (radia Llaahoe ʿanhoe) ʿani n-Nabijji (salla Llaahoe ʿalaihi wa-sallam) qaala: man naffasa ʿan moeʾminin koerbatan min koerabi d-doenjaa naffasa Llaahoe ʿanhoe koerbatan min koerabi jaumi l-qijaamati, wa-man jassara ʿalaa moeʿsirin jassara Llaahoe ʿalaihi fi d-doenjaa wa-l-aachirati, wa-man satara moesliman satarahoe Llaahoe fi d-doenjaa wa-l-aachirati, wa-Llaahoe fie ʿauni l-ʿabdi maa kaana l-ʿabdoe fie ʿauni achiehi, wa-man salaka tarieqan jaltamisoe fiehi ʿilman sahhala Llaahoe lahoe bihi tarieqan ila l-dzjannati, wa-maa dzjtamaʿa qaumoen fie baitin min boejoeti Llaahi jatloena kitaaba Llaahi wa-jatadaarasoenahoe bainahoem illaa nazalat ʿalaihimoe s-sakienatoe, wa-ghasjijat-hoemoe r-rahmatoe, wa-haffat-hoemoe l-malaaʾikatoe, wa-dhakarahoemoe Llaahoe fieman ʿindahoe, wa-man abtaʾa bihi ʿamaloehoe lam joesriʿ bihi nasaboehoe.',
  'an Ebû Hüreyre''den (radıyallâhu anh), Nebî''den (s.a.v.) rivayetle buyurdu: kim bir mümini dünya sıkıntılarından bir sıkıntıdan kurtarırsa, Allah da onu kıyamet günü sıkıntılarından bir sıkıntıdan kurtarır; kim darda olana kolaylık gösterirse, Allah ona dünya ve âhirette kolaylık gösterir; kim bir müslümanı örterse, Allah onu dünya ve âhirette örter; kul, kardeşinin yardımında olduğu sürece Allah da o kulun yardımındadır; kim ilim aramak için bir yola girerse, Allah ona cennete giden bir yolu kolaylaştırır; bir topluluk Allah''ın evlerinden bir evde toplanıp Allah''ın Kitabı''nı okur ve aralarında müzakere ederlerse, üzerlerine sekîne iner, onları rahmet kaplar, melekler onları kuşatır ve Allah onları katındakilerin yanında anar; kimi de ameli geri bıraktıysa, soyu (nesebi) onu öne geçiremez.',
  'an Abi Hurairah (radhiyallahu ʿanhu), dari Nabi (shallallahu ʿalaihi wa sallam) bersabda: barangsiapa melapangkan satu kesusahan dunia dari seorang mukmin, Allah akan melapangkan darinya satu kesusahan dari kesusahan hari kiamat; barangsiapa memudahkan orang yang kesulitan, Allah akan memudahkannya di dunia dan akhirat; barangsiapa menutupi (aib) seorang muslim, Allah akan menutupinya di dunia dan akhirat; Allah senantiasa menolong hamba selama hamba itu menolong saudaranya; barangsiapa menempuh suatu jalan untuk menuntut ilmu, Allah memudahkan baginya jalan menuju surga; dan tidaklah suatu kaum berkumpul di salah satu rumah Allah membaca Kitab Allah dan saling mempelajarinya di antara mereka, melainkan turun ketenangan (sakinah) atas mereka, rahmat meliputi mereka, malaikat mengelilingi mereka, dan Allah menyebut mereka di hadapan (makhluk) yang ada di sisi-Nya; dan barangsiapa yang amalnya memperlambatnya, maka nasabnya tidak akan mempercepatnya.',
  'ابو ہریرہ رضی اللہ عنہ سے، نبی صلی اللہ علیہ وسلم سے روایت ہے کہ آپ نے فرمایا: جو کسی مومن سے دنیا کی تکلیفوں میں سے کوئی تکلیف دور کرے، اللہ اس سے قیامت کے دن کی تکلیفوں میں سے ایک تکلیف دور کرے گا؛ جو کسی تنگ دست پر آسانی کرے، اللہ اس پر دنیا و آخرت میں آسانی کرے گا؛ جو کسی مسلمان کی پردہ پوشی کرے، اللہ دنیا و آخرت میں اس کی پردہ پوشی کرے گا؛ اور اللہ بندے کی مدد میں رہتا ہے جب تک بندہ اپنے بھائی کی مدد میں رہتا ہے؛ جو علم کی تلاش میں کسی راستے پر چلے، اللہ اس کے ذریعے اس کے لیے جنت کا راستہ آسان کر دیتا ہے؛ اور جب کوئی قوم اللہ کے گھروں میں سے کسی گھر میں جمع ہو کر اللہ کی کتاب کی تلاوت کرتی ہے اور آپس میں اس کا مذاکرہ کرتی ہے تو ان پر سکینت نازل ہوتی ہے، رحمت انہیں ڈھانپ لیتی ہے، فرشتے انہیں گھیر لیتے ہیں، اور اللہ اپنے پاس والوں میں ان کا ذکر کرتا ہے؛ اور جسے اس کے عمل نے پیچھے کر دیا، اسے اس کا نسب آگے نہیں کر سکتا۔',
  'আবু হুরায়রা (রাদিয়াল্লাহু আনহু) থেকে, নবী (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) থেকে বর্ণিত, তিনি বলেছেন: যে ব্যক্তি কোনো মুমিনের দুনিয়ার কষ্টসমূহের একটি কষ্ট দূর করে, আল্লাহ তার থেকে কিয়ামতের দিনের কষ্টসমূহের একটি কষ্ট দূর করবেন; যে কোনো অভাবগ্রস্তের জন্য সহজ করে, আল্লাহ তার জন্য দুনিয়া ও আখিরাতে সহজ করবেন; যে কোনো মুসলিমের দোষ ঢেকে রাখে, আল্লাহ দুনিয়া ও আখিরাতে তার দোষ ঢেকে রাখবেন; আর আল্লাহ বান্দার সাহায্যে থাকেন যতক্ষণ বান্দা তার ভাইয়ের সাহায্যে থাকে; যে ব্যক্তি জ্ঞান অন্বেষণে কোনো পথে চলে, আল্লাহ তার দ্বারা তার জন্য জান্নাতের পথ সহজ করে দেন; আর যখন কোনো সম্প্রদায় আল্লাহর ঘরসমূহের কোনো ঘরে একত্র হয়ে আল্লাহর কিতাব তিলাওয়াত করে ও পরস্পরে তা অধ্যয়ন করে, তখন তাদের ওপর প্রশান্তি (সাকীনা) নাযিল হয়, রহমত তাদের আচ্ছন্ন করে, ফেরেশতারা তাদের ঘিরে নেয়, এবং আল্লাহ তাঁর নিকটবর্তীদের মধ্যে তাদের আলোচনা করেন; আর যাকে তার আমল পিছিয়ে দিয়েছে, তার বংশ তাকে এগিয়ে দিতে পারবে না।',
  'an Abi Hurairah (radhiallahu ʿanhu), daripada Nabi (sallallahu ʿalaihi wa sallam) bersabda: sesiapa yang melapangkan satu kesusahan dunia daripada seorang mukmin, Allah akan melapangkan daripadanya satu kesusahan daripada kesusahan hari kiamat; sesiapa yang memudahkan orang yang kesusahan, Allah akan memudahkannya di dunia dan akhirat; sesiapa yang menutupi (aib) seorang Muslim, Allah akan menutupinya di dunia dan akhirat; Allah sentiasa menolong hamba selama hamba itu menolong saudaranya; sesiapa yang menempuh suatu jalan untuk menuntut ilmu, Allah memudahkan baginya jalan menuju syurga; dan tidaklah sesuatu kaum berkumpul di salah satu rumah Allah membaca Kitab Allah dan saling mempelajarinya antara mereka, melainkan turun ketenangan (sakinah) ke atas mereka, rahmat meliputi mereka, malaikat mengelilingi mereka, dan Allah menyebut mereka di hadapan (makhluk) yang ada di sisi-Nya; dan sesiapa yang amalnya memperlambatnya, maka nasabnya tidak akan mempercepatkannya.',
  'От Аби Хурайры (да будет доволен им Аллах), от Пророка ﷺ передаётся, что он сказал: кто избавит верующего от одной из тягот этого мира, того Аллах избавит от одной из тягот Дня воскресения; кто облегчит положение испытывающего затруднение, тому Аллах облегчит в этом мире и в будущем; кто прикроет (грех) мусульманина, того Аллах прикроет в этом мире и в будущем; и Аллах помогает рабу, пока раб помогает своему брату; кто вступит на путь в поисках знания, тому Аллах облегчит путь в Рай; и не соберётся народ в одном из домов Аллаха, читая Книгу Аллаха и изучая её между собой, кроме как снизойдёт на них покой (сакина), покроет их милость, окружат их ангелы, и Аллах помянет их среди тех, кто у Него; а кого задержали его деяния, того не ускорит его родословная.',
  -- translation
  'On the authority of Abu Hurayra (may Allah be pleased with him), from the Prophet ﷺ, who said: "Whoever relieves a believer of one of the distresses of this world, Allah will relieve him of one of the distresses of the Day of Resurrection. Whoever eases the situation of one in difficulty, Allah will ease for him in this world and the next. Whoever conceals (the faults of) a Muslim, Allah will conceal him in this world and the next. Allah continues to aid His servant so long as the servant aids his brother. Whoever travels a path seeking knowledge, Allah makes easy for him a path to Paradise. No people gather in one of the houses of Allah, reciting the Book of Allah and studying it among themselves, but that tranquillity (sakinah) descends upon them, mercy envelops them, the angels surround them, and Allah mentions them among those who are with Him. And whoever is slowed by his deeds, his lineage will not speed him up."',
  'D''après Abû Hourayra (qu''Allah l''agrée), le Prophète ﷺ a dit : « Quiconque soulage un croyant d''une des détresses de ce monde, Allah le soulagera d''une des détresses du Jour de la Résurrection. Quiconque facilite les choses à une personne en difficulté, Allah lui facilite les choses dans ce monde et dans l''autre. Quiconque couvre un musulman, Allah le couvre dans ce bas-monde et dans l''autre. Allah aide Son serviteur tant que celui-ci aide son frère. Quiconque emprunte un chemin à la recherche de la science, Allah lui facilite un chemin vers le Paradis. Toutes les fois que des gens se réunissent dans l''une des maisons d''Allah pour réciter le Livre d''Allah et l''étudier entre eux, la sérénité (sakîna) descend sur eux, la miséricorde les enveloppe, les anges les entourent, et Allah les mentionne auprès de ceux qui sont avec Lui. Et celui que ses œuvres ont retardé, sa lignée ne le fera pas avancer. »',
  'Nach Abu Hurayra (möge Allah mit ihm zufrieden sein), vom Propheten ﷺ, der sagte: „Wer einem Gläubigen eine der Nöte dieser Welt erleichtert, dem erleichtert Allah eine der Nöte des Tages der Auferstehung. Wer es einem in Schwierigkeit Befindlichen leicht macht, dem macht Allah es in dieser und der nächsten Welt leicht. Wer einen Muslim bedeckt (dessen Fehler verbirgt), den bedeckt Allah in dieser und der nächsten Welt. Allah steht dem Diener bei, solange der Diener seinem Bruder beisteht. Wer einen Weg geht, auf dem er Wissen sucht, dem erleichtert Allah dadurch einen Weg zum Paradies. Und keine Leute versammeln sich in einem der Häuser Allahs, um das Buch Allahs zu rezitieren und es untereinander zu studieren, ohne dass Ruhe (Sakina) auf sie herabkommt, Barmherzigkeit sie umhüllt, die Engel sie umgeben und Allah ihrer bei denen gedenkt, die bei Ihm sind. Und wen seine Taten zurückhalten, den wird seine Abstammung nicht beschleunigen."',
  'Op gezag van Abu Hurayra (moge Allah tevreden met hem zijn), van de Profeet ﷺ, die zei: „Wie een gelovige verlost van een van de noden van deze wereld, hem zal Allah verlossen van een van de noden van de Dag der Opstanding. Wie het iemand in moeilijkheden gemakkelijk maakt, hem zal Allah het gemakkelijk maken in deze wereld en de volgende. Wie een moslim bedekt (diens fouten verbergt), hem zal Allah bedekken in deze wereld en de volgende. Allah blijft Zijn dienaar bijstaan zolang de dienaar zijn broeder bijstaat. Wie een weg bewandelt op zoek naar kennis, hem maakt Allah daardoor een weg naar het Paradijs gemakkelijk. En geen volk komt samen in een van de huizen van Allah, het Boek van Allah reciterend en het onder elkaar bestuderend, of er daalt rust (sakina) op hen neer, barmhartigheid omhult hen, de engelen omringen hen, en Allah noemt hen bij wie bij Hem zijn. En wie door zijn daden wordt vertraagd, zal door zijn afkomst niet worden versneld."',
  'Ebû Hüreyre''den (Allah ondan razı olsun), Nebî''den ﷺ rivayetle buyurdu: „Kim bir mümini dünya sıkıntılarından bir sıkıntıdan kurtarırsa, Allah da onu kıyamet günü sıkıntılarından bir sıkıntıdan kurtarır. Kim darda olana kolaylık gösterirse, Allah ona dünya ve âhirette kolaylık gösterir. Kim bir müslümanı örterse, Allah onu dünya ve âhirette örter. Kul, kardeşinin yardımında olduğu sürece Allah da o kulun yardımındadır. Kim ilim aramak için bir yola girerse, Allah ona cennete giden bir yolu kolaylaştırır. Bir topluluk Allah''ın evlerinden bir evde toplanıp Allah''ın Kitabı''nı okur ve aralarında müzakere ederlerse, üzerlerine sekîne iner, onları rahmet kaplar, melekler onları kuşatır ve Allah onları katındakilerin yanında anar. Kimi de ameli geri bıraktıysa, soyu onu öne geçiremez."',
  'Dari Abu Hurairah (semoga Allah meridhainya), dari Nabi ﷺ, beliau bersabda: "Barangsiapa melapangkan satu kesusahan dunia dari seorang mukmin, Allah akan melapangkan darinya satu kesusahan dari kesusahan hari kiamat. Barangsiapa memudahkan orang yang kesulitan, Allah akan memudahkannya di dunia dan akhirat. Barangsiapa menutupi (aib) seorang muslim, Allah akan menutupinya di dunia dan akhirat. Allah senantiasa menolong hamba selama hamba itu menolong saudaranya. Barangsiapa menempuh suatu jalan untuk menuntut ilmu, Allah memudahkan baginya jalan menuju surga. Dan tidaklah suatu kaum berkumpul di salah satu rumah Allah membaca Kitab Allah dan saling mempelajarinya di antara mereka, melainkan turun ketenangan (sakinah) atas mereka, rahmat meliputi mereka, malaikat mengelilingi mereka, dan Allah menyebut mereka di hadapan (makhluk) yang ada di sisi-Nya. Dan barangsiapa yang amalnya memperlambatnya, maka nasabnya tidak akan mempercepatnya."',
  'ابو ہریرہ رضی اللہ عنہ سے، نبی ﷺ سے روایت ہے کہ آپ نے فرمایا: ”جو کسی مومن سے دنیا کی تکلیفوں میں سے کوئی تکلیف دور کرے، اللہ اس سے قیامت کے دن کی تکلیفوں میں سے ایک تکلیف دور کرے گا۔ جو کسی تنگ دست پر آسانی کرے، اللہ اس پر دنیا و آخرت میں آسانی کرے گا۔ جو کسی مسلمان کی پردہ پوشی کرے، اللہ دنیا و آخرت میں اس کی پردہ پوشی کرے گا۔ اور اللہ بندے کی مدد میں رہتا ہے جب تک بندہ اپنے بھائی کی مدد میں رہتا ہے۔ جو علم کی تلاش میں کسی راستے پر چلے، اللہ اس کے لیے جنت کا راستہ آسان کر دیتا ہے۔ اور جب کوئی قوم اللہ کے گھروں میں سے کسی گھر میں جمع ہو کر اللہ کی کتاب کی تلاوت کرے اور آپس میں اس کا مذاکرہ کرے تو ان پر سکینت نازل ہوتی ہے، رحمت انہیں ڈھانپ لیتی ہے، فرشتے انہیں گھیر لیتے ہیں، اور اللہ اپنے پاس والوں میں ان کا ذکر کرتا ہے۔ اور جسے اس کے عمل نے پیچھے کر دیا، اسے اس کا نسب آگے نہیں کر سکتا۔“',
  'আবু হুরায়রা (রাদিয়াল্লাহু আনহু) থেকে, নবী ﷺ থেকে বর্ণিত, তিনি বলেছেন: "যে ব্যক্তি কোনো মুমিনের দুনিয়ার কষ্টসমূহের একটি কষ্ট দূর করে, আল্লাহ তার থেকে কিয়ামতের দিনের কষ্টসমূহের একটি কষ্ট দূর করবেন। যে কোনো অভাবগ্রস্তের জন্য সহজ করে, আল্লাহ তার জন্য দুনিয়া ও আখিরাতে সহজ করবেন। যে কোনো মুসলিমের দোষ ঢেকে রাখে, আল্লাহ দুনিয়া ও আখিরাতে তার দোষ ঢেকে রাখবেন। আর আল্লাহ বান্দার সাহায্যে থাকেন যতক্ষণ বান্দা তার ভাইয়ের সাহায্যে থাকে। যে জ্ঞান অন্বেষণে কোনো পথে চলে, আল্লাহ তার জন্য জান্নাতের পথ সহজ করে দেন। আর যখন কোনো সম্প্রদায় আল্লাহর ঘরসমূহের কোনো ঘরে একত্র হয়ে আল্লাহর কিতাব তিলাওয়াত করে ও পরস্পরে তা অধ্যয়ন করে, তখন তাদের ওপর প্রশান্তি (সাকীনা) নাযিল হয়, রহমত তাদের আচ্ছন্ন করে, ফেরেশতারা তাদের ঘিরে নেয়, এবং আল্লাহ তাঁর নিকটবর্তীদের মধ্যে তাদের আলোচনা করেন। আর যাকে তার আমল পিছিয়ে দিয়েছে, তার বংশ তাকে এগিয়ে দিতে পারবে না।"',
  'Daripada Abu Hurairah (semoga Allah meredainya), daripada Nabi ﷺ, baginda bersabda: "Sesiapa yang melapangkan satu kesusahan dunia daripada seorang mukmin, Allah akan melapangkan daripadanya satu kesusahan daripada kesusahan hari kiamat. Sesiapa yang memudahkan orang yang kesusahan, Allah akan memudahkannya di dunia dan akhirat. Sesiapa yang menutupi (aib) seorang Muslim, Allah akan menutupinya di dunia dan akhirat. Allah sentiasa menolong hamba selama hamba itu menolong saudaranya. Sesiapa yang menempuh suatu jalan untuk menuntut ilmu, Allah memudahkan baginya jalan menuju syurga. Dan tidaklah sesuatu kaum berkumpul di salah satu rumah Allah membaca Kitab Allah dan saling mempelajarinya antara mereka, melainkan turun ketenangan (sakinah) ke atas mereka, rahmat meliputi mereka, malaikat mengelilingi mereka, dan Allah menyebut mereka di hadapan (makhluk) yang ada di sisi-Nya. Dan sesiapa yang amalnya memperlambatnya, maka nasabnya tidak akan mempercepatkannya."',
  'Со слов Абу Хурайры (да будет доволен им Аллах), от Пророка ﷺ, который сказал: «Кто избавит верующего от одной из тягот этого мира, того Аллах избавит от одной из тягот Дня воскресения. Кто облегчит положение оказавшегося в затруднении, тому Аллах облегчит в этом мире и в будущем. Кто прикроет (грех) мусульманина, того Аллах прикроет в этом мире и в будущем. И Аллах помогает рабу, пока раб помогает своему брату. Кто вступит на путь в поисках знания, тому Аллах облегчит путь в Рай. И не соберётся народ в одном из домов Аллаха, читая Книгу Аллаха и изучая её между собой, кроме как снизойдёт на них покой (сакина), покроет их милость, окружат их ангелы, и Аллах помянет их среди тех, кто у Него. А кого задержали его деяния, того не ускорит его родословная».',
  -- reference
  'Sahih — reported by Muslim (no. 2699), Ahmad (2/252), Abu Dawud (no. 4946), at-Tirmidhi (no. 1425), and Ibn Majah (no. 225)',
  'Hadith authentique rapporté par Muslim (n°2699), Ahmad (2/252), Abû Dâwûd (n°4946), at-Tirmidhî (n°1425) et Ibn Mâja (n°225)',
  'حديث صحيح، رواه مسلم (رقم ٢٦٩٩) وأحمد (٢/٢٥٢) وأبو داود (رقم ٤٩٤٦) والترمذي (رقم ١٤٢٥) وابن ماجه (رقم ٢٢٥)',
  'Sahih — überliefert von Muslim (Nr. 2699), Ahmad (2/252), Abu Dawud (Nr. 4946), at-Tirmidhi (Nr. 1425) und Ibn Madscha (Nr. 225)',
  'Sahih — overgeleverd door Muslim (nr. 2699), Ahmad (2/252), Abu Dawud (nr. 4946), at-Tirmidhi (nr. 1425) en Ibn Madja (nr. 225)',
  'Sahih — Müslim (no. 2699), Ahmed (2/252), Ebû Dâvûd (no. 4946), Tirmizî (no. 1425) ve İbn Mâce (no. 225) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 2699), Ahmad (2/252), Abu Dawud (no. 4946), at-Tirmidzi (no. 1425), dan Ibnu Majah (no. 225)',
  'صحیح حدیث، اسے مسلم (نمبر ۲۶۹۹)، احمد (۲/۲۵۲)، ابو داود (نمبر ۴۹۴۶)، ترمذی (نمبر ۱۴۲۵) اور ابن ماجہ (نمبر ۲۲۵) نے روایت کیا',
  'সহীহ হাদীস — মুসলিম (নং ২৬৯৯), আহমাদ (২/২৫২), আবু দাউদ (নং ৪৯৪৬), তিরমিযী (নং ১৪২৫) ও ইবনে মাজাহ (নং ২২৫) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 2699), Ahmad (2/252), Abu Dawud (no. 4946), at-Tirmizi (no. 1425), dan Ibnu Majah (no. 225)',
  'Достоверный хадис, передали Муслим (№ 2699), Ахмад (2/252), Абу Давуд (№ 4946), ат-Тирмизи (№ 1425) и Ибн Маджа (№ 225)',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-36-Nawawi-Psalmodie-Arabe.mp3',
  5,
  36
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 36
);
