-- =============================================================================
-- 40 Hadith Nawawi — Hadith 17: "Allah has prescribed excellence (ihsan) in all things"
-- Target collection: public.hadith_collections.id = 2  /  position = 17
-- Idempotent guard on (collection, position). All 11 content languages.
-- Arabic source cleaned: قتلم -> قتلتم فأحسنوا القتلة، الذبة -> الذبح.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Excellence (ihsan) in everything',
  'La généralité du bel-agir',
  'الأمر بإحسان الذبح والقتل',
  'Vortrefflichkeit (Ihsan) in allem',
  'Voortreffelijkheid (ihsan) in alles',
  'Her şeyde ihsan',
  'Berbuat ihsan dalam segala hal',
  'ہر چیز میں احسان',
  'সবকিছুতে ইহসান',
  'Berbuat ihsan dalam segala hal',
  'Ихсан во всём',
  -- arabic_text (cleaned)
  'عَنْ أَبِي يَعْلَى شَدَّادِ بْنِ أَوْسٍ رَضِيَ اللَّهُ عَنْهُ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ: «إِنَّ اللَّهَ كَتَبَ الْإِحْسَانَ عَلَى كُلِّ شَيْءٍ، فَإِذَا قَتَلْتُمْ فَأَحْسِنُوا الْقِتْلَةَ، وَإِذَا ذَبَحْتُمْ فَأَحْسِنُوا الذِّبْحَةَ، وَلْيُحِدَّ أَحَدُكُمْ شَفْرَتَهُ، وَلْيُرِحْ ذَبِيحَتَهُ»',
  -- transcription
  'ʿan Abī Yaʿlā Shaddādi bni Awsin raḍiya Llāhu ʿanhu ʿan Rasūli Llāhi ṣalla Llāhu ʿalayhi wa-sallama qāla: inna Llāha kataba l-iḥsāna ʿalā kulli shayʾin, fa-idhā qataltum fa-aḥsinu l-qitlata, wa-idhā dhabaḥtum fa-aḥsinu dh-dhibḥata, wa-l-yuḥidda aḥadukum shafratahu, wa-l-yuriḥ dhabīḥatahu.',
  'ʿan Abî Yaʿlâ Chaddâdi bni Awsin (radia Llâhou ʿanhou) ʿan Rassôli Llâhi (salla Llâhou ʿalayhi wa sallam) qâla : inna Llâha kataba l-ihsâna ʿalâ koulli chayʾin, fa-idhâ qataltoum fa-ahsinu l-qitlata, wa idhâ dhabahtoum fa-ahsinu dh-dhibhata, wa l-youhidda ahadoukoum chafratahou, wa l-yourih dhabîhatahou.',
  'ʿan Abī Jaʿlā Schaddādi bni Ausin (radiya Llāhu ʿanhu) ʿan Rasūli Llāhi (salla Llāhu ʿalaihi wa-sallam) qāla: inna Llāha kataba l-ihsāna ʿalā kulli schaiʾin, fa-idhā qataltum fa-ahsinu l-qitlata, wa-idhā dhabahtum fa-ahsinu dh-dhibhata, wa-l-juhidda ahadukum schafratahu, wa-l-jurih dhabīhatahu.',
  'ʿan Abie Jaʿlaa Sjaddaadi bni Ausin (radia Llaahoe ʿanhoe) ʿan Rasoeli Llaahi (salla Llaahoe ʿalaihi wa-sallam) qaala: inna Llaaha kataba l-ihsaana ʿalaa koelli sjaiʾin, fa-idhaa qataltoem fa-ahsinoe l-qitlata, wa-idhaa dhabahtoem fa-ahsinoe dh-dhibhata, wa-l-joehidda ahadoekoem sjafratahoe, wa-l-joerih dhabiehatahoe.',
  'an Ebû Yaʿlâ Şeddâd ibn Evs''ten (radıyallâhu anh) Resûlullah''tan (s.a.v.) rivayetle buyurdu: inna''llâhe ketebe''l-ihsâne alâ kulli şeyʾin, fe-izâ kateltum fe-ahsinu''l-kitlete, ve izâ zebahtum fe-ahsinu''z-zibhate, ve''l-yuhidde ehadukum şefratehu, ve''l-yurih zebîhateh.',
  'ʿan Abī Yaʿlā Syaddad bin Aus (radhiyallāhu ʿanhu) dari Rasulullah (shallallāhu ʿalaihi wa sallam) bersabda: innallāha kataba l-ihsāna ʿalā kulli syaiʾin, fa-idzā qataltum fa-ahsinul-qitlata, wa idzā dzabahtum fa-ahsinudz-dzibhata, wal-yuhidda ahadukum syafratah, wal-yurih dzabīhatah.',
  'ابو یعلیٰ شداد بن اوس رضی اللہ عنہ سے، رسول اللہ صلی اللہ علیہ وسلم سے روایت ہے کہ آپ نے فرمایا: اِنَّ اللہَ کَتَبَ الاِحسانَ عَلٰی کُلِّ شَیءٍ، فَاِذا قَتَلتُم فَاَحسِنُوا القِتلَۃَ، وَاِذا ذَبَحتُم فَاَحسِنُوا الذِّبحَۃَ، وَلیُحِدَّ اَحَدُکُم شَفرَتَہُ، وَلیُرِح ذَبِیحَتَہُ۔',
  'আবু ইয়ালা শাদ্দাদ ইবনে আউস (রাদিয়াল্লাহু আনহু) থেকে, রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) থেকে বর্ণিত, তিনি বলেছেন: ইন্নাল্লাহা কাতাবাল ইহসানা আলা কুল্লি শাইইন, ফাইযা কাতালতুম ফাআহসিনুল কিতলাতা, ওয়া ইযা যাবাহতুম ফাআহসিনুয যিবহাতা, ওয়ালইউহিদ্দা আহাদুকুম শাফরাতাহ, ওয়ালইউরিহ যাবীহাতাহ।',
  'ʿan Abī Yaʿlā Syaddad bin Aus (radhiallāhu ʿanhu) daripada Rasulullah (sallallāhu ʿalaihi wa sallam) bersabda: innallāha kataba l-ihsāna ʿalā kulli syaiʾin, fa-idzā qataltum fa-ahsinul-qitlata, wa idzā dzabahtum fa-ahsinudz-dzibhata, wal-yuhidda ahadukum syafratah, wal-yurih dzabīhatah.',
  'Ан Аби Яʿля Шаддад ибн Аус (да будет доволен им Аллах) от Посланника Аллаха ﷺ передал, что он сказал: инна Ллаха катаба ль-ихсана аля кулли шайʾин, фа-иза каталтум фа-ахсину ль-китлята, ва иза забахтум фа-ахсину з-зибхата, валь-юхидда ахадукум шафратаху, валь-юрих забихатаху.',
  -- translation
  'On the authority of Abu Yaʿla Shaddad ibn Aws (may Allah be pleased with him), the Messenger of Allah ﷺ said: "Indeed Allah has prescribed excellence (ihsan) in all things. So when you kill, kill well; and when you slaughter, slaughter well. Let each one of you sharpen his blade and spare suffering to the animal he slaughters."',
  'D''après Abû Yaʿlâ Shaddad ibn Aws (qu''Allah l''agrée), l''Envoyé d''Allah ﷺ a dit : « Allah a prescrit le bel-agir (ihsân) en toute chose. Quand vous tuez, faites-le de façon parfaite ; et quand vous égorgez une bête, faites-le de la manière la plus douce. Que chacun de vous aiguise bien sa lame et épargne la souffrance à la bête qu''il sacrifie. »',
  'Nach Abu Yaʿla Schaddad ibn Aws (möge Allah mit ihm zufrieden sein) sagte der Gesandte Allahs ﷺ: „Wahrlich, Allah hat die Vortrefflichkeit (Ihsan) in allen Dingen vorgeschrieben. Wenn ihr also tötet, so tötet auf gute Weise; und wenn ihr schlachtet, so schlachtet auf gute Weise. Jeder von euch schärfe seine Klinge und erspare dem Tier, das er schlachtet, das Leiden."',
  'Op gezag van Abu Yaʿla Shaddad ibn Aws (moge Allah tevreden met hem zijn) zei de Boodschapper van Allah ﷺ: „Voorwaar, Allah heeft de voortreffelijkheid (ihsan) in alle dingen voorgeschreven. Dus wanneer jullie doden, doodt op goede wijze; en wanneer jullie slachten, slacht op goede wijze. Laat ieder van jullie zijn mes scherpen en het dier dat hij slacht het lijden besparen."',
  'Ebû Yaʿlâ Şeddâd ibn Evs''ten (Allah ondan razı olsun) rivayet edildiğine göre Resûlullah ﷺ şöyle buyurdu: „Şüphesiz Allah her şeyde ihsanı (en güzel şekilde davranmayı) yazmıştır. Öyleyse öldürdüğünüzde güzel öldürün; kestiğinizde güzel kesin. Her biriniz bıçağını bilesin ve kestiği hayvanı rahat ettirsin (acı çektirmesin)."',
  'Dari Abu Yaʿla Syaddad bin Aus (semoga Allah meridhainya), Rasulullah ﷺ bersabda: "Sesungguhnya Allah telah menetapkan ihsan (berbuat baik) atas segala sesuatu. Maka apabila kalian membunuh, bunuhlah dengan cara yang baik; dan apabila kalian menyembelih, sembelihlah dengan cara yang baik. Hendaklah salah seorang dari kalian menajamkan pisaunya dan menyenangkan (tidak menyiksa) hewan sembelihannya."',
  'ابو یعلیٰ شداد بن اوس رضی اللہ عنہ سے روایت ہے کہ رسول اللہ ﷺ نے فرمایا: ”بے شک اللہ نے ہر چیز پر احسان (بہترین طریقہ) فرض کیا ہے۔ پس جب تم قتل کرو تو اچھے طریقے سے قتل کرو، اور جب ذبح کرو تو اچھے طریقے سے ذبح کرو۔ تم میں سے ہر ایک اپنی چھری تیز کرے اور اپنے ذبیحے کو راحت پہنچائے (تکلیف نہ دے)۔“',
  'আবু ইয়ালা শাদ্দাদ ইবনে আউস (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, রাসূলুল্লাহ ﷺ বলেছেন: "নিশ্চয়ই আল্লাহ প্রতিটি বিষয়ে ইহসান (উত্তম পন্থা) ফরজ করেছেন। সুতরাং যখন তোমরা হত্যা করো, উত্তমভাবে হত্যা করো; আর যখন জবাই করো, উত্তমভাবে জবাই করো। তোমাদের প্রত্যেকে যেন তার ছুরি ধারালো করে এবং তার জবাইকৃত পশুকে স্বস্তি দেয় (কষ্ট না দেয়)।"',
  'Daripada Abu Yaʿla Syaddad bin Aus (semoga Allah meredainya), Rasulullah ﷺ bersabda: "Sesungguhnya Allah telah menetapkan ihsan (berbuat baik) ke atas segala sesuatu. Maka apabila kamu membunuh, bunuhlah dengan cara yang baik; dan apabila kamu menyembelih, sembelihlah dengan cara yang baik. Hendaklah seseorang daripada kamu menajamkan pisaunya dan menyenangkan (tidak menyiksa) haiwan sembelihannya."',
  'Со слов Абу Яʿлы Шаддада ибн Ауса (да будет доволен им Аллах) Посланник Аллаха ﷺ сказал: «Поистине, Аллах предписал ихсан (совершенство) во всём. Если вы убиваете — убивайте хорошо; и если вы закалываете (животное) — закалывайте хорошо. Пусть каждый из вас наточит своё лезвие и избавит от мучений животное, которое закалывает».',
  -- reference
  'Sahih — reported by Muslim (3/1548)',
  'Hadith authentique rapporté par Muslim (3/1548)',
  'حديث صحيح، رواه مسلم (٣/١٥٤٨)',
  'Sahih — überliefert von Muslim (3/1548)',
  'Sahih — overgeleverd door Muslim (3/1548)',
  'Sahih — Müslim (3/1548) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Muslim (3/1548)',
  'صحیح حدیث، اسے مسلم (۳/۱۵۴۸) نے روایت کیا',
  'সহীহ হাদীস — মুসলিম (৩/১৫৪৮) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Muslim (3/1548)',
  'Достоверный хадис, передал Муслим (3/1548)',
  -- tafsir
  'Excellence (ihsan) must not be only towards humans; rather it is general. "When you kill, do it well; and when you slaughter, slaughter well" — all of this is part of excellence. "When you kill…" means in combat between humans, or when one wishes to kill an animal that it is lawful to kill. "Do it well" means using the swiftest means and without making the victim suffer. However, the reports affirming the stoning to death of the married person (muhsan) who later commits fornication may seem problematic. The answer is that this penalty is an exception to the rule established by this hadith. One may also say that "do it well" denotes conformity with the law, and the stoning of the muhsan is in conformity with the law. His words "when you slaughter, slaughter well" concern the animal that it is lawful to eat, such as sheep. A person should take the swiftest means to achieve the lawful objective of the sacrifice; that is why he said immediately after: "Let each one of you sharpen his blade and spare suffering to the animal he slaughters."',
  'Le bel-agir (ihsân) ne doit pas concerner seulement les humains ; il est général. « Quand vous tuez, faites-le de façon parfaite ; et quand vous égorgez une bête, faites-le de la manière la plus douce » : tout cela fait partie du bel-agir. « Quand vous tuez… » c''est-à-dire lors du combat entre humains, ou quand on veut tuer une bête qu''il est licite de tuer. « Faites-le de façon parfaite » en utilisant le moyen le plus rapide et sans faire souffrir la victime. Cependant, peuvent poser problème les traditions affirmant la lapidation jusqu''à la mort de l''homme qui a consommé un mariage valable et a ensuite commis la fornication (muhsan). La réponse est que cette peine est une exception à la règle établie par ce hadith. On peut aussi dire que « faites-le de façon parfaite » désigne la conformité à la loi, or la lapidation du muhsan est conforme à la loi. Ses paroles « quand vous égorgez, faites-le de la manière la plus douce » concernent la bête qu''il est licite de manger, comme les moutons. À l''homme de prendre le moyen le plus court pour atteindre l''objectif légal du sacrifice ; c''est pourquoi il a dit juste après : « …aiguisez bien votre lame et épargnez la souffrance à la bête. »',
  'الإحسان لا يكون للبشر فقط، بل هو عام. «فإذا قتلتم فأحسنوا القتلة، وإذا ذبحتم فأحسنوا الذبحة»: وكل ذلك من الإحسان. «فإذا قتلتم» أي في القتال بين البشر، أو عند إرادة قتل حيوان يحل قتله. «فأحسنوا القتلة» باستعمال أسرع وسيلة ودون تعذيب المقتول. غير أنه قد يُشكِل ما ورد من رجم المحصن — الذي تزوج زواجاً صحيحاً ثم زنى — حتى الموت. والجواب أن هذه العقوبة استثناء من القاعدة التي قررها هذا الحديث. ويمكن أن يقال أيضاً إن «فأحسنوا القتلة» تعني الموافقة للشرع، ورجم المحصن موافق للشرع. وقوله: «وإذا ذبحتم فأحسنوا الذبحة» يتعلق بالحيوان الذي يحل أكله كالغنم مثلاً. فعلى المرء أن يتخذ أسرع وسيلة لتحقيق المقصد الشرعي من الذبح، ولهذا قال بعده مباشرة: «وليحد أحدكم شفرته وليرح ذبيحته».',
  'Vortrefflichkeit (Ihsan) darf nicht nur den Menschen gegenüber bestehen; vielmehr ist sie allgemein. „Wenn ihr tötet, tut es gut; und wenn ihr schlachtet, schlachtet gut": all dies gehört zur Vortrefflichkeit. „Wenn ihr tötet…" heißt im Kampf zwischen Menschen oder wenn man ein Tier töten will, das zu töten erlaubt ist. „Tut es gut" bedeutet das schnellste Mittel zu nutzen und das Opfer nicht leiden zu lassen. Allerdings mögen die Überlieferungen problematisch erscheinen, die die Steinigung des Verheirateten (Muhsan), der später Unzucht begeht, bis zum Tode bestätigen. Die Antwort ist, dass diese Strafe eine Ausnahme von der durch diesen Hadith festgelegten Regel ist. Man kann auch sagen, dass „tut es gut" die Übereinstimmung mit dem Gesetz bezeichnet, und die Steinigung des Muhsan steht im Einklang mit dem Gesetz. Seine Worte „wenn ihr schlachtet, schlachtet gut" betreffen das Tier, dessen Verzehr erlaubt ist, wie Schafe. Der Mensch soll das schnellste Mittel wählen, um das gesetzliche Ziel der Schlachtung zu erreichen; deshalb sagte er gleich danach: „Jeder von euch schärfe seine Klinge und erspare dem Tier das Leiden."',
  'Voortreffelijkheid (ihsan) mag niet alleen jegens mensen bestaan; veeleer is zij algemeen. „Wanneer jullie doden, doe het goed; en wanneer jullie slachten, slacht goed": dit alles behoort tot de voortreffelijkheid. „Wanneer jullie doden…" betekent in het gevecht tussen mensen, of wanneer men een dier wil doden dat het toegestaan is te doden. „Doe het goed" betekent het snelste middel gebruiken en het slachtoffer niet laten lijden. Echter, de overleveringen die de steniging tot de dood van de gehuwde persoon (muhsan) die later ontucht pleegt bevestigen, kunnen problematisch lijken. Het antwoord is dat deze straf een uitzondering is op de regel die door deze hadith is vastgesteld. Men kan ook zeggen dat „doe het goed" overeenstemming met de wet aanduidt, en de steniging van de muhsan is in overeenstemming met de wet. Zijn woorden „wanneer jullie slachten, slacht goed" betreffen het dier waarvan het eten toegestaan is, zoals schapen. De mens moet het snelste middel nemen om het wettelijke doel van het slachten te bereiken; daarom zei hij meteen daarna: „Laat ieder van jullie zijn mes scherpen en het dier het lijden besparen."',
  'İhsan yalnızca insanlara karşı değildir; aksine geneldir. „Öldürdüğünüzde güzel öldürün; kestiğinizde güzel kesin": bütün bunlar ihsandandır. „Öldürdüğünüzde…" yani insanlar arasındaki savaşta ya da öldürülmesi helâl bir hayvanı öldürmek istendiğinde. „Güzel öldürün" en hızlı yöntemi kullanarak ve maktulü acı çektirmeden. Ancak, sahih bir nikâhla evlenip sonra zina eden evli kişinin (muhsan) ölünceye kadar recmedilmesine dair rivayetler sorun teşkil edebilir. Cevap şudur: bu ceza, bu hadisin koyduğu kuralın bir istisnasıdır. Ayrıca „güzel öldürün" ifadesinin şeriata uygunluğu kastettiği de söylenebilir; muhsanın recmi ise şeriata uygundur. „Kestiğinizde güzel kesin" sözü, koyun gibi eti helâl olan hayvanı ilgilendirir. Kişi, kesimin meşru amacına ulaşmak için en hızlı yöntemi almalıdır; bu yüzden hemen ardından: „Her biriniz bıçağını bilesin ve kestiği hayvanı rahat ettirsin" buyurmuştur.',
  'Ihsan tidak hanya kepada manusia saja, melainkan bersifat umum. "Apabila kalian membunuh, lakukanlah dengan baik; dan apabila kalian menyembelih, sembelihlah dengan baik": semua itu termasuk ihsan. "Apabila kalian membunuh…" yakni dalam peperangan antar manusia, atau ketika hendak membunuh hewan yang halal dibunuh. "Lakukanlah dengan baik" dengan menggunakan cara yang tercepat dan tanpa menyiksa yang dibunuh. Namun, riwayat-riwayat yang menetapkan rajam hingga mati bagi orang yang telah menikah secara sah lalu berzina (muhsan) mungkin tampak menjadi masalah. Jawabannya adalah bahwa hukuman ini merupakan pengecualian dari kaidah yang ditetapkan oleh hadis ini. Dapat juga dikatakan bahwa "lakukanlah dengan baik" berarti sesuai dengan syariat, dan rajam terhadap muhsan adalah sesuai dengan syariat. Sabdanya "apabila kalian menyembelih, sembelihlah dengan baik" berkaitan dengan hewan yang halal dimakan seperti kambing. Hendaklah seseorang mengambil cara tercepat untuk mencapai tujuan syar''i dari penyembelihan; karena itu beliau bersabda setelahnya: "Hendaklah salah seorang dari kalian menajamkan pisaunya dan menyenangkan hewan sembelihannya."',
  'احسان صرف انسانوں کے ساتھ نہیں ہونا چاہیے، بلکہ یہ عام ہے۔ ”جب تم قتل کرو تو اچھے طریقے سے کرو، اور جب ذبح کرو تو اچھے طریقے سے کرو“: یہ سب احسان میں سے ہے۔ ”جب تم قتل کرو…“ یعنی انسانوں کے درمیان لڑائی میں، یا جب کسی ایسے جانور کو مارنا چاہو جس کا مارنا جائز ہو۔ ”اچھے طریقے سے کرو“ یعنی تیز ترین ذریعہ استعمال کر کے اور مقتول کو تکلیف دیے بغیر۔ تاہم وہ روایات اشکال پیدا کر سکتی ہیں جو صحیح نکاح کے بعد زنا کرنے والے شادی شدہ (محصن) کے رجم تک کی موت کو ثابت کرتی ہیں۔ جواب یہ ہے کہ یہ سزا اس حدیث کے مقرر کردہ قاعدے سے ایک استثنا ہے۔ یہ بھی کہا جا سکتا ہے کہ ”اچھے طریقے سے کرو“ کا مطلب شریعت کے موافق ہونا ہے، اور محصن کا رجم شریعت کے موافق ہے۔ آپ کا فرمان ”جب ذبح کرو تو اچھے طریقے سے کرو“ اس جانور سے متعلق ہے جس کا کھانا حلال ہے جیسے بکری۔ آدمی کو چاہیے کہ ذبح کے شرعی مقصد کو حاصل کرنے کے لیے تیز ترین ذریعہ اختیار کرے، اسی لیے آپ نے فوراً بعد فرمایا: ”تم میں سے ہر ایک اپنی چھری تیز کرے اور اپنے ذبیحے کو راحت پہنچائے۔“',
  'ইহসান কেবল মানুষের প্রতি নয়, বরং তা ব্যাপক। "যখন তোমরা হত্যা করো, উত্তমভাবে করো; আর যখন জবাই করো, উত্তমভাবে করো": এ সবই ইহসানের অন্তর্ভুক্ত। "যখন তোমরা হত্যা করো…" অর্থাৎ মানুষের মধ্যকার যুদ্ধে, কিংবা যখন এমন কোনো পশুকে মারতে চাও যা মারা বৈধ। "উত্তমভাবে করো" অর্থাৎ দ্রুততম উপায় ব্যবহার করে এবং নিহতকে কষ্ট না দিয়ে। তবে যেসব বর্ণনা বৈধ বিবাহের পর ব্যভিচারকারী বিবাহিত ব্যক্তির (মুহসান) মৃত্যু পর্যন্ত রজমকে প্রমাণ করে, তা সমস্যাজনক মনে হতে পারে। উত্তর হলো এই শাস্তি এই হাদীস কর্তৃক প্রতিষ্ঠিত নীতির একটি ব্যতিক্রম। এও বলা যায় যে "উত্তমভাবে করো" মানে শরীয়তের অনুরূপ হওয়া, আর মুহসানের রজম শরীয়তের অনুরূপ। তাঁর বাণী "যখন জবাই করো, উত্তমভাবে করো" সেই পশু সম্পর্কে যার খাওয়া বৈধ যেমন ভেড়া। মানুষের উচিত জবাইয়ের শরয়ী উদ্দেশ্য অর্জনের জন্য দ্রুততম উপায় গ্রহণ করা; এজন্যই তিনি এর পরপরই বলেছেন: "তোমাদের প্রত্যেকে যেন তার ছুরি ধারালো করে এবং তার জবাইকৃত পশুকে স্বস্তি দেয়।"',
  'Ihsan tidak hanya kepada manusia sahaja, sebaliknya bersifat umum. "Apabila kamu membunuh, lakukanlah dengan baik; dan apabila kamu menyembelih, sembelihlah dengan baik": semua itu termasuk ihsan. "Apabila kamu membunuh…" iaitu dalam peperangan antara manusia, atau ketika hendak membunuh haiwan yang halal dibunuh. "Lakukanlah dengan baik" dengan menggunakan cara yang terpantas dan tanpa menyeksa yang dibunuh. Namun, riwayat-riwayat yang menetapkan rejam sehingga mati bagi orang yang telah berkahwin secara sah lalu berzina (muhsan) mungkin kelihatan menjadi masalah. Jawapannya ialah hukuman ini merupakan pengecualian daripada kaedah yang ditetapkan oleh hadis ini. Boleh juga dikatakan bahawa "lakukanlah dengan baik" bermaksud menepati syariat, dan rejam terhadap muhsan menepati syariat. Sabdanya "apabila kamu menyembelih, sembelihlah dengan baik" berkaitan dengan haiwan yang halal dimakan seperti kambing. Hendaklah seseorang mengambil cara terpantas untuk mencapai tujuan syarie penyembelihan; itulah sebabnya baginda bersabda selepasnya: "Hendaklah seseorang daripada kamu menajamkan pisaunya dan menyenangkan haiwan sembelihannya."',
  'Ихсан не должен быть только по отношению к людям; напротив, он всеобщ. «Когда вы убиваете — делайте это хорошо; и когда закалываете — закалывайте хорошо»: всё это относится к ихсану. «Когда вы убиваете…» — то есть в сражении между людьми или когда хотят убить животное, которое дозволено убивать. «Делайте это хорошо» — используя быстрейшее средство и не причиняя страданий убиваемому. Однако сообщения, утверждающие побивание камнями до смерти женатого человека (мухсан), впоследствии совершившего прелюбодеяние, могут показаться проблематичными. Ответ в том, что это наказание является исключением из правила, установленного этим хадисом. Можно также сказать, что «делайте это хорошо» означает соответствие закону, а побивание камнями мухсана соответствует закону. Его слова «когда закалываете — закалывайте хорошо» касаются животного, которое дозволено есть, как овцы. Человеку следует избрать быстрейшее средство для достижения законной цели заклания; поэтому он сказал сразу после: «Пусть каждый из вас наточит своё лезвие и избавит от мучений животное, которое закалывает».',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-17-Nawawi-Psalmodie-Arabe.mp3',
  5,
  17
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 17
);
