-- =============================================================================
-- 40 Hadith Nawawi — Hadith 35: "Brotherhood in Islam"
-- Target collection: public.hadith_collections.id = 2  /  position = 35
-- Idempotent guard on (collection, position). All 11 content languages.
-- tafsir_* intentionally left NULL (no commentary provided for this hadith).
-- Arabic cleaned: المسلم خو المسلم -> المسلم أخو المسلم.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Brotherhood in Islam',
  'La vraie fraternité en Islam',
  'أخوة الإسلام',
  'Die Brüderlichkeit im Islam',
  'De broederschap in de islam',
  'İslam kardeşliği',
  'Persaudaraan dalam Islam',
  'اسلامی بھائی چارہ',
  'ইসলামে ভ্রাতৃত্ব',
  'Persaudaraan dalam Islam',
  'Братство в исламе',
  -- arabic_text
  'عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللَّهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «لَا تَحَاسَدُوا، وَلَا تَنَاجَشُوا، وَلَا تَبَاغَضُوا، وَلَا تَدَابَرُوا، وَلَا يَبِعْ بَعْضُكُمْ عَلَى بَيْعِ بَعْضٍ، وَكُونُوا عِبَادَ اللَّهِ إِخْوَانًا. الْمُسْلِمُ أَخُو الْمُسْلِمِ، لَا يَظْلِمُهُ وَلَا يَخْذُلُهُ وَلَا يَكْذِبُهُ وَلَا يَحْقِرُهُ. التَّقْوَى هَا هُنَا» وَيُشِيرُ إِلَى صَدْرِهِ ثَلَاثَ مَرَّاتٍ «بِحَسْبِ امْرِئٍ مِنَ الشَّرِّ أَنْ يَحْقِرَ أَخَاهُ الْمُسْلِمَ. كُلُّ الْمُسْلِمِ عَلَى الْمُسْلِمِ حَرَامٌ: دَمُهُ وَمَالُهُ وَعِرْضُهُ»',
  -- transcription
  'ʿan Abī Hurayrata raḍiya Llāhu ʿanhu qāla: qāla Rasūlu Llāhi ṣalla Llāhu ʿalayhi wa-sallama: lā taḥāsadū, wa-lā tanājashū, wa-lā tabāghaḍū, wa-lā tadābarū, wa-lā yabiʿ baʿḍukum ʿalā bayʿi baʿḍin, wa-kūnū ʿibāda Llāhi ikhwānan. al-muslimu akhu l-muslimi, lā yaẓlimuhu wa-lā yakhdhuluhu wa-lā yakdhibuhu wa-lā yaḥqiruhu. at-taqwā hā hunā — wa-yushīru ilā ṣadrihi thalātha marrātin — bi-ḥasbi mriʾin mina sh-sharri an yaḥqira akhāhu l-muslima. kullu l-muslimi ʿala l-muslimi ḥarāmun: damuhu wa-māluhu wa-ʿirḍuhu.',
  'ʿan Abî Hourayrata (radia Llâhou ʿanhou) qâla : qâla Rassôlou Llâhi (salla Llâhou ʿalayhi wa sallam) : lâ tahâsadô, wa lâ tanâjachô, wa lâ tabâghadô, wa lâ tadâbarô, wa lâ yabiʿ baʿdoukoum ʿalâ bayʿi baʿdin, wa kônô ʿibâda Llâhi ikhwânan. al-mouslimou akhou l-mouslimi, lâ yazlimouhou wa lâ yakhdhoulouhou wa lâ yakdhibouhou wa lâ yahqirouhou. at-taqwâ hâ hounâ — wa youchîrou ilâ sadrihi thalâtha marrâtin — bi-hasbi mriʾin mina ch-charri an yahqira akhâhou l-mouslima. koullou l-mouslimi ʿala l-mouslimi harâmoun : damouhou wa mâlouhou wa ʿirdouhou.',
  'ʿan Abī Hurairata (radiya Llāhu ʿanhu) qāla: qāla Rasūlu Llāhi (salla Llāhu ʿalaihi wa-sallam): lā tahāsadū, wa-lā tanādschaschū, wa-lā tabāghadū, wa-lā tadābarū, wa-lā jabiʿ baʿdukum ʿalā baiʿi baʿdin, wa-kūnū ʿibāda Llāhi ichwānan. al-muslimu achu l-muslimi, lā jazlimuhu wa-lā jachdhuluhu wa-lā jakdhibuhu wa-lā jahqiruhu. at-taqwā hā hunā — wa-juschīru ilā sadrihi thalātha marrātin — bi-hasbi mriʾin mina sch-scharri an jahqira achāhu l-muslima. kullu l-muslimi ʿala l-muslimi harāmun: damuhu wa-māluhu wa-ʿirduhu.',
  'ʿan Abie Hoerairata (radia Llaahoe ʿanhoe) qaala: qaala Rasoeloe Llaahi (salla Llaahoe ʿalaihi wa-sallam): laa tahaasadoe, wa-laa tanaadzjasjoe, wa-laa tabaaghadoe, wa-laa tadaabaroe, wa-laa jabiʿ baʿdoekoem ʿalaa baiʿi baʿdin, wa-koenoe ʿibaada Llaahi ichwaanan. al-moeslimoe achoe l-moeslimi, laa jazlimoehoe wa-laa jachdhoeloehoe wa-laa jakdhiboehoe wa-laa jahqiroehoe. at-taqwaa haa hoenaa — wa-joesjieroe ilaa sadrihi thalaatha marraatin — bi-hasbi mriʾin mina sj-sjarri an jahqira achaahoe l-moeslima. koelloe l-moeslimi ʿala l-moeslimi haraamoen: damoehoe wa-maaloehoe wa-ʿirdoehoe.',
  'an Ebû Hüreyre''den (radıyallâhu anh) rivayetle dedi ki: Resûlullah (s.a.v.) şöyle buyurdu: birbirinize haset etmeyin, alıcı olmadan fiyat kızıştırmayın (neceş yapmayın), birbirinize buğzetmeyin, birbirinize sırt çevirmeyin, biriniz diğerinin satışı üzerine satış yapmasın; ey Allah''ın kulları, kardeşler olun! Müslüman müslümanın kardeşidir: ona zulmetmez, onu yardımsız bırakmaz, ona yalan söylemez ve onu hor görmez. Takvâ işte buradadır — ve göğsüne üç kez işaret etti — kişiye kötülük olarak müslüman kardeşini hor görmesi yeter. Müslümanın müslümana her şeyi haramdır: kanı, malı ve ırzı.',
  'an Abi Hurairah (radhiyallahu ʿanhu) berkata: Rasulullah (shallallahu ʿalaihi wa sallam) bersabda: janganlah kalian saling mendengki, janganlah kalian melakukan najasy (menaikkan harga tanpa berniat membeli), janganlah kalian saling membenci, janganlah kalian saling membelakangi, dan janganlah sebagian kalian menjual di atas penjualan sebagian yang lain; jadilah kalian hamba-hamba Allah yang bersaudara! Seorang muslim adalah saudara muslim lainnya: ia tidak menzaliminya, tidak menelantarkannya, tidak mendustainya, dan tidak menghinakannya. Takwa itu di sini — beliau menunjuk ke dadanya tiga kali — cukuplah keburukan bagi seseorang dengan menghina saudaranya yang muslim. Setiap muslim atas muslim lainnya haram: darahnya, hartanya, dan kehormatannya.',
  'ابو ہریرہ رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: آپس میں حسد نہ کرو، خریدنے کی نیت کے بغیر قیمت نہ بڑھاؤ (نجش نہ کرو)، آپس میں بغض نہ رکھو، ایک دوسرے سے منہ نہ موڑو، اور تم میں سے کوئی دوسرے کی بیع پر بیع نہ کرے؛ اے اللہ کے بندو! بھائی بھائی بن جاؤ۔ مسلمان مسلمان کا بھائی ہے: نہ اس پر ظلم کرتا ہے، نہ اسے بے یار و مددگار چھوڑتا ہے، نہ اس سے جھوٹ بولتا ہے، اور نہ اسے حقیر سمجھتا ہے۔ تقویٰ یہاں ہے — اور آپ نے تین بار اپنے سینے کی طرف اشارہ کیا — آدمی کے برا ہونے کے لیے اتنا ہی کافی ہے کہ وہ اپنے مسلمان بھائی کو حقیر سمجھے۔ ہر مسلمان کا (دوسرے) مسلمان پر سب کچھ حرام ہے: اس کا خون، اس کا مال اور اس کی عزت۔',
  'আবু হুরায়রা (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) বলেছেন: তোমরা পরস্পর হিংসা করো না, ক্রয়ের নিয়ত ছাড়া দাম বাড়িয়ো না (নাজাশ করো না), পরস্পর বিদ্বেষ রেখো না, একে অপরের থেকে মুখ ফিরিয়ে নিয়ো না, এবং তোমাদের কেউ অপরের বেচাকেনার উপর বেচাকেনা করো না; হে আল্লাহর বান্দারা! ভাই ভাই হয়ে যাও। মুসলিম মুসলিমের ভাই: সে তার ওপর যুলম করে না, তাকে অসহায় ছেড়ে দেয় না, তার সাথে মিথ্যা বলে না, এবং তাকে তুচ্ছ মনে করে না। তাকওয়া এখানে — তিনি তিনবার তাঁর বুকের দিকে ইশারা করলেন — একজন মানুষের মন্দ হওয়ার জন্য এতটুকুই যথেষ্ট যে সে তার মুসলিম ভাইকে তুচ্ছ মনে করে। প্রত্যেক মুসলিমের (অপর) মুসলিমের উপর সবকিছু হারাম: তার রক্ত, তার সম্পদ ও তার সম্মান।',
  'an Abi Hurairah (radhiallahu ʿanhu) berkata: Rasulullah (sallallahu ʿalaihi wa sallam) bersabda: janganlah kamu saling mendengki, janganlah kamu melakukan najasy (menaikkan harga tanpa berniat membeli), janganlah kamu saling membenci, janganlah kamu saling membelakangi, dan janganlah sebahagian kamu menjual di atas jualan sebahagian yang lain; jadilah kamu hamba-hamba Allah yang bersaudara! Seorang Muslim adalah saudara Muslim yang lain: dia tidak menzaliminya, tidak membiarkannya tanpa pertolongan, tidak mendustainya, dan tidak menghinanya. Takwa itu di sini — baginda menunjuk ke dadanya tiga kali — cukuplah keburukan bagi seseorang dengan menghina saudaranya yang Muslim. Setiap Muslim atas Muslim yang lain haram: darahnya, hartanya, dan kehormatannya.',
  'От Аби Хурайры (да будет доволен им Аллах) передаётся: Посланник Аллаха ﷺ сказал: не завидуйте друг другу, не вздувайте цену (наджаш — без намерения купить), не питайте взаимной ненависти, не отворачивайтесь друг от друга, и пусть один из вас не торгует поверх торговли другого; будьте, о рабы Аллаха, братьями! Мусульманин — брат мусульманину: он не притесняет его, не оставляет без помощи, не лжёт ему и не презирает его. Богобоязненность — здесь — и он трижды указал на свою грудь — достаточно человеку зла, чтобы он презирал своего брата-мусульманина. Всё у мусульманина для (другого) мусульманина запретно: его кровь, его имущество и его честь.',
  -- translation
  'On the authority of Abu Hurayra (may Allah be pleased with him), the Messenger of Allah ﷺ said: "Do not envy one another, do not inflate prices against one another (najash), do not hate one another, do not turn your backs on one another, and let none of you sell over the sale of another. Be, O servants of Allah, brothers! The Muslim is the brother of the Muslim: he does not wrong him, nor abandon him, nor lie to him, nor despise him. Piety is here" — and he pointed to his chest three times — "It is enough evil for a person to despise his Muslim brother. The whole of a Muslim is inviolable to another Muslim: his blood, his wealth, and his honour."',
  'D''après Abû Hurayra (qu''Allah l''agrée), l''Envoyé d''Allah ﷺ a dit : « Ne vous enviez pas les uns les autres, ne faites pas monter les prix les uns contre les autres (najash), ne vous haïssez pas, ne vous tournez pas le dos, et que les uns ne vendent pas par-dessus la vente des autres. Soyez, ô serviteurs d''Allah, des frères ! Le musulman est le frère du musulman : il ne lui fait pas d''injustice, ne l''abandonne pas, ne lui ment pas et ne le méprise pas. La piété est ici » — et il désigna sa poitrine trois fois — « Il suffit à l''homme, comme mal, de mépriser son frère musulman. Tout est sacré chez le musulman pour le musulman : son sang, ses biens et son honneur. »',
  'Nach Abu Hurayra (möge Allah mit ihm zufrieden sein) sagte der Gesandte Allahs ﷺ: „Beneidet einander nicht, treibt die Preise gegeneinander nicht in die Höhe (Nadschasch), hasst einander nicht, kehrt einander nicht den Rücken, und keiner von euch verkaufe über den Verkauf eines anderen hinweg. Seid, o Diener Allahs, Brüder! Der Muslim ist der Bruder des Muslims: er tut ihm kein Unrecht, lässt ihn nicht im Stich, belügt ihn nicht und verachtet ihn nicht. Die Frömmigkeit ist hier" — und er deutete dreimal auf seine Brust — „Es genügt einem Menschen an Schlechtigkeit, dass er seinen muslimischen Bruder verachtet. Alles am Muslim ist dem (anderen) Muslim unverletzlich: sein Blut, sein Vermögen und seine Ehre."',
  'Op gezag van Abu Hurayra (moge Allah tevreden met hem zijn) zei de Boodschapper van Allah ﷺ: „Benijd elkaar niet, drijf de prijzen tegen elkaar niet op (najash), haat elkaar niet, keer elkaar niet de rug toe, en laat niemand van jullie verkopen over de verkoop van een ander heen. Wees, o dienaren van Allah, broeders! De moslim is de broeder van de moslim: hij doet hem geen onrecht, laat hem niet in de steek, liegt niet tegen hem en veracht hem niet. De vroomheid is hier" — en hij wees drie keer naar zijn borst — „Het is genoeg kwaad voor een mens dat hij zijn moslimbroeder veracht. Alles van de moslim is onschendbaar voor de (andere) moslim: zijn bloed, zijn bezit en zijn eer."',
  'Ebû Hüreyre''den (Allah ondan razı olsun) rivayet edildiğine göre Resûlullah ﷺ şöyle buyurdu: „Birbirinize haset etmeyin, alıcı olmadan fiyat kızıştırmayın (neceş yapmayın), birbirinize buğzetmeyin, birbirinize sırt çevirmeyin, biriniz diğerinin satışı üzerine satış yapmasın. Ey Allah''ın kulları, kardeşler olun! Müslüman müslümanın kardeşidir: ona zulmetmez, onu yardımsız bırakmaz, ona yalan söylemez ve onu hor görmez. Takvâ işte buradadır" — ve göğsüne üç kez işaret etti — „Kişiye kötülük olarak müslüman kardeşini hor görmesi yeter. Müslümanın müslümana her şeyi haramdır: kanı, malı ve ırzı."',
  'Dari Abu Hurairah (semoga Allah meridhainya), Rasulullah ﷺ bersabda: "Janganlah kalian saling mendengki, janganlah kalian melakukan najasy, janganlah kalian saling membenci, janganlah kalian saling membelakangi, dan janganlah sebagian kalian menjual di atas penjualan sebagian yang lain. Jadilah kalian, wahai hamba-hamba Allah, bersaudara! Seorang muslim adalah saudara muslim lainnya: ia tidak menzaliminya, tidak menelantarkannya, tidak mendustainya, dan tidak menghinakannya. Takwa itu di sini" — beliau menunjuk ke dadanya tiga kali — "Cukuplah keburukan bagi seseorang dengan menghina saudaranya yang muslim. Setiap muslim atas muslim lainnya haram: darahnya, hartanya, dan kehormatannya."',
  'ابو ہریرہ رضی اللہ عنہ سے روایت ہے کہ رسول اللہ ﷺ نے فرمایا: ”آپس میں حسد نہ کرو، خریدنے کی نیت کے بغیر قیمت نہ بڑھاؤ (نجش نہ کرو)، آپس میں بغض نہ رکھو، ایک دوسرے سے منہ نہ موڑو، اور تم میں سے کوئی دوسرے کی بیع پر بیع نہ کرے۔ اے اللہ کے بندو! بھائی بھائی بن جاؤ۔ مسلمان مسلمان کا بھائی ہے: نہ اس پر ظلم کرتا ہے، نہ اسے بے یار و مددگار چھوڑتا ہے، نہ اس سے جھوٹ بولتا ہے، اور نہ اسے حقیر سمجھتا ہے۔ تقویٰ یہاں ہے“ — اور آپ نے تین بار اپنے سینے کی طرف اشارہ کیا — ”آدمی کے برا ہونے کے لیے اتنا ہی کافی ہے کہ وہ اپنے مسلمان بھائی کو حقیر سمجھے۔ ہر مسلمان کا (دوسرے) مسلمان پر سب کچھ حرام ہے: اس کا خون، اس کا مال اور اس کی عزت۔“',
  'আবু হুরায়রা (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, রাসূলুল্লাহ ﷺ বলেছেন: "তোমরা পরস্পর হিংসা করো না, ক্রয়ের নিয়ত ছাড়া দাম বাড়িয়ো না (নাজাশ করো না), পরস্পর বিদ্বেষ রেখো না, একে অপরের থেকে মুখ ফিরিয়ে নিয়ো না, এবং তোমাদের কেউ অপরের বেচাকেনার উপর বেচাকেনা করো না। হে আল্লাহর বান্দারা! ভাই ভাই হয়ে যাও। মুসলিম মুসলিমের ভাই: সে তার ওপর যুলম করে না, তাকে অসহায় ছেড়ে দেয় না, তার সাথে মিথ্যা বলে না, এবং তাকে তুচ্ছ মনে করে না। তাকওয়া এখানে" — তিনি তিনবার তাঁর বুকের দিকে ইশারা করলেন — "একজন মানুষের মন্দ হওয়ার জন্য এতটুকুই যথেষ্ট যে সে তার মুসলিম ভাইকে তুচ্ছ মনে করে। প্রত্যেক মুসলিমের (অপর) মুসলিমের উপর সবকিছু হারাম: তার রক্ত, তার সম্পদ ও তার সম্মান।"',
  'Daripada Abu Hurairah (semoga Allah meredainya), Rasulullah ﷺ bersabda: "Janganlah kamu saling mendengki, janganlah kamu melakukan najasy, janganlah kamu saling membenci, janganlah kamu saling membelakangi, dan janganlah sebahagian kamu menjual di atas jualan sebahagian yang lain. Jadilah kamu, wahai hamba-hamba Allah, bersaudara! Seorang Muslim adalah saudara Muslim yang lain: dia tidak menzaliminya, tidak membiarkannya tanpa pertolongan, tidak mendustainya, dan tidak menghinanya. Takwa itu di sini" — baginda menunjuk ke dadanya tiga kali — "Cukuplah keburukan bagi seseorang dengan menghina saudaranya yang Muslim. Setiap Muslim atas Muslim yang lain haram: darahnya, hartanya, dan kehormatannya."',
  'Со слов Абу Хурайры (да будет доволен им Аллах) Посланник Аллаха ﷺ сказал: «Не завидуйте друг другу, не вздувайте цену друг против друга (наджаш), не питайте взаимной ненависти, не отворачивайтесь друг от друга, и пусть один из вас не торгует поверх торговли другого. Будьте, о рабы Аллаха, братьями! Мусульманин — брат мусульманину: он не притесняет его, не оставляет без помощи, не лжёт ему и не презирает его. Богобоязненность — здесь» — и он трижды указал на свою грудь — «Достаточно человеку зла, чтобы он презирал своего брата-мусульманина. Всё у мусульманина для (другого) мусульманина запретно: его кровь, его имущество и его честь».',
  -- reference
  'Sahih — reported by Muslim (no. 2564), al-Bayhaqi (7/303), Ahmad (3/110, 119, 209, 277), and al-Humaydi (no. 1183)',
  'Hadith authentique rapporté par Muslim (n°2564), al-Bayhaqî (7/303), Ahmad (3/110, 119, 209, 277) et al-Humaydî (n°1183)',
  'حديث صحيح، رواه مسلم (رقم ٢٥٦٤) والبيهقي (٧/٣٠٣) وأحمد (٣/١١٠، ١١٩، ٢٠٩، ٢٧٧) والحميدي (رقم ١١٨٣)',
  'Sahih — überliefert von Muslim (Nr. 2564), al-Bayhaqi (7/303), Ahmad (3/110, 119, 209, 277) und al-Humaydi (Nr. 1183)',
  'Sahih — overgeleverd door Muslim (nr. 2564), al-Bayhaqi (7/303), Ahmad (3/110, 119, 209, 277) en al-Humaydi (nr. 1183)',
  'Sahih — Müslim (no. 2564), Beyhakî (7/303), Ahmed (3/110, 119, 209, 277) ve Humeydî (no. 1183) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 2564), al-Baihaqi (7/303), Ahmad (3/110, 119, 209, 277), dan al-Humaidi (no. 1183)',
  'صحیح حدیث، اسے مسلم (نمبر ۲۵۶۴)، بیہقی (۷/۳۰۳)، احمد (۳/۱۱۰، ۱۱۹، ۲۰۹، ۲۷۷) اور حمیدی (نمبر ۱۱۸۳) نے روایت کیا',
  'সহীহ হাদীস — মুসলিম (নং ২৫৬৪), বায়হাকী (৭/৩০৩), আহমাদ (৩/১১০, ১১৯, ২০৯, ২৭৭) ও হুমায়দী (নং ১১৮৩) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 2564), al-Baihaqi (7/303), Ahmad (3/110, 119, 209, 277), dan al-Humaidi (no. 1183)',
  'Достоверный хадис, передали Муслим (№ 2564), аль-Байхаки (7/303), Ахмад (3/110, 119, 209, 277) и аль-Хумайди (№ 1183)',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-35-Nawawi-Psalmodie-Arabe.mp3',
  5,
  35
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 35
);
