-- =============================================================================
-- 40 Hadith Nawawi — Hadith 11: "Leave what makes you doubt" (waraʿ)
-- Target collection: public.hadith_collections.id = 2  /  position = 11
-- Idempotent guard on (collection, position). All 11 content languages.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Leave what makes you doubt',
  'Se préserver du douteux',
  'التورع عن الشبهات',
  'Lass, was dich zweifeln lässt',
  'Laat wat je doet twijfelen',
  'Şüpheliden sakınmak',
  'Menjauhi yang meragukan',
  'مشتبہ سے بچنا',
  'সন্দেহজনক বিষয় পরিহার',
  'Menjauhi yang meragukan',
  'Оставление сомнительного',
  -- arabic_text
  'عَنْ أَبِي مُحَمَّدٍ الْحَسَنِ بْنِ عَلِيِّ بْنِ أَبِي طَالِبٍ سِبْطِ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَرَيْحَانَتِهِ رَضِيَ اللَّهُ عَنْهُمَا قَالَ: حَفِظْتُ مِنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «دَعْ مَا يَرِيبُكَ إِلَى مَا لَا يَرِيبُكَ»',
  -- transcription
  'ʿan Abī Muḥammadin al-Ḥasani bni ʿAliyyi bni Abī Ṭālibin sibṭi Rasūli Llāhi ṣalla Llāhu ʿalayhi wa-sallama wa-rayḥānatihi raḍiya Llāhu ʿanhumā qāla: ḥafiẓtu min Rasūli Llāhi ṣalla Llāhu ʿalayhi wa-sallama: daʿ mā yarībuka ilā mā lā yarībuk.',
  'ʿan Abî Mouhammadin al-Hasani bni ʿAliyyi bni Abî Tâlibin sibti Rassôli Llâhi (salla Llâhou ʿalayhi wa sallam) wa rayhânatihi (radia Llâhou ʿanhoumâ) qâla : hafiztou min Rassôli Llâhi : daʿ mâ yarîbouka ilâ mâ lâ yarîbouk.',
  'ʿan Abī Muhammadin al-Hasani bni ʿAlijji bni Abī Tālibin sibti Rasūli Llāhi (salla Llāhu ʿalaihi wa-sallam) wa-raihānatihi (radiya Llāhu ʿanhumā) qāla: hafiztu min Rasūli Llāhi: daʿ mā jarībuka ilā mā lā jarībuk.',
  'ʿan Abie Moehammadin al-Hasani bni ʿAlijji bni Abie Taalibin sibti Rasoeli Llaahi (salla Llaahoe ʿalaihi wa-sallam) wa-raihaanatihi (radia Llaahoe ʿanhoemaa) qaala: hafiztoe min Rasoeli Llaahi: daʿ maa jarieboeka ilaa maa laa jarieboek.',
  'an Ebû Muhammed el-Hasen ibn Alî ibn Ebî Tâlib''ten — Resûlullah''ın (s.a.v.) torunu ve reyhanı (radıyallâhu anhümâ) — rivayetle dedi ki: Resûlullah''tan (s.a.v.) şunu belledim: deʿ mâ yerîbuke ilâ mâ lâ yerîbuk.',
  'ʿan Abī Muhammad al-Hasan bin ʿAli bin Abī Thālib cucu Rasulullah (shallallāhu ʿalaihi wa sallam) dan kesayangannya (radhiyallāhu ʿanhumā) berkata: aku menghafal dari Rasulullah (shallallāhu ʿalaihi wa sallam): daʿ mā yarībuka ilā mā lā yarībuk.',
  'ابو محمد حسن بن علی بن ابی طالب — جو رسول اللہ صلی اللہ علیہ وسلم کے نواسے اور آپ کے پھول ہیں — رضی اللہ عنہما سے روایت ہے، انہوں نے کہا: میں نے رسول اللہ صلی اللہ علیہ وسلم سے یہ یاد رکھا: دَع ما یَرِیبُکَ اِلٰی ما لا یَرِیبُکَ۔',
  'আবু মুহাম্মাদ হাসান ইবনে আলী ইবনে আবী তালিব — রাসূলুল্লাহ ﷺ-এর দৌহিত্র ও তাঁর ফুল (রাইহানা) (রাদিয়াল্লাহু আনহুমা) থেকে বর্ণিত, তিনি বলেন: আমি রাসূলুল্লাহ ﷺ থেকে এটি মুখস্থ করেছি: দাʿ মা ইয়ারীবুকা ইলা মা লা ইয়ারীবুক।',
  'ʿan Abī Muhammad al-Hasan bin ʿAli bin Abī Tālib cucu Rasulullah (sallallāhu ʿalaihi wa sallam) dan kesayangannya (radhiallāhu ʿanhumā) berkata: aku menghafal daripada Rasulullah (sallallāhu ʿalaihi wa sallam): daʿ mā yarībuka ilā mā lā yarībuk.',
  'Ан Аби Мухаммад аль-Хасан ибн Али ибн Аби Талиб — внук Посланника Аллаха ﷺ и его благоухание (да будет доволен Аллах ими обоими) — сказал: я запомнил от Посланника Аллаха ﷺ: даʿ ма ярибука иля ма ля ярибук.',
  -- translation
  'On the authority of Abu Muhammad al-Hasan ibn ʿAli ibn Abi Talib — the grandson of the Messenger of Allah ﷺ and his beloved (rayhana) (may Allah be pleased with them both) — who said: I memorised from the Messenger of Allah ﷺ: "Leave what makes you doubt for what does not make you doubt."',
  'D''après Abû Muhammad al-Hasan ibn ʿAli ibn Abî Tâlib — le petit-fils de l''Envoyé d''Allah ﷺ et sa fleur (rayhâna) (qu''Allah les agrée tous deux) — qui a dit : J''ai retenu de l''Envoyé d''Allah ﷺ ces paroles : « Renonce à ce qui t''inspire du doute pour ce qui ne t''en inspire pas. »',
  'Nach Abu Muhammad al-Hasan ibn ʿAli ibn Abi Talib — dem Enkel des Gesandten Allahs ﷺ und seiner Wonne (Rayhana) (möge Allah mit beiden zufrieden sein) — der sagte: Ich habe vom Gesandten Allahs ﷺ behalten: „Lass, was dich zweifeln lässt, für das, was dich nicht zweifeln lässt."',
  'Op gezag van Abu Muhammad al-Hasan ibn ʿAli ibn Abi Talib — de kleinzoon van de Boodschapper van Allah ﷺ en zijn lieveling (rayhana) (moge Allah tevreden met hen beiden zijn) — die zei: Ik heb van de Boodschapper van Allah ﷺ onthouden: „Laat wat je doet twijfelen voor wat je niet doet twijfelen."',
  'Ebû Muhammed el-Hasen ibn Alî ibn Ebî Tâlib''ten — Resûlullah''ın ﷺ torunu ve reyhanı (Allah her ikisinden de razı olsun) — rivayet edildiğine göre şöyle dedi: Resûlullah''tan ﷺ şunu belledim: „Sana şüphe vereni bırak, şüphe vermeyene geç."',
  'Dari Abu Muhammad al-Hasan bin Ali bin Abi Thalib — cucu Rasulullah ﷺ dan kesayangannya (semoga Allah meridhai keduanya) — yang berkata: Aku menghafal dari Rasulullah ﷺ: "Tinggalkanlah apa yang meragukanmu kepada apa yang tidak meragukanmu."',
  'ابو محمد حسن بن علی بن ابی طالب — جو رسول اللہ ﷺ کے نواسے اور آپ کی خوشبو (ریحانہ) ہیں (رضی اللہ عنہما) — سے روایت ہے، انہوں نے کہا: میں نے رسول اللہ ﷺ سے یہ یاد رکھا: ”جو چیز تجھے شک میں ڈالے اسے چھوڑ کر اس چیز کی طرف چلا جا جو تجھے شک میں نہ ڈالے۔“',
  'আবু মুহাম্মাদ হাসান ইবনে আলী ইবনে আবী তালিব — রাসূলুল্লাহ ﷺ-এর দৌহিত্র ও তাঁর সুরভি (রাইহানা) (রাদিয়াল্লাহু আনহুমা) — থেকে বর্ণিত, তিনি বলেন: আমি রাসূলুল্লাহ ﷺ থেকে এটি মুখস্থ করেছি: "যা তোমাকে সন্দেহে ফেলে তা ছেড়ে যা তোমাকে সন্দেহে ফেলে না তার দিকে চলে যাও।"',
  'Daripada Abu Muhammad al-Hasan bin Ali bin Abi Talib — cucu Rasulullah ﷺ dan kesayangannya (semoga Allah meredai keduanya) — yang berkata: Aku menghafal daripada Rasulullah ﷺ: "Tinggalkanlah apa yang meragukanmu kepada apa yang tidak meragukanmu."',
  'Со слов Абу Мухаммада аль-Хасана ибн Али ибн Аби Талиба — внука Посланника Аллаха ﷺ и его благоухания (райхана) (да будет доволен Аллах ими обоими) — который сказал: Я запомнил от Посланника Аллаха ﷺ: «Оставь то, что вызывает у тебя сомнение, ради того, что сомнения не вызывает».',
  -- reference
  'Hasan Sahih — reported by at-Tirmidhi (no. 2518) and an-Nasaʾi (8/327-328); at-Tirmidhi said: "A good, sound hadith (hasan sahih)."',
  'Hadith hasan sahih rapporté par at-Tirmidhî (n°2518) et an-Nasâʾî (8/327-328) ; at-Tirmidhî a dit : « Hadith hasan sahih. »',
  'حديث حسن صحيح، رواه الترمذي (رقم ٢٥١٨) والنسائي (٨/٣٢٧-٣٢٨)، وقال الترمذي: حديث حسن صحيح',
  'Hasan Sahih — überliefert von at-Tirmidhi (Nr. 2518) und an-Nasaʾi (8/327-328); at-Tirmidhi sagte: „Ein guter, gesunder Hadith (hasan sahih)."',
  'Hasan Sahih — overgeleverd door at-Tirmidhi (nr. 2518) en an-Nasaʾi (8/327-328); at-Tirmidhi zei: „Een goede, gezonde hadith (hasan sahih)."',
  'Hasen-Sahih — Tirmizî (no. 2518) ve Nesâî (8/327-328) rivayet etmiştir; Tirmizî: „Hasen-sahih bir hadistir" demiştir',
  'Hadis hasan sahih, diriwayatkan oleh at-Tirmidzi (no. 2518) dan an-Nasaʾi (8/327-328); at-Tirmidzi berkata: "Hadis hasan sahih."',
  'حسن صحیح حدیث، اسے ترمذی (نمبر ۲۵۱۸) اور نسائی (۸/۳۲۷-۳۲۸) نے روایت کیا، اور ترمذی نے کہا: حدیث حسن صحیح ہے',
  'হাসান সহীহ হাদীস — তিরমিযী (নং ২৫১৮) ও নাসাঈ (৮/৩২৭-৩২৮) বর্ণনা করেছেন; তিরমিযী বলেছেন: "হাদীসটি হাসান সহীহ।"',
  'Hadis hasan sahih, diriwayatkan oleh at-Tirmizi (no. 2518) dan an-Nasaʾi (8/327-328); at-Tirmizi berkata: "Hadis hasan sahih."',
  'Хороший достоверный (хасан сахих) хадис, передали ат-Тирмизи (№ 2518) и ан-Насаи (8/327-328); ат-Тирмизи сказал: «Хадис хасан сахих».',
  -- tafsir
  'Abu Muhammad al-Hasan ibn ʿAli is the grandson of the Messenger of Allah ﷺ, the better of the two Hasans (his brother is named al-Husayn). The Prophet ﷺ praised him with the words: "This son of mine is a master (sayyid), and Allah may reconcile through him two great parties of the Muslims." Indeed, Allah reconciled through him two conflicting parties when he relinquished the caliphate in favour of Muʿawiya, son of Abu Sufyan, thereby attaining this nobility.\nThese words of the Prophet ﷺ — "Leave what makes you doubt for what does not make you doubt" — carry the same meaning as his words in the previous hadith: "Between them (the lawful and the unlawful) are doubtful matters which many people do not know; whoever guards against the doubtful matters has protected his religion and his honour."\nSo whatever inspires doubt, whether in worldly affairs or those of the Hereafter, it is best to discard it and leave it, so as not to subject the soul to anxiety and uncertainty.',
  'Abû Muhammad al-Hasan ibn ʿAli est le petit-fils de l''Envoyé d''Allah ﷺ, le meilleur des deux Hasan (son frère s''appelle al-Husayn). Le Prophète ﷺ l''a loué par ces paroles : « Ce mien fils est un noble (sayyid), et il se peut qu''Allah réconcilie par lui deux grands partis d''entre les musulmans. » En effet, Allah a réconcilié par lui deux partis en conflit lorsqu''il a abdiqué le califat au profit de Muʿawiya fils d''Abû Sufyân, acquérant ainsi cette noblesse.\nCes paroles du Prophète ﷺ — « Renonce à ce qui t''inspire du doute pour ce qui ne t''en inspire pas » — vont dans le même sens que ses paroles du hadith précédent : « Entre les deux (le licite et l''illicite), il y a des choses équivoques que beaucoup de gens ignorent ; quiconque se met à l''abri des choses équivoques préserve sa religion et son honneur. »\nDonc, ce qui inspire le doute, que ce soit dans les affaires d''ici-bas ou celles de l''au-delà, le mieux est de s''en débarrasser et d''y renoncer, afin de ne pas livrer l''âme à l''inquiétude et à l''incertitude.',
  'أبو محمد الحسن بن علي هو سبط رسول الله صلى الله عليه وسلم، وهو أفضل الحسنين (وأخوه اسمه الحسين)، وقد أثنى عليه النبي صلى الله عليه وسلم بقوله: «إن ابني هذا سيد، ولعل الله أن يصلح به بين فئتين عظيمتين من المسلمين». وقد أصلح الله به بين فئتين متنازعتين حين تنازل عن الخلافة لمعاوية بن أبي سفيان، فنال بذلك هذه السيادة.\nوقول النبي صلى الله عليه وسلم: «دع ما يريبك إلى ما لا يريبك» يحمل المعنى نفسه الذي في الحديث السابق: «وبينهما (الحلال والحرام) أمور مشتبهات لا يعلمهن كثير من الناس، فمن اتقى الشبهات فقد استبرأ لدينه وعرضه».\nفما أوقعك في الريبة، سواء في أمور الدنيا أو الآخرة، فالأفضل أن تتركه وتطرحه، حتى لا تُسلِّم النفس للقلق وعدم اليقين.',
  'Abu Muhammad al-Hasan ibn ʿAli ist der Enkel des Gesandten Allahs ﷺ, der bessere der beiden Hasan (sein Bruder heißt al-Husayn). Der Prophet ﷺ lobte ihn mit den Worten: „Dieser mein Sohn ist ein Herr (Sayyid), und vielleicht wird Allah durch ihn zwei große Parteien der Muslime versöhnen." In der Tat versöhnte Allah durch ihn zwei verfeindete Parteien, als er das Kalifat zugunsten Muʿawiyas, des Sohnes Abu Sufyans, niederlegte und so diesen Adel erlangte.\nDiese Worte des Propheten ﷺ — „Lass, was dich zweifeln lässt, für das, was dich nicht zweifeln lässt" — tragen dieselbe Bedeutung wie seine Worte im vorigen Hadith: „Zwischen beiden (dem Erlaubten und dem Verbotenen) liegen zweifelhafte Dinge, die viele Menschen nicht kennen; wer sich vor den zweifelhaften Dingen hütet, hat seine Religion und seine Ehre bewahrt."\nWas also Zweifel hervorruft, sei es in weltlichen oder jenseitigen Angelegenheiten, das ist am besten zu verwerfen und zu lassen, um die Seele nicht der Unruhe und Ungewissheit auszuliefern.',
  'Abu Muhammad al-Hasan ibn ʿAli is de kleinzoon van de Boodschapper van Allah ﷺ, de betere van de twee Hasans (zijn broer heet al-Husayn). De Profeet ﷺ prees hem met de woorden: „Deze zoon van mij is een meester (sayyid), en wellicht zal Allah door hem twee grote partijen van de moslims verzoenen." Inderdaad verzoende Allah door hem twee strijdende partijen toen hij het kalifaat opgaf ten gunste van Muʿawiya, de zoon van Abu Sufyan, en zo deze adel verwierf.\nDeze woorden van de Profeet ﷺ — „Laat wat je doet twijfelen voor wat je niet doet twijfelen" — dragen dezelfde betekenis als zijn woorden in de vorige hadith: „Tussen beide (het toegestane en het verbodene) liggen twijfelachtige zaken die veel mensen niet kennen; wie zich voor de twijfelachtige zaken hoedt, heeft zijn religie en zijn eer beschermd."\nWat dus twijfel oproept, hetzij in wereldse zaken of die van het Hiernamaals, is het beste te verwerpen en te laten, om de ziel niet over te leveren aan onrust en onzekerheid.',
  'Ebû Muhammed el-Hasen ibn Alî, Resûlullah''ın ﷺ torunudur, iki Hasen''in (kardeşinin adı Hüseyin''dir) daha faziletlisidir. Peygamber ﷺ onu şu sözüyle övmüştür: „Şu oğlum bir seyyiddir (efendidir); umulur ki Allah onun eliyle Müslümanlardan iki büyük topluluğun arasını düzeltir." Nitekim o, hilafetten Muâviye ibn Ebî Süfyân lehine feragat ettiğinde, Allah onun eliyle iki çekişen topluluğun arasını düzeltmiş ve böylece o bu efendiliği elde etmiştir.\nPeygamber''in ﷺ „Sana şüphe vereni bırak, şüphe vermeyene geç" sözü, önceki hadisteki şu sözüyle aynı manayı taşır: „İkisi (helal ve haram) arasında, birçok insanın bilmediği şüpheli işler vardır; kim şüpheli şeylerden sakınırsa dinini ve ırzını korumuş olur."\nDolayısıyla, ister dünya ister âhiret işlerinde olsun, seni şüpheye düşüren şeyi terk edip bir kenara atman daha iyidir; ta ki nefsi kaygıya ve belirsizliğe teslim etmeyesin.',
  'Abu Muhammad al-Hasan bin Ali adalah cucu Rasulullah ﷺ, yang lebih utama di antara dua Hasan (saudaranya bernama al-Husain). Nabi ﷺ memujinya dengan sabdanya: "Sesungguhnya anakku ini adalah seorang sayyid (pemimpin), dan semoga Allah mendamaikan dengannya dua golongan besar kaum muslimin." Sungguh Allah telah mendamaikan dengannya dua golongan yang berselisih ketika ia menyerahkan kekhalifahan kepada Muʿawiyah bin Abi Sufyan, sehingga ia memperoleh kemuliaan ini.\nSabda Nabi ﷺ — "Tinggalkanlah apa yang meragukanmu kepada apa yang tidak meragukanmu" — mengandung makna yang sama dengan sabdanya pada hadis sebelumnya: "Di antara keduanya (yang halal dan yang haram) ada perkara-perkara samar yang tidak diketahui oleh kebanyakan manusia; barangsiapa menjaga diri dari perkara-perkara samar, sungguh ia telah membersihkan agama dan kehormatannya."\nMaka apa pun yang menimbulkan keraguan, baik dalam urusan dunia maupun akhirat, yang terbaik adalah membuangnya dan meninggalkannya, agar tidak menyerahkan jiwa kepada kegelisahan dan ketidakpastian.',
  'ابو محمد حسن بن علی رسول اللہ ﷺ کے نواسے ہیں، اور دونوں حسن میں افضل ہیں (ان کے بھائی کا نام حسین ہے)۔ نبی ﷺ نے ان کی تعریف ان الفاظ سے کی: ”میرا یہ بیٹا سردار ہے، اور امید ہے کہ اللہ اس کے ذریعے مسلمانوں کے دو بڑے گروہوں میں صلح کرا دے گا۔“ چنانچہ اللہ نے ان کے ذریعے دو متنازع گروہوں میں صلح کرا دی جب انہوں نے معاویہ بن ابی سفیان کے حق میں خلافت سے دستبرداری اختیار کی، اور یوں انہوں نے یہ سرداری حاصل کی۔\nنبی ﷺ کا یہ فرمان — ”جو چیز تجھے شک میں ڈالے اسے چھوڑ کر اس کی طرف چلا جا جو شک میں نہ ڈالے“ — وہی معنی رکھتا ہے جو پچھلی حدیث کے ان الفاظ میں ہے: ”ان دونوں (حلال و حرام) کے درمیان کچھ مشتبہ چیزیں ہیں جنہیں بہت سے لوگ نہیں جانتے؛ جو مشتبہ چیزوں سے بچ گیا اس نے اپنے دین اور عزت کو محفوظ کر لیا۔“\nپس جو چیز تجھے شک میں ڈالے، خواہ دنیا کے معاملات میں ہو یا آخرت کے، بہتر یہی ہے کہ اسے چھوڑ دے اور پھینک دے، تاکہ نفس کو پریشانی اور بے یقینی کے حوالے نہ کرے۔',
  'আবু মুহাম্মাদ হাসান ইবনে আলী রাসূলুল্লাহ ﷺ-এর দৌহিত্র, দুই হাসানের মধ্যে শ্রেষ্ঠতর (তাঁর ভাইয়ের নাম হুসাইন)। নবী ﷺ তাঁর প্রশংসা করেছেন এই বলে: "আমার এই পুত্র একজন সায়্যিদ (নেতা), এবং আশা করা যায় আল্লাহ তার মাধ্যমে মুসলমানদের দুটি বড় দলের মধ্যে মীমাংসা করাবেন।" প্রকৃতপক্ষে আল্লাহ তাঁর মাধ্যমে দুটি বিবদমান দলের মধ্যে মীমাংসা করিয়েছেন যখন তিনি মুআবিয়া ইবনে আবী সুফিয়ানের পক্ষে খিলাফত ত্যাগ করেছিলেন, এভাবে তিনি এই মর্যাদা অর্জন করেন।\nনবী ﷺ-এর এই বাণী — "যা তোমাকে সন্দেহে ফেলে তা ছেড়ে যা সন্দেহে ফেলে না তার দিকে যাও" — পূর্ববর্তী হাদীসের এই বাণীর সমার্থক: "এ দুইয়ের (হালাল ও হারামের) মাঝে রয়েছে কিছু সন্দেহজনক বিষয় যা অনেক মানুষ জানে না; যে সন্দেহজনক বিষয় থেকে বেঁচে থাকল সে তার দ্বীন ও সম্মান রক্ষা করল।"\nসুতরাং যা সন্দেহ সৃষ্টি করে, তা দুনিয়ার বিষয়েই হোক বা আখিরাতের, সবচেয়ে উত্তম হলো তা ত্যাগ করা ও পরিহার করা, যাতে অন্তরকে উদ্বেগ ও অনিশ্চয়তার হাতে সমর্পণ না করা হয়।',
  'Abu Muhammad al-Hasan bin Ali ialah cucu Rasulullah ﷺ, yang lebih utama antara dua Hasan (saudaranya bernama al-Husain). Nabi ﷺ memujinya dengan sabdanya: "Sesungguhnya anakku ini ialah seorang sayyid (pemimpin), dan semoga Allah mendamaikan dengannya dua golongan besar kaum Muslimin." Sungguh Allah telah mendamaikan dengannya dua golongan yang berselisih ketika dia menyerahkan khilafah kepada Muʿawiyah bin Abi Sufyan, sehingga dia memperoleh kemuliaan ini.\nSabda Nabi ﷺ — "Tinggalkanlah apa yang meragukanmu kepada apa yang tidak meragukanmu" — mengandungi makna yang sama dengan sabdanya pada hadis sebelumnya: "Antara keduanya (yang halal dan yang haram) ada perkara-perkara samar yang tidak diketahui oleh kebanyakan manusia; sesiapa yang menjaga diri daripada perkara-perkara samar, sungguh dia telah membersihkan agama dan maruahnya."\nMaka apa sahaja yang menimbulkan keraguan, sama ada dalam urusan dunia mahupun akhirat, yang terbaik ialah membuangnya dan meninggalkannya, agar tidak menyerahkan jiwa kepada kegelisahan dan ketidakpastian.',
  'Абу Мухаммад аль-Хасан ибн Али — внук Посланника Аллаха ﷺ, лучший из двух аль-Хасанов (его брата зовут аль-Хусайн). Пророк ﷺ похвалил его словами: «Поистине, этот мой сын — господин (саййид), и, возможно, Аллах примирит через него две большие группы мусульман». И действительно, Аллах примирил через него две враждующие группы, когда он отказался от халифата в пользу Муавии, сына Абу Суфьяна, обретя тем самым это благородство.\nЭти слова Пророка ﷺ — «Оставь то, что вызывает у тебя сомнение, ради того, что сомнения не вызывает» — несут тот же смысл, что и его слова в предыдущем хадисе: «Между ними (дозволенным и запретным) — сомнительные вещи, которых не знают многие люди; кто остерегается сомнительного, тот оберегает свою религию и свою честь».\nИтак, всё, что вызывает сомнение, будь то в делах этого мира или будущего, лучше всего отбросить и оставить, чтобы не предавать душу тревоге и неуверенности.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-11-Nawawi-Psalmodie-Arabe.mp3',
  5,
  11
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 11
);
