-- =============================================================================
-- 40 Hadith Nawawi — Hadith 23: "Purification is half of faith"
-- Target collection: public.hadith_collections.id = 2  /  position = 23
-- Idempotent guard on (collection, position). All 11 content languages.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Purification is half of faith',
  'L''empressement dans les œuvres de bien',
  'الطهور شطر الإيمان',
  'Reinheit ist die Hälfte des Glaubens',
  'Reinheid is de helft van het geloof',
  'Temizlik imanın yarısıdır',
  'Bersuci adalah separuh iman',
  'پاکیزگی ایمان کا نصف ہے',
  'পবিত্রতা ঈমানের অর্ধেক',
  'Bersuci ialah separuh iman',
  'Чистота — половина веры',
  -- arabic_text
  'عَنْ أَبِي مَالِكٍ الْحَارِثِ بْنِ عَاصِمٍ الْأَشْعَرِيِّ رَضِيَ اللَّهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «الطُّهُورُ شَطْرُ الْإِيمَانِ، وَالْحَمْدُ لِلَّهِ تَمْلَأُ الْمِيزَانَ، وَسُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ تَمْلَآنِ — أَوْ: تَمْلَأُ — مَا بَيْنَ السَّمَاءِ وَالْأَرْضِ، وَالصَّلَاةُ نُورٌ، وَالصَّدَقَةُ بُرْهَانٌ، وَالصَّبْرُ ضِيَاءٌ، وَالْقُرْآنُ حُجَّةٌ لَكَ أَوْ عَلَيْكَ. كُلُّ النَّاسِ يَغْدُو فَبَائِعٌ نَفْسَهُ فَمُعْتِقُهَا أَوْ مُوبِقُهَا»',
  -- transcription
  'ʿan Abī Mālikin al-Ḥārithi bni ʿĀṣimin al-Ashʿariyyi raḍiya Llāhu ʿanhu qāla: qāla Rasūlu Llāhi ṣalla Llāhu ʿalayhi wa-sallama: aṭ-ṭuhūru shaṭru l-īmāni, wa-l-ḥamdu li-Llāhi tamlaʾu l-mīzāna, wa-subḥāna Llāhi wa-l-ḥamdu li-Llāhi tamlaʾāni — aw: tamlaʾu — mā bayna s-samāʾi wa-l-arḍi, wa-ṣ-ṣalātu nūrun, wa-ṣ-ṣadaqatu burhānun, wa-ṣ-ṣabru ḍiyāʾun, wa-l-qurʾānu ḥujjatun laka aw ʿalayka. kullu n-nāsi yaghdū fa-bāʾiʿun nafsahu fa-muʿtiquhā aw mūbiquhā.',
  'ʿan Abî Mâlikin al-Hârithi bni ʿÂsimin al-Achʿariyyi (radia Llâhou ʿanhou) qâla : qâla Rassôlou Llâhi (salla Llâhou ʿalayhi wa sallam) : at-touhôurou chatrou l-îmâni, wa l-hamdou li-Llâhi tamlaʾou l-mîzâna, wa soubhâna Llâhi wa l-hamdou li-Llâhi tamlaʾâni — aw : tamlaʾou — mâ bayna s-samâʾi wa l-ardi, wa s-salâtou nôuroun, wa s-sadaqatou bourhânoun, wa s-sabrou diyâʾoun, wa l-qourʾânou houjjatoun laka aw ʿalayka. koullou n-nâsi yaghdô fa-bâʾiʿoun nafsahou fa-mouʿtiqouhâ aw môubiqouhâ.',
  'ʿan Abī Mālikin al-Hārithi bni ʿĀsimin al-Aschʿarijji (radiya Llāhu ʿanhu) qāla: qāla Rasūlu Llāhi (salla Llāhu ʿalaihi wa-sallam): at-tuhūru schatru l-īmāni, wa-l-hamdu li-Llāhi tamlaʾu l-mīzāna, wa-subhāna Llāhi wa-l-hamdu li-Llāhi tamlaʾāni — au: tamlaʾu — mā baina s-samāʾi wa-l-ardi, wa-s-salātu nūrun, wa-s-sadaqatu burhānun, wa-s-sabru dijāʾun, wa-l-qurʾānu hudschdschatun laka au ʿalaika. kullu n-nāsi jaghdū fa-bāʾiʿun nafsahu fa-muʿtiquhā au mūbiquhā.',
  'ʿan Abie Maalikin al-Haarithi bni ʿAasimin al-Asjʿarijji (radia Llaahoe ʿanhoe) qaala: qaala Rasoeloe Llaahi (salla Llaahoe ʿalaihi wa-sallam): at-toehoeroe sjatroe l-iemaani, wa-l-hamdoe li-Llaahi tamlaʾoe l-miezaana, wa-soebhaana Llaahi wa-l-hamdoe li-Llaahi tamlaʾaani — au: tamlaʾoe — maa baina s-samaaʾi wa-l-ardi, wa-s-salaatoe noeroen, wa-s-sadaqatoe boerhaanoen, wa-s-sabroe dijaaʾoen, wa-l-qoerʾaanoe hoedzjdzjatoen laka au ʿalaika. koelloe n-naasi jaghdoe fa-baaʾiʿoen nafsahoe fa-moeʿtiqoehaa au moebiqoehaa.',
  'an Ebû Mâlik el-Hâris ibn Âsım el-Eşʿarî''den (radıyallâhu anh) rivayetle dedi ki: Resûlullah (s.a.v.) şöyle buyurdu: et-tuhûru şatru''l-îmân, ve''l-hamdu li''llâhi temleu''l-mîzân, ve subhâna''llâhi ve''l-hamdu li''llâhi temleâni — ev: temleu — mâ beyne''s-semâi ve''l-ard, ve''s-salâtu nûr, ve''s-sadakatu burhân, ve''s-sabru ziyâʾ, ve''l-kurʾânu huccetun leke ev aleyk. kullu''n-nâsi yagdû fe-bâiʿun nefsehu fe-muʿtikuhâ ev mûbikuhâ.',
  'ʿan Abī Malik al-Harits bin ʿAshim al-Asyʿari (radhiyallāhu ʿanhu) berkata: Rasulullah (shallallāhu ʿalaihi wa sallam) bersabda: ath-thuhūru syathrul-īmān, wal-hamdu lillāhi tamlaʾul-mīzān, wa subhānallāhi wal-hamdu lillāhi tamlaʾāni — au: tamlaʾu — mā bainas-samāʾi wal-ardh, wash-shalātu nūr, wash-shadaqatu burhān, wash-shabru dhiyāʾ, wal-qurʾānu hujjatun laka au ʿalaik. kullun-nāsi yaghdū fabāʾiʿun nafsahu famuʿtiquhā au mūbiquhā.',
  'ابو مالک حارث بن عاصم الاشعری رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: الطُّہُورُ شَطرُ الاِیمانِ، وَالحَمدُ لِلّٰہِ تَملَاُ المِیزانَ، وَسُبحانَ اللہِ وَالحَمدُ لِلّٰہِ تَملَآنِ — اَو: تَملَاُ — ما بَینَ السَّماءِ وَالاَرضِ، وَالصَّلاۃُ نُورٌ، وَالصَّدَقَۃُ بُرہانٌ، وَالصَّبرُ ضِیاءٌ، وَالقُرآنُ حُجَّۃٌ لَکَ اَو عَلَیکَ۔ کُلُّ النّاسِ یَغدُو فَبائِعٌ نَفسَہُ فَمُعتِقُہا اَو مُوبِقُہا۔',
  'আবু মালিক হারিস ইবনে আসিম আল-আশআরী (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) বলেছেন: আত-তুহূরু শাতরুল ঈমান, ওয়াল হামদু লিল্লাহি তামলাউল মীযান, ওয়া সুবহানাল্লাহি ওয়াল হামদু লিল্লাহি তামলাআনি — আও: তামলাউ — মা বাইনাস সামাই ওয়াল আরদ, ওয়াস সালাতু নূর, ওয়াস সাদাকাতু বুরহান, ওয়াস সাবরু দিয়াউন, ওয়াল কুরআনু হুজ্জাতুন লাকা আও আলাইক। কুল্লুন নাসি ইয়াগদূ ফাবাইউন নাফসাহু ফামুতিকুহা আও মূবিকুহা।',
  'ʿan Abī Malik al-Harits bin ʿAsim al-Asyʿari (radhiallāhu ʿanhu) berkata: Rasulullah (sallallāhu ʿalaihi wa sallam) bersabda: ath-thuhūru syatrul-īmān, wal-hamdu lillāhi tamlaʾul-mīzān, wa subhānallāhi wal-hamdu lillāhi tamlaʾāni — atau: tamlaʾu — mā bainas-samāʾi wal-ardh, was-solātu nūr, was-sodaqotu burhān, was-sobru dhiyāʾ, wal-qurʾānu hujjatun laka atau ʿalaik. kullun-nāsi yaghdū fabāʾiʿun nafsahu famuʿtiquhā atau mūbiquhā.',
  'Ан Аби Малик аль-Харис ибн Асим аль-Ашари (да будет доволен им Аллах) сказал: сказал Посланник Аллаха ﷺ: ат-тухуру шатру ль-иман, валь-хамду ли-Лляхи тамлаʾу ль-мизан, ва субхана Ллахи валь-хамду ли-Лляхи тамлаʾани — ау: тамлаʾу — ма байна с-самаʾи валь-ард, ва с-саляту нур, ва с-садакату бурхан, ва с-сабру дияʾ, валь-курʾану худжжатун ляка ау аляйк. куллю н-наси ягду фа-баʾиʿун нафсаху фа-муʿтикуха ау мубикуха.',
  -- translation
  'On the authority of Abu Malik al-Harith ibn ʿAsim al-Ashʿari (may Allah be pleased with him), the Messenger of Allah ﷺ said: "Purification is half of faith. ''Alhamdu lillah'' (praise be to Allah) fills the scale. ''Subhan Allah wa-l-hamdu lillah'' (glory be to Allah and praise be to Allah) fill — or fills — what is between the heaven and the earth. Prayer is light. Charity is a proof. Patience is a radiance. The Qur''an is an argument for you or against you. Every person sets out in the morning and trades his soul, either freeing it or destroying it."',
  'D''après Abû Mâlik al-Hârith ibn ʿÂsim al-Ashʿarî (qu''Allah l''agrée), l''Envoyé d''Allah ﷺ a dit : « La purification est la moitié de la foi. Dire "Al-hamdu lillah" (louange à Allah) remplit la balance. Dire "Subhân Allah wa-l-hamdu lillah" (gloire et louange à Allah) remplit l''espace entre le ciel et la terre. La prière est lumière. L''aumône est une preuve. La patience est un flamboiement. Le Coran est un argument en ta faveur ou contre toi. Chaque homme part le matin et fait commerce de son âme, la libérant ou la faisant périr. »',
  'Nach Abu Malik al-Harith ibn ʿAsim al-Ashʿari (möge Allah mit ihm zufrieden sein) sagte der Gesandte Allahs ﷺ: „Die Reinheit ist die Hälfte des Glaubens. ''Alhamdu lillah'' (Lob sei Allah) füllt die Waage. ''Subhan Allah wa-l-hamdu lillah'' (Preis sei Allah und Lob sei Allah) füllen — oder füllt — was zwischen Himmel und Erde ist. Das Gebet ist Licht. Die Almosen sind ein Beweis. Die Geduld ist ein Leuchten. Der Qur''an ist ein Beweis für dich oder gegen dich. Jeder Mensch zieht am Morgen aus und handelt mit seiner Seele, sie befreiend oder sie zugrunde richtend."',
  'Op gezag van Abu Malik al-Harith ibn ʿAsim al-Ashʿari (moge Allah tevreden met hem zijn) zei de Boodschapper van Allah ﷺ: „Reinheid is de helft van het geloof. ''Alhamdoe lillah'' (lof zij Allah) vult de weegschaal. ''Soebhan Allah wa-l-hamdoe lillah'' (glorie zij Allah en lof zij Allah) vullen — of vult — wat tussen de hemel en de aarde is. Het gebed is licht. De aalmoes is een bewijs. Het geduld is een schittering. De Koran is een argument vóór jou of tegen jou. Ieder mens trekt in de ochtend uit en verhandelt zijn ziel, haar bevrijdend of haar te gronde richtend."',
  'Ebû Mâlik el-Hâris ibn Âsım el-Eşʿarî''den (Allah ondan razı olsun) rivayet edildiğine göre Resûlullah ﷺ şöyle buyurdu: „Temizlik imanın yarısıdır. ''Elhamdülillah'' (hamd Allah''a mahsustur) mizanı doldurur. ''Sübhânallâhi ve''l-hamdü lillâh'' (Allah''ı tenzih ederim ve hamd Allah''a mahsustur) gökle yer arasını doldurur. Namaz nurdur. Sadaka burhandır (delildir). Sabır ziyâdır (ışıktır). Kur''ân ya lehine ya da aleyhine bir delildir. Her insan sabahleyin yola çıkar; nefsini satar, ya onu azat eder ya da helâk eder."',
  'Dari Abu Malik al-Harits bin ʿAsim al-Asyʿari (semoga Allah meridhainya), Rasulullah ﷺ bersabda: "Bersuci adalah separuh iman. ''Alhamdulillah'' (segala puji bagi Allah) memenuhi timbangan. ''Subhanallah wal-hamdulillah'' (Mahasuci Allah dan segala puji bagi Allah) memenuhi — atau: memenuhi — ruang antara langit dan bumi. Shalat adalah cahaya. Sedekah adalah bukti. Sabar adalah sinar. Al-Qur''an adalah hujah yang membelamu atau memberatkanmu. Setiap manusia berangkat di pagi hari lalu menjual dirinya, maka ia membebaskannya atau membinasakannya."',
  'ابو مالک حارث بن عاصم الاشعری رضی اللہ عنہ سے روایت ہے کہ رسول اللہ ﷺ نے فرمایا: ”پاکیزگی ایمان کا نصف ہے۔ ''الحمد للہ'' کہنا میزان کو بھر دیتا ہے۔ ''سبحان اللہ والحمد للہ'' کہنا آسمان اور زمین کے درمیان کی جگہ کو بھر دیتا ہے۔ نماز نور ہے۔ صدقہ دلیل ہے۔ صبر روشنی ہے۔ قرآن تمہارے حق میں دلیل ہے یا تمہارے خلاف۔ ہر شخص صبح کو نکلتا ہے اور اپنی جان کا سودا کرتا ہے، پس یا تو اسے آزاد کر لیتا ہے یا اسے ہلاک کر دیتا ہے۔“',
  'আবু মালিক হারিস ইবনে আসিম আল-আশআরী (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, রাসূলুল্লাহ ﷺ বলেছেন: "পবিত্রতা ঈমানের অর্ধেক। ''আলহামদুলিল্লাহ'' (সমস্ত প্রশংসা আল্লাহর) মীযান পূর্ণ করে দেয়। ''সুবহানাল্লাহ ওয়াল হামদুলিল্লাহ'' (আল্লাহ পবিত্র ও সমস্ত প্রশংসা আল্লাহর) আসমান ও জমিনের মধ্যবর্তী স্থান পূর্ণ করে দেয়। সালাত নূর। সদকা প্রমাণ। ধৈর্য জ্যোতি। কুরআন তোমার পক্ষে অথবা বিপক্ষে দলিল। প্রত্যেক মানুষ সকালে বের হয় এবং নিজের আত্মার সওদা করে, ফলে হয় সে তাকে মুক্ত করে নয়তো তাকে ধ্বংস করে।"',
  'Daripada Abu Malik al-Harith bin ʿAsim al-Asyʿari (semoga Allah meredainya), Rasulullah ﷺ bersabda: "Bersuci ialah separuh iman. ''Alhamdulillah'' (segala puji bagi Allah) memenuhi timbangan. ''Subhanallah wal-hamdulillah'' (Mahasuci Allah dan segala puji bagi Allah) memenuhi ruang antara langit dan bumi. Solat ialah cahaya. Sedekah ialah bukti. Sabar ialah sinar. Al-Qur''an ialah hujah yang membelamu atau memberatkanmu. Setiap manusia berangkat pada waktu pagi lalu menjual dirinya, maka dia membebaskannya atau membinasakannya."',
  'Со слов Абу Малика аль-Хариса ибн Асима аль-Ашари (да будет доволен им Аллах) Посланник Аллаха ﷺ сказал: «Чистота — половина веры. ''Альхамду лиллях'' (хвала Аллаху) наполняет весы. ''Субхана Ллах ва-ль-хамду лиллях'' (пречист Аллах и хвала Аллаху) наполняют — или: наполняет — то, что между небом и землёй. Молитва — свет. Милостыня — доказательство. Терпение — сияние. Коран — довод за тебя или против тебя. Каждый человек выходит поутру и продаёт свою душу, либо освобождая её, либо губя её».',
  -- reference
  'Sahih — reported by Muslim (no. 223), at-Tirmidhi (no. 3517), an-Nasaʾi (5/5-6), Ibn Majah (no. 280), and Ahmad in his Musnad',
  'Hadith authentique rapporté par Muslim (n°223), at-Tirmidhî (n°3517), an-Nasâʾî (5/5-6), Ibn Mâja (n°280) et Ahmad dans son Musnad',
  'حديث صحيح، رواه مسلم (رقم ٢٢٣) والترمذي (رقم ٣٥١٧) والنسائي (٥/٥-٦) وابن ماجه (رقم ٢٨٠) وأحمد في مسنده',
  'Sahih — überliefert von Muslim (Nr. 223), at-Tirmidhi (Nr. 3517), an-Nasaʾi (5/5-6), Ibn Madscha (Nr. 280) und Ahmad in seinem Musnad',
  'Sahih — overgeleverd door Muslim (nr. 223), at-Tirmidhi (nr. 3517), an-Nasaʾi (5/5-6), Ibn Madja (nr. 280) en Ahmad in zijn Musnad',
  'Sahih — Müslim (no. 223), Tirmizî (no. 3517), Nesâî (5/5-6), İbn Mâce (no. 280) ve Ahmed Müsned''inde rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 223), at-Tirmidzi (no. 3517), an-Nasaʾi (5/5-6), Ibnu Majah (no. 280), dan Ahmad dalam Musnad-nya',
  'صحیح حدیث، اسے مسلم (نمبر ۲۲۳)، ترمذی (نمبر ۳۵۱۷)، نسائی (۵/۵-۶)، ابن ماجہ (نمبر ۲۸۰) اور احمد نے اپنی مسند میں روایت کیا',
  'সহীহ হাদীস — মুসলিম (নং ২২৩), তিরমিযী (নং ৩৫১৭), নাসাঈ (৫/৫-৬), ইবনে মাজাহ (নং ২৮০) ও আহমাদ তাঁর মুসনাদে বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 223), at-Tirmizi (no. 3517), an-Nasaʾi (5/5-6), Ibnu Majah (no. 280), dan Ahmad dalam Musnadnya',
  'Достоверный хадис, передали Муслим (№ 223), ат-Тирмизи (№ 3517), ан-Насаи (5/5-6), Ибн Маджа (№ 280) и Ахмад в своём «Муснаде»',
  -- tafsir
  '• An exhortation to purification, showing the place it occupies in the religion.\n• An exhortation to praise of Allah, the Exalted, and to glorifying His transcendence: this fills the scale of good deeds, and these two remembrances together fill what is between the heaven and the earth.\n• An exhortation to prayer: it is a light that opens to a person the door of knowledge and insight.\n• An exhortation to charity: it is a sign that proves the truthfulness of one''s faith.\n• An exhortation to patience: it is a radiance — for from patience results a pain just as from heat results a pain.\n• The Qur''an is either an argument for a person or against him; there is no middle position — it is one or the other. We implore Allah, the Exalted, that it be an argument for us and not against us.\n• Every being must necessarily act; the Prophet ﷺ said: "Every person sets out in the morning," and it is reported that he said: "The most truthful of names are Harith (one who strives/earns) and Hammam (one who resolves/intends)," for every person has a will and an activity.\n• The worker may either free his soul or destroy it. If he acts in obedience to Allah and avoids disobeying Him, he frees his soul and liberates it from enslavement to Iblis. If he does the opposite, he destroys it.\n• True freedom lies in fulfilling the commands of Allah, not in letting the soul do whatever it desires.\n• Every person who turns away from the worship of Allah will inevitably become a slave and worshipper of Iblis.',
  '• Une exhortation à la purification, en montrant la place qu''elle occupe dans la religion.\n• Une exhortation à la louange d''Allah, le Très-Haut, et à la glorification de Sa transcendance : cela remplit la balance des bonnes actions, et ces deux évocations ensemble remplissent l''espace entre le ciel et la terre.\n• Une exhortation à la prière : elle est une lumière qui ouvre à l''homme la porte de la science et de la clairvoyance.\n• Une exhortation à l''aumône : c''est un signe qui prouve la véracité de la foi.\n• Une exhortation à la patience : c''est un flamboiement — de cette patience résulte une douleur, comme de la chaleur résulte une douleur.\n• Le Coran est soit un argument en faveur de l''homme, soit contre lui ; il n''y a pas de position intermédiaire, c''est l''un ou l''autre. Nous implorons Allah, le Très-Haut, qu''il soit un argument en notre faveur et non contre nous.\n• Tout être doit nécessairement œuvrer ; le Prophète ﷺ a dit : « Tout homme part le matin », et il est rapporté qu''il a dit : « Les noms les plus véridiques sont Hârith (celui qui œuvre/gagne) et Hammâm (celui qui projette/aspire) », car tout homme a une volonté et une activité.\n• L''ouvrier peut soit libérer son âme, soit la faire périr. S''il œuvre dans l''obéissance d''Allah et évite de Le désobéir, il affranchit son âme et la libère de l''asservissement à Iblis. S''il fait le contraire, il la fait périr.\n• La vraie liberté réside dans l''accomplissement des ordres d''Allah, non dans le fait de laisser son âme faire ce qu''elle désire.\n• Tout homme qui se détourne de l''adoration d''Allah deviendra nécessairement esclave et adorateur d''Iblis.',
  '• حث على الطهارة، ببيان المنزلة التي تحتلها في الدين.\n• حث على حمد الله تعالى وتسبيحه: فهذا يملأ ميزان الحسنات، وهذان الذكران معاً يملآن ما بين السماء والأرض.\n• حث على الصلاة: فهي نور يفتح للإنسان باب العلم والبصيرة.\n• حث على الصدقة: فهي علامة تدل على صدق الإيمان.\n• حث على الصبر: فهو ضياء — يحصل من الصبر ألم كما يحصل من الحرارة ألم.\n• القرآن إما حجة للإنسان أو عليه؛ لا منزلة بين ذلك، فهو أحدهما. ونسأل الله تعالى أن يكون حجة لنا لا علينا.\n• كل إنسان لا بد أن يعمل؛ قال النبي صلى الله عليه وسلم: «كل الناس يغدو»، وثبت أنه قال: «أصدق الأسماء حارث وهمام»، فإن كل إنسان له إرادة وحركة.\n• العامل إما أن يعتق نفسه أو يوبقها. فإن عمل في طاعة الله واجتنب معصيته، فقد أعتق نفسه وحررها من العبودية لإبليس. وإن فعل العكس فقد أوبقها.\n• الحرية الحقيقية في امتثال أوامر الله تعالى، لا في ترك النفس تفعل ما تشاء.\n• كل من أعرض عن عبادة الله تعالى صار حتماً عبداً لإبليس وعابداً له.',
  '• Eine Ermahnung zur Reinheit, indem ihr Rang in der Religion gezeigt wird.\n• Eine Ermahnung zum Lob Allahs, des Erhabenen, und zum Preisen Seiner Erhabenheit: dies füllt die Waage der guten Taten, und diese beiden Gedenkformeln zusammen füllen das, was zwischen Himmel und Erde ist.\n• Eine Ermahnung zum Gebet: es ist ein Licht, das dem Menschen die Tür des Wissens und der Einsicht öffnet.\n• Eine Ermahnung zur Almosengabe: sie ist ein Zeichen, das die Wahrhaftigkeit des Glaubens beweist.\n• Eine Ermahnung zur Geduld: sie ist ein Leuchten — aus der Geduld entsteht ein Schmerz, wie aus der Hitze ein Schmerz entsteht.\n• Der Qur''an ist entweder ein Beweis für den Menschen oder gegen ihn; es gibt keine Zwischenstellung, es ist das eine oder das andere. Wir flehen Allah, den Erhabenen, an, dass er ein Beweis für uns sei und nicht gegen uns.\n• Jedes Wesen muss notwendigerweise handeln; der Prophet ﷺ sagte: „Jeder Mensch zieht am Morgen aus", und es ist überliefert, dass er sagte: „Die wahrhaftigsten Namen sind Harith (der Erwerbende) und Hammam (der Strebende)", denn jeder Mensch hat einen Willen und eine Tätigkeit.\n• Der Handelnde kann entweder seine Seele befreien oder sie zugrunde richten. Handelt er im Gehorsam gegenüber Allah und meidet den Ungehorsam, so befreit er seine Seele aus der Knechtschaft gegenüber Iblis. Tut er das Gegenteil, so richtet er sie zugrunde.\n• Die wahre Freiheit liegt im Befolgen der Gebote Allahs, nicht darin, die Seele tun zu lassen, was sie begehrt.\n• Jeder Mensch, der sich von der Anbetung Allahs abwendet, wird zwangsläufig ein Sklave und Anbeter von Iblis.',
  '• Een aansporing tot reinheid, door de plaats te tonen die zij in de religie inneemt.\n• Een aansporing tot lof aan Allah, de Verhevene, en tot het verheerlijken van Zijn verhevenheid: dit vult de weegschaal van de goede daden, en deze twee gedenkingen samen vullen wat tussen hemel en aarde is.\n• Een aansporing tot het gebed: het is een licht dat de mens de deur van kennis en inzicht opent.\n• Een aansporing tot de aalmoes: het is een teken dat de waarachtigheid van het geloof bewijst.\n• Een aansporing tot geduld: het is een schittering — uit geduld komt een pijn voort, zoals uit hitte een pijn voortkomt.\n• De Koran is óf een argument vóór de mens óf tegen hem; er is geen tussenpositie, het is het een of het ander. Wij smeken Allah, de Verhevene, dat hij een argument vóór ons is en niet tegen ons.\n• Ieder wezen moet noodzakelijkerwijs handelen; de Profeet ﷺ zei: „Ieder mens trekt in de ochtend uit," en het is overgeleverd dat hij zei: „De meest waarachtige namen zijn Harith (de verwervende) en Hammam (de strevende)," want ieder mens heeft een wil en een activiteit.\n• De handelende kan óf zijn ziel bevrijden óf haar te gronde richten. Handelt hij in gehoorzaamheid aan Allah en mijdt hij de ongehoorzaamheid, dan bevrijdt hij zijn ziel uit de slavernij aan Iblis. Doet hij het tegenovergestelde, dan richt hij haar te gronde.\n• De ware vrijheid ligt in het opvolgen van de geboden van Allah, niet in het de ziel laten doen wat zij begeert.\n• Ieder mens die zich afkeert van de aanbidding van Allah, wordt onvermijdelijk een slaaf en aanbidder van Iblis.',
  '• Temizliğe teşvik; onun dindeki yerini göstererek.\n• Yüce Allah''a hamde ve O''nu tesbihe teşvik: bu, iyilikler mizanını doldurur; bu iki zikir birlikte gökle yer arasını doldurur.\n• Namaza teşvik: o, insana ilim ve basiret kapısını açan bir nurdur.\n• Sadakaya teşvik: o, imanın doğruluğuna delâlet eden bir işarettir.\n• Sabra teşvik: o bir ziyâdır (ışıktır) — sıcaktan bir acı hasıl olduğu gibi, sabırdan da bir acı hasıl olur.\n• Kur''ân ya insanın lehine ya da aleyhine bir delildir; ikisi arasında bir konum yoktur, ya biri ya da öteki. Yüce Allah''tan, onun lehimize olmasını, aleyhimize olmamasını niyaz ederiz.\n• Her varlık mutlaka çalışmak zorundadır; Peygamber ﷺ: „Her insan sabahleyin yola çıkar" buyurmuş ve „En doğru isimler Hâris (kazanan) ve Hemmâm (azmedip niyetlenen)dir" dediği sabit olmuştur; zira her insanın bir iradesi ve faaliyeti vardır.\n• Çalışan ya nefsini azat eder ya da onu helâk eder. Allah''a itaat doğrultusunda çalışıp O''na isyandan kaçınırsa, nefsini İblis''e kullukdan kurtarmış olur. Aksini yaparsa onu helâk eder.\n• Gerçek özgürlük, Allah''ın emirlerine uymakta yatar; nefsi dilediğini yapmaya bırakmakta değil.\n• Allah''a ibadetten yüz çeviren her insan, kaçınılmaz olarak İblis''e kul ve ona ibadet eden biri olur.',
  '• Anjuran untuk bersuci, dengan menunjukkan kedudukannya dalam agama.\n• Anjuran untuk memuji Allah Taʿala dan mensucikan-Nya: hal ini memenuhi timbangan kebaikan, dan kedua zikir ini bersama-sama memenuhi ruang antara langit dan bumi.\n• Anjuran untuk shalat: ia adalah cahaya yang membuka pintu ilmu dan mata hati bagi seseorang.\n• Anjuran untuk bersedekah: ia adalah tanda yang membuktikan kebenaran iman.\n• Anjuran untuk bersabar: ia adalah sinar — dari kesabaran timbul rasa sakit sebagaimana dari panas timbul rasa sakit.\n• Al-Qur''an adakalanya menjadi hujah yang membela seseorang atau memberatkannya; tidak ada kedudukan di antara keduanya, ia salah satunya. Kami memohon kepada Allah Taʿala agar ia menjadi hujah yang membela kami, bukan memberatkan kami.\n• Setiap makhluk pasti harus berbuat; Nabi ﷺ bersabda: "Setiap manusia berangkat di pagi hari," dan telah sahih bahwa beliau bersabda: "Nama yang paling benar adalah Harits (yang berusaha) dan Hammam (yang berkemauan)," karena setiap manusia memiliki kehendak dan aktivitas.\n• Pelaku adakalanya membebaskan dirinya atau membinasakannya. Jika ia berbuat dalam ketaatan kepada Allah dan menjauhi maksiat kepada-Nya, maka ia membebaskan dirinya dari perbudakan kepada Iblis. Jika ia berbuat sebaliknya, maka ia membinasakannya.\n• Kebebasan sejati terletak pada menjalankan perintah Allah, bukan pada membiarkan jiwa berbuat sesukanya.\n• Setiap orang yang berpaling dari ibadah kepada Allah pasti akan menjadi budak dan penyembah Iblis.',
  '• پاکیزگی کی ترغیب، اس کے دین میں مقام کو واضح کر کے۔\n• اللہ تعالیٰ کی حمد اور اس کی تسبیح کی ترغیب: یہ نیکیوں کی میزان کو بھر دیتی ہے، اور یہ دونوں اذکار مل کر آسمان و زمین کے درمیان کی جگہ کو بھر دیتے ہیں۔\n• نماز کی ترغیب: یہ ایک نور ہے جو انسان کے لیے علم اور بصیرت کا دروازہ کھولتا ہے۔\n• صدقے کی ترغیب: یہ ایک علامت ہے جو ایمان کی سچائی پر دلالت کرتی ہے۔\n• صبر کی ترغیب: یہ روشنی ہے — صبر سے ایک تکلیف حاصل ہوتی ہے جیسے گرمی سے تکلیف ہوتی ہے۔\n• قرآن یا تو انسان کے حق میں دلیل ہے یا اس کے خلاف؛ ان دونوں کے درمیان کوئی مقام نہیں، یا یہ یا وہ۔ ہم اللہ تعالیٰ سے دعا کرتے ہیں کہ وہ ہمارے حق میں دلیل ہو، ہمارے خلاف نہ ہو۔\n• ہر انسان کو لازماً عمل کرنا ہے؛ نبی ﷺ نے فرمایا: ”ہر شخص صبح کو نکلتا ہے“، اور ثابت ہے کہ آپ نے فرمایا: ”سب سے سچے نام حارث (کمانے والا) اور ہمام (ارادہ کرنے والا) ہیں“، کیونکہ ہر انسان کے پاس ایک ارادہ اور سرگرمی ہے۔\n• عمل کرنے والا یا تو اپنی جان کو آزاد کرتا ہے یا اسے ہلاک کرتا ہے۔ اگر وہ اللہ کی اطاعت میں عمل کرے اور اس کی نافرمانی سے بچے تو اس نے اپنی جان کو ابلیس کی غلامی سے آزاد کر لیا۔ اگر اس کے برعکس کرے تو اسے ہلاک کر دیا۔\n• حقیقی آزادی اللہ تعالیٰ کے احکام کی تعمیل میں ہے، نہ کہ نفس کو اس کی خواہش پر چھوڑ دینے میں۔\n• ہر وہ شخص جو اللہ تعالیٰ کی عبادت سے منہ موڑے، لازماً ابلیس کا غلام اور عبادت گزار بن جائے گا۔',
  '• পবিত্রতার প্রতি উৎসাহ, দ্বীনে তার মর্যাদা দেখিয়ে।\n• আল্লাহ তাআলার প্রশংসা ও তাঁর তাসবীহের প্রতি উৎসাহ: এটি নেকির মীযান পূর্ণ করে দেয়, আর এই দুই যিকর একসাথে আসমান ও জমিনের মধ্যবর্তী স্থান পূর্ণ করে দেয়।\n• সালাতের প্রতি উৎসাহ: এটি একটি নূর যা মানুষের জন্য জ্ঞান ও অন্তর্দৃষ্টির দরজা খুলে দেয়।\n• সদকার প্রতি উৎসাহ: এটি একটি নিদর্শন যা ঈমানের সত্যতা প্রমাণ করে।\n• ধৈর্যের প্রতি উৎসাহ: এটি জ্যোতি — ধৈর্য থেকে কষ্ট হয় যেমন তাপ থেকে কষ্ট হয়।\n• কুরআন হয় মানুষের পক্ষে দলিল নয়তো তার বিপক্ষে; এ দুইয়ের মাঝে কোনো অবস্থান নেই, হয় এটি নয়তো ওটি। আমরা আল্লাহ তাআলার কাছে দোয়া করি যেন তা আমাদের পক্ষে দলিল হয়, বিপক্ষে নয়।\n• প্রত্যেক সত্তাকে অবশ্যই আমল করতে হয়; নবী ﷺ বলেছেন: "প্রত্যেক মানুষ সকালে বের হয়", এবং সাব্যস্ত আছে যে তিনি বলেছেন: "সবচেয়ে সত্য নাম হলো হারিস (উপার্জনকারী) ও হাম্মাম (সংকল্পকারী)", কারণ প্রত্যেক মানুষের একটি ইচ্ছা ও কর্মতৎপরতা রয়েছে।\n• কর্মী হয় তার আত্মাকে মুক্ত করে নয়তো ধ্বংস করে। সে যদি আল্লাহর আনুগত্যে আমল করে ও তাঁর অবাধ্যতা এড়িয়ে চলে, তবে সে তার আত্মাকে ইবলিসের দাসত্ব থেকে মুক্ত করল। বিপরীত করলে তা ধ্বংস করল।\n• প্রকৃত স্বাধীনতা আল্লাহ তাআলার আদেশ পালনে, নফসকে তার ইচ্ছামতো ছেড়ে দেওয়ায় নয়।\n• যে ব্যক্তি আল্লাহ তাআলার ইবাদত থেকে মুখ ফিরিয়ে নেয়, সে অবশ্যম্ভাবীরূপে ইবলিসের দাস ও উপাসক হয়ে যাবে।',
  '• Galakan untuk bersuci, dengan menunjukkan kedudukannya dalam agama.\n• Galakan untuk memuji Allah Taʿala dan mensucikan-Nya: hal ini memenuhi timbangan kebaikan, dan kedua-dua zikir ini bersama-sama memenuhi ruang antara langit dan bumi.\n• Galakan untuk solat: ia adalah cahaya yang membuka pintu ilmu dan mata hati bagi seseorang.\n• Galakan untuk bersedekah: ia adalah tanda yang membuktikan kebenaran iman.\n• Galakan untuk bersabar: ia adalah sinar — daripada kesabaran timbul rasa sakit sebagaimana daripada panas timbul rasa sakit.\n• Al-Qur''an adakalanya menjadi hujah yang membela seseorang atau memberatkannya; tiada kedudukan antara keduanya, ia salah satunya. Kami memohon kepada Allah Taʿala agar ia menjadi hujah yang membela kami, bukan memberatkan kami.\n• Setiap makhluk pasti harus berbuat; Nabi ﷺ bersabda: "Setiap manusia berangkat pada waktu pagi," dan telah sahih bahawa baginda bersabda: "Nama yang paling benar ialah Harith (yang berusaha) dan Hammam (yang berkemauan)," kerana setiap manusia mempunyai kehendak dan aktiviti.\n• Pelaku adakalanya membebaskan dirinya atau membinasakannya. Jika dia berbuat dalam ketaatan kepada Allah dan menjauhi maksiat kepada-Nya, maka dia membebaskan dirinya daripada perhambaan kepada Iblis. Jika dia berbuat sebaliknya, maka dia membinasakannya.\n• Kebebasan sejati terletak pada melaksanakan perintah Allah, bukan pada membiarkan jiwa berbuat sesuka hatinya.\n• Setiap orang yang berpaling daripada ibadah kepada Allah pasti akan menjadi hamba dan penyembah Iblis.',
  '• Побуждение к чистоте, с указанием на место, которое она занимает в религии.\n• Побуждение к восхвалению Аллаха Всевышнего и прославлению Его пречистости: это наполняет весы благих дел, а эти два поминания вместе наполняют то, что между небом и землёй.\n• Побуждение к молитве: она — свет, открывающий человеку дверь знания и проницательности.\n• Побуждение к милостыне: она — знак, доказывающий истинность веры.\n• Побуждение к терпению: оно — сияние; от терпения возникает боль, как от жара возникает боль.\n• Коран — либо довод за человека, либо против него; нет промежуточного положения, либо одно, либо другое. Мы молим Аллаха Всевышнего, чтобы он был доводом за нас, а не против нас.\n• Каждое существо неизбежно должно действовать; Пророк ﷺ сказал: «Каждый человек выходит поутру», и достоверно, что он сказал: «Самые правдивые имена — Харис (трудящийся, добывающий) и Хаммам (стремящийся, намеревающийся)», ибо у каждого человека есть воля и деятельность.\n• Действующий либо освобождает свою душу, либо губит её. Если он действует в повиновении Аллаху и избегает ослушания Его, то освобождает свою душу от порабощения Иблису. Если поступает наоборот — губит её.\n• Истинная свобода — в исполнении повелений Аллаха, а не в том, чтобы позволять душе делать что она пожелает.\n• Всякий, кто отворачивается от поклонения Аллаху, неизбежно становится рабом и поклоняющимся Иблису.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-23-Nawawi-Psalmodie-Arabe.mp3',
  5,
  23
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 23
);
