-- =============================================================================
-- 40 Hadith Nawawi — Hadith 8: "The sanctity of the Muslim"
-- Target collection: public.hadith_collections.id = 2  /  position = 8
-- Idempotent guard on (collection, position). All 11 content languages.
-- Arabic source cleaned: أَمْوَ الَهُمْ -> أَمْوَالَهُمْ.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'The sanctity of the Muslim',
  'Le caractère sacré du musulman',
  'حرمة المسلم',
  'Die Unverletzlichkeit des Muslims',
  'De onschendbaarheid van de moslim',
  'Müslümanın dokunulmazlığı',
  'Kehormatan seorang muslim',
  'مسلمان کی حرمت',
  'মুসলিমের মর্যাদা',
  'Kehormatan seorang Muslim',
  'Неприкосновенность мусульманина',
  -- arabic_text (cleaned)
  'عَنِ ابْنِ عُمَرَ رَضِيَ اللَّهُ عَنْهُمَا أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ: «أُمِرْتُ أَنْ أُقَاتِلَ النَّاسَ حَتَّى يَشْهَدُوا أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَيُقِيمُوا الصَّلَاةَ، وَيُؤْتُوا الزَّكَاةَ، فَإِذَا فَعَلُوا ذَلِكَ عَصَمُوا مِنِّي دِمَاءَهُمْ وَأَمْوَالَهُمْ إِلَّا بِحَقِّ الْإِسْلَامِ، وَحِسَابُهُمْ عَلَى اللَّهِ تَعَالَى»',
  -- transcription
  'ʿani bni ʿUmara raḍiya Llāhu ʿanhumā anna Rasūla Llāhi ṣalla Llāhu ʿalayhi wa-sallama qāla: umirtu an uqātila n-nāsa ḥattā yashhadū an lā ilāha illa Llāhu wa-anna Muḥammadan Rasūlu Llāhi, wa-yuqīmū ṣ-ṣalāta, wa-yuʾtu z-zakāta, fa-idhā faʿalū dhālika ʿaṣamū minnī dimāʾahum wa-amwālahum illā bi-ḥaqqi l-islāmi, wa-ḥisābuhum ʿalā Llāhi taʿālā.',
  'ʿani bni ʿOumar (radia Llâhou ʿanhoumâ) anna Rassôla Llâhi (salla Llâhou ʿalayhi wa sallam) qâla : oumirtou an ouqâtila n-nâsa hattâ yachhadô an lâ ilâha illa Llâhou wa anna Mouhammadan Rassôlou Llâhi, wa youqîmô s-salât, wa youʾtô z-zakât, fa-idhâ faʿalô dhâlika ʿasamô minnî dimâʾahoum wa amwâlahoum illâ bi-haqqi l-islâmi, wa hisâbouhoum ʿalâ Llâhi taʿâlâ.',
  'ʿani bni ʿUmar (radiya Llāhu ʿanhumā) anna Rasūla Llāhi (salla Llāhu ʿalaihi wa-sallam) qāla: umirtu an uqātila n-nāsa hattā jaschhadū an lā ilāha illa Llāhu wa-anna Muhammadan Rasūlu Llāhi, wa-juqīmū s-salāta, wa-juʾtu z-zakāta, fa-idhā faʿalū dhālika ʿasamū minnī dimāʾahum wa-amwālahum illā bi-haqqi l-islāmi, wa-hisābuhum ʿalā Llāhi taʿālā.',
  'ʿani bni ʿOemar (radia Llaahoe ʿanhoemaa) anna Rasoela Llaahi (salla Llaahoe ʿalaihi wa-sallam) qaala: oemirtoe an oeqaatila n-naasa hattaa jasjhadoe an laa ilaaha illa Llaahoe wa-anna Moehammadan Rasoeloe Llaahi, wa-joeqiemoe s-salaata, wa-joeʾtoe z-zakaata, fa-idhaa faʿaloe dhaalika ʿasamoe minnie dimaaʾahoem wa-amwaalahoem illaa bi-haqqi l-islaami, wa-hisaaboehoem ʿalaa Llaahi taʿaalaa.',
  'an İbn Ömer''den (radıyallâhu anhümâ) rivayetle Resûlullah (s.a.v.) şöyle buyurdu: umirtu en ukâtile''n-nâse hattâ yeşhedû en lâ ilâhe illa''llâhu ve enne Muhammeden Resûlu''llâhi, ve yukîmu''s-salâte, ve yuʾtu''z-zekâte, fe-izâ feʿalû zâlike ʿasamû minnî dimâehum ve emvâlehum illâ bi-hakkı''l-islâmi, ve hisâbuhum ʿala''llâhi teʿâlâ.',
  'ʿanibni ʿUmar (radhiyallāhu ʿanhumā) bahwa Rasulullah (shallallāhu ʿalaihi wa sallam) bersabda: umirtu an uqātilan-nāsa hattā yasyhadū an lā ilāha illallāhu wa anna Muhammadan Rasūlullāhi, wa yuqīmush-shalāta, wa yuʾtuz-zakāta, fa-idzā faʿalū dzālika ʿashamū minnī dimāʾahum wa amwālahum illā bi-haqqil-islāmi, wa hisābuhum ʿalallāhi taʿālā.',
  'ابن عمر رضی اللہ عنہما سے روایت ہے کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: اُمِرتُ اَن اُقاتِلَ النّاسَ حَتّٰی یَشہَدُوا اَن لا اِلٰہَ اِلَّا اللہُ وَاَنَّ مُحَمَّدًا رَسُولُ اللہِ، وَیُقِیمُوا الصَّلاۃَ، وَیُؤتُوا الزَّکاۃَ، فَاِذا فَعَلُوا ذٰلِکَ عَصَمُوا مِنِّی دِماءَہُم وَاَموالَہُم اِلَّا بِحَقِّ الاِسلامِ، وَحِسابُہُم عَلَی اللہِ تَعالٰی۔',
  'ইবনে উমার (রাদিয়াল্লাহু আনহুমা) থেকে বর্ণিত, রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) বলেছেন: উমিরতু আন উকাতিলান নাসা হাত্তা ইয়াশহাদূ আন লা ইলাহা ইল্লাল্লাহু ওয়া আন্না মুহাম্মাদান রাসূলুল্লাহি, ওয়া ইউকীমুস সালাতা, ওয়া ইউতুজ যাকাতা, ফাইযা ফাআলূ যালিকা আসামূ মিন্নী দিমাআহুম ওয়া আমওয়ালাহুম ইল্লা বিহাক্কিল ইসলামি, ওয়া হিসাবুহুম আলাল্লাহি তাআলা।',
  'ʿanibni ʿUmar (radhiallāhu ʿanhumā) bahawa Rasulullah (sallallāhu ʿalaihi wa sallam) bersabda: umirtu an uqātilan-nāsa hattā yasyhadū an lā ilāha illallāhu wa anna Muhammadan Rasūlullāhi, wa yuqīmus-solāta, wa yuʾtuz-zakāta, fa-idzā faʿalū dzālika ʿasamū minnī dimāʾahum wa amwālahum illā bi-haqqil-islāmi, wa hisābuhum ʿalallāhi taʿālā.',
  'Ани бни Умар (да будет доволен Аллах ими обоими), что Посланник Аллаха ﷺ сказал: умирту ан укатилан-наса хатта яшхаду ан ля иляха илля Ллах ва анна Мухаммадан Расулу Ллах, ва юкиму с-салят, ва юʾту з-закят, фа-иза фаалю залика асаму минни димаахум ва амвалахум илля би-хакки ль-ислям, ва хисабухум аля Ллахи таʿаля.',
  -- translation
  'On the authority of Ibn ʿUmar (may Allah be pleased with them both), the Messenger of Allah ﷺ said: "I have been commanded to fight the people until they testify that there is no god but Allah and that Muhammad is the Messenger of Allah, and they establish the prayer and give the zakat. If they do that, they will have protected from me their lives and their wealth, except by the right of Islam, and their reckoning is with Allah, the Exalted."',
  'D''après Ibn ʿUmar (qu''Allah soit satisfait de lui et de son père), l''Envoyé d''Allah ﷺ a dit : « Il m''a été ordonné de combattre les gens jusqu''à ce qu''ils témoignent qu''il n''est d''autre divinité qu''Allah et que Muhammad est Son Envoyé, qu''ils accomplissent la prière et acquittent la zakât. S''ils font cela, ils auront préservé de moi leurs personnes et leurs biens, sauf en vertu du droit de l''Islam, et leur jugement incombe à Allah, le Très-Haut. »',
  'Nach Ibn ʿUmar (möge Allah mit beiden zufrieden sein) sagte der Gesandte Allahs ﷺ: „Mir wurde befohlen, die Menschen zu bekämpfen, bis sie bezeugen, dass es keinen Gott außer Allah gibt und dass Muhammad der Gesandte Allahs ist, und sie das Gebet verrichten und die Zakat entrichten. Tun sie das, so haben sie ihr Blut und ihr Vermögen vor mir geschützt, außer durch das Recht des Islam, und ihre Abrechnung obliegt Allah, dem Erhabenen."',
  'Op gezag van Ibn ʿUmar (moge Allah tevreden met hen beiden zijn) zei de Boodschapper van Allah ﷺ: „Mij is bevolen de mensen te bestrijden totdat zij getuigen dat er geen god is behalve Allah en dat Muhammad de Boodschapper van Allah is, en zij het gebed verrichten en de zakat geven. Doen zij dat, dan hebben zij hun bloed en hun bezit voor mij beschermd, behalve door het recht van de islam, en hun afrekening berust bij Allah, de Verhevene."',
  'İbn Ömer''den (Allah her ikisinden de razı olsun) rivayet edildiğine göre Resûlullah ﷺ şöyle buyurdu: „Bana, insanlarla, Allah''tan başka ilâh olmadığına ve Muhammed''in Allah''ın Resûlü olduğuna şehâdet edinceye, namazı kılıncaya ve zekâtı verinceye kadar savaşmam emrolundu. Bunu yaptıkları takdirde, İslâm''ın hakkı dışında, kanlarını ve mallarını benden korumuş olurlar; hesapları ise Yüce Allah''a aittir."',
  'Dari Ibnu Umar (semoga Allah meridhai keduanya), Rasulullah ﷺ bersabda: "Aku diperintahkan untuk memerangi manusia hingga mereka bersaksi bahwa tidak ada tuhan yang berhak disembah selain Allah dan bahwa Muhammad adalah utusan Allah, mendirikan shalat, dan menunaikan zakat. Apabila mereka melakukan itu, maka mereka telah melindungi darah dan harta mereka dariku, kecuali dengan hak Islam, dan perhitungan mereka ada pada Allah Taʿala."',
  'ابن عمر رضی اللہ عنہما سے روایت ہے کہ رسول اللہ ﷺ نے فرمایا: ”مجھے حکم دیا گیا ہے کہ میں لوگوں سے اس وقت تک قتال کروں جب تک وہ گواہی نہ دیں کہ اللہ کے سوا کوئی معبود نہیں اور محمد اللہ کے رسول ہیں، اور نماز قائم کریں اور زکوٰۃ ادا کریں۔ پس جب وہ ایسا کر لیں تو انہوں نے اسلام کے حق کے سوا اپنے خون اور اپنے مال مجھ سے محفوظ کر لیے، اور ان کا حساب اللہ تعالیٰ پر ہے۔“',
  'ইবনে উমার (রাদিয়াল্লাহু আনহুমা) থেকে বর্ণিত, রাসূলুল্লাহ ﷺ বলেছেন: "আমাকে আদেশ দেওয়া হয়েছে যে আমি মানুষের সাথে ততক্ষণ লড়াই করব যতক্ষণ না তারা সাক্ষ্য দেয় যে আল্লাহ ছাড়া কোনো ইলাহ নেই এবং মুহাম্মাদ আল্লাহর রাসূল, এবং সালাত কায়েম করে ও যাকাত প্রদান করে। অতঃপর তারা যদি তা করে, তবে তারা ইসলামের অধিকার ব্যতীত তাদের রক্ত ও সম্পদ আমার থেকে রক্ষা করল, আর তাদের হিসাব আল্লাহ তাআলার নিকট।"',
  'Daripada Ibnu Umar (semoga Allah meredai keduanya), Rasulullah ﷺ bersabda: "Aku diperintahkan untuk memerangi manusia sehingga mereka bersaksi bahawa tiada tuhan yang berhak disembah melainkan Allah dan bahawa Muhammad ialah utusan Allah, mendirikan solat, dan menunaikan zakat. Apabila mereka melakukan itu, maka mereka telah memelihara darah dan harta mereka daripadaku, kecuali dengan hak Islam, dan perhitungan mereka terserah kepada Allah Taʿala."',
  'Со слов Ибн ʿУмара (да будет доволен Аллах ими обоими) Посланник Аллаха ﷺ сказал: «Мне велено сражаться с людьми, пока они не засвидетельствуют, что нет божества, кроме Аллаха, и что Мухаммад — Посланник Аллаха, не станут совершать молитву и давать закят. Если они сделают это, то защитят от меня свою кровь и своё имущество, кроме как по праву ислама, а их расчёт — у Аллаха Всевышнего».',
  -- reference
  'Sahih — reported by Al-Bukhari and Muslim',
  'Hadith authentique rapporté par Al-Bukhari et Muslim',
  'حديث صحيح، رواه البخاري ومسلم',
  'Sahih — überliefert von Al-Bukhari und Muslim',
  'Sahih — overgeleverd door Al-Bukhari en Muslim',
  'Sahih — Buhârî ve Müslim rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari dan Muslim',
  'صحیح حدیث، اسے بخاری اور مسلم نے روایت کیا',
  'সহীহ হাদীস — বুখারী ও মুসলিম বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari dan Muslim',
  'Достоверный хадис, передали аль-Бухари и Муслим',
  -- tafsir
  '"I have been commanded": it is Allah, the Mighty and Majestic, who commanded. The phrasing is in the passive because the subject is known: the One who commands and forbids is evidently Allah, the Exalted. "…to fight the people until they testify…": this hadith has a general meaning, but the following divine word restricts it: {Fight those who do not believe in Allah nor in the Last Day, who do not forbid what Allah and His Messenger have forbidden, and who do not follow the religion of truth among those who were given the Book, until they pay the jizya willingly while in a state of submission.} Likewise, the Sunnah underscores that people are to be fought until they embrace Islam or pay the jizya.',
  '« Il m''a été ordonné » : c''est Allah, le Puissant, le Majestueux, qui a ordonné. La phrase est à la forme passive car le sujet est connu : Celui qui ordonne et interdit est évidemment Allah, le Très-Haut. « … de combattre les gens jusqu''à ce qu''ils témoignent… » : ce hadith a un sens général, mais la parole divine suivante en constitue la restriction : { Combattez ceux qui ne croient pas en Allah ni au Jour dernier, qui n''interdisent pas ce qu''Allah et Son Messager ont interdit, et qui, parmi ceux qui ont reçu le Livre, ne suivent pas la religion du Vrai, jusqu''à ce qu''ils versent la capitation (jizya) de leur propre main, en signe de soumission. } De même, la Tradition souligne que les gens doivent être combattus jusqu''à ce qu''ils embrassent l''Islam ou paient la capitation.',
  '«أُمِرْتُ» أي أمرني الله عز وجل. وجاءت الجملة مبنية للمجهول لأن الفاعل معلوم: فالذي يأمر وينهى هو الله تعالى بلا شك. «أن أقاتل الناس حتى يشهدوا» هذا الحديث عام، لكن قوله تعالى مقيّد له: {قَاتِلُوا الَّذِينَ لَا يُؤْمِنُونَ بِاللَّهِ وَلَا بِالْيَوْمِ الْآخِرِ وَلَا يُحَرِّمُونَ مَا حَرَّمَ اللَّهُ وَرَسُولُهُ وَلَا يَدِينُونَ دِينَ الْحَقِّ مِنَ الَّذِينَ أُوتُوا الْكِتَابَ حَتَّى يُعْطُوا الْجِزْيَةَ عَنْ يَدٍ وَهُمْ صَاغِرُونَ}. وكذلك تؤكد السنة أن الناس يُقاتَلون حتى يدخلوا في الإسلام أو يدفعوا الجزية.',
  '„Mir wurde befohlen": Es ist Allah, der Mächtige und Majestätische, der befohlen hat. Der Satz steht im Passiv, weil das Subjekt bekannt ist: Derjenige, der gebietet und verbietet, ist offensichtlich Allah, der Erhabene. „…die Menschen zu bekämpfen, bis sie bezeugen…": Dieser Hadith hat eine allgemeine Bedeutung, doch das folgende göttliche Wort schränkt ihn ein: {Bekämpft diejenigen, die nicht an Allah und nicht an den Jüngsten Tag glauben, die nicht verbieten, was Allah und Sein Gesandter verboten haben, und die nicht der wahren Religion angehören — von denen, denen die Schrift gegeben wurde — bis sie eigenhändig den Tribut (Dschizya) entrichten und sich unterwerfen.} Ebenso betont die Sunna, dass die Menschen bekämpft werden, bis sie den Islam annehmen oder die Dschizya zahlen.',
  '„Mij is bevolen": het is Allah, de Machtige en Majesteitelijke, die heeft bevolen. De zin staat in de lijdende vorm omdat het onderwerp bekend is: Degene die gebiedt en verbiedt is uiteraard Allah, de Verhevene. „…de mensen te bestrijden totdat zij getuigen…": deze hadith heeft een algemene betekenis, maar het volgende goddelijke woord beperkt hem: {Bestrijd hen die niet in Allah en niet in de Laatste Dag geloven, die niet verbieden wat Allah en Zijn Boodschapper hebben verboden, en die niet de ware religie aanhangen — onder hen aan wie het Boek is gegeven — totdat zij eigenhandig de schatting (jizya) betalen, in een staat van onderwerping.} Eveneens benadrukt de Soenna dat de mensen bestreden worden totdat zij de islam aannemen of de jizya betalen.',
  '„Bana emrolundu": yani bana Azîz ve Celîl olan Allah emretti. Cümle, fâili bilindiği için meçhul (edilgen) gelmiştir: emreden ve yasaklayan, şüphesiz Yüce Allah''tır. „İnsanlarla, şehâdet edinceye kadar savaşmam…": bu hadis geneldir, ancak şu âyet onu kayıtlar: {Kendilerine Kitap verilenlerden Allah''a ve âhiret gününe iman etmeyen, Allah''ın ve Resûlü''nün haram kıldığını haram saymayan ve hak dini din edinmeyenlerle, küçük düşerek kendi elleriyle cizye verinceye kadar savaşın.} Aynı şekilde Sünnet, insanların İslâm''a girinceye veya cizye verinceye kadar kendileriyle savaşılacağını vurgular.',
  '"Aku diperintahkan": yakni Allah Yang Maha Perkasa lagi Maha Agung yang memerintahkan. Kalimat ini dibuat dalam bentuk pasif karena pelakunya telah diketahui: yang memerintah dan melarang tidak diragukan lagi adalah Allah Taʿala. "…untuk memerangi manusia hingga mereka bersaksi…": hadis ini bermakna umum, tetapi firman Allah berikut ini menjadi pembatasnya: {Perangilah orang-orang yang tidak beriman kepada Allah dan tidak pula kepada hari akhir, tidak mengharamkan apa yang diharamkan Allah dan Rasul-Nya, dan tidak beragama dengan agama yang benar (Islam), yaitu di antara orang-orang yang diberi Al-Kitab, hingga mereka membayar jizyah dengan patuh sedang mereka dalam keadaan tunduk.} Demikian pula Sunnah menegaskan bahwa manusia diperangi hingga mereka masuk Islam atau membayar jizyah.',
  '”مجھے حکم دیا گیا“: یعنی اللہ عز و جل نے حکم دیا۔ جملہ مجہول کے صیغے میں آیا کیونکہ فاعل معلوم ہے: حکم دینے اور منع کرنے والا بلا شبہ اللہ تعالیٰ ہی ہے۔ ”لوگوں سے قتال کروں یہاں تک کہ وہ گواہی دیں“: یہ حدیث عام ہے، لیکن اللہ تعالیٰ کا یہ فرمان اسے مقید کرتا ہے: {اہلِ کتاب میں سے ان لوگوں سے قتال کرو جو نہ اللہ پر ایمان رکھتے ہیں نہ یومِ آخرت پر، اور نہ اس چیز کو حرام سمجھتے ہیں جسے اللہ اور اس کے رسول نے حرام کیا، اور نہ دینِ حق کو اپناتے ہیں، یہاں تک کہ وہ ذلیل ہو کر اپنے ہاتھ سے جزیہ دیں۔} اسی طرح سنت اس بات کی تاکید کرتی ہے کہ لوگوں سے اس وقت تک قتال کیا جائے گا جب تک وہ اسلام میں داخل نہ ہو جائیں یا جزیہ ادا نہ کر دیں۔',
  '"আমাকে আদেশ দেওয়া হয়েছে": অর্থাৎ মহাপরাক্রমশালী আল্লাহ আদেশ দিয়েছেন। বাক্যটি কর্মবাচ্যে এসেছে কারণ কর্তা জানা: যিনি আদেশ ও নিষেধ করেন তিনি নিঃসন্দেহে আল্লাহ তাআলা। "…মানুষের সাথে লড়াই করব যতক্ষণ না তারা সাক্ষ্য দেয়…": এই হাদীসটি ব্যাপক অর্থবোধক, কিন্তু আল্লাহর নিম্নোক্ত বাণী এটিকে সীমাবদ্ধ করে: {যারা আল্লাহ ও শেষ দিবসে বিশ্বাস করে না, আল্লাহ ও তাঁর রাসূল যা হারাম করেছেন তা হারাম গণ্য করে না এবং সত্য দ্বীন গ্রহণ করে না — কিতাবপ্রাপ্তদের মধ্য থেকে — তাদের সাথে লড়াই করো যতক্ষণ না তারা বশীভূত হয়ে নিজ হাতে জিযিয়া প্রদান করে।} অনুরূপভাবে সুন্নাহ এ কথা জোর দেয় যে মানুষের সাথে ততক্ষণ লড়াই করা হবে যতক্ষণ না তারা ইসলামে প্রবেশ করে বা জিযিয়া প্রদান করে।',
  '"Aku diperintahkan": iaitu Allah Yang Maha Perkasa lagi Maha Agung yang memerintahkan. Ayat ini dibentuk dalam bentuk pasif kerana pelakunya telah diketahui: yang memerintah dan melarang tidak syak lagi ialah Allah Taʿala. "…untuk memerangi manusia sehingga mereka bersaksi…": hadis ini bermakna umum, tetapi firman Allah berikut ini menjadi pembatasnya: {Perangilah orang-orang yang tidak beriman kepada Allah dan tidak pula kepada hari akhir, tidak mengharamkan apa yang diharamkan Allah dan Rasul-Nya, dan tidak beragama dengan agama yang benar (Islam), iaitu dalam kalangan orang-orang yang diberi Kitab, sehingga mereka membayar jizyah dengan patuh sedang mereka dalam keadaan tunduk.} Demikian juga Sunnah menegaskan bahawa manusia diperangi sehingga mereka masuk Islam atau membayar jizyah.',
  '«Мне велено»: повелел Аллах, Могущественный и Великий. Фраза стоит в страдательном залоге, потому что действующее лицо известно: Тот, Кто повелевает и запрещает, — несомненно, Аллах Всевышний. «…сражаться с людьми, пока они не засвидетельствуют…»: этот хадис имеет общий смысл, но последующее слово Аллаха ограничивает его: {Сражайтесь с теми из людей Писания, которые не веруют ни в Аллаха, ни в Последний день, которые не считают запретным то, что запретили Аллах и Его Посланник, и которые не исповедуют истинную религию, пока они не станут собственноручно платить дань (джизью), будучи униженными.} Точно так же Сунна подчёркивает, что с людьми сражаются, пока они не примут ислам или не уплатят джизью.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-8-Nawawi-Psalmodie-Arabe.mp3',
  5,
  8
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 8
);
