-- =============================================================================
-- 40 Hadith Nawawi — Hadith 14: "The inviolability of the Muslim''s blood"
-- Target collection: public.hadith_collections.id = 2  /  position = 14
-- Idempotent guard on (collection, position). All 11 content languages.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'The inviolability of the Muslim''s blood',
  'L''inviolabilité du sang d''un musulman',
  'حرمة دم المسلم وأسباب إهداره',
  'Die Unverletzlichkeit des Blutes des Muslims',
  'De onschendbaarheid van het bloed van de moslim',
  'Müslümanın kanının dokunulmazlığı',
  'Kemuliaan darah seorang muslim',
  'مسلمان کے خون کی حرمت',
  'মুসলিমের রক্তের পবিত্রতা',
  'Kemuliaan darah seorang Muslim',
  'Неприкосновенность крови мусульманина',
  -- arabic_text
  'عَنِ ابْنِ مَسْعُودٍ رَضِيَ اللَّهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «لَا يَحِلُّ دَمُ امْرِئٍ مُسْلِمٍ يَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَنِّي رَسُولُ اللَّهِ إِلَّا بِإِحْدَى ثَلَاثٍ: الثَّيِّبُ الزَّانِي، وَالنَّفْسُ بِالنَّفْسِ، وَالتَّارِكُ لِدِينِهِ الْمُفَارِقُ لِلْجَمَاعَةِ»',
  -- transcription
  'ʿani bni Masʿūdin raḍiya Llāhu ʿanhu qāla: qāla Rasūlu Llāhi ṣalla Llāhu ʿalayhi wa-sallama: lā yaḥillu damu mriʾin muslimin yashhadu an lā ilāha illa Llāhu wa-annī Rasūlu Llāhi illā bi-iḥdā thalāthin: ath-thayyibu z-zānī, wa-n-nafsu bi-n-nafsi, wa-t-tāriku li-dīnihi l-mufāriqu li-l-jamāʿati.',
  'ʿani bni Masʿôdin (radia Llâhou ʿanhou) qâla : qâla Rassôlou Llâhi (salla Llâhou ʿalayhi wa sallam) : lâ yahillou damou mriʾin mouslimin yachhadou an lâ ilâha illa Llâhou wa annî Rassôlou Llâhi illâ bi-ihdâ thalâthin : ath-thayyibou z-zânî, wa n-nafsou bi-n-nafsi, wa t-târikou li-dînihi l-moufâriqou li-l-jamâʿati.',
  'ʿani bni Masʿūdin (radiya Llāhu ʿanhu) qāla: qāla Rasūlu Llāhi (salla Llāhu ʿalaihi wa-sallam): lā jahillu damu mriʾin muslimin jaschhadu an lā ilāha illa Llāhu wa-annī Rasūlu Llāhi illā bi-ihdā thalāthin: ath-thajjibu z-zānī, wa-n-nafsu bi-n-nafsi, wa-t-tāriku li-dīnihi l-mufāriqu li-l-dschamāʿati.',
  'ʿani bni Masʿoedin (radia Llaahoe ʿanhoe) qaala: qaala Rasoeloe Llaahi (salla Llaahoe ʿalaihi wa-sallam): laa jahilloe damoe mriʾin moeslimin jasjhadoe an laa ilaaha illa Llaahoe wa-annie Rasoeloe Llaahi illaa bi-ihdaa thalaathin: ath-thajjiboe z-zaanie, wa-n-nafsoe bi-n-nafsi, wa-t-taarikoe li-dienihi l-moefaariqoe li-l-dzjamaaʿati.',
  'an İbn Mesûd''dan (radıyallâhu anh) rivayetle dedi ki: Resûlullah (s.a.v.) şöyle buyurdu: lâ yahillu demu''mriʾin muslimin yeşhedu en lâ ilâhe illa''llâhu ve ennî Resûlu''llâhi illâ bi-ihdâ selâsin: es-seyyibu''z-zânî, ve''n-nefsu bi''n-nefsi, ve''t-târiku li-dînihi''l-mufâriku li''l-cemâʿati.',
  'ʿanibni Masʿud (radhiyallāhu ʿanhu) berkata: Rasulullah (shallallāhu ʿalaihi wa sallam) bersabda: lā yahillu damu mriʾin muslimin yasyhadu an lā ilāha illallāhu wa annī Rasūlullāhi illā bi-ihdā tsalātsin: ats-tsayyibuz-zānī, wan-nafsu bin-nafsi, wat-tāriku li-dīnihil-mufāriqu lil-jamāʿati.',
  'ابن مسعود رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: لا یَحِلُّ دَمُ امرِئٍ مُسلِمٍ یَشہَدُ اَن لا اِلٰہَ اِلَّا اللہُ وَاَنِّی رَسُولُ اللہِ اِلَّا بِاِحدٰی ثَلاثٍ: الثَّیِّبُ الزّانِی، وَالنَّفسُ بِالنَّفسِ، وَالتّارِکُ لِدِینِہِ المُفارِقُ لِلجَماعَۃِ۔',
  'ইবনে মাসউদ (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) বলেছেন: লা ইয়াহিল্লু দামুম রিইম মুসলিমিন ইয়াশহাদু আন লা ইলাহা ইল্লাল্লাহু ওয়া আন্নী রাসূলুল্লাহি ইল্লা বিইহদা সালাসিন: আস-সাইয়িবুজ যানী, ওয়ান নাফসু বিন নাফসি, ওয়াত তারিকু লিদীনিহিল মুফারিকু লিল জামাআতি।',
  'ʿanibni Masʿud (radhiallāhu ʿanhu) berkata: Rasulullah (sallallāhu ʿalaihi wa sallam) bersabda: lā yahillu damu mriʾin muslimin yasyhadu an lā ilāha illallāhu wa annī Rasūlullāhi illā bi-ihdā tsalātsin: ats-tsayyibuz-zānī, wan-nafsu bin-nafsi, wat-tāriku li-dīnihil-mufāriqu lil-jamāʿati.',
  'Ани бни Масуд (да будет доволен им Аллах) сказал: сказал Посланник Аллаха ﷺ: ля яхиллу даму мриʾин муслимин яшхаду ан ля иляха илля Ллах ва анни Расулу Ллах илля би-ихда саляс: ас-саййибу з-зани, ва н-нафсу би-н-нафси, ва т-тарику ли-динихи ль-муфарику ли-ль-джамаа.',
  -- translation
  'On the authority of Ibn Masʿud (may Allah be pleased with him), the Messenger of Allah ﷺ said: "The blood of a Muslim who testifies that there is no god but Allah and that I am the Messenger of Allah is not lawful (to shed) except in one of three cases: the married person who commits adultery, a life for a life, and the one who forsakes his religion and separates from the community."',
  'D''après Ibn Masʿud (qu''Allah l''agrée), l''Envoyé d''Allah ﷺ a dit : « Le sang d''un musulman qui atteste qu''il n''est de divinité qu''Allah et que je suis l''Envoyé d''Allah n''est licite (à verser) que dans l''un de trois cas : la personne mariée qui commet l''adultère, une âme pour une âme (le meurtrier), et celui qui délaisse sa religion en se séparant de la communauté. »',
  'Nach Ibn Masʿud (möge Allah mit ihm zufrieden sein) sagte der Gesandte Allahs ﷺ: „Das Blut eines Muslims, der bezeugt, dass es keinen Gott außer Allah gibt und dass ich der Gesandte Allahs bin, ist (zu vergießen) nur in einem von drei Fällen erlaubt: die verheiratete Person, die Ehebruch begeht; ein Leben für ein Leben (der Mörder); und derjenige, der seine Religion verlässt und sich von der Gemeinschaft trennt."',
  'Op gezag van Ibn Masʿud (moge Allah tevreden met hem zijn) zei de Boodschapper van Allah ﷺ: „Het bloed van een moslim die getuigt dat er geen god is behalve Allah en dat ik de Boodschapper van Allah ben, is (te vergieten) slechts in een van drie gevallen toegestaan: de gehuwde persoon die overspel pleegt; een leven voor een leven (de moordenaar); en degene die zijn religie verlaat en zich van de gemeenschap afscheidt."',
  'İbn Mesûd''dan (Allah ondan razı olsun) rivayet edildiğine göre Resûlullah ﷺ şöyle buyurdu: „Allah''tan başka ilâh olmadığına ve benim Allah''ın Resûlü olduğuma şehâdet eden bir Müslümanın kanı, üç durumdan biri dışında helâl olmaz: zina eden evli kişi, cana karşılık can (kâtil) ve dinini terk edip cemaatten ayrılan kimse."',
  'Dari Ibnu Masʿud (semoga Allah meridhainya), Rasulullah ﷺ bersabda: "Tidak halal darah seorang muslim yang bersaksi bahwa tidak ada tuhan yang berhak disembah selain Allah dan bahwa aku adalah utusan Allah, kecuali karena salah satu dari tiga perkara: orang yang telah menikah lalu berzina, nyawa dibalas dengan nyawa (pembunuh), dan orang yang meninggalkan agamanya seraya memisahkan diri dari jamaah."',
  'ابن مسعود رضی اللہ عنہ سے روایت ہے کہ رسول اللہ ﷺ نے فرمایا: ”ایسے مسلمان کا خون جو گواہی دیتا ہے کہ اللہ کے سوا کوئی معبود نہیں اور میں اللہ کا رسول ہوں، حلال نہیں سوائے تین میں سے کسی ایک صورت کے: شادی شدہ زانی، جان کے بدلے جان (قاتل)، اور وہ شخص جو اپنا دین چھوڑ کر جماعت سے جدا ہو جائے۔“',
  'ইবনে মাসউদ (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, রাসূলুল্লাহ ﷺ বলেছেন: "যে মুসলিম সাক্ষ্য দেয় যে আল্লাহ ছাড়া কোনো ইলাহ নেই এবং আমি আল্লাহর রাসূল, তার রক্ত (প্রবাহিত করা) হালাল নয় তিনটির একটি ব্যতীত: বিবাহিত ব্যভিচারী, প্রাণের বদলে প্রাণ (হত্যাকারী), এবং যে ব্যক্তি নিজের দ্বীন ত্যাগ করে জামাত থেকে বিচ্ছিন্ন হয়।"',
  'Daripada Ibnu Masʿud (semoga Allah meredainya), Rasulullah ﷺ bersabda: "Tidak halal darah seorang Muslim yang bersaksi bahawa tiada tuhan yang berhak disembah melainkan Allah dan bahawa aku ialah utusan Allah, kecuali kerana salah satu daripada tiga perkara: orang yang telah berkahwin lalu berzina, nyawa dibalas dengan nyawa (pembunuh), dan orang yang meninggalkan agamanya seraya memisahkan diri daripada jemaah."',
  'Со слов Ибн Масуда (да будет доволен им Аллах) Посланник Аллаха ﷺ сказал: «Кровь мусульманина, который свидетельствует, что нет божества, кроме Аллаха, и что я — Посланник Аллаха, недозволена (для пролития), кроме как в одном из трёх случаев: женатый (человек), совершивший прелюбодеяние; душа за душу (убийца); и тот, кто оставляет свою религию, отделяясь от общины».',
  -- reference
  'Sahih — reported by Al-Bukhari (12/201, no. 6878) and Muslim (3/1302)',
  'Hadith authentique rapporté par Al-Bukhari (12/201, n°6878) et Muslim (3/1302)',
  'حديث صحيح، رواه البخاري (١٢/٢٠١) (رقم ٦٨٧٨) ومسلم (٣/١٣٠٢)',
  'Sahih — überliefert von Al-Bukhari (12/201, Nr. 6878) und Muslim (3/1302)',
  'Sahih — overgeleverd door Al-Bukhari (12/201, nr. 6878) en Muslim (3/1302)',
  'Sahih — Buhârî (12/201, no. 6878) ve Müslim (3/1302) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (12/201, no. 6878) dan Muslim (3/1302)',
  'صحیح حدیث، اسے بخاری (۱۲/۲۰۱، نمبر ۶۸۷۸) اور مسلم (۳/۱۳۰۲) نے روایت کیا',
  'সহীহ হাদীস — বুখারী (১২/২০১, নং ৬৮৭৮) ও মুসলিম (৩/১৩০২) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (12/201, no. 6878) dan Muslim (3/1302)',
  'Достоверный хадис, передали аль-Бухари (12/201, № 6878) и Муслим (3/1302)',
  -- tafsir
  '1) The Messenger of Allah ﷺ shows by this hadith that the blood of a Muslim must be respected and is inviolable; it is not permitted to shed it except in three cases. "…the married person who commits adultery": this is a person who has consummated a marriage and then commits fornication; by the legal ruling of the scholars his blood becomes lawful and he is liable to the prescribed penalty (hadd) for this offence.\n2) "…a life for a life": the deliberate murderer is liable to legal retribution (qisas), in accordance with the divine words: {O you who believe, retribution is prescribed for you in cases of murder} (2:178), and His words: {We prescribed for them therein: a life for a life} (5:45).\n3) "…the one who forsakes his religion and separates from the community": this refers to the apostate (murtadd). Whoever rejects faith after having embraced Islam, his case is referred to the Islamic authority; if he does not repent, the ruling is applied to him.',
  '1) L''Envoyé d''Allah ﷺ montre par ce hadith que le sang du musulman doit être respecté et qu''il est inviolable ; il n''est permis de le verser que dans trois cas. « … la personne mariée qui commet l''adultère » : c''est celui qui a consommé un mariage puis a commis la fornication ; selon le jugement des savants son sang devient licite et il encourt la peine prescrite (hadd) pour ce délit.\n2) « … une âme pour une âme » : le meurtrier volontaire encourt la loi du talion (qisâs), conformément aux paroles divines : {Ô vous qui croyez, le talion vous est prescrit en cas de meurtre} (2:178), et : {Nous leur avons prescrit : âme pour âme} (5:45).\n3) « … celui qui délaisse sa religion en se séparant de la communauté » : il s''agit de l''apostat (murtadd). Quiconque renie après avoir embrassé l''Islam, son cas est renvoyé à l''autorité ; s''il ne se repent pas, le jugement lui est appliqué.',
  '١) يبيّن رسول الله صلى الله عليه وسلم بهذا الحديث أن دم المسلم محترم معصوم، لا يجوز إراقته إلا في ثلاث. «الثيب الزاني»: وهو الذي تزوج ودخل ثم زنى، فبحكم العلماء يحل دمه ويُقام عليه الحد في هذه الجريمة.\n٢) «النفس بالنفس»: القاتل عمداً تجب عليه القصاص، عملاً بقوله تعالى: {يا أيها الذين آمنوا كُتب عليكم القصاص في القتلى} (٢:١٧٨)، وقوله: {وكتبنا عليهم فيها أن النفس بالنفس} (٥:٤٥).\n٣) «التارك لدينه المفارق للجماعة»: هو المرتد. فمن كفر بعد أن أسلم، يُرفع أمره إلى ولي الأمر؛ فإن لم يتب أُقيم عليه الحكم.',
  '1) Der Gesandte Allahs ﷺ zeigt mit diesem Hadith, dass das Blut des Muslims geachtet und unverletzlich ist; es ist nur in drei Fällen erlaubt, es zu vergießen. „…die verheiratete Person, die Ehebruch begeht": das ist jemand, der eine Ehe vollzogen und dann Unzucht begangen hat; nach dem Urteil der Gelehrten wird sein Blut erlaubt und die vorgeschriebene Strafe (Hadd) für dieses Vergehen an ihm vollzogen.\n2) „…ein Leben für ein Leben": der vorsätzliche Mörder unterliegt der Wiedervergeltung (Qisas), gemäß den göttlichen Worten: {O ihr, die ihr glaubt, die Wiedervergeltung ist euch im Falle von Mord vorgeschrieben} (2:178) und Seinen Worten: {Wir haben ihnen darin vorgeschrieben: ein Leben für ein Leben} (5:45).\n3) „…derjenige, der seine Religion verlässt und sich von der Gemeinschaft trennt": dies bezieht sich auf den Apostaten (Murtadd). Wer den Glauben verleugnet, nachdem er den Islam angenommen hat, dessen Angelegenheit wird der Obrigkeit übergeben; bereut er nicht, so wird das Urteil an ihm vollzogen.',
  '1) De Boodschapper van Allah ﷺ toont met deze hadith aan dat het bloed van de moslim geëerbiedigd en onschendbaar is; het is slechts in drie gevallen toegestaan het te vergieten. „…de gehuwde persoon die overspel pleegt": dit is iemand die een huwelijk heeft voltrokken en daarna ontucht pleegt; volgens het oordeel van de geleerden wordt zijn bloed toegestaan en wordt de voorgeschreven straf (hadd) voor dit vergrijp aan hem voltrokken.\n2) „…een leven voor een leven": de opzettelijke moordenaar is onderworpen aan de vergelding (qisas), overeenkomstig de goddelijke woorden: {O jullie die geloven, de vergelding is jullie voorgeschreven in gevallen van moord} (2:178), en Zijn woorden: {Wij hebben hun daarin voorgeschreven: een leven voor een leven} (5:45).\n3) „…degene die zijn religie verlaat en zich van de gemeenschap afscheidt": dit verwijst naar de afvallige (murtadd). Wie het geloof verloochent nadat hij de islam heeft aangenomen, diens zaak wordt aan het gezag voorgelegd; toont hij geen berouw, dan wordt het oordeel aan hem voltrokken.',
  '1) Resûlullah ﷺ bu hadisle, Müslümanın kanının saygın ve dokunulmaz olduğunu, ancak üç durumda akıtılmasının caiz olduğunu beyan eder. „Zina eden evli kişi": evlenip zifafa girmiş, sonra zina etmiş kimsedir; âlimlerin hükmüne göre kanı helâl olur ve bu suçtan dolayı hakkında had uygulanır.\n2) „Cana karşılık can": kasten adam öldürene kısas gerekir; nitekim Yüce Allah şöyle buyurur: {Ey iman edenler! Öldürülenler hakkında size kısas farz kılındı} (2:178) ve: {Onlara, cana can ile (kısas) yazdık} (5:45).\n3) „Dinini terk edip cemaatten ayrılan": bu, mürteddir (dinden dönen). İslâm''a girdikten sonra inkâr eden kimsenin durumu yetkili makama havale edilir; tövbe etmezse hakkında hüküm uygulanır.',
  '1) Rasulullah ﷺ menjelaskan dengan hadis ini bahwa darah seorang muslim itu terhormat dan terlindungi; tidak boleh ditumpahkan kecuali dalam tiga keadaan. "…orang yang telah menikah lalu berzina": yaitu orang yang telah menikah dan menggauli istrinya kemudian berzina; menurut hukum para ulama darahnya menjadi halal dan ditegakkan atasnya hukuman had atas kejahatan ini.\n2) "…nyawa dibalas dengan nyawa": pembunuh dengan sengaja wajib dikenai qishash, sesuai firman Allah: {Wahai orang-orang yang beriman, diwajibkan atas kamu qishash berkenaan dengan orang-orang yang dibunuh} (2:178), dan firman-Nya: {Dan Kami telah menetapkan bagi mereka di dalamnya bahwa nyawa dibalas dengan nyawa} (5:45).\n3) "…orang yang meninggalkan agamanya seraya memisahkan diri dari jamaah": yaitu orang yang murtad. Barangsiapa kafir setelah masuk Islam, perkaranya diserahkan kepada penguasa (waliyul amri); jika ia tidak bertaubat, hukuman ditegakkan atasnya.',
  '۱) رسول اللہ ﷺ اس حدیث سے یہ بیان فرماتے ہیں کہ مسلمان کا خون محترم اور محفوظ ہے، اسے بہانا صرف تین صورتوں میں جائز ہے۔ ”شادی شدہ زانی“: یہ وہ شخص ہے جس نے نکاح کر کے ہمبستری کی پھر زنا کیا؛ علماء کے حکم کے مطابق اس کا خون حلال ہو جاتا ہے اور اس جرم پر اس پر حد قائم کی جاتی ہے۔\n۲) ”جان کے بدلے جان“: جان بوجھ کر قتل کرنے والے پر قصاص واجب ہے، اللہ تعالیٰ کے اس فرمان کے مطابق: {اے ایمان والو! مقتولوں کے بارے میں تم پر قصاص فرض کیا گیا} (۲:۱۷۸)، اور اس کے فرمان: {اور ہم نے ان پر اس میں لکھ دیا کہ جان کے بدلے جان} (۵:۴۵)۔\n۳) ”اپنا دین چھوڑ کر جماعت سے جدا ہونے والا“: یہ مرتد ہے۔ جو اسلام لانے کے بعد کفر کرے، اس کا معاملہ ولیِ امر کے سپرد کیا جاتا ہے؛ اگر وہ توبہ نہ کرے تو اس پر حکم نافذ کیا جاتا ہے۔',
  '১) রাসূলুল্লাহ ﷺ এই হাদীস দ্বারা দেখান যে মুসলিমের রক্ত সম্মানিত ও সুরক্ষিত; তা প্রবাহিত করা কেবল তিনটি ক্ষেত্রে জায়েজ। "…বিবাহিত ব্যভিচারী": এটি এমন ব্যক্তি যে বিবাহ করে স্ত্রীসহবাস করেছে অতঃপর ব্যভিচার করেছে; আলেমগণের বিধান অনুযায়ী তার রক্ত হালাল হয় এবং এই অপরাধে তার ওপর হদ প্রতিষ্ঠিত হয়।\n২) "…প্রাণের বদলে প্রাণ": ইচ্ছাকৃত হত্যাকারীর ওপর কিসাস ওয়াজিব, আল্লাহর এই বাণী অনুযায়ী: {হে ঈমানদারগণ! নিহতদের ব্যাপারে তোমাদের ওপর কিসাস ফরজ করা হয়েছে} (২:১৭৮), এবং তাঁর বাণী: {আর আমি তাতে তাদের জন্য বিধান দিয়েছি যে প্রাণের বদলে প্রাণ} (৫:৪৫)।\n৩) "…যে নিজের দ্বীন ত্যাগ করে জামাত থেকে বিচ্ছিন্ন হয়": এটি মুরতাদ (ধর্মত্যাগী)। যে ইসলাম গ্রহণের পর কুফরি করে, তার বিষয় কর্তৃপক্ষের নিকট সোপর্দ করা হয়; যদি সে তওবা না করে তবে তার ওপর বিধান কার্যকর করা হয়।',
  '1) Rasulullah ﷺ menjelaskan dengan hadis ini bahawa darah seorang Muslim itu terhormat dan terpelihara; tidak boleh ditumpahkan kecuali dalam tiga keadaan. "…orang yang telah berkahwin lalu berzina": iaitu orang yang telah berkahwin dan menggauli isterinya kemudian berzina; menurut hukum para ulama darahnya menjadi halal dan ditegakkan ke atasnya hukuman had atas jenayah ini.\n2) "…nyawa dibalas dengan nyawa": pembunuh dengan sengaja wajib dikenakan qisas, sesuai firman Allah: {Wahai orang-orang yang beriman, diwajibkan ke atas kamu qisas berkenaan orang-orang yang dibunuh} (2:178), dan firman-Nya: {Dan Kami telah menetapkan bagi mereka di dalamnya bahawa nyawa dibalas dengan nyawa} (5:45).\n3) "…orang yang meninggalkan agamanya seraya memisahkan diri daripada jemaah": iaitu orang yang murtad. Sesiapa yang kufur selepas memeluk Islam, perkaranya diserahkan kepada pemerintah (waliyul amri); jika dia tidak bertaubat, hukuman ditegakkan ke atasnya.',
  '1) Посланник Аллаха ﷺ показывает этим хадисом, что кровь мусульманина уважаема и неприкосновенна; проливать её дозволено лишь в трёх случаях. «…женатый, совершивший прелюбодеяние»: это тот, кто вступил в брак и затем совершил прелюбодеяние; по решению учёных его кровь становится дозволенной, и за это преступление к нему применяется предписанное наказание (хадд).\n2) «…душа за душу»: умышленному убийце полагается возмездие (кисас), согласно словам Аллаха: {О те, которые уверовали! Предписано вам возмездие за убитых} (2:178) и Его словам: {Мы предписали им в нём: душа за душу} (5:45).\n3) «…тот, кто оставляет свою религию, отделяясь от общины»: это вероотступник (муртадд). Дело того, кто отрёкся после принятия ислама, передаётся властям; если он не покается, в отношении него применяется установление.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-14-Nawawi-Psalmodie-Arabe.mp3',
  5,
  14
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 14
);
