-- =============================================================================
-- 40 Hadith Nawawi — Hadith 4: "Deeds are judged by their endings" (the decree)
-- Target collection: public.hadith_collections.id = 2  /  position = 4
-- Idempotent guard on (collection, position). All 11 content languages.
-- Arabic source cleaned: narrator order restored, typos fixed
-- (فَيَدْجُلَها -> فَيَدْخُلُهَا, شَقِيٌّ أَوْ سَعِيدٌ, اُمِّهِ, etc.).
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Deeds are judged by their endings',
  'Les dernières œuvres sont déterminantes',
  'الأعمال بخواتيمها',
  'Die Taten werden nach ihrem Ende beurteilt',
  'Daden worden beoordeeld naar hun einde',
  'Ameller sonuçlarına göredir',
  'Amal dinilai dari akhirnya',
  'اعمال کا دارومدار خاتمے پر ہے',
  'কাজের ফলাফল তার পরিণতির উপর নির্ভরশীল',
  'Amalan dinilai pada pengakhirannya',
  'Дела (оцениваются) по их завершению',
  -- arabic_text (cleaned)
  'عَنْ أَبِي عَبْدِ الرَّحْمَنِ عَبْدِ اللَّهِ بْنِ مَسْعُودٍ رَضِيَ اللَّهُ عَنْهُ قَالَ: حَدَّثَنَا رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَهُوَ الصَّادِقُ الْمَصْدُوقُ: «إِنَّ أَحَدَكُمْ يُجْمَعُ خَلْقُهُ فِي بَطْنِ أُمِّهِ أَرْبَعِينَ يَوْمًا نُطْفَةً، ثُمَّ يَكُونُ عَلَقَةً مِثْلَ ذَلِكَ، ثُمَّ يَكُونُ مُضْغَةً مِثْلَ ذَلِكَ، ثُمَّ يُرْسَلُ إِلَيْهِ الْمَلَكُ فَيَنْفُخُ فِيهِ الرُّوحَ، وَيُؤْمَرُ بِأَرْبَعِ كَلِمَاتٍ: بِكَتْبِ رِزْقِهِ وَأَجَلِهِ وَعَمَلِهِ وَشَقِيٌّ أَوْ سَعِيدٌ. فَوَاللَّهِ الَّذِي لَا إِلَهَ غَيْرُهُ إِنَّ أَحَدَكُمْ لَيَعْمَلُ بِعَمَلِ أَهْلِ الْجَنَّةِ حَتَّى مَا يَكُونُ بَيْنَهُ وَبَيْنَهَا إِلَّا ذِرَاعٌ، فَيَسْبِقُ عَلَيْهِ الْكِتَابُ فَيَعْمَلُ بِعَمَلِ أَهْلِ النَّارِ فَيَدْخُلُهَا، وَإِنَّ أَحَدَكُمْ لَيَعْمَلُ بِعَمَلِ أَهْلِ النَّارِ حَتَّى مَا يَكُونُ بَيْنَهُ وَبَيْنَهَا إِلَّا ذِرَاعٌ، فَيَسْبِقُ عَلَيْهِ الْكِتَابُ فَيَعْمَلُ بِعَمَلِ أَهْلِ الْجَنَّةِ فَيَدْخُلُهَا»',
  -- transcription
  'ʿan Abī ʿAbdi r-Raḥmāni ʿAbdi Llāhi bni Masʿūdin raḍiya Llāhu ʿanhu qāla: ḥaddathanā Rasūlu Llāhi ṣalla Llāhu ʿalayhi wa-sallama wa-huwa ṣ-ṣādiqu l-maṣdūqu: inna aḥadakum yujmaʿu khalquhu fī baṭni ummihi arbaʿīna yawman nuṭfatan, thumma yakūnu ʿalaqatan mithla dhālik, thumma yakūnu muḍghatan mithla dhālik, thumma yursalu ilayhi l-malaku fa-yanfukhu fīhi r-rūḥa, wa-yuʾmaru bi-arbaʿi kalimātin: bi-katbi rizqihi wa-ajalihi wa-ʿamalihi wa-shaqiyyun aw saʿīd. fa-wa-Llāhi lladhī lā ilāha ghayruhu inna aḥadakum la-yaʿmalu bi-ʿamali ahli l-jannati ḥattā mā yakūnu baynahu wa-baynahā illā dhirāʿun, fa-yasbiqu ʿalayhi l-kitābu fa-yaʿmalu bi-ʿamali ahli n-nāri fa-yadkhuluhā, wa-inna aḥadakum la-yaʿmalu bi-ʿamali ahli n-nāri ḥattā mā yakūnu baynahu wa-baynahā illā dhirāʿun, fa-yasbiqu ʿalayhi l-kitābu fa-yaʿmalu bi-ʿamali ahli l-jannati fa-yadkhuluhā.',
  'ʿan Abî ʿAbdi r-Rahmâni ʿAbdi Llâhi bni Masʿôdin (radia Llâhou ʿanhou) qâla : haddathanâ Rassôlou Llâhi (salla Llâhou ʿalayhi wa sallam) wa houwa s-sâdiqou l-masdôqou : inna ahadakoum youjmaʿou khalqouhou fî batni oummihi arbaʿîna yawman noutfatan, thoumma yakônou ʿalaqatan mithla dhâlik, thoumma yakônou moudghatan mithla dhâlik, thoumma yoursalou ilayhi l-malakou fa-yanfoukhou fîhi r-rôha, wa youʾmarou bi-arbaʿi kalimâtin : bi-katbi rizqihi wa ajalihi wa ʿamalihi wa chaqiyyoun aw saʿîd. fa-wa-Llâhi lladhî lâ ilâha ghayrouhou inna ahadakoum la-yaʿmalou bi-ʿamali ahli l-jannati hattâ mâ yakôounou baynahou wa baynahâ illâ dhirâʿoun, fa-yasbiqou ʿalayhi l-kitâbou fa-yaʿmalou bi-ʿamali ahli n-nâri fa-yadkhoulouhâ, wa inna ahadakoum la-yaʿmalou bi-ʿamali ahli n-nâri hattâ mâ yakôounou baynahou wa baynahâ illâ dhirâʿoun, fa-yasbiqou ʿalayhi l-kitâbou fa-yaʿmalou bi-ʿamali ahli l-jannati fa-yadkhoulouhâ.',
  'ʿan Abī ʿAbdi r-Rahmāni ʿAbdi Llāhi bni Masʿūdin (radiya Llāhu ʿanhu) qāla: haddathanā Rasūlu Llāhi (salla Llāhu ʿalaihi wa-sallam) wa-huwa s-sādiqu l-masdūqu: inna ahadakum judschmaʿu chalquhu fī batni ummihi arbaʿīna jauman nutfatan, thumma jakūnu ʿalaqatan mithla dhālik, thumma jakūnu mudghatan mithla dhālik, thumma jursalu ilaihi l-malaku fa-janfuchu fīhi r-rūha, wa-juʾmaru bi-arbaʿi kalimātin: bi-katbi rizqihi wa-adschalihi wa-ʿamalihi wa-schaqijjun au saʿīd. fa-wa-Llāhi lladhī lā ilāha ghairuhu inna ahadakum la-jaʿmalu bi-ʿamali ahli l-dschannati hattā mā jakūnu bainahu wa-bainahā illā dhirāʿun, fa-jasbiqu ʿalaihi l-kitābu fa-jaʿmalu bi-ʿamali ahli n-nāri fa-jadchuluhā, wa-inna ahadakum la-jaʿmalu bi-ʿamali ahli n-nāri hattā mā jakūnu bainahu wa-bainahā illā dhirāʿun, fa-jasbiqu ʿalaihi l-kitābu fa-jaʿmalu bi-ʿamali ahli l-dschannati fa-jadchuluhā.',
  'ʿan Abie ʿAbdi r-Rahmaani ʿAbdi Llaahi bni Masʿoedin (radia Llaahoe ʿanhoe) qaala: haddathanaa Rasoeloe Llaahi (salla Llaahoe ʿalaihi wa-sallam) wa-hoewa s-saadiqoe l-masdoeqoe: inna ahadakoem joedzjmaʿoe chalqoehoe fie batni oemmihi arbaʿiena jauman noetfatan, thoemma jakoenoe ʿalaqatan mithla dhaalik, thoemma jakoenoe moedghatan mithla dhaalik, thoemma joersaloe ilaihi l-malakoe fa-janfoechoe fiehi r-roeha, wa-joeʾmaroe bi-arbaʿi kalimaatin: bi-katbi rizqihi wa-adzjalihi wa-ʿamalihi wa-sjaqijjoen au saʿied. fa-wa-Llaahi lladhie laa ilaaha ghairoehoe inna ahadakoem la-jaʿmaloe bi-ʿamali ahli l-dzjannati hattaa maa jakoenoe bainahoe wa-bainahaa illaa dhiraaʿoen, fa-jasbiqoe ʿalaihi l-kitaaboe fa-jaʿmaloe bi-ʿamali ahli n-naari fa-jadchoeloehaa, wa-inna ahadakoem la-jaʿmaloe bi-ʿamali ahli n-naari hattaa maa jakoenoe bainahoe wa-bainahaa illaa dhiraaʿoen, fa-jasbiqoe ʿalaihi l-kitaaboe fa-jaʿmaloe bi-ʿamali ahli l-dzjannati fa-jadchoeloehaa.',
  'an Ebû Abdurrahman Abdullah ibn Mesûd''dan (radıyallâhu anh) rivayetle dedi ki: bize sözünde doğru ve kendisi tasdik edilmiş olan Resûlullah (s.a.v.) şöyle haber verdi: sizden birinin yaratılışı annesinin karnında kırk gün nutfe olarak toplanır, sonra bir o kadar süre alaka (kan pıhtısı) olur, sonra bir o kadar süre mudga (et parçası) olur, sonra ona melek gönderilir, ruhu üflenir ve dört kelimeyi yazması emrolunur: rızkı, eceli, ameli ve şaki mi yoksa said mi olduğu. Kendisinden başka ilâh olmayan Allah''a yemin olsun ki, sizden biri cennet ehlinin ameliyle amel eder, nihayet kendisiyle cennet arasında bir arşın kalır, derken kitap (kader) onu geçer de cehennem ehlinin ameliyle amel eder ve oraya girer. Yine sizden biri cehennem ehlinin ameliyle amel eder, nihayet kendisiyle cehennem arasında bir arşın kalır, derken kitap onu geçer de cennet ehlinin ameliyle amel eder ve oraya girer.',
  'ʿan Abī ʿAbdir-Rahmān ʿAbdillāh bin Masʿūd (radhiyallāhu ʿanhu) berkata: telah menceritakan kepada kami Rasulullah (shallallāhu ʿalaihi wa sallam), dan beliau adalah orang yang benar lagi dibenarkan: inna ahadakum yujmaʿu khalquhu fī bathni ummihi arbaʿīna yauman nuthfatan, tsumma yakūnu ʿalaqatan mitsla dzālik, tsumma yakūnu mudhghatan mitsla dzālik, tsumma yursalu ilaihil-malaku fayanfukhu fīhir-rūha, wa yuʾmaru bi-arbaʿi kalimātin: bi-katbi rizqihi wa ajalihi wa ʿamalihi wa syaqiyyun au saʿīd. fawallāhilladzī lā ilāha ghairuhu inna ahadakum layaʿmalu bi-ʿamali ahlil-jannati hattā mā yakūnu bainahu wa bainahā illā dzirāʿun, fayasbiqu ʿalaihil-kitābu fayaʿmalu bi-ʿamali ahlin-nāri fayadkhuluhā, wa inna ahadakum layaʿmalu bi-ʿamali ahlin-nāri hattā mā yakūnu bainahu wa bainahā illā dzirāʿun, fayasbiqu ʿalaihil-kitābu fayaʿmalu bi-ʿamali ahlil-jannati fayadkhuluhā.',
  'ابو عبد الرحمن عبد اللہ بن مسعود رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: ہم سے رسول اللہ صلی اللہ علیہ وسلم نے بیان فرمایا، اور آپ سچے اور سچا مانے گئے ہیں: تم میں سے ہر ایک کی تخلیق اس کی ماں کے پیٹ میں چالیس دن تک نطفہ کی صورت میں جمع رہتی ہے، پھر اتنے ہی عرصے میں جما ہوا خون بنتا ہے، پھر اتنے ہی عرصے میں گوشت کا لوتھڑا بنتا ہے، پھر اس کی طرف فرشتہ بھیجا جاتا ہے جو اس میں روح پھونکتا ہے اور اسے چار باتیں لکھنے کا حکم دیا جاتا ہے: اس کا رزق، اس کی عمر، اس کے عمل اور یہ کہ وہ بدبخت ہے یا نیک بخت۔ پس اس اللہ کی قسم جس کے سوا کوئی معبود نہیں! تم میں سے کوئی جنت والوں کے عمل کرتا رہتا ہے یہاں تک کہ اس کے اور جنت کے درمیان صرف ایک ہاتھ کا فاصلہ رہ جاتا ہے، تب تقدیر اس پر سبقت لے جاتی ہے اور وہ جہنم والوں کے عمل کرنے لگتا ہے اور اس میں داخل ہو جاتا ہے۔ اور تم میں سے کوئی جہنم والوں کے عمل کرتا رہتا ہے یہاں تک کہ اس کے اور جہنم کے درمیان صرف ایک ہاتھ کا فاصلہ رہ جاتا ہے، تب تقدیر اس پر سبقت لے جاتی ہے اور وہ جنت والوں کے عمل کرنے لگتا ہے اور اس میں داخل ہو جاتا ہے۔',
  'আবু আবদুর রহমান আবদুল্লাহ ইবনে মাসউদ (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: আমাদের নিকট রাসূলুল্লাহ ﷺ বর্ণনা করেছেন, আর তিনি সত্যবাদী ও সত্যায়িত: তোমাদের প্রত্যেকের সৃষ্টি তার মায়ের গর্ভে চল্লিশ দিন শুক্ররূপে একত্র থাকে, অতঃপর অনুরূপ সময় জমাট রক্ত হয়, অতঃপর অনুরূপ সময় মাংসপিণ্ড হয়, অতঃপর তার নিকট একজন ফেরেশতা পাঠানো হয় যিনি তার মধ্যে রূহ ফুঁকে দেন এবং তাকে চারটি বিষয় লেখার নির্দেশ দেওয়া হয়: তার রিজিক, তার আয়ু, তার আমল এবং সে দুর্ভাগা না সৌভাগ্যবান। সেই আল্লাহর কসম যিনি ছাড়া কোনো ইলাহ নেই! তোমাদের কেউ জান্নাতবাসীদের আমল করতে থাকে এমনকি তার ও জান্নাতের মধ্যে মাত্র এক হাত ব্যবধান থাকে, তখন তার ওপর তাকদির অগ্রগামী হয় এবং সে জাহান্নামবাসীদের আমল করে ফেলে ও তাতে প্রবেশ করে। আর তোমাদের কেউ জাহান্নামবাসীদের আমল করতে থাকে এমনকি তার ও জাহান্নামের মধ্যে মাত্র এক হাত ব্যবধান থাকে, তখন তার ওপর তাকদির অগ্রগামী হয় এবং সে জান্নাতবাসীদের আমল করে ফেলে ও তাতে প্রবেশ করে।',
  'ʿan Abī ʿAbdir-Rahmān ʿAbdullāh bin Masʿūd (radhiallāhu ʿanhu) berkata: telah menceritakan kepada kami Rasulullah (sallallāhu ʿalaihi wa sallam), dan baginda ialah orang yang benar lagi dibenarkan: inna ahadakum yujmaʿu khalquhu fī batni ummihi arbaʿīna yauman nutfatan, tsumma yakūnu ʿalaqatan mitsla dzālik, tsumma yakūnu mudghatan mitsla dzālik, tsumma yursalu ilaihil-malaku fayanfukhu fīhir-rūha, wa yuʾmaru bi-arbaʿi kalimātin: bi-katbi rizqihi wa ajalihi wa ʿamalihi wa syaqiyyun au saʿīd. fawallāhilladzī lā ilāha ghairuhu inna ahadakum layaʿmalu bi-ʿamali ahlil-jannati hattā mā yakūnu bainahu wa bainahā illā dzirāʿun, fayasbiqu ʿalaihil-kitābu fayaʿmalu bi-ʿamali ahlin-nāri fayadkhuluhā, wa inna ahadakum layaʿmalu bi-ʿamali ahlin-nāri hattā mā yakūnu bainahu wa bainahā illā dzirāʿun, fayasbiqu ʿalaihil-kitābu fayaʿmalu bi-ʿamali ahlil-jannati fayadkhuluhā.',
  'От Аби Абдиррахмана Абдуллаха ибн Масуда (да будет доволен им Аллах) передаётся: рассказал нам Посланник Аллаха ﷺ, а он — правдивый, чья правдивость подтверждена: поистине, творение каждого из вас собирается во чреве его матери сорок дней в виде капли (нутфа), затем столько же времени он бывает сгустком крови (аляка), затем столько же времени — кусочком плоти (мудга), затем к нему посылается ангел, который вдувает в него дух, и ему велят записать четыре слова: его удел, его срок, его дела и то, несчастен он или счастлив. Клянусь Аллахом, кроме Которого нет божества! Поистине, один из вас совершает деяния обитателей Рая, пока между ним и Раем не остаётся лишь локоть, но предписание опережает его, и он начинает совершать деяния обитателей Огня и входит в него. И поистине, один из вас совершает деяния обитателей Огня, пока между ним и Огнём не остаётся лишь локоть, но предписание опережает его, и он начинает совершать деяния обитателей Рая и входит в него.',
  -- translation
  'On the authority of Abu ʿAbd ar-Rahman ʿAbd Allah ibn Masʿud (may Allah be pleased with him) — the truthful and trustworthy one — the Messenger of Allah ﷺ said: "Verily the creation of each one of you is gathered in the womb of his mother for forty days as a drop (nutfa), then he becomes a clinging clot (ʿalaqa) for a like period, then a lump of flesh (mudgha) for a like period, then an angel is sent to him who breathes the soul into him and is commanded to record four things: his provision, his lifespan, his deeds, and whether he will be wretched or happy. By Allah, besides Whom there is no god, one of you may perform the deeds of the people of Paradise until there is but a cubit between him and it, then the decree overtakes him and he performs the deeds of the people of the Fire and enters it. And one of you may perform the deeds of the people of the Fire until there is but a cubit between him and it, then the decree overtakes him and he performs the deeds of the people of Paradise and enters it."',
  'D''après Abû ʿAbd ar-Rahmân ʿAbd Allah ibn Masʿûd (qu''Allah l''agrée), lui qui est le véridique, le digne d''être cru, l''Envoyé d''Allah ﷺ a dit : « La conception de chacun d''entre vous, dans le ventre de sa mère, s''accomplit en quarante jours sous la forme d''une semence (nutfa) ; puis il devient pour une même période un caillot de sang (ʿalaqa) ; puis un morceau de chair (mudgha) pour une même période ; puis un ange lui est envoyé, il y insuffle l''esprit, et reçoit l''ordre d''inscrire quatre paroles : ce qui lui est imparti comme subsistance, son terme (de vie), ses actes, et s''il sera malheureux ou heureux. Par Allah, en dehors duquel il n''est de divinité, l''un de vous accomplit les actes des gens du Paradis au point qu''il ne reste plus entre lui et lui qu''une coudée ; c''est alors qu''il est devancé par le destin, il accomplit les actes des gens de l''Enfer et y entre. Et l''un de vous accomplit les actes des gens de l''Enfer au point qu''il ne reste plus entre lui et lui qu''une coudée ; c''est alors qu''il est devancé par le destin, il accomplit les actes des gens du Paradis et y entre. »',
  'Nach Abu ʿAbd ar-Rahman ʿAbd Allah ibn Masʿud (möge Allah mit ihm zufrieden sein), dem Wahrhaftigen, dem die Wahrhaftigkeit bestätigt wurde, sagte der Gesandte Allahs ﷺ: „Wahrlich, die Erschaffung eines jeden von euch wird im Leib seiner Mutter vierzig Tage als Tropfen (Nutfa) zusammengefügt, dann ist er für einen gleichen Zeitraum ein anhaftender Klumpen (ʿAlaqa), dann ein Stück Fleisch (Mudgha) für einen gleichen Zeitraum, dann wird ein Engel zu ihm gesandt, der ihm die Seele einhaucht und beauftragt wird, vier Dinge aufzuschreiben: seine Versorgung, seine Lebensspanne, seine Taten und ob er elend oder glücklich sein wird. Bei Allah, außer Dem es keinen Gott gibt: Einer von euch verrichtet die Taten der Leute des Paradieses, bis zwischen ihm und ihm nur noch eine Elle bleibt, dann holt ihn die Vorherbestimmung ein, und er verrichtet die Taten der Leute des Feuers und tritt in es ein. Und einer von euch verrichtet die Taten der Leute des Feuers, bis zwischen ihm und ihm nur noch eine Elle bleibt, dann holt ihn die Vorherbestimmung ein, und er verrichtet die Taten der Leute des Paradieses und tritt in es ein."',
  'Op gezag van Abu ʿAbd ar-Rahman ʿAbd Allah ibn Masʿud (moge Allah tevreden met hem zijn), de waarachtige wiens waarachtigheid bevestigd is, zei de Boodschapper van Allah ﷺ: „Voorwaar, de schepping van ieder van jullie wordt in de buik van zijn moeder veertig dagen verzameld als een druppel (nutfa), dan is hij voor eenzelfde periode een klonter (ʿalaqa), dan een klompje vlees (mudgha) voor eenzelfde periode, dan wordt er een engel naar hem gezonden die de ziel in hem blaast en bevolen wordt vier dingen op te schrijven: zijn voorziening, zijn levensduur, zijn daden en of hij ellendig of gelukkig zal zijn. Bij Allah, buiten Wie er geen god is: een van jullie verricht de daden van de mensen van het Paradijs totdat er tussen hem en het nog maar een el is, dan haalt de voorbeschikking hem in en verricht hij de daden van de mensen van het Vuur en treedt erin binnen. En een van jullie verricht de daden van de mensen van het Vuur totdat er tussen hem en het nog maar een el is, dan haalt de voorbeschikking hem in en verricht hij de daden van de mensen van het Paradijs en treedt erin binnen."',
  'Ebû Abdurrahman Abdullah ibn Mesûd''dan (Allah ondan razı olsun) — ki o doğru sözlü ve doğrulanmıştır — rivayet edildiğine göre Resûlullah ﷺ şöyle buyurdu: „Şüphesiz her birinizin yaratılışı, annesinin karnında kırk gün nutfe olarak toplanır, sonra bir o kadar süre alaka (kan pıhtısı) olur, sonra bir o kadar süre mudga (et parçası) olur, sonra ona bir melek gönderilir, ruhu üflenir ve dört şeyi yazması emrolunur: rızkı, eceli, ameli ve şaki mi yoksa said mi olacağı. Kendisinden başka ilâh olmayan Allah''a yemin olsun ki, sizden biri cennet ehlinin ameliyle amel eder, nihayet kendisiyle cennet arasında yalnızca bir arşın kalır, derken kader onu geçer, cehennem ehlinin ameliyle amel eder ve oraya girer. Yine sizden biri cehennem ehlinin ameliyle amel eder, nihayet kendisiyle cehennem arasında yalnızca bir arşın kalır, derken kader onu geçer, cennet ehlinin ameliyle amel eder ve oraya girer."',
  'Dari Abu Abdurrahman Abdullah bin Masʿud (semoga Allah meridhainya) — orang yang benar lagi dibenarkan — Rasulullah ﷺ bersabda: "Sesungguhnya penciptaan salah seorang dari kalian dikumpulkan di dalam perut ibunya selama empat puluh hari berupa nutfah (setetes mani), kemudian menjadi ʿalaqah (segumpal darah) selama itu pula, kemudian menjadi mudghah (segumpal daging) selama itu pula, kemudian diutus kepadanya seorang malaikat yang meniupkan ruh ke dalamnya dan diperintahkan untuk menuliskan empat perkara: rezekinya, ajalnya, amalnya, serta celaka atau bahagia. Demi Allah yang tidak ada tuhan selain-Nya, sesungguhnya salah seorang dari kalian benar-benar beramal dengan amalan penghuni surga hingga jarak antara dirinya dan surga tinggal sehasta, lalu catatan (takdir) mendahuluinya sehingga ia beramal dengan amalan penghuni neraka lalu memasukinya. Dan sesungguhnya salah seorang dari kalian benar-benar beramal dengan amalan penghuni neraka hingga jarak antara dirinya dan neraka tinggal sehasta, lalu catatan (takdir) mendahuluinya sehingga ia beramal dengan amalan penghuni surga lalu memasukinya."',
  'ابو عبد الرحمن عبد اللہ بن مسعود رضی اللہ عنہ سے روایت ہے — اور آپ سچے اور سچا مانے گئے ہیں — کہ رسول اللہ ﷺ نے فرمایا: ”بے شک تم میں سے ہر ایک کی تخلیق اس کی ماں کے پیٹ میں چالیس دن تک نطفہ کی صورت میں جمع رہتی ہے، پھر اتنے ہی عرصے میں جما ہوا خون بنتا ہے، پھر اتنے ہی عرصے میں گوشت کا لوتھڑا بنتا ہے، پھر اس کی طرف ایک فرشتہ بھیجا جاتا ہے جو اس میں روح پھونکتا ہے اور اسے چار باتیں لکھنے کا حکم دیا جاتا ہے: اس کا رزق، اس کی عمر، اس کا عمل اور یہ کہ وہ بدبخت ہے یا نیک بخت۔ اس اللہ کی قسم جس کے سوا کوئی معبود نہیں! تم میں سے کوئی جنت والوں کے عمل کرتا رہتا ہے یہاں تک کہ اس کے اور جنت کے درمیان صرف ایک ہاتھ کا فاصلہ رہ جاتا ہے، پھر تقدیر اس پر سبقت لے جاتی ہے اور وہ جہنم والوں کے عمل کرنے لگتا ہے اور اس میں داخل ہو جاتا ہے۔ اور تم میں سے کوئی جہنم والوں کے عمل کرتا رہتا ہے یہاں تک کہ اس کے اور جہنم کے درمیان صرف ایک ہاتھ کا فاصلہ رہ جاتا ہے، پھر تقدیر اس پر سبقت لے جاتی ہے اور وہ جنت والوں کے عمل کرنے لگتا ہے اور اس میں داخل ہو جاتا ہے۔“',
  'আবু আবদুর রহমান আবদুল্লাহ ইবনে মাসউদ (রাদিয়াল্লাহু আনহু) — যিনি সত্যবাদী ও সত্যায়িত — থেকে বর্ণিত, রাসূলুল্লাহ ﷺ বলেছেন: "নিশ্চয়ই তোমাদের প্রত্যেকের সৃষ্টি তার মায়ের গর্ভে চল্লিশ দিন শুক্ররূপে একত্র থাকে, অতঃপর অনুরূপ সময় জমাট রক্ত হয়, অতঃপর অনুরূপ সময় মাংসপিণ্ড হয়, অতঃপর তার নিকট একজন ফেরেশতা পাঠানো হয় যিনি তার মধ্যে রূহ ফুঁকে দেন এবং তাকে চারটি বিষয় লেখার নির্দেশ দেওয়া হয়: তার রিজিক, তার আয়ু, তার আমল এবং সে দুর্ভাগা না সৌভাগ্যবান। সেই আল্লাহর কসম যিনি ছাড়া কোনো ইলাহ নেই! নিশ্চয়ই তোমাদের কেউ জান্নাতবাসীদের আমল করতে থাকে এমনকি তার ও জান্নাতের মধ্যে মাত্র এক হাত ব্যবধান থাকে, অতঃপর তার ওপর তাকদির অগ্রগামী হয় এবং সে জাহান্নামবাসীদের আমল করে ফেলে ও তাতে প্রবেশ করে। আর তোমাদের কেউ জাহান্নামবাসীদের আমল করতে থাকে এমনকি তার ও জাহান্নামের মধ্যে মাত্র এক হাত ব্যবধান থাকে, অতঃপর তার ওপর তাকদির অগ্রগামী হয় এবং সে জান্নাতবাসীদের আমল করে ফেলে ও তাতে প্রবেশ করে।"',
  'Daripada Abu Abdul Rahman Abdullah bin Masʿud (semoga Allah meredainya) — yang benar lagi dibenarkan — Rasulullah ﷺ bersabda: "Sesungguhnya penciptaan salah seorang daripada kamu dikumpulkan di dalam perut ibunya selama empat puluh hari sebagai nutfah (air mani), kemudian menjadi ʿalaqah (segumpal darah) selama itu juga, kemudian menjadi mudghah (segumpal daging) selama itu juga, kemudian diutus kepadanya seorang malaikat yang meniupkan roh ke dalamnya dan diperintahkan menuliskan empat perkara: rezekinya, ajalnya, amalnya, serta celaka atau bahagia. Demi Allah yang tiada tuhan selain-Nya, sesungguhnya salah seorang daripada kamu benar-benar beramal dengan amalan ahli syurga sehingga jarak antara dirinya dengan syurga tinggal sehasta, lalu catatan (takdir) mendahuluinya sehingga dia beramal dengan amalan ahli neraka lalu memasukinya. Dan sesungguhnya salah seorang daripada kamu benar-benar beramal dengan amalan ahli neraka sehingga jarak antara dirinya dengan neraka tinggal sehasta, lalu catatan (takdir) mendahuluinya sehingga dia beramal dengan amalan ahli syurga lalu memasukinya."',
  'Со слов Абу ʿАбд ар-Рахмана ʿАбдуллаха ибн Масʿуда (да будет доволен им Аллах) — правдивого, чья правдивость подтверждена — Посланник Аллаха ﷺ сказал: «Поистине, творение каждого из вас собирается во чреве его матери сорок дней в виде капли (нутфа), затем столько же он бывает сгустком крови (аляка), затем столько же — кусочком плоти (мудга), затем к нему посылается ангел, который вдувает в него дух и которому велено записать четыре слова: его удел, его срок, его дела и то, будет ли он несчастен или счастлив. Клянусь Аллахом, кроме Которого нет божества: один из вас совершает деяния обитателей Рая, пока между ним и Раем не останется лишь локоть, но предписание опережает его, и он совершает деяния обитателей Огня и входит в него. И один из вас совершает деяния обитателей Огня, пока между ним и Огнём не останется лишь локоть, но предписание опережает его, и он совершает деяния обитателей Рая и входит в него».',
  -- reference
  'Sahih — reported by Al-Bukhari (11/447, no. 6594) and Muslim (4/2036, no. 2643)',
  'Hadith authentique rapporté par Al-Bukhari (11/447, n°6594) et Muslim (4/2036, n°2643)',
  'حديث صحيح، رواه البخاري (١١/٤٤٧) (رقم ٦٥٩٤) ومسلم (٤/٢٠٣٦) (رقم ٢٦٤٣)',
  'Sahih — überliefert von Al-Bukhari (11/447, Nr. 6594) und Muslim (4/2036, Nr. 2643)',
  'Sahih — overgeleverd door Al-Bukhari (11/447, nr. 6594) en Muslim (4/2036, nr. 2643)',
  'Sahih — Buhârî (11/447, no. 6594) ve Müslim (4/2036, no. 2643) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (11/447, no. 6594) dan Muslim (4/2036, no. 2643)',
  'صحیح حدیث، اسے بخاری (۱۱/۴۴۷، نمبر ۶۵۹۴) اور مسلم (۴/۲۰۳۶، نمبر ۲۶۴۳) نے روایت کیا',
  'সহীহ হাদীস — বুখারী (১১/৪৪৭, নং ৬৫৯৪) ও মুসলিম (৪/২০৩৬, নং ২৬৪৩) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (11/447, no. 6594) dan Muslim (4/2036, no. 2643)',
  'Достоверный хадис, передали аль-Бухари (11/447, № 6594) и Муслим (4/2036, № 2643)',
  -- tafsir
  'In this fourth hadith, the Prophet ﷺ shows that within the mother''s womb the human being passes from one stage to another, and that the time of his death, what is allotted to him, and so forth are written down. ʿAbd Allah ibn Masʿud said: "The Messenger of Allah ﷺ — the truthful, the trustworthy — told us…" — meaning truthful in his speech and trustworthy in what he receives of divine revelation. He gave this introduction because what follows belongs to the unseen (ghayb), which can only be known through divine revelation.',
  'Dans ce quatrième hadith, le Prophète ﷺ montre que c''est dans le ventre de sa mère que s''effectue le passage de l''homme d''une étape à une autre, ainsi que l''écriture du moment de sa mort, de ce qui lui sera accordé, etc. ʿAbd Allah ibn Masʿud a dit : « Le Messager d''Allah ﷺ nous a dit, lui qui est le véridique, le digne d''être cru… » — c''est-à-dire le véridique dans son parler et le digne d''être cru dans ce qu''il reçoit comme révélation divine. Il a en effet placé cette introduction, car les paroles qui suivent relèvent de l''invisible (ghayb), que l''on ne peut connaître que par une révélation divine.',
  'في هذا الحديث الرابع يبيّن النبي صلى الله عليه وسلم أن الإنسان في بطن أمه ينتقل من طور إلى طور، وأنه يُكتب أجل موته وما يُقدَّر له ونحو ذلك. قال عبد الله بن مسعود: «حدثنا رسول الله صلى الله عليه وسلم وهو الصادق المصدوق» أي الصادق في قوله، المصدوق فيما يتلقاه من الوحي الإلهي. وإنما قدّم هذه المقدمة لأن ما سيأتي من الكلام هو من أمور الغيب التي لا تُعرف إلا بالوحي الإلهي.',
  'In diesem vierten Hadith zeigt der Prophet ﷺ, dass sich im Leib der Mutter der Übergang des Menschen von einer Stufe zur anderen vollzieht und dass der Zeitpunkt seines Todes, was ihm zugeteilt wird usw. niedergeschrieben werden. ʿAbd Allah ibn Masʿud sagte: „Der Gesandte Allahs ﷺ — der Wahrhaftige, dem die Wahrhaftigkeit bestätigt wurde — berichtete uns…" — das heißt wahrhaftig in seiner Rede und bestätigt in dem, was er an göttlicher Offenbarung empfängt. Er stellte diese Einleitung voran, weil das Folgende zum Verborgenen (Ghayb) gehört, das nur durch göttliche Offenbarung erkannt werden kann.',
  'In deze vierde hadith toont de Profeet ﷺ aan dat in de buik van de moeder de overgang van de mens van het ene stadium naar het andere plaatsvindt, en dat het tijdstip van zijn dood, wat hem wordt toebedeeld, enzovoort worden opgeschreven. ʿAbd Allah ibn Masʿud zei: „De Boodschapper van Allah ﷺ — de waarachtige, wiens waarachtigheid bevestigd is — vertelde ons…" — dat wil zeggen waarachtig in zijn spreken en bevestigd in wat hij aan goddelijke openbaring ontvangt. Hij plaatste deze inleiding vooraf, omdat wat volgt tot het onzichtbare (ghayb) behoort, dat slechts door goddelijke openbaring gekend kan worden.',
  'Bu dördüncü hadiste Peygamber ﷺ, insanın anne karnında bir aşamadan diğerine geçtiğini, ölüm zamanının, kendisine takdir edilenin vb. yazıldığını beyan eder. Abdullah ibn Mesûd dedi ki: „Bize Resûlullah ﷺ — ki o doğru sözlü ve doğrulanmıştır — şöyle haber verdi…" — yani sözünde doğru, aldığı ilâhî vahiyde doğrulanmış. Bu girişi öne almıştır, çünkü bundan sonra gelecek sözler, ancak ilâhî vahiyle bilinebilen gayb işlerindendir.',
  'Dalam hadis keempat ini, Nabi ﷺ menjelaskan bahwa di dalam perut ibunya manusia berpindah dari satu fase ke fase lain, dan bahwa waktu kematiannya, apa yang ditakdirkan baginya, dan sebagainya dituliskan. Abdullah bin Masʿud berkata: "Rasulullah ﷺ — yang benar lagi dibenarkan — telah menceritakan kepada kami…" — yakni benar dalam ucapannya dan dibenarkan dalam apa yang ia terima dari wahyu ilahi. Beliau (Ibnu Masʿud) memberi pendahuluan ini karena ucapan yang akan datang termasuk perkara gaib yang tidak dapat diketahui kecuali melalui wahyu ilahi.',
  'اس چوتھی حدیث میں نبی ﷺ یہ بیان فرماتے ہیں کہ انسان اپنی ماں کے پیٹ میں ایک مرحلے سے دوسرے مرحلے کی طرف منتقل ہوتا ہے، اور اس کی موت کا وقت، جو کچھ اس کے لیے مقدر کیا جاتا ہے وغیرہ لکھ دیا جاتا ہے۔ عبد اللہ بن مسعود نے کہا: ”ہم سے رسول اللہ ﷺ نے بیان فرمایا، اور آپ سچے اور سچا مانے گئے ہیں…“ یعنی اپنے قول میں سچے اور جو وحیِ الٰہی آپ کو ملتی ہے اس میں سچا مانے گئے۔ انہوں نے یہ تمہید اس لیے پیش کی کیونکہ آگے آنے والی باتیں اُمورِ غیب میں سے ہیں جنہیں صرف وحیِ الٰہی کے ذریعے ہی جانا جا سکتا ہے۔',
  'এই চতুর্থ হাদীসে নবী ﷺ দেখান যে মায়ের গর্ভে মানুষ এক স্তর থেকে আরেক স্তরে স্থানান্তরিত হয়, এবং তার মৃত্যুর সময়, তার জন্য যা নির্ধারিত হয় ইত্যাদি লিখে দেওয়া হয়। আবদুল্লাহ ইবনে মাসউদ বলেন: "রাসূলুল্লাহ ﷺ — যিনি সত্যবাদী ও সত্যায়িত — আমাদের নিকট বর্ণনা করেছেন…" অর্থাৎ তাঁর কথায় সত্যবাদী এবং যে ওহী তিনি লাভ করেন তাতে সত্যায়িত। তিনি এই ভূমিকা পেশ করেছেন কারণ পরবর্তী কথাগুলো গায়েবের অন্তর্ভুক্ত, যা কেবল ঐশী ওহীর মাধ্যমেই জানা যায়।',
  'Dalam hadis keempat ini, Nabi ﷺ menjelaskan bahawa di dalam perut ibunya manusia berpindah dari satu peringkat ke peringkat yang lain, dan bahawa waktu kematiannya, apa yang ditakdirkan baginya, dan sebagainya dituliskan. Abdullah bin Masʿud berkata: "Rasulullah ﷺ — yang benar lagi dibenarkan — telah menceritakan kepada kami…" — iaitu benar dalam ucapannya dan dibenarkan dalam apa yang baginda terima daripada wahyu ilahi. Baginda (Ibnu Masʿud) memberikan pendahuluan ini kerana ucapan yang akan datang termasuk perkara ghaib yang tidak dapat diketahui melainkan melalui wahyu ilahi.',
  'В этом четвёртом хадисе Пророк ﷺ показывает, что во чреве матери совершается переход человека из одной стадии в другую, и что записываются время его смерти, то, что ему предопределено, и тому подобное. Абдуллах ибн Масуд сказал: «Рассказал нам Посланник Аллаха ﷺ — правдивый, чья правдивость подтверждена…» — то есть правдивый в своих словах и подтверждённый в том, что он получает из божественного откровения. Он предпослал это вступление, потому что последующие слова относятся к сокровенному (гайб), которое можно познать только через божественное откровение.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-4-Nawawi-Psalmodie-Arabe.mp3',
  5,
  4
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 4
);
