-- =============================================================================
-- 40 Hadith Nawawi — Hadith 31: "Real asceticism (zuhd)"
-- Target collection: public.hadith_collections.id = 2  /  position = 31
-- Idempotent guard on (collection, position). All 11 content languages.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Real asceticism (zuhd)',
  'L''ascétisme réel',
  'الزهد الحقيقي',
  'Die wahre Genügsamkeit (Zuhd)',
  'De ware soberheid (zuhd)',
  'Gerçek zühd',
  'Zuhud yang sebenarnya',
  'حقیقی زہد',
  'প্রকৃত যুহদ',
  'Zuhud yang sebenar',
  'Истинный аскетизм (зухд)',
  -- arabic_text
  'عَنْ أَبِي الْعَبَّاسِ سَهْلِ بْنِ سَعْدٍ السَّاعِدِيِّ رَضِيَ اللَّهُ عَنْهُ قَالَ: جَاءَ رَجُلٌ إِلَى النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَقَالَ: يَا رَسُولَ اللَّهِ، دُلَّنِي عَلَى عَمَلٍ إِذَا عَمِلْتُهُ أَحَبَّنِي اللَّهُ وَأَحَبَّنِي النَّاسُ. فَقَالَ: «ازْهَدْ فِي الدُّنْيَا يُحِبَّكَ اللَّهُ، وَازْهَدْ فِيمَا عِنْدَ النَّاسِ يُحِبَّكَ النَّاسُ»',
  -- transcription
  'ʿan Abi l-ʿAbbāsi Sahli bni Saʿdin as-Sāʿidiyyi raḍiya Llāhu ʿanhu qāla: jāʾa rajulun ila n-Nabiyyi ṣalla Llāhu ʿalayhi wa-sallama fa-qāla: yā Rasūla Llāhi, dullanī ʿalā ʿamalin idhā ʿamiltuhu aḥabbanī Llāhu wa-aḥabbani n-nāsu. fa-qāla: izhad fi d-dunyā yuḥibbaka Llāhu, wa-zhad fīmā ʿinda n-nāsi yuḥibbaka n-nāsu.',
  'ʿan Abi l-ʿAbbâsi Sahli bni Saʿdin as-Sâʿidiyyi (radia Llâhou ʿanhou) qâla : jâʾa rajouloun ila n-Nabiyyi (salla Llâhou ʿalayhi wa sallam) fa-qâla : yâ Rassôla Llâhi, doullanî ʿalâ ʿamalin idhâ ʿamiltouhou ahabbanî Llâhou wa ahabbani n-nâsou. fa-qâla : izhad fi d-dounyâ youhibbaka Llâhou, wa zhad fîmâ ʿinda n-nâsi youhibbaka n-nâsou.',
  'ʿan Abi l-ʿAbbāsi Sahli bni Saʿdin as-Sāʿidijji (radiya Llāhu ʿanhu) qāla: dschāʾa radschulun ila n-Nabijji (salla Llāhu ʿalaihi wa-sallam) fa-qāla: jā Rasūla Llāhi, dullanī ʿalā ʿamalin idhā ʿamiltuhu ahabbanī Llāhu wa-ahabbani n-nāsu. fa-qāla: izhad fi d-dunjā juhibbaka Llāhu, wa-zhad fīmā ʿinda n-nāsi juhibbaka n-nāsu.',
  'ʿan Abi l-ʿAbbaasi Sahli bni Saʿdin as-Saaʿidijji (radia Llaahoe ʿanhoe) qaala: dzjaaʾa radzjoeloen ila n-Nabijji (salla Llaahoe ʿalaihi wa-sallam) fa-qaala: jaa Rasoela Llaahi, doellanie ʿalaa ʿamalin idhaa ʿamiltoehoe ahabbanie Llaahoe wa-ahabbani n-naasoe. fa-qaala: izhad fi d-doenjaa joehibbaka Llaahoe, wa-zhad fiemaa ʿinda n-naasi joehibbaka n-naasoe.',
  'an Ebü''l-Abbâs Sehl ibn Saʿd es-Sâidî''den (radıyallâhu anh) rivayetle dedi ki: bir adam Nebî''ye (s.a.v.) geldi ve: yâ Resûlallah, bana bir amel göster ki onu yaptığımda Allah beni sevsin ve insanlar da beni sevsin, dedi. Buyurdu: dünyaya karşı zâhid ol, Allah seni sever; insanların elindekine karşı zâhid ol, insanlar seni sever.',
  'an Abil-ʿAbbas Sahl bin Saʿd as-Saʿidi (radhiyallahu ʿanhu) berkata: seorang lelaki datang kepada Nabi (shallallahu ʿalaihi wa sallam) lalu berkata: wahai Rasulullah, tunjukkanlah kepadaku suatu amal yang apabila aku mengerjakannya Allah mencintaiku dan manusia mencintaiku. Beliau bersabda: zuhudlah terhadap dunia niscaya Allah mencintaimu, dan zuhudlah terhadap apa yang ada pada manusia niscaya manusia mencintaimu.',
  'ابو العباس سہل بن سعد الساعدی رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: ایک شخص نبی صلی اللہ علیہ وسلم کے پاس آیا اور کہا: یا رسول اللہ! مجھے کوئی ایسا عمل بتائیے جسے کرنے سے اللہ مجھ سے محبت کرے اور لوگ بھی مجھ سے محبت کریں۔ آپ نے فرمایا: دنیا سے بے رغبتی اختیار کرو، اللہ تم سے محبت کرے گا؛ اور جو کچھ لوگوں کے پاس ہے اس سے بے رغبتی اختیار کرو، لوگ تم سے محبت کریں گے۔',
  'আবুল আব্বাস সাহল ইবনে সাদ আস-সাইদী (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: এক ব্যক্তি নবী (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম)-এর নিকট এসে বলল: হে আল্লাহর রাসূল! আমাকে এমন একটি আমল বলুন যা করলে আল্লাহ আমাকে ভালোবাসবেন এবং মানুষও আমাকে ভালোবাসবে। তিনি বললেন: দুনিয়ার প্রতি নিরাসক্ত হও, আল্লাহ তোমাকে ভালোবাসবেন; আর মানুষের কাছে যা আছে তার প্রতি নিরাসক্ত হও, মানুষ তোমাকে ভালোবাসবে।',
  'an Abil-ʿAbbas Sahl bin Saʿd as-Saʿidi (radhiallahu ʿanhu) berkata: seorang lelaki datang kepada Nabi (sallallahu ʿalaihi wa sallam) lalu berkata: wahai Rasulullah, tunjukkanlah kepadaku suatu amal yang apabila aku mengerjakannya Allah mencintaiku dan manusia mencintaiku. Baginda bersabda: zuhudlah terhadap dunia nescaya Allah mencintaimu, dan zuhudlah terhadap apa yang ada pada manusia nescaya manusia mencintaimu.',
  'От Абуль-Аббаса Сахля ибн Саада ас-Саиди (да будет доволен им Аллах) передаётся: к Пророку ﷺ пришёл человек и сказал: о Посланник Аллаха, укажи мне деяние, которое, если я его совершу, Аллах полюбит меня и люди полюбят меня. Он сказал: будь воздержан к мирскому — и Аллах полюбит тебя; и будь воздержан к тому, что у людей, — и люди полюбят тебя.',
  -- translation
  'On the authority of Abu al-ʿAbbas Sahl ibn Saʿd as-Saʿidi (may Allah be pleased with him), who said: A man came to the Prophet ﷺ and said: "O Messenger of Allah, direct me to a deed which, if I do it, Allah will love me and people will love me." He said: "Be detached from this world, and Allah will love you; and be detached from what people possess, and people will love you."',
  'D''après Abû al-ʿAbbâs Sahl ibn Saʿd as-Sâʿidî (qu''Allah l''agrée), qui a dit : Un homme vint au Prophète ﷺ et dit : « Ô Envoyé d''Allah, indique-moi une œuvre qui, si je la fais, fera qu''Allah m''aime et que les gens m''aiment. » Il dit : « Mène une vie de détachement à l''égard de ce bas-monde, et Allah t''aimera ; et détache-toi de ce que possèdent les gens, et les gens t''aimeront. »',
  'Nach Abu al-ʿAbbas Sahl ibn Saʿd as-Saʿidi (möge Allah mit ihm zufrieden sein), der sagte: Ein Mann kam zum Propheten ﷺ und sagte: „O Gesandter Allahs, weise mich auf eine Tat, die, wenn ich sie tue, bewirkt, dass Allah mich liebt und die Menschen mich lieben." Er sagte: „Sei genügsam gegenüber dieser Welt, so wird Allah dich lieben; und sei genügsam gegenüber dem, was die Menschen besitzen, so werden die Menschen dich lieben."',
  'Op gezag van Abu al-ʿAbbas Sahl ibn Saʿd as-Saʿidi (moge Allah tevreden met hem zijn), die zei: Een man kwam bij de Profeet ﷺ en zei: „O Boodschapper van Allah, wijs mij een daad die, als ik haar verricht, maakt dat Allah mij liefheeft en de mensen mij liefhebben." Hij zei: „Wees onthecht van deze wereld, dan zal Allah jou liefhebben; en wees onthecht van wat de mensen bezitten, dan zullen de mensen jou liefhebben."',
  'Ebü''l-Abbâs Sehl ibn Saʿd es-Sâidî''den (Allah ondan razı olsun) rivayet edildiğine göre şöyle dedi: Bir adam Peygamber''e ﷺ geldi ve: „Yâ Resûlallah, bana öyle bir amel göster ki onu yaptığımda Allah beni sevsin ve insanlar da beni sevsin," dedi. Buyurdu: „Dünyaya karşı zâhid ol, Allah seni sever; insanların elindekine karşı zâhid ol, insanlar seni sever."',
  'Dari Abul-ʿAbbas Sahl bin Saʿd as-Saʿidi (semoga Allah meridhainya), ia berkata: Seorang lelaki datang kepada Nabi ﷺ lalu berkata: "Wahai Rasulullah, tunjukkanlah kepadaku suatu amal yang apabila aku mengerjakannya Allah mencintaiku dan manusia mencintaiku." Beliau bersabda: "Zuhudlah terhadap dunia, niscaya Allah mencintaimu; dan zuhudlah terhadap apa yang ada pada manusia, niscaya manusia mencintaimu."',
  'ابو العباس سہل بن سعد الساعدی رضی اللہ عنہ سے روایت ہے: ایک شخص نبی ﷺ کے پاس آیا اور کہا: ”یا رسول اللہ! مجھے کوئی ایسا عمل بتائیے جسے کرنے سے اللہ مجھ سے محبت کرے اور لوگ بھی مجھ سے محبت کریں۔“ آپ نے فرمایا: ”دنیا سے بے رغبتی اختیار کرو، اللہ تم سے محبت کرے گا؛ اور جو کچھ لوگوں کے پاس ہے اس سے بے رغبتی اختیار کرو، لوگ تم سے محبت کریں گے۔“',
  'আবুল আব্বাস সাহল ইবনে সাদ আস-সাইদী (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত: এক ব্যক্তি নবী ﷺ-এর নিকট এসে বলল: "হে আল্লাহর রাসূল! আমাকে এমন একটি আমল বলুন যা করলে আল্লাহ আমাকে ভালোবাসবেন এবং মানুষও আমাকে ভালোবাসবে।" তিনি বললেন: "দুনিয়ার প্রতি নিরাসক্ত হও, আল্লাহ তোমাকে ভালোবাসবেন; আর মানুষের কাছে যা আছে তার প্রতি নিরাসক্ত হও, মানুষ তোমাকে ভালোবাসবে।"',
  'Daripada Abul-ʿAbbas Sahl bin Saʿd as-Saʿidi (semoga Allah meredainya), dia berkata: Seorang lelaki datang kepada Nabi ﷺ lalu berkata: "Wahai Rasulullah, tunjukkanlah kepadaku suatu amal yang apabila aku mengerjakannya Allah mencintaiku dan manusia mencintaiku." Baginda bersabda: "Zuhudlah terhadap dunia, nescaya Allah mencintaimu; dan zuhudlah terhadap apa yang ada pada manusia, nescaya manusia mencintaimu."',
  'Со слов Абуль-Аббаса Сахля ибн Саада ас-Саиди (да будет доволен им Аллах), который сказал: К Пророку ﷺ пришёл человек и сказал: «О Посланник Аллаха, укажи мне деяние, которое, если я его совершу, Аллах полюбит меня и люди полюбят меня». Он сказал: «Будь воздержан к этому миру — и Аллах полюбит тебя; и будь воздержан к тому, что есть у людей, — и люди полюбят тебя».',
  -- reference
  'Hasan — reported by Ibn Majah (no. 4102), at-Tabarani (no. 5972), al-Hakim (4/313), and others; see as-Silsila as-Sahiha (no. 944)',
  'Hadith hasan rapporté par Ibn Mâja (n°4102), at-Tabarânî (n°5972), al-Hâkim (4/313) et d''autres ; voir as-Silsila as-Sahîha (n°944)',
  'حديث حسن، رواه ابن ماجه (رقم ٤١٠٢) والطبراني (رقم ٥٩٧٢) والحاكم (٤/٣١٣) وغيرهم؛ انظر السلسلة الصحيحة (رقم ٩٤٤)',
  'Hasan — überliefert von Ibn Madscha (Nr. 4102), at-Tabarani (Nr. 5972), al-Hakim (4/313) und anderen; siehe as-Silsila as-Sahiha (Nr. 944)',
  'Hasan — overgeleverd door Ibn Madja (nr. 4102), at-Tabarani (nr. 5972), al-Hakim (4/313) en anderen; zie as-Silsila as-Sahiha (nr. 944)',
  'Hasen — İbn Mâce (no. 4102), Taberânî (no. 5972), Hâkim (4/313) ve diğerleri rivayet etmiştir; bk. es-Silsiletü''s-Sahîha (no. 944)',
  'Hadis hasan, diriwayatkan oleh Ibnu Majah (no. 4102), at-Tabarani (no. 5972), al-Hakim (4/313), dan lainnya; lihat as-Silsilah as-Sahihah (no. 944)',
  'حسن حدیث، اسے ابن ماجہ (نمبر ۴۱۰۲)، طبرانی (نمبر ۵۹۷۲)، حاکم (۴/۳۱۳) وغیرہ نے روایت کیا؛ دیکھیں السلسلۃ الصحیحۃ (نمبر ۹۴۴)',
  'হাসান হাদীস — ইবনে মাজাহ (নং ৪১০২), তাবারানী (নং ৫৯৭২), হাকিম (৪/৩১৩) প্রমুখ বর্ণনা করেছেন; দেখুন আস-সিলসিলা আস-সহীহা (নং ৯৪৪)',
  'Hadis hasan, diriwayatkan oleh Ibnu Majah (no. 4102), at-Tabarani (no. 5972), al-Hakim (4/313), dan lain-lain; lihat as-Silsilah as-Sahihah (no. 944)',
  'Хороший (хасан) хадис, передали Ибн Маджа (№ 4102), ат-Табарани (№ 5972), аль-Хаким (4/313) и другие; см. «ас-Сильсиля ас-Сахиха» (№ 944)',
  -- tafsir
  '• The Companions (may Allah be pleased with them) always sought to ask the Prophet ﷺ about what would benefit them.\n• A person by nature loves that Allah, Glorified and Exalted, love him and that people love him; and he dislikes that Allah be displeased with him or that people dislike him.\n• Whoever practises detachment (zuhd) in this world, Allah will love him, for this necessarily entails desire for what is in the Hereafter.\n• Renouncing what people possess earns their love.\n• Coveting the pleasures and delights of this world and clinging to them makes a person hated by Allah, Glorified and Exalted; and coveting what people possess and watching for an opportunity to ask them for it makes those people dislike that person.',
  '• Les compagnons (qu''Allah les agrée) cherchaient toujours à interroger le Prophète ﷺ sur ce qui leur était utile.\n• L''homme, par sa nature, aime qu''Allah, Glorifié et Exalté, l''aime et que les gens l''aiment ; et il n''aime pas qu''Allah le déteste ni que les gens le détestent.\n• Celui qui fait preuve de détachement (zuhd) dans ce bas-monde, Allah l''aimera, car cela entraîne nécessairement le désir de ce qu''il y a dans l''au-delà.\n• Renoncer à ce que possèdent les gens procure leur amour.\n• Convoiter les jouissances et les délices de ce bas-monde et s''y cramponner rend la personne haïe par Allah, Glorifié et Exalté ; et convoiter ce que possèdent les gens en guettant l''occasion de le leur demander fait que ces gens détestent cette personne.',
  '• كان الصحابة رضي الله عنهم يحرصون دائماً على سؤال النبي صلى الله عليه وسلم عما ينفعهم.\n• الإنسان بطبيعته يحب أن يحبه الله سبحانه وتعالى وأن يحبه الناس، ويكره أن يبغضه الله أو يبغضه الناس.\n• من زهد في الدنيا أحبه الله، لأن ذلك يستلزم الرغبة فيما عند الآخرة.\n• الزهد فيما عند الناس يجلب محبتهم.\n• الرغبة فيما في الدنيا من ملذات ونعيم والتعلق بها يجعل المرء مبغوضاً عند الله سبحانه وتعالى؛ والطمع فيما عند الناس وترقّب الفرصة لسؤالهم يجعل الناس يبغضون هذا المرء.',
  '• Die Gefährten (möge Allah mit ihnen zufrieden sein) waren stets darum bemüht, den Propheten ﷺ nach dem zu fragen, was ihnen nützte.\n• Der Mensch liebt von Natur aus, dass Allah, der Gepriesene und Erhabene, ihn liebt und dass die Menschen ihn lieben; und er verabscheut, dass Allah ihm zürnt oder dass die Menschen ihn verabscheuen.\n• Wer in dieser Welt Genügsamkeit (Zuhd) übt, den wird Allah lieben, denn dies bringt notwendigerweise das Verlangen nach dem Jenseits mit sich.\n• Auf das zu verzichten, was die Menschen besitzen, erwirbt ihre Liebe.\n• Nach den Genüssen und Freuden dieser Welt zu trachten und an ihnen zu hängen, macht den Menschen Allah, dem Gepriesenen und Erhabenen, verhasst; und nach dem zu trachten, was die Menschen besitzen, und die Gelegenheit abzupassen, sie darum zu bitten, macht, dass jene Menschen diesen Menschen verabscheuen.',
  '• De metgezellen (moge Allah tevreden met hen zijn) trachtten altijd de Profeet ﷺ te vragen naar wat hun van nut was.\n• De mens houdt van nature ervan dat Allah, de Verheerlijkte en Verhevene, hem liefheeft en dat de mensen hem liefhebben; en hij verafschuwt dat Allah hem misnoegd is of dat de mensen hem verafschuwen.\n• Wie in deze wereld onthechting (zuhd) beoefent, die zal Allah liefhebben, want dit brengt noodzakelijkerwijs het verlangen naar het Hiernamaals met zich mee.\n• Afzien van wat de mensen bezitten, verwerft hun liefde.\n• Het begeren van de genietingen en geneugten van deze wereld en het zich eraan vastklampen, maakt de mens gehaat bij Allah, de Verheerlijkte en Verhevene; en het begeren van wat de mensen bezitten en het loeren op de gelegenheid om hen erom te vragen, maakt dat die mensen deze persoon verafschuwen.',
  '• Sahabe (Allah onlardan razı olsun), Peygamber''e ﷺ kendilerine faydalı olanı sormaya daima gayret ederlerdi.\n• İnsan, tabiatı gereği, Allah''ın (sübhânehû ve teâlâ) kendisini sevmesini ve insanların kendisini sevmesini ister; Allah''ın kendisine gazap etmesini yahut insanların kendisinden nefret etmesini sevmez.\n• Dünyaya karşı zâhid olanı Allah sever, çünkü bu, zorunlu olarak âhiretteki şeylere rağbeti gerektirir.\n• İnsanların elindekine karşı zâhid olmak, onların sevgisini kazandırır.\n• Dünyanın zevk ve nimetlerine rağbet edip onlara bağlanmak, kişiyi Allah''ın (sübhânehû ve teâlâ) nazarında sevilmeyen biri yapar; insanların elindekine tamah edip onlardan istemek için fırsat kollamak ise o insanların bu kişiden nefret etmesine yol açar.',
  '• Para sahabat (semoga Allah meridhai mereka) senantiasa bersemangat untuk menanyakan kepada Nabi ﷺ tentang apa yang bermanfaat bagi mereka.\n• Manusia secara tabiat mencintai agar Allah Subhanahu wa Taʿala mencintainya dan agar manusia mencintainya; dan ia membenci jika Allah murka kepadanya atau manusia membencinya.\n• Barangsiapa zuhud terhadap dunia, Allah akan mencintainya, karena hal itu mengharuskan adanya kecintaan terhadap apa yang ada di akhirat.\n• Zuhud terhadap apa yang ada pada manusia mendatangkan kecintaan mereka.\n• Menginginkan kenikmatan dan kelezatan dunia serta bergantung kepadanya menjadikan seseorang dibenci di sisi Allah Subhanahu wa Taʿala; dan menginginkan apa yang ada pada manusia serta menanti-nanti kesempatan untuk memintanya membuat manusia membenci orang tersebut.',
  '• صحابہ رضی اللہ عنہم ہمیشہ اس بات کے حریص رہتے تھے کہ نبی ﷺ سے وہ بات پوچھیں جو ان کے لیے نفع بخش ہو۔\n• انسان فطری طور پر چاہتا ہے کہ اللہ سبحانہ و تعالیٰ اس سے محبت کرے اور لوگ بھی اس سے محبت کریں؛ اور وہ ناپسند کرتا ہے کہ اللہ اس سے ناراض ہو یا لوگ اس سے نفرت کریں۔\n• جو دنیا سے بے رغبتی اختیار کرے اللہ اس سے محبت کرے گا، کیونکہ یہ لازمی طور پر آخرت کی چیزوں میں رغبت کا تقاضا کرتا ہے۔\n• لوگوں کے پاس جو کچھ ہے اس سے بے رغبتی ان کی محبت کھینچ لاتی ہے۔\n• دنیا کی لذتوں اور نعمتوں میں رغبت اور ان سے تعلق انسان کو اللہ سبحانہ و تعالیٰ کے نزدیک مبغوض بنا دیتا ہے؛ اور لوگوں کے پاس جو ہے اس کا لالچ اور ان سے مانگنے کے موقع کی تاک میں رہنا لوگوں کو اس شخص سے نفرت میں مبتلا کر دیتا ہے۔',
  '• সাহাবীগণ (রাদিয়াল্লাহু আনহুম) সর্বদা নবী ﷺ-এর কাছে তাদের জন্য উপকারী বিষয় জিজ্ঞাসা করতে আগ্রহী থাকতেন।\n• মানুষ স্বভাবগতভাবে চায় যে আল্লাহ সুবহানাহু ওয়া তাআলা তাকে ভালোবাসুন এবং মানুষও তাকে ভালোবাসুক; আর সে অপছন্দ করে যে আল্লাহ তার ওপর অসন্তুষ্ট হন বা মানুষ তাকে ঘৃণা করে।\n• যে দুনিয়ার প্রতি নিরাসক্ত হয় আল্লাহ তাকে ভালোবাসবেন, কারণ তা অবশ্যম্ভাবীভাবে আখিরাতের বিষয়ের প্রতি আগ্রহের দাবি করে।\n• মানুষের কাছে যা আছে তার প্রতি নিরাসক্তি তাদের ভালোবাসা এনে দেয়।\n• দুনিয়ার ভোগ-বিলাস ও সুখের প্রতি আগ্রহ ও তাতে আসক্তি মানুষকে আল্লাহ সুবহানাহু ওয়া তাআলার নিকট ঘৃণিত করে; আর মানুষের কাছে যা আছে তার লোভ ও তাদের কাছে চাওয়ার সুযোগের অপেক্ষায় থাকা মানুষকে সেই ব্যক্তির প্রতি ঘৃণায় লিপ্ত করে।',
  '• Para sahabat (semoga Allah meredai mereka) sentiasa bersungguh-sungguh untuk bertanya kepada Nabi ﷺ tentang apa yang bermanfaat bagi mereka.\n• Manusia secara tabiat mencintai agar Allah Subhanahu wa Taʿala mencintainya dan agar manusia mencintainya; dan dia membenci jika Allah murka kepadanya atau manusia membencinya.\n• Sesiapa yang zuhud terhadap dunia, Allah akan mencintainya, kerana hal itu mengharuskan adanya kecintaan terhadap apa yang ada di akhirat.\n• Zuhud terhadap apa yang ada pada manusia mendatangkan kecintaan mereka.\n• Menginginkan kenikmatan dan kelazatan dunia serta bergantung kepadanya menjadikan seseorang dibenci di sisi Allah Subhanahu wa Taʿala; dan menginginkan apa yang ada pada manusia serta menanti-nanti peluang untuk memintanya membuat manusia membenci orang tersebut.',
  '• Сподвижники (да будет доволен ими Аллах) всегда стремились спрашивать Пророка ﷺ о том, что приносило им пользу.\n• Человек по своей природе любит, чтобы Аллах, Пречистый и Всевышний, любил его и чтобы люди любили его; и он не любит, чтобы Аллах гневался на него или чтобы люди питали к нему неприязнь.\n• Кто проявляет воздержанность (зухд) в этом мире, того Аллах полюбит, ибо это с необходимостью влечёт стремление к тому, что в будущей жизни.\n• Отказ от того, что есть у людей, обретает их любовь.\n• Жажда наслаждений и услад этого мира и привязанность к ним делают человека ненавистным Аллаху, Пречистому и Всевышнему; а жажда того, что есть у людей, и подстерегание случая попросить у них этого приводят к тому, что эти люди питают к такому человеку неприязнь.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-31-Nawawi-Psalmodie-Arabe.mp3',
  5,
  31
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 31
);
