-- =============================================================================
-- 40 Hadith Nawawi — Hadith 30: "The rights and limits of Allah"
-- Target collection: public.hadith_collections.id = 2  /  position = 30
-- Idempotent guard on (collection, position). All 11 content languages.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'The limits and rights of Allah',
  'Les droits d''Allah sur nous',
  'حقوق الله تعالى',
  'Die Grenzen und Rechte Allahs',
  'De grenzen en rechten van Allah',
  'Allah''ın hakları ve sınırları',
  'Hak-hak dan batasan Allah',
  'اللہ کے حقوق اور حدود',
  'আল্লাহর অধিকার ও সীমারেখা',
  'Hak-hak dan batasan Allah',
  'Права и границы Аллаха',
  -- arabic_text
  'عَنْ أَبِي ثَعْلَبَةَ الْخُشَنِيِّ جُرْثُومِ بْنِ نَاشِرٍ رَضِيَ اللَّهُ عَنْهُ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ: «إِنَّ اللَّهَ تَعَالَى فَرَضَ فَرَائِضَ فَلَا تُضَيِّعُوهَا، وَحَدَّ حُدُودًا فَلَا تَعْتَدُوهَا، وَحَرَّمَ أَشْيَاءَ فَلَا تَنْتَهِكُوهَا، وَسَكَتَ عَنْ أَشْيَاءَ رَحْمَةً لَكُمْ غَيْرَ نِسْيَانٍ فَلَا تَبْحَثُوا عَنْهَا»',
  -- transcription
  'ʿan Abī Thaʿlabata l-Khushaniyyi Jurthūmi bni Nāshirin raḍiya Llāhu ʿanhu ʿan Rasūli Llāhi ṣalla Llāhu ʿalayhi wa-sallama qāla: inna Llāha taʿālā faraḍa farāʾiḍa fa-lā tuḍayyiʿūhā, wa-ḥadda ḥudūdan fa-lā taʿtadūhā, wa-ḥarrama ashyāʾa fa-lā tantahikūhā, wa-sakata ʿan ashyāʾa raḥmatan lakum ghayra nisyānin fa-lā tabḥathū ʿanhā.',
  'ʿan Abî Thaʿlabata l-Khouchaniyyi Jourthôumi bni Nâchirin (radia Llâhou ʿanhou) ʿan Rassôli Llâhi (salla Llâhou ʿalayhi wa sallam) qâla : inna Llâha taʿâlâ farada farâʾida fa-lâ toudayyiʿôuhâ, wa hadda houdôudan fa-lâ taʿtadôuhâ, wa harrama achyâʾa fa-lâ tantahikôuhâ, wa sakata ʿan achyâʾa rahmatan lakoum ghayra nisyânin fa-lâ tabhathô ʿanhâ.',
  'ʿan Abī Thaʿlabata l-Chuschanijji Dschurthūmi bni Nāschirin (radiya Llāhu ʿanhu) ʿan Rasūli Llāhi (salla Llāhu ʿalaihi wa-sallam) qāla: inna Llāha taʿālā farada farāʾida fa-lā tudajjiʿūhā, wa-hadda hudūdan fa-lā taʿtadūhā, wa-harrama aschjāʾa fa-lā tantahikūhā, wa-sakata ʿan aschjāʾa rahmatan lakum ghaira nisjānin fa-lā tabhathū ʿanhā.',
  'ʿan Abie Thaʿlabata l-Choesjanijji Dzjoerthoemi bni Naasjirin (radia Llaahoe ʿanhoe) ʿan Rasoeli Llaahi (salla Llaahoe ʿalaihi wa-sallam) qaala: inna Llaaha taʿaalaa farada faraaʾida fa-laa toedajjiʿoehaa, wa-hadda hoedoedan fa-laa taʿtadoehaa, wa-harrama asjjaaʾa fa-laa tantahikoehaa, wa-sakata ʿan asjjaaʾa rahmatan lakoem ghaira nisjaanin fa-laa tabhathoe ʿanhaa.',
  'an Ebû Saʿlebe el-Huşenî Cürsûm ibn Nâşir''den (radıyallâhu anh), Resûlullah''tan (s.a.v.) rivayetle buyurdu: şüphesiz Allah Teâlâ birtakım farzlar farz kıldı, onları zayi etmeyin; birtakım sınırlar koydu, onları aşmayın; birtakım şeyleri haram kıldı, onları çiğnemeyin; ve birtakım şeyler hakkında — unutarak değil, size rahmet olarak — sustu, onları araştırmayın.',
  'an Abi Tsaʿlabah al-Khusyani Jurtsum bin Nasyir (radhiyallahu ʿanhu), dari Rasulullah (shallallahu ʿalaihi wa sallam) bersabda: sesungguhnya Allah Taʿala telah mewajibkan beberapa kewajiban, maka janganlah kalian menyia-nyiakannya; menetapkan beberapa batasan, maka janganlah kalian melanggarnya; mengharamkan beberapa perkara, maka janganlah kalian melanggarnya; dan mendiamkan beberapa perkara sebagai rahmat bagi kalian — bukan karena lupa — maka janganlah kalian membahasnya.',
  'ابو ثعلبہ الخشنی جرثوم بن ناشر رضی اللہ عنہ سے، رسول اللہ صلی اللہ علیہ وسلم سے روایت ہے کہ آپ نے فرمایا: بے شک اللہ تعالیٰ نے کچھ فرائض فرض کیے ہیں، انہیں ضائع نہ کرو؛ کچھ حدیں مقرر کی ہیں، ان سے تجاوز نہ کرو؛ کچھ چیزیں حرام کی ہیں، ان کی حرمت کو نہ توڑو؛ اور کچھ چیزوں کے بارے میں تمہاری رحمت کے لیے خاموشی اختیار کی — بھول کر نہیں — پس ان کے بارے میں کرید نہ کرو۔',
  'আবু সালাবা আল-খুশানী জুরসূম ইবনে নাশির (রাদিয়াল্লাহু আনহু) থেকে, রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) থেকে বর্ণিত, তিনি বলেছেন: নিশ্চয়ই আল্লাহ তাআলা কিছু ফরজ নির্ধারণ করেছেন, সেগুলো নষ্ট করো না; কিছু সীমা নির্ধারণ করেছেন, সেগুলো লঙ্ঘন করো না; কিছু জিনিস হারাম করেছেন, সেগুলোর পবিত্রতা নষ্ট করো না; এবং কিছু বিষয়ে তোমাদের প্রতি রহমতস্বরূপ নীরব থেকেছেন — ভুলে নয় — সুতরাং সেগুলো নিয়ে অনুসন্ধান করো না।',
  'an Abi Tsaʿlabah al-Khusyani Jurtsum bin Nasyir (radhiallahu ʿanhu), daripada Rasulullah (sallallahu ʿalaihi wa sallam) bersabda: sesungguhnya Allah Taʿala telah mewajibkan beberapa kewajipan, maka janganlah kamu mensia-siakannya; menetapkan beberapa batasan, maka janganlah kamu melanggarnya; mengharamkan beberapa perkara, maka janganlah kamu mencerobohinya; dan mendiamkan beberapa perkara sebagai rahmat bagi kamu — bukan kerana lupa — maka janganlah kamu membahasnya.',
  'От Аби Саалабы аль-Хушани Джурсума ибн Нашира (да будет доволен им Аллах), от Посланника Аллаха ﷺ передаётся, что он сказал: поистине, Аллах Всевышний установил обязательные предписания — не пренебрегайте ими; определил границы — не преступайте их; запретил некоторые вещи — не нарушайте их запретность; и умолчал о некоторых вещах как милость к вам, не по забывчивости, — так не доискивайтесь же о них.',
  -- translation
  'On the authority of Abu Thaʿlaba al-Khushani Jurthum ibn Nashir (may Allah be pleased with him), the Messenger of Allah ﷺ said: "Indeed Allah, the Exalted, has ordained obligations, so do not neglect them; He has set limits, so do not transgress them; He has forbidden certain things, so do not violate them; and He has remained silent about certain things, as a mercy to you and not out of forgetfulness, so do not inquire into them."',
  'D''après Abû Thaʿlaba al-Khushanî Jurthûm ibn Nâshir (qu''Allah l''agrée), l''Envoyé d''Allah ﷺ a dit : « Certes, Allah le Très-Haut a imposé des préceptes, ne les laissez pas perdre ; Il a fixé des limites, ne les transgressez pas ; Il a interdit des choses, n''en violez pas le caractère illicite ; et Il s''est tu à propos d''autres choses par miséricorde envers vous, non par oubli, ne vous enquérez pas d''elles. »',
  'Nach Abu Thaʿlaba al-Khushani Jurthum ibn Nashir (möge Allah mit ihm zufrieden sein) sagte der Gesandte Allahs ﷺ: „Wahrlich, Allah, der Erhabene, hat Pflichten auferlegt, so vernachlässigt sie nicht; Er hat Grenzen gesetzt, so überschreitet sie nicht; Er hat gewisse Dinge verboten, so verletzt sie nicht; und Er hat über gewisse Dinge geschwiegen, aus Barmherzigkeit zu euch und nicht aus Vergesslichkeit, so forscht ihnen nicht nach."',
  'Op gezag van Abu Thaʿlaba al-Khushani Jurthum ibn Nashir (moge Allah tevreden met hem zijn) zei de Boodschapper van Allah ﷺ: „Voorwaar, Allah, de Verhevene, heeft verplichtingen opgelegd, verwaarloos ze dus niet; Hij heeft grenzen gesteld, overschrijd ze dus niet; Hij heeft bepaalde dingen verboden, schend ze dus niet; en Hij heeft over bepaalde dingen gezwegen, uit barmhartigheid jegens jullie en niet uit vergeetachtigheid, vraag er dus niet naar."',
  'Ebû Saʿlebe el-Huşenî Cürsûm ibn Nâşir''den (Allah ondan razı olsun) rivayet edildiğine göre Resûlullah ﷺ şöyle buyurdu: „Şüphesiz Allah Teâlâ birtakım farzlar farz kıldı, onları zayi etmeyin; birtakım sınırlar koydu, onları aşmayın; birtakım şeyleri haram kıldı, onları çiğnemeyin; ve birtakım şeyler hakkında — unutarak değil, size rahmet olarak — sustu, onları araştırmayın."',
  'Dari Abu Tsaʿlabah al-Khusyani Jurtsum bin Nasyir (semoga Allah meridhainya), Rasulullah ﷺ bersabda: "Sesungguhnya Allah Taʿala telah mewajibkan beberapa kewajiban, maka janganlah kalian menyia-nyiakannya; menetapkan beberapa batasan, maka janganlah kalian melanggarnya; mengharamkan beberapa perkara, maka janganlah kalian melanggarnya; dan mendiamkan beberapa perkara sebagai rahmat bagi kalian — bukan karena lupa — maka janganlah kalian membahasnya."',
  'ابو ثعلبہ الخشنی جرثوم بن ناشر رضی اللہ عنہ سے روایت ہے کہ رسول اللہ ﷺ نے فرمایا: ”بے شک اللہ تعالیٰ نے کچھ فرائض فرض کیے ہیں، انہیں ضائع نہ کرو؛ کچھ حدیں مقرر کی ہیں، ان سے تجاوز نہ کرو؛ کچھ چیزیں حرام کی ہیں، ان کی حرمت کو نہ توڑو؛ اور کچھ چیزوں کے بارے میں تمہاری رحمت کے لیے خاموشی اختیار کی — بھول کر نہیں — پس ان کے بارے میں کرید نہ کرو۔“',
  'আবু সালাবা আল-খুশানী জুরসূম ইবনে নাশির (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, রাসূলুল্লাহ ﷺ বলেছেন: "নিশ্চয়ই আল্লাহ তাআলা কিছু ফরজ নির্ধারণ করেছেন, সেগুলো নষ্ট করো না; কিছু সীমা নির্ধারণ করেছেন, সেগুলো লঙ্ঘন করো না; কিছু জিনিস হারাম করেছেন, সেগুলোর পবিত্রতা নষ্ট করো না; এবং কিছু বিষয়ে তোমাদের প্রতি রহমতস্বরূপ নীরব থেকেছেন — ভুলে নয় — সুতরাং সেগুলো নিয়ে অনুসন্ধান করো না।"',
  'Daripada Abu Tsaʿlabah al-Khusyani Jurtsum bin Nasyir (semoga Allah meredainya), Rasulullah ﷺ bersabda: "Sesungguhnya Allah Taʿala telah mewajibkan beberapa kewajipan, maka janganlah kamu mensia-siakannya; menetapkan beberapa batasan, maka janganlah kamu melanggarnya; mengharamkan beberapa perkara, maka janganlah kamu mencerobohinya; dan mendiamkan beberapa perkara sebagai rahmat bagi kamu — bukan kerana lupa — maka janganlah kamu membahasnya."',
  'Со слов Абу Саалабы аль-Хушани Джурсума ибн Нашира (да будет доволен им Аллах) Посланник Аллаха ﷺ сказал: «Поистине, Аллах Всевышний установил обязательные предписания — не пренебрегайте ими; определил границы — не преступайте их; запретил некоторые вещи — не нарушайте их запретность; и умолчал о некоторых вещах как милость к вам, не по забывчивости, — так не доискивайтесь же о них».',
  -- reference
  'Hasan — reported by al-Bayhaqi (10/13), al-Hakim (2/122), ad-Daraqutni, and others; graded hasan',
  'Hadith hasan rapporté par al-Bayhaqî (10/13), al-Hâkim (2/122), ad-Dâraqutnî et d''autres ; déclaré hasan',
  'حديث حسن، رواه البيهقي (١٠/١٣) والحاكم (٢/١٢٢) والدارقطني وغيرهم',
  'Hasan — überliefert von al-Bayhaqi (10/13), al-Hakim (2/122), ad-Daraqutni und anderen; als hasan eingestuft',
  'Hasan — overgeleverd door al-Bayhaqi (10/13), al-Hakim (2/122), ad-Daraqutni en anderen; als hasan beoordeeld',
  'Hasen — Beyhakî (10/13), Hâkim (2/122), Dârekutnî ve diğerleri rivayet etmiştir; hasen sayılmıştır',
  'Hadis hasan, diriwayatkan oleh al-Baihaqi (10/13), al-Hakim (2/122), ad-Daraquthni, dan lainnya; dinilai hasan',
  'حسن حدیث، اسے بیہقی (۱۰/۱۳)، حاکم (۲/۱۲۲)، دارقطنی وغیرہ نے روایت کیا؛ حسن قرار دیا گیا',
  'হাসান হাদীস — বায়হাকী (১০/১৩), হাকিম (২/১২২), দারাকুতনী প্রমুখ বর্ণনা করেছেন; হাসান বলা হয়েছে',
  'Hadis hasan, diriwayatkan oleh al-Baihaqi (10/13), al-Hakim (2/122), ad-Daraqutni, dan lain-lain; dinilai hasan',
  'Хороший (хасан) хадис, передали аль-Байхаки (10/13), аль-Хаким (2/122), ад-Даракутни и другие; назван хасаном',
  -- tafsir
  '• The excellent manner of the Messenger of Allah ﷺ in conveying this hadith with a clear, explicit classification.\n• Allah has prescribed for His servants formal obligations (faraʾid). These are of two kinds: the communal obligation (fard kifaya), which concerns the obligatory act regardless of who performs it — its ruling is that if some individuals carry it out, the sin of neglecting it does not fall upon the rest, such as the call to prayer (adhan), the iqama, and the funeral prayer; and the individual obligation (fard ʿayn) required of every person.\n• It is not permitted for a person to transgress the sacred limits of Allah, the Exalted. It follows from this lesson that it is not permitted to go to extremes in religion; this is why the Prophet ﷺ rebuked the three men who resolved to do so. One of them said: "As for me, I will pray all night, forever." Another said: "And I will fast continuously, all my life." The third said: "And I will never marry." The Prophet ﷺ rebuked them and said: "By Allah, I am the most fearful of Allah among you, yet I fast and break my fast, I pray part of the night and sleep part of it, and I marry women. Whoever turns away from my way (sunnah) is not of me."',
  '• La bonne manière de l''Envoyé d''Allah ﷺ en citant ce hadith avec une classification claire et explicite.\n• Allah a prescrit à Ses serviteurs des obligations formelles (farâʾid). Elles sont de deux sortes : l''obligation communautaire (fard kifâya), qui vise l''acte obligatoire indépendamment de son auteur — son statut est que si certains individus l''accomplissent, le péché d''y faillir ne frappe pas les autres, comme l''appel à la prière (adhân), l''iqâma et la prière mortuaire ; et l''obligation individuelle (fard ʿayn) requise de chaque homme.\n• Il n''est pas permis à l''homme de transgresser les limites sacrées d''Allah, le Très-Haut. Il s''ensuit qu''il n''est pas permis d''aller à l''extrême dans la religion ; c''est pourquoi le Prophète ﷺ a blâmé les trois hommes qui décidèrent d''agir ainsi. L''un dit : « Pour ma part, je m''engage à passer toutes mes nuits en prière, pour toujours. » L''autre dit : « Et moi, je m''engage à jeûner sans interruption toute ma vie. » Le dernier dit : « Et moi, je ne me marierai jamais. » Le Prophète ﷺ les réprimanda et dit : « Par Allah, je suis celui qui craint le plus Allah parmi vous, et pourtant je jeûne et je romps le jeûne, je prie une partie de la nuit et je dors une autre partie, et j''épouse les femmes. Celui qui se détourne de ma voie (sunna) n''est pas des miens. »',
  '• حسن أسلوب رسول الله صلى الله عليه وسلم في إيراد هذا الحديث بتقسيم واضح صريح.\n• فرض الله على عباده فرائض، وهي نوعان: فرض الكفاية، وهو ما قُصد فيه الفعل بغض النظر عن فاعله، وحكمه أنه إذا قام به بعض الناس سقط الإثم عن الباقين، كالأذان والإقامة وصلاة الجنازة؛ وفرض العين المطلوب من كل أحد.\n• لا يجوز للإنسان أن يتعدى حدود الله تعالى. ويُستفاد من هذا أنه لا يجوز الغلو في الدين، ولذلك أنكر النبي صلى الله عليه وسلم على الثلاثة الذين عزموا على ذلك. قال أحدهم: «أما أنا فأقوم الليل أبداً». وقال الآخر: «وأنا أصوم الدهر ولا أفطر». وقال الثالث: «وأنا لا أتزوج النساء أبداً». فأنكر عليهم النبي صلى الله عليه وسلم وقال: «والله إني لأخشاكم لله، لكني أصوم وأفطر، وأصلي وأرقد، وأتزوج النساء، فمن رغب عن سنتي فليس مني».',
  '• Die vortreffliche Art des Gesandten Allahs ﷺ, diesen Hadith mit einer klaren, deutlichen Einteilung vorzutragen.\n• Allah hat Seinen Dienern formale Pflichten (farāʾid) auferlegt. Diese sind zweierlei: die Gemeinschaftspflicht (Fard Kifaya), die die Pflichthandlung unabhängig vom Ausführenden betrifft — ihr Urteil ist, dass die Sünde des Unterlassens nicht auf die Übrigen fällt, wenn einige sie ausführen, wie der Gebetsruf (Adhan), die Iqama und das Totengebet; und die individuelle Pflicht (Fard ʿAin), die von jedem verlangt wird.\n• Es ist dem Menschen nicht erlaubt, die heiligen Grenzen Allahs zu überschreiten. Daraus folgt, dass Übertreibung in der Religion nicht erlaubt ist; deshalb tadelte der Prophet ﷺ die drei Männer, die dies beschlossen. Einer sagte: „Ich werde für immer die ganze Nacht beten." Ein anderer: „Und ich werde mein ganzes Leben ununterbrochen fasten." Der dritte: „Und ich werde nie heiraten." Der Prophet ﷺ tadelte sie und sagte: „Bei Allah, ich bin der Gottesfürchtigste von euch, doch ich faste und breche das Fasten, ich bete einen Teil der Nacht und schlafe einen Teil, und ich heirate Frauen. Wer sich von meinem Weg (Sunna) abwendet, gehört nicht zu mir."',
  '• De voortreffelijke wijze van de Boodschapper van Allah ﷺ om deze hadith met een heldere, duidelijke indeling over te brengen.\n• Allah heeft Zijn dienaren formele verplichtingen (farāʾid) opgelegd. Deze zijn van twee soorten: de gemeenschapsverplichting (fard kifaya), die de verplichte handeling betreft ongeacht wie haar verricht — haar oordeel is dat de zonde van nalatigheid niet op de overigen valt als sommigen haar verrichten, zoals de gebedsoproep (adhan), de iqama en het dodengebed; en de individuele verplichting (fard ʿayn) die van iedereen vereist is.\n• Het is de mens niet toegestaan de heilige grenzen van Allah te overschrijden. Hieruit volgt dat overdrijving in de religie niet is toegestaan; daarom berispte de Profeet ﷺ de drie mannen die dat besloten. Een zei: „Wat mij betreft, ik zal voor altijd de hele nacht bidden." Een ander: „En ik zal mijn hele leven onafgebroken vasten." De derde: „En ik zal nooit trouwen." De Profeet ﷺ berispte hen en zei: „Bij Allah, ik ben de meest godvrezende onder jullie, toch vast ik en verbreek ik het vasten, ik bid een deel van de nacht en slaap een deel, en ik trouw met vrouwen. Wie zich afkeert van mijn weg (soenna) behoort niet tot mij."',
  '• Resûlullah''ın ﷺ bu hadisi açık ve net bir tasnifle nakletmesindeki güzel üslup.\n• Allah kullarına farzlar farz kıldı; bunlar iki türlüdür: farz-ı kifâye, ki bunda failine bakılmaksızın fiilin kendisi kastedilir — hükmü şudur: bazı insanlar onu yerine getirirse, terkinin günahı diğerlerinden düşer; ezan, kamet ve cenaze namazı gibi. Ve herkesten istenen farz-ı ayn.\n• İnsanın Allah''ın sınırlarını aşması caiz değildir. Bundan, dinde aşırılığın (gulüv) câiz olmadığı anlaşılır; bu yüzden Peygamber ﷺ bunu yapmaya azmeden üç kişiyi kınamıştır. Biri: „Bana gelince, ben ebediyen bütün gece namaz kılacağım" dedi. Diğeri: „Ben de ömür boyu hiç ara vermeden oruç tutacağım" dedi. Üçüncüsü: „Ben de hiç evlenmeyeceğim" dedi. Peygamber ﷺ onları kınadı ve buyurdu: „Vallahi, ben aranızda Allah''tan en çok korkanınızım; ama hem oruç tutarım hem yerim, gecenin bir kısmında namaz kılar bir kısmında uyurum, ve kadınlarla evlenirim. Kim benim sünnetimden yüz çevirirse benden değildir."',
  '• Cara yang baik dari Rasulullah ﷺ dalam menyampaikan hadis ini dengan pembagian yang jelas dan tegas.\n• Allah telah mewajibkan atas hamba-hamba-Nya beberapa kewajiban (faraʾid). Ia ada dua jenis: fardhu kifayah, yaitu yang dimaksudkan padanya adalah perbuatannya tanpa memandang pelakunya — hukumnya, jika sebagian orang menunaikannya maka dosa meninggalkannya gugur dari yang lain, seperti azan, iqamah, dan shalat jenazah; dan fardhu ain yang dituntut dari setiap orang.\n• Tidak boleh bagi seseorang melampaui batasan-batasan Allah Taʿala. Dari sini dipahami bahwa tidak boleh berlebih-lebihan (ghuluw) dalam agama; karena itu Nabi ﷺ mengingkari tiga orang yang berazam melakukannya. Salah seorang berkata: "Adapun aku, aku akan shalat sepanjang malam selamanya." Yang lain berkata: "Dan aku akan berpuasa terus-menerus seumur hidup." Yang ketiga berkata: "Dan aku tidak akan pernah menikah." Nabi ﷺ mengingkari mereka dan bersabda: "Demi Allah, sesungguhnya aku adalah orang yang paling takut kepada Allah di antara kalian, tetapi aku berpuasa dan berbuka, aku shalat sebagian malam dan tidur sebagiannya, dan aku menikahi wanita. Barangsiapa membenci sunnahku, maka ia bukan dari golonganku."',
  '• رسول اللہ ﷺ کا اس حدیث کو واضح اور صریح تقسیم کے ساتھ بیان کرنے کا عمدہ اسلوب۔\n• اللہ نے اپنے بندوں پر کچھ فرائض فرض کیے ہیں، اور وہ دو قسم کے ہیں: فرضِ کفایہ، جس میں فاعل سے قطع نظر خود فعل مقصود ہوتا ہے — اس کا حکم یہ ہے کہ اگر کچھ لوگ اسے ادا کر دیں تو باقیوں سے گناہ ساقط ہو جاتا ہے، جیسے اذان، اقامت اور نمازِ جنازہ؛ اور فرضِ عین جو ہر ایک سے مطلوب ہے۔\n• انسان کے لیے اللہ تعالیٰ کی حدود سے تجاوز جائز نہیں۔ اس سے یہ سمجھ آتا ہے کہ دین میں غلو جائز نہیں؛ اسی لیے نبی ﷺ نے ان تین آدمیوں پر نکیر کی جنہوں نے ایسا عزم کیا۔ ایک نے کہا: ”میں تو ہمیشہ ساری رات نماز پڑھوں گا۔“ دوسرے نے کہا: ”اور میں زندگی بھر بلا ناغہ روزہ رکھوں گا۔“ تیسرے نے کہا: ”اور میں کبھی شادی نہیں کروں گا۔“ نبی ﷺ نے ان پر نکیر کی اور فرمایا: ”اللہ کی قسم! میں تم میں سب سے زیادہ اللہ سے ڈرنے والا ہوں، مگر میں روزہ بھی رکھتا ہوں اور افطار بھی کرتا ہوں، رات کا کچھ حصہ نماز پڑھتا ہوں اور کچھ سوتا ہوں، اور عورتوں سے نکاح کرتا ہوں۔ جو میری سنت سے منہ موڑے وہ مجھ سے نہیں۔“',
  '• রাসূলুল্লাহ ﷺ-এর এই হাদীস স্পষ্ট ও সুস্পষ্ট বিভাজনসহ বর্ণনা করার উত্তম পদ্ধতি।\n• আল্লাহ তাঁর বান্দাদের ওপর কিছু ফরজ নির্ধারণ করেছেন, আর তা দুই প্রকার: ফরজে কিফায়া, যাতে কর্তা নির্বিশেষে কাজটিই উদ্দেশ্য — এর বিধান হলো কিছু লোক তা আদায় করলে বাকিদের থেকে গুনাহ মাফ হয়ে যায়, যেমন আযান, ইকামত ও জানাযার সালাত; এবং ফরজে আইন যা প্রত্যেকের ওপর আবশ্যক।\n• মানুষের জন্য আল্লাহ তাআলার সীমা লঙ্ঘন করা জায়েজ নয়। এ থেকে বোঝা যায় যে দ্বীনে বাড়াবাড়ি (গুলুউ) জায়েজ নয়; এজন্যই নবী ﷺ সেই তিন ব্যক্তির ওপর আপত্তি করেছিলেন যারা এমন সংকল্প করেছিল। একজন বলল: "আমি তো সারা রাত চিরকাল সালাত পড়ব।" অন্যজন বলল: "আর আমি সারা জীবন বিরতিহীন সিয়াম পালন করব।" তৃতীয়জন বলল: "আর আমি কখনো বিবাহ করব না।" নবী ﷺ তাদের ওপর আপত্তি করলেন ও বললেন: "আল্লাহর কসম! আমি তোমাদের মধ্যে আল্লাহকে সবচেয়ে বেশি ভয় করি, তবু আমি সিয়াম পালন করি ও ইফতার করি, রাতের কিছু অংশ সালাত পড়ি ও কিছু অংশ ঘুমাই, এবং নারীদের বিবাহ করি। যে আমার সুন্নাহ থেকে মুখ ফিরিয়ে নেয় সে আমার নয়।"',
  '• Cara yang baik daripada Rasulullah ﷺ dalam menyampaikan hadis ini dengan pembahagian yang jelas dan tegas.\n• Allah telah mewajibkan ke atas hamba-hamba-Nya beberapa kewajipan (faraʾid). Ia ada dua jenis: fardu kifayah, iaitu yang dimaksudkan padanya ialah perbuatannya tanpa memandang pelakunya — hukumnya, jika sebahagian orang menunaikannya maka dosa meninggalkannya gugur daripada yang lain, seperti azan, iqamah, dan solat jenazah; dan fardu ain yang dituntut daripada setiap orang.\n• Tidak harus bagi seseorang melampaui batasan-batasan Allah Taʿala. Daripada sini difahami bahawa tidak harus berlebih-lebihan (ghuluw) dalam agama; kerana itu Nabi ﷺ mengingkari tiga orang yang berazam melakukannya. Salah seorang berkata: "Adapun aku, aku akan solat sepanjang malam selama-lamanya." Yang lain berkata: "Dan aku akan berpuasa terus-menerus seumur hidup." Yang ketiga berkata: "Dan aku tidak akan berkahwin." Nabi ﷺ mengingkari mereka dan bersabda: "Demi Allah, sesungguhnya aku ialah orang yang paling takut kepada Allah dalam kalangan kamu, tetapi aku berpuasa dan berbuka, aku solat sebahagian malam dan tidur sebahagiannya, dan aku berkahwin dengan wanita. Sesiapa yang membenci sunnahku, maka dia bukan daripada golonganku."',
  '• Прекрасная манера Посланника Аллаха ﷺ передавать этот хадис с ясной, чёткой классификацией.\n• Аллах вменил Своим рабам формальные обязанности (фараид). Они бывают двух видов: коллективная обязанность (фард кифая), которая касается обязательного действия независимо от исполнителя — её установление в том, что если некоторые её исполнят, грех за пренебрежение спадает с остальных, как призыв к молитве (азан), икама и заупокойная молитва; и индивидуальная обязанность (фард айн), требуемая от каждого.\n• Человеку не дозволено преступать священные границы Аллаха Всевышнего. Отсюда следует, что не дозволено впадать в крайности в религии; поэтому Пророк ﷺ порицал трёх мужчин, решивших так поступить. Один сказал: «Что до меня, я буду молиться всю ночь, всегда». Другой: «А я буду поститься непрерывно всю жизнь». Третий: «А я никогда не женюсь». Пророк ﷺ упрекнул их и сказал: «Клянусь Аллахом, я боюсь Аллаха больше всех вас, однако я и пощусь, и разговляюсь, молюсь часть ночи и сплю часть её, и женюсь на женщинах. Кто отвращается от моего пути (Сунны), тот не из меня».',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-30-Nawawi-Psalmodie-Arabe.mp3',
  5,
  30
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 30
);
