-- =============================================================================
-- 40 Hadith Nawawi — Hadith 10: "Allah is Pure and accepts only what is pure"
-- Target collection: public.hadith_collections.id = 2  /  position = 10
-- Idempotent guard on (collection, position). All 11 content languages.
-- NOTE: source paste contained Hadith 9's Arabic by mistake; the correct
-- standard Arabic for Hadith 10 (إن الله طيب لا يقبل إلا طيباً...) is used here.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Lawful, pure earnings and answered supplication',
  'Le gain licite, cause d''exaucement des invocations',
  'الاقتصار على الحلال الطيب',
  'Reiner, erlaubter Erwerb und das erhörte Bittgebet',
  'Reine, toegestane verdiensten en verhoring',
  'Helal ve temiz kazanç, duanın kabulü',
  'Rezeki halal lagi baik dan terkabulnya doa',
  'پاکیزہ حلال کمائی اور قبولیتِ دعا',
  'হালাল পবিত্র উপার্জন ও দোয়া কবুল',
  'Rezeki halal lagi baik dan termakbulnya doa',
  'Дозволенный, чистый заработок и принятие мольбы',
  -- arabic_text (correct standard text for Hadith 10)
  'عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللَّهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «إِنَّ اللَّهَ تَعَالَى طَيِّبٌ لَا يَقْبَلُ إِلَّا طَيِّبًا، وَإِنَّ اللَّهَ أَمَرَ الْمُؤْمِنِينَ بِمَا أَمَرَ بِهِ الْمُرْسَلِينَ، فَقَالَ تَعَالَى: ﴿يَا أَيُّهَا الرُّسُلُ كُلُوا مِنَ الطَّيِّبَاتِ وَاعْمَلُوا صَالِحًا﴾، وَقَالَ تَعَالَى: ﴿يَا أَيُّهَا الَّذِينَ آمَنُوا كُلُوا مِنْ طَيِّبَاتِ مَا رَزَقْنَاكُمْ﴾، ثُمَّ ذَكَرَ الرَّجُلَ يُطِيلُ السَّفَرَ أَشْعَثَ أَغْبَرَ يَمُدُّ يَدَيْهِ إِلَى السَّمَاءِ: يَا رَبِّ يَا رَبِّ، وَمَطْعَمُهُ حَرَامٌ، وَمَشْرَبُهُ حَرَامٌ، وَمَلْبَسُهُ حَرَامٌ، وَغُذِيَ بِالْحَرَامِ، فَأَنَّى يُسْتَجَابُ لِذَلِكَ؟»',
  -- transcription
  'ʿan Abī Hurayrata raḍiya Llāhu ʿanhu qāla: qāla Rasūlu Llāhi ṣalla Llāhu ʿalayhi wa-sallama: inna Llāha taʿālā ṭayyibun lā yaqbalu illā ṭayyiban, wa-inna Llāha amara l-muʾminīna bimā amara bihi l-mursalīna, fa-qāla taʿālā: yā ayyuha r-rusulu kulū mina ṭ-ṭayyibāti wa-ʿmalū ṣāliḥan, wa-qāla taʿālā: yā ayyuha lladhīna āmanū kulū min ṭayyibāti mā razaqnākum, thumma dhakara r-rajula yuṭīlu s-safara ashʿatha aghbara yamuddu yadayhi ila s-samāʾi: yā Rabbi yā Rabbi, wa-maṭʿamuhu ḥarāmun, wa-mashrabuhu ḥarāmun, wa-malbasuhu ḥarāmun, wa-ghudhiya bi-l-ḥarāmi, fa-annā yustajābu li-dhālik?',
  'ʿan Abî Hourayrata (radia Llâhou ʿanhou) qâla : qâla Rassôlou Llâhi (salla Llâhou ʿalayhi wa sallam) : inna Llâha taʿâlâ tayyiboun lâ yaqbalou illâ tayyiban, wa inna Llâha amara l-mouʾminîna bimâ amara bihi l-moursalîna, fa-qâla taʿâlâ : yâ ayyouha r-roussoulou koulô mina t-tayyibâti wa ʿmalô sâlihan, wa qâla taʿâlâ : yâ ayyouha lladhîna âmanô koulô min tayyibâti mâ razaqnâkoum, thoumma dhakara r-rajoula youtîlou s-safara achʿatha aghbara yamouddou yadayhi ila s-samâʾi : yâ Rabbi yâ Rabbi, wa matʿamouhou harâmoun, wa machrabouhou harâmoun, wa malbasouhou harâmoun, wa ghoudhiya bi-l-harâmi, fa-annâ youstajâbou li-dhâlik ?',
  'ʿan Abī Hurairata (radiya Llāhu ʿanhu) qāla: qāla Rasūlu Llāhi (salla Llāhu ʿalaihi wa-sallam): inna Llāha taʿālā tajjibun lā jaqbalu illā tajjiban, wa-inna Llāha amara l-muʾminīna bimā amara bihi l-mursalīna, fa-qāla taʿālā: jā ajjuha r-rusulu kulū mina t-tajjibāti wa-ʿmalū sālihan, wa-qāla taʿālā: jā ajjuha lladhīna āmanū kulū min tajjibāti mā razaqnākum, thumma dhakara r-radschula jutīlu s-safara aschʿatha aghbara jamuddu jadaihi ila s-samāʾi: jā Rabbi jā Rabbi, wa-matʿamuhu harāmun, wa-maschrabuhu harāmun, wa-malbasuhu harāmun, wa-ghudhija bi-l-harāmi, fa-annā justadschābu li-dhālik?',
  'ʿan Abie Hoerairata (radia Llaahoe ʿanhoe) qaala: qaala Rasoeloe Llaahi (salla Llaahoe ʿalaihi wa-sallam): inna Llaaha taʿaalaa tajjiboen laa jaqbaloe illaa tajjiban, wa-inna Llaaha amara l-moeʾminiena bimaa amara bihi l-moersaliena, fa-qaala taʿaalaa: jaa ajjoeha r-roesoeloe koeloe mina t-tajjibaati wa-ʿmaloe saalihan, wa-qaala taʿaalaa: jaa ajjoeha lladhiena aamanoe koeloe min tajjibaati maa razaqnaakoem, thoemma dhakara r-radzjoela joetieloe s-safara asjʿatha aghbara jamoeddoe jadaihi ila s-samaaʾi: jaa Rabbi jaa Rabbi, wa-matʿamoehoe haraamoen, wa-masjraboehoe haraamoen, wa-malbasoehoe haraamoen, wa-ghoedhija bi-l-haraami, fa-annaa joestadzjaaboe li-dhaalik?',
  'an Ebû Hüreyre''den (radıyallâhu anh) rivayetle dedi ki: Resûlullah (s.a.v.) şöyle buyurdu: inna''llâhe teʿâlâ tayyibun lâ yakbelu illâ tayyiben, ve inna''llâhe emera''l-muʾminîne bimâ emera bihi''l-murselîne, fe-kâle teʿâlâ: yâ eyyuhe''r-rusulu kulû mine''t-tayyibâti va''melû sâlihan, ve kâle teʿâlâ: yâ eyyuhe''llezîne âmenû kulû min tayyibâti mâ razaknâkum, summe zekere''r-racule yutîlu''s-sefere eşʿase agbera yemuddu yedeyhi ile''s-semâi: yâ Rabbi yâ Rabbi, ve matʿamuhu harâmun, ve meşrabuhu harâmun, ve melbesuhu harâmun, ve guziye bi''l-harâmi, fe-ennâ yustecâbu li-zâlik?',
  'ʿan Abī Hurairah (radhiyallāhu ʿanhu) berkata: Rasulullah (shallallāhu ʿalaihi wa sallam) bersabda: innallāha taʿālā thayyibun lā yaqbalu illā thayyiban, wa innallāha amaral-muʾminīna bimā amara bihil-mursalīna, faqāla taʿālā: yā ayyuhar-rusulu kulū minath-thayyibāti waʿmalū shālihan, wa qāla taʿālā: yā ayyuhalladzīna āmanū kulū min thayyibāti mā razaqnākum, tsumma dzakarar-rajula yuthīlus-safara asyʿatsa aghbara yamuddu yadaihi ilas-samāʾi: yā Rabbi yā Rabbi, wa mathʿamuhu harāmun, wa masyrabuhu harāmun, wa malbasuhu harāmun, wa ghudziya bil-harāmi, fa-annā yustajābu li-dzālik?',
  'ابو ہریرہ رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: اِنَّ اللہَ تَعالٰی طَیِّبٌ لا یَقبَلُ اِلَّا طَیِّبًا، وَاِنَّ اللہَ اَمَرَ المُؤمِنِینَ بِما اَمَرَ بِہِ المُرسَلِینَ، فَقالَ تَعالٰی: ﴿یا اَیُّہَا الرُّسُلُ کُلُوا مِنَ الطَّیِّباتِ وَاعمَلُوا صالِحًا﴾، وَقالَ تَعالٰی: ﴿یا اَیُّہَا الَّذِینَ آمَنُوا کُلُوا مِن طَیِّباتِ ما رَزَقناکُم﴾، ثُمَّ ذَکَرَ الرَّجُلَ یُطِیلُ السَّفَرَ اَشعَثَ اَغبَرَ یَمُدُّ یَدَیہِ اِلَی السَّماءِ: یا رَبِّ یا رَبِّ، وَمَطعَمُہُ حَرامٌ، وَمَشرَبُہُ حَرامٌ، وَمَلبَسُہُ حَرامٌ، وَغُذِیَ بِالحَرامِ، فَاَنّٰی یُستَجابُ لِذٰلِکَ؟',
  'আবু হুরায়রা (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) বলেছেন: ইন্নাল্লাহা তাআলা তাইয়িবুন লা ইয়াকবালু ইল্লা তাইয়িবা, ওয়া ইন্নাল্লাহা আমারাল মুমিনীনা বিমা আমারা বিহিল মুরসালীনা, ফাকালা তাআলা: ﴿ইয়া আইয়ুহার রুসুলু কুলূ মিনাত তাইয়িবাতি ওয়াʿমালূ সালিহা﴾, ওয়া কালা তাআলা: ﴿ইয়া আইয়ুহাল্লাযীনা আমানূ কুলূ মিন তাইয়িবাতি মা রাযাকনাকুম﴾, সুম্মা যাকারার রাজুলা ইউতীলুস সাফারা আশআসা আগবারা ইয়ামুদ্দু ইয়াদাইহি ইলাস সামাই: ইয়া রাব্বি ইয়া রাব্বি, ওয়া মাতআমুহু হারাম, ওয়া মাশরাবুহু হারাম, ওয়া মালবাসুহু হারাম, ওয়া গুযিয়া বিল হারাম, ফাআন্না ইউসতাজাবু লিযালিক?',
  'ʿan Abī Hurairah (radhiallāhu ʿanhu) berkata: Rasulullah (sallallāhu ʿalaihi wa sallam) bersabda: innallāha taʿālā tayyibun lā yaqbalu illā tayyiban, wa innallāha amaral-muʾminīna bimā amara bihil-mursalīna, faqāla taʿālā: yā ayyuhar-rusulu kulū minat-tayyibāti waʿmalū solihan, wa qāla taʿālā: yā ayyuhalladzīna āmanū kulū min tayyibāti mā razaqnākum, tsumma dzakarar-rajula yutīlus-safara asyʿatsa aghbara yamuddu yadaihi ilas-samāʾi: yā Rabbi yā Rabbi, wa matʿamuhu harāmun, wa masyrabuhu harāmun, wa malbasuhu harāmun, wa ghudziya bil-harāmi, fa-annā yustajābu li-dzālik?',
  'Ан Аби Хурайра (да будет доволен им Аллах) сказал: сказал Посланник Аллаха ﷺ: инна Ллаха таʿаля таййибун ля яқбалу илля таййиба, ва инна Ллаха амараль-муʾминина бима амара бихиль-мурсалина, фа-каля таʿаля: я аййуха р-русулу кулю мина т-таййибати ва-ʿмалю салиха, ва каля таʿаля: я аййуха ллязина аману кулю мин таййибати ма разакнакум, сумма закара р-раджуля ютилю с-сафара ашʿаса агбара ямудду ядайхи иля с-самаʾи: я Рабби я Рабби, ва матʿамуху харам, ва машрабуху харам, ва малбасуху харам, ва гузия биль-харам, фа-анна юстаджабу ли-залик?',
  -- translation
  'On the authority of Abu Hurayra (may Allah be pleased with him), the Messenger of Allah ﷺ said: "Indeed Allah, the Exalted, is Pure (Tayyib) and accepts only what is pure. Allah has commanded the believers with what He commanded the messengers, saying: {O messengers, eat of the good things and do righteousness} (23:51), and saying: {O you who believe, eat of the good things We have provided you} (2:172)." Then he mentioned a man who undertakes a long journey, dishevelled and dusty, stretching his hands to the sky: "O Lord, O Lord!" — while his food is unlawful, his drink is unlawful, his clothing is unlawful, and he is nourished by the unlawful. "So how could he be answered?"',
  'D''après Abû Hurayra (qu''Allah l''agrée), l''Envoyé d''Allah ﷺ a dit : « Certes Allah, le Très-Haut, est Pur (Tayyib) et n''accepte que ce qui est pur. Allah a ordonné aux croyants ce qu''Il a ordonné aux Envoyés, en disant : {Ô Messagers ! Mangez des bonnes choses et faites le bien} (23:51), et : {Ô vous qui croyez ! Mangez des bonnes choses que Nous vous avons attribuées} (2:172). » Puis il évoqua l''homme qui prolonge un voyage, échevelé et poussiéreux, tendant les mains vers le ciel : « Ô Seigneur, ô Seigneur ! » — alors que sa nourriture est illicite, sa boisson illicite, son vêtement illicite, et qu''il a été nourri d''illicite. « Comment donc pourrait-il être exaucé ? »',
  'Nach Abu Hurayra (möge Allah mit ihm zufrieden sein) sagte der Gesandte Allahs ﷺ: „Wahrlich, Allah, der Erhabene, ist rein (Tayyib) und nimmt nur das Reine an. Allah hat den Gläubigen geboten, was Er den Gesandten geboten hat, indem Er sprach: {O ihr Gesandten, esst von den guten Dingen und handelt rechtschaffen} (23:51), und: {O ihr, die ihr glaubt, esst von den guten Dingen, mit denen Wir euch versorgt haben} (2:172)." Dann erwähnte er einen Mann, der eine lange Reise unternimmt, zerzaust und staubig, der seine Hände zum Himmel ausstreckt: „O Herr, o Herr!" — während seine Speise verboten, sein Trank verboten, seine Kleidung verboten ist und er mit Verbotenem genährt wurde. „Wie sollte ihm da erhört werden?"',
  'Op gezag van Abu Hurayra (moge Allah tevreden met hem zijn) zei de Boodschapper van Allah ﷺ: „Voorwaar, Allah, de Verhevene, is rein (Tayyib) en aanvaardt slechts het reine. Allah heeft de gelovigen geboden wat Hij de boodschappers heeft geboden, door te zeggen: {O boodschappers, eet van de goede dingen en doe het goede} (23:51), en: {O jullie die geloven, eet van de goede dingen waarmee Wij jullie hebben voorzien} (2:172)." Toen noemde hij een man die een lange reis onderneemt, verward en stoffig, zijn handen ten hemel heffend: „O Heer, o Heer!" — terwijl zijn voedsel verboden is, zijn drank verboden, zijn kleding verboden, en hij met het verbodene is gevoed. „Hoe zou hem dan verhoord worden?"',
  'Ebû Hüreyre''den (Allah ondan razı olsun) rivayet edildiğine göre Resûlullah ﷺ şöyle buyurdu: „Şüphesiz Allah Teâlâ temizdir (Tayyib), ancak temiz olanı kabul eder. Allah, müminlere de peygamberlere emrettiğini emretmiş ve şöyle buyurmuştur: {Ey peygamberler! Temiz şeylerden yiyin ve sâlih amel işleyin} (23:51); ve şöyle buyurmuştur: {Ey iman edenler! Size verdiğimiz rızıkların temiz olanlarından yiyin} (2:172)." Sonra uzun yolculuğa çıkan, saçı başı dağınık, toza bulanmış, ellerini göğe açıp „Yâ Rabbi, yâ Rabbi!" diyen bir adamı andı — oysa yediği haram, içtiği haram, giydiği haram ve haramla beslenmiştir. „Böyle birine nasıl icabet edilsin?"',
  'Dari Abu Hurairah (semoga Allah meridhainya), Rasulullah ﷺ bersabda: "Sesungguhnya Allah Taʿala itu baik (Thayyib) dan tidak menerima kecuali yang baik. Allah memerintahkan kaum mukminin dengan apa yang Dia perintahkan kepada para rasul, Dia berfirman: {Wahai para rasul, makanlah dari makanan yang baik-baik dan kerjakanlah amal saleh} (23:51), dan berfirman: {Wahai orang-orang yang beriman, makanlah dari rezeki yang baik-baik yang Kami berikan kepadamu} (2:172)." Kemudian beliau menyebutkan seorang lelaki yang menempuh perjalanan jauh, kusut dan berdebu, menengadahkan kedua tangannya ke langit: "Wahai Rabb, wahai Rabb!" — sedangkan makanannya haram, minumannya haram, pakaiannya haram, dan ia diberi makan dari yang haram. "Maka bagaimana mungkin doanya dikabulkan?"',
  'ابو ہریرہ رضی اللہ عنہ سے روایت ہے کہ رسول اللہ ﷺ نے فرمایا: ”بے شک اللہ تعالیٰ پاک ہے اور پاک کے سوا کچھ قبول نہیں کرتا۔ اور اللہ نے مومنوں کو وہی حکم دیا ہے جو رسولوں کو دیا، چنانچہ فرمایا: ﴿اے رسولو! پاکیزہ چیزوں میں سے کھاؤ اور نیک عمل کرو﴾ (۲۳:۵۱)، اور فرمایا: ﴿اے ایمان والو! ہماری دی ہوئی پاکیزہ چیزوں میں سے کھاؤ﴾ (۲:۱۷۲)۔“ پھر آپ نے اس شخص کا ذکر کیا جو لمبا سفر کرتا ہے، پراگندہ بال، غبار آلود، اپنے ہاتھ آسمان کی طرف پھیلا کر کہتا ہے: ”اے رب! اے رب!“ — حالانکہ اس کا کھانا حرام، اس کا پینا حرام، اس کا لباس حرام ہے اور اس کی پرورش حرام سے ہوئی۔ ”تو ایسے شخص کی دعا کیسے قبول ہو؟“',
  'আবু হুরায়রা (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, রাসূলুল্লাহ ﷺ বলেছেন: "নিশ্চয়ই আল্লাহ তাআলা পবিত্র (তাইয়িব), তিনি পবিত্র ছাড়া কিছু গ্রহণ করেন না। আল্লাহ মুমিনদের সেই আদেশ দিয়েছেন যা তিনি রাসূলগণকে দিয়েছেন, তিনি বলেছেন: ﴿হে রাসূলগণ! পবিত্র বস্তু থেকে আহার করো এবং সৎকর্ম করো﴾ (২৩:৫১), আর বলেছেন: ﴿হে ঈমানদারগণ! আমি তোমাদের যে পবিত্র রিজিক দিয়েছি তা থেকে আহার করো﴾ (২:১৭২)।" অতঃপর তিনি এমন এক ব্যক্তির কথা উল্লেখ করলেন যে দীর্ঘ সফর করে, এলোমেলো চুল ও ধুলোমলিন অবস্থায় আকাশের দিকে দুই হাত প্রসারিত করে বলে: "হে রব! হে রব!" — অথচ তার খাদ্য হারাম, তার পানীয় হারাম, তার পোশাক হারাম এবং সে হারাম দিয়ে প্রতিপালিত। "তাহলে কীভাবে তার দোয়া কবুল হবে?"',
  'Daripada Abu Hurairah (semoga Allah meredainya), Rasulullah ﷺ bersabda: "Sesungguhnya Allah Taʿala itu baik (Tayyib) dan tidak menerima melainkan yang baik. Allah memerintahkan orang-orang beriman dengan apa yang Dia perintahkan kepada para rasul, Dia berfirman: {Wahai para rasul, makanlah daripada makanan yang baik-baik dan kerjakanlah amal soleh} (23:51), dan berfirman: {Wahai orang-orang yang beriman, makanlah daripada rezeki yang baik-baik yang Kami kurniakan kepada kamu} (2:172)." Kemudian baginda menyebut seorang lelaki yang menempuh perjalanan jauh, kusut dan berdebu, menadahkan kedua-dua tangannya ke langit: "Wahai Tuhan, wahai Tuhan!" — sedangkan makanannya haram, minumannya haram, pakaiannya haram, dan dia diberi makan daripada yang haram. "Maka bagaimanakah doanya hendak dimakbulkan?"',
  'Со слов Абу Хурайры (да будет доволен им Аллах) Посланник Аллаха ﷺ сказал: «Поистине, Аллах Всевышний — Чист (Таййиб) и принимает только чистое. Аллах повелел верующим то же, что повелел посланникам, сказав: {О посланники! Вкушайте благое и творите праведное} (23:51), и сказав: {О те, которые уверовали! Вкушайте из тех благ, которыми Мы вас наделили} (2:172)». Затем он упомянул человека, который совершает долгое путешествие, растрёпанный и запылённый, простирая руки к небу: «О Господь, о Господь!» — тогда как его пища запретна, его питьё запретно, его одежда запретна, и вскормлен он запретным. «Так как же будет отвечено такому?»',
  -- reference
  'Sahih — reported by Muslim (no. 1015) and at-Tirmidhi (no. 2989)',
  'Hadith authentique rapporté par Muslim (n°1015) et at-Tirmidhî (n°2989)',
  'حديث صحيح، رواه مسلم (رقم ١٠١٥) والترمذي (رقم ٢٩٨٩)',
  'Sahih — überliefert von Muslim (Nr. 1015) und at-Tirmidhi (Nr. 2989)',
  'Sahih — overgeleverd door Muslim (nr. 1015) en at-Tirmidhi (nr. 2989)',
  'Sahih — Müslim (no. 1015) ve Tirmizî (no. 2989) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 1015) dan at-Tirmidzi (no. 2989)',
  'صحیح حدیث، اسے مسلم (نمبر ۱۰۱۵) اور ترمذی (نمبر ۲۹۸۹) نے روایت کیا',
  'সহীহ হাদীস — মুসলিম (নং ১০১৫) ও তিরমিযী (নং ২৯৮৯) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 1015) dan at-Tirmizi (no. 2989)',
  'Достоверный хадис, передали Муслим (№ 1015) и ат-Тирмизи (№ 2989)',
  -- tafsir
  '"Allah, the Exalted, is good (Tayyib) and accepts only what is good": Allah is good in His essence, good in His attributes, good in His acts. He accepts only what is good in its nature and good in the means of its acquisition. As for what is foul (khabith) in its nature, like wine, or foul in its means of acquisition, like what is gained through usury (riba), Allah the Exalted does not accept it.\n"Allah commanded the believers with what He commanded the messengers, saying (regarding the messengers): {O messengers, eat of the good things and do righteousness}": the command Allah addressed to the messengers and His command to the believers are the same — to eat of the good things. As for foul things, they are unlawful for them; the Exalted said regarding His Messenger: {…he makes lawful for them the good things and forbids them the foul things} (7:157).',
  '« Allah, le Très-Haut, est bon (Tayyib) et n''accepte que ce qui est bon » : Allah est bon dans Son essence, bon dans Ses attributs, bon dans Ses actes. Il n''accepte que ce qui est bon par nature et bon par le moyen de son acquisition. Quant à ce qui est pernicieux (khabîth) par nature, comme le vin, ou pernicieux par le moyen d''acquisition, comme ce qui est acquis par l''usure (ribâ), Allah exalté ne l''accepte pas.\n« Allah a ordonné aux croyants ce qu''Il a ordonné aux Envoyés, en disant (au sujet des Envoyés) : {Ô Envoyés ! Mangez des bonnes choses et œuvrez salutairement} » : l''ordre adressé par Allah aux Envoyés et Son ordre adressé aux croyants sont le même : manger des bonnes choses. Quant aux choses pernicieuses, elles leur sont illicites ; le Très-Haut a dit au sujet de Son Envoyé : {…Il leur rend licites les bonnes choses et illicites les pernicieuses} (7:157).',
  '«إن الله تعالى طيب لا يقبل إلا طيباً»: فالله طيب في ذاته، طيب في صفاته، طيب في أفعاله، ولا يقبل إلا ما كان طيباً في نفسه وطيباً في طريق اكتسابه. وأما الخبيث في نفسه كالخمر، أو الخبيث في طريق اكتسابه كالمكتسب بالربا، فإن الله تعالى لا يقبله.\n«وإن الله أمر المؤمنين بما أمر به المرسلين، فقال في حق المرسلين: {يا أيها الرسل كلوا من الطيبات واعملوا صالحاً}»: فالأمر الموجه من الله للرسل وأمره للمؤمنين واحد: وهو الأكل من الطيبات. وأما الخبائث فهي محرمة عليهم، فقد قال تعالى في حق رسوله: {ويحل لهم الطيبات ويحرم عليهم الخبائث}.',
  '„Allah, der Erhabene, ist gut (Tayyib) und nimmt nur das Gute an": Allah ist gut in Seinem Wesen, gut in Seinen Eigenschaften, gut in Seinen Handlungen. Er nimmt nur das an, was gut in seiner Natur und gut in der Art seines Erwerbs ist. Was hingegen von Natur aus schlecht (khabith) ist, wie der Wein, oder schlecht in der Art des Erwerbs, wie das durch Wucher (Riba) Erworbene, das nimmt Allah der Erhabene nicht an.\n„Allah gebot den Gläubigen, was Er den Gesandten gebot, indem Er (über die Gesandten) sprach: {O ihr Gesandten, esst von den guten Dingen und handelt rechtschaffen}": Das Gebot Allahs an die Gesandten und Sein Gebot an die Gläubigen sind dasselbe — von den guten Dingen zu essen. Die schlechten Dinge aber sind ihnen verboten; der Erhabene sprach über Seinen Gesandten: {…er erlaubt ihnen die guten Dinge und verbietet ihnen die schlechten} (7:157).',
  '„Allah, de Verhevene, is goed (Tayyib) en aanvaardt slechts het goede": Allah is goed in Zijn essentie, goed in Zijn eigenschappen, goed in Zijn handelingen. Hij aanvaardt slechts wat goed is van aard en goed is in de wijze van verwerving. Wat echter van nature slecht (khabith) is, zoals wijn, of slecht in de wijze van verwerving, zoals wat door woeker (riba) verkregen wordt, dat aanvaardt Allah de Verhevene niet.\n„Allah gebood de gelovigen wat Hij de boodschappers gebood, door (over de boodschappers) te zeggen: {O boodschappers, eet van de goede dingen en doe het goede}": het gebod dat Allah tot de boodschappers richtte en Zijn gebod tot de gelovigen zijn hetzelfde — eten van de goede dingen. De slechte dingen echter zijn hun verboden; de Verhevene zei over Zijn Boodschapper: {…hij staat hun de goede dingen toe en verbiedt hun de slechte} (7:157).',
  '„Allah Teâlâ temizdir (Tayyib), ancak temizi kabul eder": Allah zâtında temizdir, sıfatlarında temizdir, fiillerinde temizdir; ancak özünde temiz ve elde ediliş yolu temiz olanı kabul eder. Özünde pis (habîs) olan şaraba ya da elde ediliş yolu pis olan, faiz (ribâ) ile kazanılan şeye gelince, Yüce Allah onu kabul etmez.\n„Allah, müminlere de peygamberlere emrettiğini emretmiş ve peygamberler hakkında şöyle buyurmuştur: {Ey peygamberler! Temiz şeylerden yiyin ve sâlih amel işleyin}": Allah''ın peygamberlere yönelttiği emir ile müminlere yönelttiği emir aynıdır: temiz şeylerden yemek. Pis şeyler ise onlara haramdır; Yüce Allah, Resûlü hakkında şöyle buyurmuştur: {…temiz şeyleri onlara helal, pis şeyleri haram kılar} (7:157).',
  '"Allah Taʿala itu baik (Thayyib) dan tidak menerima kecuali yang baik": Allah baik pada zat-Nya, baik pada sifat-sifat-Nya, baik pada perbuatan-perbuatan-Nya. Dia tidak menerima kecuali yang baik pada zatnya dan baik pada cara memperolehnya. Adapun yang buruk (khabits) pada zatnya seperti khamar, atau buruk pada cara memperolehnya seperti yang diperoleh dengan riba, maka Allah Taʿala tidak menerimanya.\n"Allah memerintahkan kaum mukminin dengan apa yang Dia perintahkan kepada para rasul, Dia berfirman tentang para rasul: {Wahai para rasul, makanlah dari makanan yang baik-baik dan kerjakanlah amal saleh}": perintah Allah kepada para rasul dan perintah-Nya kepada kaum mukminin adalah sama: yaitu makan dari yang baik-baik. Adapun yang buruk, ia haram bagi mereka; Allah Taʿala berfirman tentang Rasul-Nya: {…dan menghalalkan bagi mereka yang baik-baik dan mengharamkan bagi mereka yang buruk-buruk} (7:157).',
  '”اللہ تعالیٰ پاک ہے اور پاک کے سوا کچھ قبول نہیں کرتا“: اللہ اپنی ذات میں پاک ہے، اپنی صفات میں پاک ہے، اپنے افعال میں پاک ہے؛ وہ صرف اسی چیز کو قبول کرتا ہے جو اپنی ذات میں پاک ہو اور جس کے حصول کا ذریعہ بھی پاک ہو۔ رہی وہ چیز جو اپنی ذات میں خبیث ہو جیسے شراب، یا جس کے حصول کا ذریعہ خبیث ہو جیسے سود سے کمائی ہوئی، تو اللہ تعالیٰ اسے قبول نہیں کرتا۔\n”اللہ نے مومنوں کو وہی حکم دیا جو رسولوں کو دیا، چنانچہ رسولوں کے حق میں فرمایا: ﴿اے رسولو! پاکیزہ چیزوں میں سے کھاؤ اور نیک عمل کرو﴾“: اللہ کا رسولوں کو دیا گیا حکم اور مومنوں کو دیا گیا حکم ایک ہی ہے: پاکیزہ چیزوں میں سے کھانا۔ رہی خبیث چیزیں تو وہ ان پر حرام ہیں؛ اللہ تعالیٰ نے اپنے رسول کے حق میں فرمایا: ﴿اور ان کے لیے پاکیزہ چیزیں حلال کرتا ہے اور خبیث چیزیں حرام کرتا ہے﴾ (۷:۱۵۷)۔',
  '"আল্লাহ তাআলা পবিত্র (তাইয়িব), তিনি পবিত্র ছাড়া কিছু গ্রহণ করেন না": আল্লাহ তাঁর সত্তায় পবিত্র, তাঁর গুণাবলিতে পবিত্র, তাঁর কর্মে পবিত্র; তিনি কেবল তা-ই গ্রহণ করেন যা নিজে পবিত্র এবং যার অর্জনের উপায়ও পবিত্র। আর যা স্বভাবগতভাবে অপবিত্র (খাবীস) যেমন মদ, কিংবা অর্জনের উপায়ে অপবিত্র যেমন সুদ দিয়ে অর্জিত সম্পদ, আল্লাহ তাআলা তা গ্রহণ করেন না।\n"আল্লাহ মুমিনদের সেই আদেশ দিয়েছেন যা তিনি রাসূলগণকে দিয়েছেন, রাসূলগণ সম্পর্কে বলেছেন: ﴿হে রাসূলগণ! পবিত্র বস্তু থেকে আহার করো এবং সৎকর্ম করো﴾": আল্লাহ রাসূলগণকে যে আদেশ দিয়েছেন এবং মুমিনদের যে আদেশ দিয়েছেন তা একই — পবিত্র বস্তু থেকে আহার করা। আর অপবিত্র বস্তু তাদের জন্য হারাম; আল্লাহ তাআলা তাঁর রাসূল সম্পর্কে বলেছেন: ﴿আর তিনি তাদের জন্য পবিত্র বস্তু হালাল করেন এবং অপবিত্র বস্তু হারাম করেন﴾ (৭:১৫৭)।',
  '"Allah Taʿala itu baik (Tayyib) dan tidak menerima melainkan yang baik": Allah baik pada zat-Nya, baik pada sifat-sifat-Nya, baik pada perbuatan-perbuatan-Nya. Dia tidak menerima melainkan yang baik pada zatnya dan baik pada cara memperolehnya. Adapun yang buruk (khabith) pada zatnya seperti arak, atau buruk pada cara memperolehnya seperti yang diperoleh dengan riba, maka Allah Taʿala tidak menerimanya.\n"Allah memerintahkan orang-orang beriman dengan apa yang Dia perintahkan kepada para rasul, Dia berfirman tentang para rasul: {Wahai para rasul, makanlah daripada makanan yang baik-baik dan kerjakanlah amal soleh}": perintah Allah kepada para rasul dan perintah-Nya kepada orang-orang beriman adalah sama: iaitu makan daripada yang baik-baik. Adapun yang buruk, ia haram bagi mereka; Allah Taʿala berfirman tentang Rasul-Nya: {…dan menghalalkan bagi mereka yang baik-baik dan mengharamkan bagi mereka yang buruk-buruk} (7:157).',
  '«Аллах Всевышний — Чист (Таййиб) и принимает только чистое»: Аллах чист в Своей сущности, чист в Своих качествах, чист в Своих действиях; Он принимает лишь то, что чисто по своей природе и чисто по способу приобретения. Что же касается мерзкого (хабис) по своей природе, как вино, или мерзкого по способу приобретения, как приобретённое через ростовщичество (риба), — этого Аллах Всевышний не принимает.\n«Аллах повелел верующим то же, что повелел посланникам, сказав о посланниках: {О посланники! Вкушайте благое и творите праведное}»: повеление, обращённое Аллахом к посланникам, и Его повеление к верующим — одно и то же: вкушать благое. А мерзкое запретно для них; Всевышний сказал о Своём Посланнике: {…он дозволяет им благое и запрещает им скверное} (7:157).',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-10-Nawawi-Psalmodie-Arabe.mp3',
  5,
  10
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 10
);
