-- =============================================================================
-- 40 Hadith Nawawi — Hadith 42: "The vastness of Allah's forgiveness"
-- Target collection: public.hadith_collections.id = 2  /  position = 42 (final)
-- Idempotent guard on (collection, position). All 11 content languages.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'The vastness of Allah''s forgiveness',
  'L''immensité de l''indulgence d''Allah',
  'سعة مغفرة الله تعالى',
  'Die Weite der Vergebung Allahs',
  'De wijdte van Allahs vergeving',
  'Allah''ın mağfiretinin genişliği',
  'Luasnya ampunan Allah',
  'اللہ کی مغفرت کی وسعت',
  'আল্লাহর ক্ষমার ব্যাপকতা',
  'Luasnya keampunan Allah',
  'Безграничность прощения Аллаха',
  -- arabic_text
  'عَنْ أَنَسٍ رَضِيَ اللَّهُ عَنْهُ قَالَ: سَمِعْتُ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يَقُولُ: «قَالَ اللَّهُ تَعَالَى: يَا ابْنَ آدَمَ، إِنَّكَ مَا دَعَوْتَنِي وَرَجَوْتَنِي غَفَرْتُ لَكَ عَلَى مَا كَانَ مِنْكَ وَلَا أُبَالِي. يَا ابْنَ آدَمَ، لَوْ بَلَغَتْ ذُنُوبُكَ عَنَانَ السَّمَاءِ ثُمَّ اسْتَغْفَرْتَنِي غَفَرْتُ لَكَ. يَا ابْنَ آدَمَ، إِنَّكَ لَوْ أَتَيْتَنِي بِقُرَابِ الْأَرْضِ خَطَايَا ثُمَّ لَقِيتَنِي لَا تُشْرِكُ بِي شَيْئًا لَأَتَيْتُكَ بِقُرَابِهَا مَغْفِرَةً»',
  -- transcription
  'ʿan Anasin raḍiya Llāhu ʿanhu qāla: samiʿtu Rasūla Llāhi ṣalla Llāhu ʿalayhi wa-sallama yaqūlu: qāla Llāhu taʿālā: yā bna Ādama, innaka mā daʿawtanī wa-rajawtanī ghafartu laka ʿalā mā kāna minka wa-lā ubālī. yā bna Ādama, law balaghat dhunūbuka ʿanāna s-samāʾi thumma staghfartanī ghafartu laka. yā bna Ādama, innaka law ataytanī bi-qurābi l-arḍi khaṭāyā thumma laqītanī lā tushriku bī shayʾan la-ataytuka bi-qurābihā maghfiratan.',
  'ʿan Anasin (radia Llâhou ʿanhou) qâla : samiʿtou Rassôla Llâhi (salla Llâhou ʿalayhi wa sallam) yaqôulou : qâla Llâhou taʿâlâ : yâ bna Âdama, innaka mâ daʿawtanî wa rajawtanî ghafartou laka ʿalâ mâ kâna minka wa lâ oubâlî. yâ bna Âdama, law balaghat dhounôubouka ʿanâna s-samâʾi thoumma staghfartanî ghafartou laka. yâ bna Âdama, innaka law ataytanî bi-qourâbi l-ardi khatâyâ thoumma laqîtanî lâ touchrikou bî chayʾan la-ataytouka bi-qourâbihâ maghfiratan.',
  'ʿan Anasin (radiya Llāhu ʿanhu) qāla: samiʿtu Rasūla Llāhi (salla Llāhu ʿalaihi wa-sallam) jaqūlu: qāla Llāhu taʿālā: jā bna Ādama, innaka mā daʿautanī wa-radschautanī ghafartu laka ʿalā mā kāna minka wa-lā ubālī. jā bna Ādama, lau balaghat dhunūbuka ʿanāna s-samāʾi thumma staghfartanī ghafartu laka. jā bna Ādama, innaka lau ataitanī bi-qurābi l-ardi chatājā thumma laqītanī lā tuschriku bī schaiʾan la-ataituka bi-qurābihā maghfiratan.',
  'ʿan Anasin (radia Llaahoe ʿanhoe) qaala: samiʿtoe Rasoela Llaahi (salla Llaahoe ʿalaihi wa-sallam) jaqoeloe: qaala Llaahoe taʿaalaa: jaa bna Aadama, innaka maa daʿautanie wa-radzjautanie ghafartoe laka ʿalaa maa kaana minka wa-laa oebaalie. jaa bna Aadama, lau balaghat dhoenoeboeka ʿanaana s-samaaʾi thoemma staghfartanie ghafartoe laka. jaa bna Aadama, innaka lau ataitanie bi-qoeraabi l-ardi chataajaa thoemma laqietanie laa toesjrikoe bie sjaiʾan la-ataitoeka bi-qoeraabihaa maghfiratan.',
  'an Enes''ten (radıyallâhu anh) rivayetle dedi ki: Resûlullah''ın (s.a.v.) şöyle dediğini işittim: Allah Teâlâ buyurdu ki: ey Âdemoğlu! Sen Bana dua edip Benden ümit ettikçe, senden olan (günahlara) rağmen seni bağışlarım ve aldırmam. Ey Âdemoğlu! Günahların göğün bulutlarına ulaşsa, sonra Benden bağışlanma dilesen, seni bağışlarım. Ey Âdemoğlu! Bana yeryüzü dolusu günahla gelsen, sonra Bana hiçbir şeyi ortak koşmadan kavuşsan, Ben de sana onun dolusu kadar mağfiretle gelirim.',
  'an Anas (radhiyallahu ʿanhu) berkata: aku mendengar Rasulullah (shallallahu ʿalaihi wa sallam) bersabda: Allah Taʿala berfirman: wahai anak Adam! Selama engkau berdoa kepada-Ku dan berharap kepada-Ku, Aku ampuni dosa-dosa yang ada padamu dan Aku tidak peduli. Wahai anak Adam! Seandainya dosa-dosamu mencapai awan di langit, kemudian engkau memohon ampun kepada-Ku, niscaya Aku ampuni engkau. Wahai anak Adam! Seandainya engkau datang kepada-Ku dengan kesalahan sepenuh bumi, kemudian engkau menjumpai-Ku dalam keadaan tidak menyekutukan-Ku dengan sesuatu pun, niscaya Aku datangkan untukmu ampunan sepenuh itu pula.',
  'انس رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: میں نے رسول اللہ صلی اللہ علیہ وسلم کو فرماتے سنا: اللہ تعالیٰ نے فرمایا: اے ابنِ آدم! جب تک تو مجھے پکارتا اور مجھ سے امید رکھتا رہے گا، میں تجھ سے سرزد ہونے والے (گناہوں) کے باوجود تجھے بخش دوں گا اور کوئی پروا نہ کروں گا۔ اے ابنِ آدم! اگر تیرے گناہ آسمان کے بادلوں تک پہنچ جائیں، پھر تو مجھ سے بخشش مانگے تو میں تجھے بخش دوں گا۔ اے ابنِ آدم! اگر تو زمین بھر گناہ لے کر میرے پاس آئے، پھر مجھ سے اس حال میں ملے کہ میرے ساتھ کسی کو شریک نہ ٹھہراتا ہو، تو میں اتنی ہی زمین بھر مغفرت لے کر تیرے پاس آؤں گا۔',
  'আনাস (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: আমি রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম)-কে বলতে শুনেছি: আল্লাহ তাআলা বলেছেন: হে আদম সন্তান! যতক্ষণ তুমি আমাকে ডাকবে ও আমার কাছে আশা রাখবে, আমি তোমার থেকে যা কিছু ঘটেছে তা সত্ত্বেও তোমাকে ক্ষমা করে দেব এবং পরোয়া করব না। হে আদম সন্তান! যদি তোমার গুনাহ আসমানের মেঘমালা পর্যন্ত পৌঁছে যায়, অতঃপর তুমি আমার কাছে ক্ষমা চাও, আমি তোমাকে ক্ষমা করে দেব। হে আদম সন্তান! যদি তুমি জমিন ভর্তি গুনাহ নিয়ে আমার কাছে আসো, অতঃপর আমার সাথে কাউকে শরিক না করা অবস্থায় আমার সাক্ষাৎ লাভ করো, তবে আমি তোমার কাছে তত পরিমাণ ক্ষমা নিয়ে আসব।',
  'an Anas (radhiallahu ʿanhu) berkata: aku mendengar Rasulullah (sallallahu ʿalaihi wa sallam) bersabda: Allah Taʿala berfirman: wahai anak Adam! Selama engkau berdoa kepada-Ku dan berharap kepada-Ku, Aku ampuni dosa-dosa yang ada padamu dan Aku tidak peduli. Wahai anak Adam! Seandainya dosa-dosamu mencapai awan di langit, kemudian engkau memohon ampun kepada-Ku, nescaya Aku ampuni engkau. Wahai anak Adam! Seandainya engkau datang kepada-Ku dengan kesalahan sepenuh bumi, kemudian engkau menemui-Ku dalam keadaan tidak menyekutukan-Ku dengan sesuatu pun, nescaya Aku datangkan untukmu keampunan sepenuh itu pula.',
  'От Анаса (да будет доволен им Аллах) передаётся: я слышал, как Посланник Аллаха ﷺ говорил: Аллах Всевышний сказал: о сын Адама! Пока ты взываешь ко Мне и надеешься на Меня, Я прощаю тебе то, что от тебя исходит, и не придаю этому значения. О сын Адама! Если бы грехи твои достигли облаков небесных, а затем ты попросил бы у Меня прощения, Я простил бы тебя. О сын Адама! Если бы ты пришёл ко Мне с грехами величиной с землю, а затем встретил Меня, не придавая Мне никого в сотоварищи, Я пришёл бы к тебе с прощением такой же величины.',
  -- translation
  'On the authority of Anas (may Allah be pleased with him), who said: I heard the Messenger of Allah ﷺ say: "Allah, the Exalted, said: ''O son of Adam, so long as you call upon Me and place your hope in Me, I will forgive you for whatever has come from you, and I will not mind. O son of Adam, were your sins to reach the clouds of the sky and then you asked My forgiveness, I would forgive you. O son of Adam, were you to come to Me with sins nearly as great as the earth, and then meet Me without associating anything with Me, I would bring you forgiveness nearly as great as it.''"',
  'D''après Anas (qu''Allah l''agrée), qui a dit : J''ai entendu l''Envoyé d''Allah ﷺ dire : « Allah le Très-Haut a dit : "Ô fils d''Adam, tant que tu M''invoques et que tu espères en Moi, Je t''absoudrai pour ce qui s''est produit de toi, et Je ne M''en soucierai pas. Ô fils d''Adam, si tes péchés atteignaient les nuages du ciel et qu''ensuite tu Me demandais pardon, Je te pardonnerais. Ô fils d''Adam, si tu venais à Moi avec des péchés (presque) aussi grands que la terre, puis que tu Me rencontrais sans rien M''associer, Je viendrais à toi avec un pardon (presque) aussi grand qu''elle." »',
  'Nach Anas (möge Allah mit ihm zufrieden sein), der sagte: Ich hörte den Gesandten Allahs ﷺ sagen: „Allah, der Erhabene, sprach: ''O Sohn Adams, solange du Mich anrufst und auf Mich hoffst, vergebe Ich dir, was von dir gekommen ist, und Ich kümmere Mich nicht darum. O Sohn Adams, würden deine Sünden die Wolken des Himmels erreichen und du Mich dann um Vergebung bätest, so würde Ich dir vergeben. O Sohn Adams, kämst du zu Mir mit Sünden beinahe so groß wie die Erde und begegnetest Mir dann, ohne Mir etwas beizugesellen, so käme Ich zu dir mit Vergebung beinahe ebenso groß wie sie.''"',
  'Op gezag van Anas (moge Allah tevreden met hem zijn), die zei: Ik hoorde de Boodschapper van Allah ﷺ zeggen: „Allah, de Verhevene, zei: ''O zoon van Adam, zolang je Mij aanroept en op Mij hoopt, zal Ik je vergeven voor wat van jou is gekomen, en het kan Mij niet schelen. O zoon van Adam, al zouden je zonden de wolken van de hemel bereiken en je Mij vervolgens om vergeving vragen, dan zou Ik je vergeven. O zoon van Adam, al zou je tot Mij komen met zonden bijna zo groot als de aarde en Mij vervolgens ontmoeten zonder iets aan Mij toe te kennen, dan zou Ik tot jou komen met vergeving bijna zo groot als zij.''"',
  'Enes''ten (Allah ondan razı olsun) rivayet edildiğine göre şöyle dedi: Resûlullah''ın ﷺ şöyle buyurduğunu işittim: „Allah Teâlâ buyurdu ki: ''Ey Âdemoğlu! Sen Bana dua edip Benden ümit ettikçe, senden olan (günahlara) rağmen seni bağışlarım ve aldırmam. Ey Âdemoğlu! Günahların göğün bulutlarına ulaşsa, sonra Benden bağışlanma dilesen, seni bağışlarım. Ey Âdemoğlu! Bana yeryüzü dolusu günahla gelsen, sonra Bana hiçbir şeyi ortak koşmadan kavuşsan, Ben de sana onun dolusu kadar mağfiretle gelirim.''"',
  'Dari Anas (semoga Allah meridhainya), ia berkata: Aku mendengar Rasulullah ﷺ bersabda: "Allah Taʿala berfirman: ''Wahai anak Adam, selama engkau berdoa kepada-Ku dan berharap kepada-Ku, Aku ampuni dosa-dosa yang ada padamu dan Aku tidak peduli. Wahai anak Adam, seandainya dosa-dosamu mencapai awan di langit, kemudian engkau memohon ampun kepada-Ku, niscaya Aku ampuni engkau. Wahai anak Adam, seandainya engkau datang kepada-Ku dengan kesalahan sepenuh bumi, kemudian engkau menjumpai-Ku dalam keadaan tidak menyekutukan-Ku dengan sesuatu pun, niscaya Aku datangkan untukmu ampunan sepenuh itu pula.''"',
  'انس رضی اللہ عنہ سے روایت ہے: میں نے رسول اللہ ﷺ کو فرماتے سنا: ”اللہ تعالیٰ نے فرمایا: اے ابنِ آدم! جب تک تو مجھے پکارتا اور مجھ سے امید رکھتا رہے گا، میں تجھ سے سرزد ہونے والے (گناہوں) کے باوجود تجھے بخش دوں گا اور کوئی پروا نہ کروں گا۔ اے ابنِ آدم! اگر تیرے گناہ آسمان کے بادلوں تک پہنچ جائیں، پھر تو مجھ سے بخشش مانگے تو میں تجھے بخش دوں گا۔ اے ابنِ آدم! اگر تو زمین بھر گناہ لے کر میرے پاس آئے، پھر مجھ سے اس حال میں ملے کہ میرے ساتھ کسی کو شریک نہ ٹھہراتا ہو، تو میں اتنی ہی زمین بھر مغفرت لے کر تیرے پاس آؤں گا۔“',
  'আনাস (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত: আমি রাসূলুল্লাহ ﷺ-কে বলতে শুনেছি: "আল্লাহ তাআলা বলেছেন: ''হে আদম সন্তান! যতক্ষণ তুমি আমাকে ডাকবে ও আমার কাছে আশা রাখবে, আমি তোমার থেকে যা কিছু ঘটেছে তা সত্ত্বেও তোমাকে ক্ষমা করে দেব এবং পরোয়া করব না। হে আদম সন্তান! যদি তোমার গুনাহ আসমানের মেঘমালা পর্যন্ত পৌঁছে যায়, অতঃপর তুমি আমার কাছে ক্ষমা চাও, আমি তোমাকে ক্ষমা করে দেব। হে আদম সন্তান! যদি তুমি জমিন ভর্তি গুনাহ নিয়ে আমার কাছে আসো, অতঃপর আমার সাথে কাউকে শরিক না করা অবস্থায় আমার সাক্ষাৎ লাভ করো, তবে আমি তোমার কাছে তত পরিমাণ ক্ষমা নিয়ে আসব।''"',
  'Daripada Anas (semoga Allah meredainya), dia berkata: Aku mendengar Rasulullah ﷺ bersabda: "Allah Taʿala berfirman: ''Wahai anak Adam, selama engkau berdoa kepada-Ku dan berharap kepada-Ku, Aku ampuni dosa-dosa yang ada padamu dan Aku tidak peduli. Wahai anak Adam, seandainya dosa-dosamu mencapai awan di langit, kemudian engkau memohon ampun kepada-Ku, nescaya Aku ampuni engkau. Wahai anak Adam, seandainya engkau datang kepada-Ku dengan kesalahan sepenuh bumi, kemudian engkau menemui-Ku dalam keadaan tidak menyekutukan-Ku dengan sesuatu pun, nescaya Aku datangkan untukmu keampunan sepenuh itu pula.''"',
  'Со слов Анаса (да будет доволен им Аллах), который сказал: Я слышал, как Посланник Аллаха ﷺ говорил: «Аллах Всевышний сказал: ''О сын Адама, пока ты взываешь ко Мне и надеешься на Меня, Я прощаю тебе то, что от тебя исходит, и не придаю этому значения. О сын Адама, если бы грехи твои достигли облаков небесных, а затем ты попросил бы у Меня прощения, Я простил бы тебя. О сын Адама, если бы ты пришёл ко Мне с грехами величиной почти с землю, а затем встретил Меня, не придавая Мне никого в сотоварищи, Я пришёл бы к тебе с прощением почти такой же величины.''»',
  -- reference
  'Hasan — reported by at-Tirmidhi (no. 3540), ad-Darimi (2/322), and Ahmad in his Musnad (5/172); graded hasan by al-Albani due to corroborating reports (shawahid) in as-Sahiha (no. 127)',
  'Hadith hasan rapporté par at-Tirmidhî (n°3540), ad-Dârimî (2/322) et Ahmad dans son Musnad (5/172) ; déclaré hasan par al-Albânî en raison de hadiths corroborants (shawâhid) dans as-Sahîha (n°127)',
  'حديث حسن، رواه الترمذي (رقم ٣٥٤٠) والدارمي (٢/٣٢٢) وأحمد في مسنده (٥/١٧٢)، وحسّنه الألباني بشواهده في السلسلة الصحيحة (رقم ١٢٧)',
  'Hasan — überliefert von at-Tirmidhi (Nr. 3540), ad-Darimi (2/322) und Ahmad in seinem Musnad (5/172); von al-Albani aufgrund stützender Überlieferungen (Schawahid) in as-Sahiha (Nr. 127) als hasan eingestuft',
  'Hasan — overgeleverd door at-Tirmidhi (nr. 3540), ad-Darimi (2/322) en Ahmad in zijn Musnad (5/172); door al-Albani als hasan beoordeeld vanwege ondersteunende overleveringen (shawahid) in as-Sahiha (nr. 127)',
  'Hasen — Tirmizî (no. 3540), Dârimî (2/322) ve Ahmed Müsned''inde (5/172) rivayet etmiştir; Elbânî, şâhitleri (şevâhid) sebebiyle es-Silsiletü''s-Sahîha''da (no. 127) hasen demiştir',
  'Hadis hasan, diriwayatkan oleh at-Tirmidzi (no. 3540), ad-Darimi (2/322), dan Ahmad dalam Musnadnya (5/172); dinilai hasan oleh al-Albani karena adanya riwayat-riwayat penguat (syawahid) dalam as-Silsilah as-Sahihah (no. 127)',
  'حسن حدیث، اسے ترمذی (نمبر ۳۵۴۰)، دارمی (۲/۳۲۲) اور احمد نے اپنی مسند (۵/۱۷۲) میں روایت کیا؛ البانی نے شواہد کی بنا پر السلسلۃ الصحیحۃ (نمبر ۱۲۷) میں اسے حسن قرار دیا',
  'হাসান হাদীস — তিরমিযী (নং ৩৫৪০), দারিমী (২/৩২২) ও আহমাদ তাঁর মুসনাদে (৫/১৭২) বর্ণনা করেছেন; আলবানী সমর্থক বর্ণনাসমূহের (শাওয়াহিদ) কারণে আস-সিলসিলা আস-সহীহায় (নং ১২৭) একে হাসান বলেছেন',
  'Hadis hasan, diriwayatkan oleh at-Tirmizi (no. 3540), ad-Darimi (2/322), dan Ahmad dalam Musnadnya (5/172); dinilai hasan oleh al-Albani kerana adanya riwayat-riwayat penyokong (syawahid) dalam as-Silsilah as-Sahihah (no. 127)',
  'Хороший (хасан) хадис, передали ат-Тирмизи (№ 3540), ад-Дарими (2/322) и Ахмад в своём «Муснаде» (5/172); аль-Альбани назвал его хасаном благодаря подкрепляющим версиям (шавахид) в «ас-Сильсиля ас-Сахиха» (№ 127)',
  -- tafsir
  '• The immensity of the grace of Allah, the Exalted.\n• Even if sins become enormous, if a person asks Allah to forgive them, Allah will do so.\n• The great merit of sincere devotion (tawhid) — that worship belongs to Allah alone — and that it is a cause for the forgiveness of sins; the Exalted said: {Indeed Allah does not forgive that partners be associated with Him, but He forgives anything less than that for whom He wills} (4:48).',
  '• L''immensité de la grâce d''Allah, le Très-Haut.\n• Même si les péchés deviennent énormes, si l''homme demande à Allah de les lui pardonner, Allah le fera.\n• Le grand mérite de la consécration (le monothéisme — que l''adoration soit vouée à Allah seul), et qu''elle est une cause d''absolution des péchés ; le Très-Haut a dit : {Certes Allah ne pardonne pas qu''on Lui associe quoi que ce soit, mais Il pardonne, à qui Il veut, tout autre péché} (4:48).',
  '• سعة فضل الله تعالى.\n• وإن عظمت الذنوب، فإذا سأل الإنسان الله أن يغفرها له غفرها الله.\n• عظيم فضل الإخلاص (التوحيد) وأنه سبب لمغفرة الذنوب، قال تعالى: {إن الله لا يغفر أن يُشرك به ويغفر ما دون ذلك لمن يشاء} (٤:٤٨).',
  '• Die Weite der Gnade Allahs, des Erhabenen.\n• Auch wenn die Sünden gewaltig werden: bittet der Mensch Allah um deren Vergebung, so vergibt Allah sie.\n• Der große Vorzug der aufrichtigen Hingabe (Tauhid — dass die Anbetung Allah allein gilt) und dass sie eine Ursache für die Vergebung der Sünden ist; der Erhabene sagte: {Wahrlich, Allah vergibt nicht, dass man Ihm etwas beigesellt, doch was darunter liegt, vergibt Er, wem Er will} (4:48).',
  '• De wijdte van de gunst van Allah, de Verhevene.\n• Zelfs als de zonden enorm worden: vraagt de mens Allah om vergeving ervan, dan vergeeft Allah ze.\n• De grote verdienste van oprechte toewijding (tawhid — dat de aanbidding alleen Allah toebehoort) en dat zij een oorzaak is voor de vergeving van zonden; de Verhevene zei: {Voorwaar, Allah vergeeft niet dat men Hem deelgenoten toekent, maar daarbuiten vergeeft Hij wie Hij wil} (4:48).',
  '• Allah Teâlâ''nın lütfunun genişliği.\n• Günahlar ne kadar büyürse büyüsün, insan Allah''tan onları bağışlamasını isterse, Allah onları bağışlar.\n• İhlâsın (tevhidin — ibadetin yalnız Allah''a has kılınmasının) büyük fazileti ve onun günahların bağışlanmasına sebep olması; Yüce Allah şöyle buyurdu: {Şüphesiz Allah, kendisine ortak koşulmasını bağışlamaz; bunun dışındakini dilediğine bağışlar} (4:48).',
  '• Luasnya karunia Allah Taʿala.\n• Sekalipun dosa-dosa menjadi besar, jika seseorang memohon kepada Allah agar mengampuninya, niscaya Allah mengampuninya.\n• Besarnya keutamaan keikhlasan (tauhid — bahwa ibadah hanya untuk Allah semata) dan bahwa ia menjadi sebab diampuninya dosa-dosa; Allah Taʿala berfirman: {Sesungguhnya Allah tidak mengampuni dosa syirik kepada-Nya, dan Dia mengampuni dosa selain itu bagi siapa yang Dia kehendaki} (4:48).',
  '• اللہ تعالیٰ کے فضل کی وسعت۔\n• گناہ خواہ کتنے ہی بڑے ہو جائیں، اگر انسان اللہ سے ان کی مغفرت مانگے تو اللہ انہیں بخش دے گا۔\n• اخلاص (توحید — یعنی عبادت کو صرف اللہ کے لیے خاص کرنے) کی عظیم فضیلت، اور یہ کہ وہ گناہوں کی مغفرت کا سبب ہے؛ اللہ تعالیٰ نے فرمایا: {بے شک اللہ اس بات کو نہیں بخشتا کہ اس کے ساتھ شرک کیا جائے، اور اس کے سوا جسے چاہے بخش دیتا ہے} (۴:۴۸)۔',
  '• আল্লাহ তাআলার অনুগ্রহের ব্যাপকতা।\n• গুনাহ যত বড়ই হোক, যদি মানুষ আল্লাহর কাছে তা ক্ষমা চায়, আল্লাহ তা ক্ষমা করে দেবেন।\n• ইখলাস (তাওহীদ — অর্থাৎ ইবাদত কেবল আল্লাহর জন্য নির্দিষ্ট করা)-এর মহান ফজিলত, এবং তা গুনাহ মাফের কারণ; আল্লাহ তাআলা বলেছেন: {নিশ্চয়ই আল্লাহ তাঁর সাথে শিরক করা ক্ষমা করেন না, আর তা ছাড়া অন্য সব যাকে ইচ্ছা ক্ষমা করেন} (৪:৪৮)।',
  '• Luasnya kurnia Allah Taʿala.\n• Sekalipun dosa-dosa menjadi besar, jika seseorang memohon kepada Allah agar mengampuninya, nescaya Allah mengampuninya.\n• Besarnya kelebihan keikhlasan (tauhid — bahawa ibadah hanya untuk Allah semata) dan bahawa ia menjadi sebab diampuninya dosa-dosa; Allah Taʿala berfirman: {Sesungguhnya Allah tidak mengampuni dosa mempersekutukan-Nya, dan Dia mengampuni dosa selain itu bagi sesiapa yang Dia kehendaki} (4:48).',
  '• Безграничность милости Аллаха Всевышнего.\n• Сколь бы велики ни были грехи, если человек попросит у Аллаха их прощения, Аллах простит их.\n• Великое достоинство искренности (таухида — посвящения поклонения одному лишь Аллаху) и то, что она является причиной прощения грехов; Всевышний сказал: {Поистине, Аллах не прощает, когда к Нему приобщают сотоварищей, но прощает всё, кроме этого, кому пожелает} (4:48).',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-42-Nawawi-Psalmodie-Arabe.mp3',
  5,
  42
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 42
);
