-- =============================================================================
-- 40 Hadith Nawawi — Hadith 37: "Allah's grace and mercy (recording deeds)"
-- Target collection: public.hadith_collections.id = 2  /  position = 37
-- Idempotent guard on (collection, position). All 11 content languages.
-- tafsir_* intentionally left NULL (no commentary provided for this hadith).
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Allah''s grace and mercy',
  'Les faveurs d''Allah et Sa miséricorde',
  'فضل الله تعالى ورحمته',
  'Allahs Gnade und Barmherzigkeit',
  'Allahs gunst en barmhartigheid',
  'Allah''ın lütfu ve rahmeti',
  'Karunia dan rahmat Allah',
  'اللہ کا فضل اور اس کی رحمت',
  'আল্লাহর অনুগ্রহ ও রহমত',
  'Kurnia dan rahmat Allah',
  'Милость и благодать Аллаха',
  -- arabic_text
  'عَنِ ابْنِ عَبَّاسٍ رَضِيَ اللَّهُ عَنْهُمَا عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فِيمَا يَرْوِيهِ عَنْ رَبِّهِ تَبَارَكَ وَتَعَالَى قَالَ: «إِنَّ اللَّهَ تَعَالَى كَتَبَ الْحَسَنَاتِ وَالسَّيِّئَاتِ، ثُمَّ بَيَّنَ ذَلِكَ: فَمَنْ هَمَّ بِحَسَنَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللَّهُ عِنْدَهُ حَسَنَةً كَامِلَةً، وَإِنْ هَمَّ بِهَا فَعَمِلَهَا كَتَبَهَا اللَّهُ عِنْدَهُ عَشْرَ حَسَنَاتٍ إِلَى سَبْعِمِائَةِ ضِعْفٍ إِلَى أَضْعَافٍ كَثِيرَةٍ، وَإِنْ هَمَّ بِسَيِّئَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللَّهُ عِنْدَهُ حَسَنَةً كَامِلَةً، وَإِنْ هَمَّ بِهَا فَعَمِلَهَا كَتَبَهَا اللَّهُ عِنْدَهُ سَيِّئَةً وَاحِدَةً»',
  -- transcription
  'ʿani bni ʿAbbāsin raḍiya Llāhu ʿanhumā ʿan Rasūli Llāhi ṣalla Llāhu ʿalayhi wa-sallama fīmā yarwīhi ʿan Rabbihi tabāraka wa-taʿālā qāla: inna Llāha taʿālā kataba l-ḥasanāti wa-s-sayyiʾāti, thumma bayyana dhālika: fa-man hamma bi-ḥasanatin fa-lam yaʿmalhā katabahā Llāhu ʿindahu ḥasanatan kāmilatan, wa-in hamma bihā fa-ʿamilahā katabahā Llāhu ʿindahu ʿashra ḥasanātin ilā sabʿimiʾati ḍiʿfin ilā aḍʿāfin kathīratin, wa-in hamma bi-sayyiʾatin fa-lam yaʿmalhā katabahā Llāhu ʿindahu ḥasanatan kāmilatan, wa-in hamma bihā fa-ʿamilahā katabahā Llāhu ʿindahu sayyiʾatan wāḥidatan.',
  'ʿani bni ʿAbbâsin (radia Llâhou ʿanhoumâ) ʿan Rassôli Llâhi (salla Llâhou ʿalayhi wa sallam) fîmâ yarwîhi ʿan Rabbihi tabâraka wa taʿâlâ qâla : inna Llâha taʿâlâ kataba l-hasanâti wa s-sayyiʾâti, thoumma bayyana dhâlika : fa-man hamma bi-hasanatin fa-lam yaʿmalhâ katabahâ Llâhou ʿindahou hasanatan kâmilatan, wa in hamma bihâ fa-ʿamilahâ katabahâ Llâhou ʿindahou ʿachra hasanâtin ilâ sabʿimiʾati diʿfin ilâ adʿâfin kathîratin, wa in hamma bi-sayyiʾatin fa-lam yaʿmalhâ katabahâ Llâhou ʿindahou hasanatan kâmilatan, wa in hamma bihâ fa-ʿamilahâ katabahâ Llâhou ʿindahou sayyiʾatan wâhidatan.',
  'ʿani bni ʿAbbāsin (radiya Llāhu ʿanhumā) ʿan Rasūli Llāhi (salla Llāhu ʿalaihi wa-sallam) fīmā jarwīhi ʿan Rabbihi tabāraka wa-taʿālā qāla: inna Llāha taʿālā kataba l-hasanāti wa-s-sajjiʾāti, thumma bajjana dhālika: fa-man hamma bi-hasanatin fa-lam jaʿmalhā katabahā Llāhu ʿindahu hasanatan kāmilatan, wa-in hamma bihā fa-ʿamilahā katabahā Llāhu ʿindahu ʿaschra hasanātin ilā sabʿimiʾati diʿfin ilā adʿāfin kathīratin, wa-in hamma bi-sajjiʾatin fa-lam jaʿmalhā katabahā Llāhu ʿindahu hasanatan kāmilatan, wa-in hamma bihā fa-ʿamilahā katabahā Llāhu ʿindahu sajjiʾatan wāhidatan.',
  'ʿani bni ʿAbbaasin (radia Llaahoe ʿanhoemaa) ʿan Rasoeli Llaahi (salla Llaahoe ʿalaihi wa-sallam) fiemaa jarwiehi ʿan Rabbihi tabaaraka wa-taʿaalaa qaala: inna Llaaha taʿaalaa kataba l-hasanaati wa-s-sajjiʾaati, thoemma bajjana dhaalika: fa-man hamma bi-hasanatin fa-lam jaʿmalhaa katabahaa Llaahoe ʿindahoe hasanatan kaamilatan, wa-in hamma bihaa fa-ʿamilahaa katabahaa Llaahoe ʿindahoe ʿasjra hasanaatin ilaa sabʿimiʾati diʿfin ilaa adʿaafin kathieratin, wa-in hamma bi-sajjiʾatin fa-lam jaʿmalhaa katabahaa Llaahoe ʿindahoe hasanatan kaamilatan, wa-in hamma bihaa fa-ʿamilahaa katabahaa Llaahoe ʿindahoe sajjiʾatan waahidatan.',
  'an İbn Abbâs''tan (radıyallâhu anhümâ), Resûlullah''ın (s.a.v.) Rabbi Tebâreke ve Teâlâ''dan rivayet ettiğine göre buyurdu: şüphesiz Allah Teâlâ iyilikleri ve kötülükleri yazdı, sonra bunu açıkladı: kim bir iyiliğe niyetlenir de onu yapmazsa, Allah onu katında tam bir iyilik olarak yazar; eğer niyetlenip de onu yaparsa, Allah onu katında on iyilikten yedi yüz kata, hatta kat kat fazlasına kadar yazar; kim bir kötülüğe niyetlenir de onu yapmazsa, Allah onu katında tam bir iyilik olarak yazar; eğer niyetlenip de onu yaparsa, Allah onu katında bir tek kötülük olarak yazar.',
  'an Ibni ʿAbbas (radhiyallahu ʿanhuma), dari Rasulullah (shallallahu ʿalaihi wa sallam) tentang apa yang beliau riwayatkan dari Rabbnya Tabaraka wa Taʿala, bahwa Dia berfirman: sesungguhnya Allah Taʿala telah menetapkan kebaikan dan keburukan, kemudian Dia menjelaskannya: barangsiapa berniat melakukan kebaikan lalu tidak mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu kebaikan yang sempurna; jika ia berniat lalu mengerjakannya, Allah menulisnya di sisi-Nya sepuluh kebaikan hingga tujuh ratus kali lipat sampai berlipat-lipat banyaknya; dan barangsiapa berniat melakukan keburukan lalu tidak mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu kebaikan yang sempurna; jika ia berniat lalu mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu keburukan saja.',
  'ابن عباس رضی اللہ عنہما سے، رسول اللہ صلی اللہ علیہ وسلم سے روایت ہے، اس میں جو آپ اپنے رب تبارک و تعالیٰ سے روایت کرتے ہیں کہ اس نے فرمایا: بے شک اللہ تعالیٰ نے نیکیاں اور برائیاں لکھ دیں، پھر اسے واضح کیا: جو کسی نیکی کا ارادہ کرے پھر اسے نہ کرے، اللہ اسے اپنے ہاں ایک مکمل نیکی لکھ دیتا ہے؛ اور اگر اس کا ارادہ کرے اور اسے کر لے تو اللہ اسے اپنے ہاں دس نیکیوں سے سات سو گنا تک، بلکہ اس سے بھی کئی گنا زیادہ لکھ دیتا ہے؛ اور جو کسی برائی کا ارادہ کرے پھر اسے نہ کرے، اللہ اسے اپنے ہاں ایک مکمل نیکی لکھ دیتا ہے؛ اور اگر اس کا ارادہ کرے اور اسے کر لے تو اللہ اسے اپنے ہاں صرف ایک برائی لکھتا ہے۔',
  'ইবনে আব্বাস (রাদিয়াল্লাহু আনহুমা) থেকে, রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম) থেকে বর্ণিত, তিনি যা তাঁর রব তাবারাকা ওয়া তাআলা থেকে বর্ণনা করেন যে তিনি বলেছেন: নিশ্চয়ই আল্লাহ তাআলা ভালো ও মন্দ কাজসমূহ লিখে রেখেছেন, অতঃপর তা স্পষ্ট করেছেন: যে কোনো ভালো কাজের নিয়ত করে অতঃপর তা না করে, আল্লাহ তা তাঁর নিকট একটি পূর্ণ নেকি লিখে রাখেন; আর যদি সে তার নিয়ত করে ও তা করে, আল্লাহ তা তাঁর নিকট দশ নেকি থেকে সাতশ গুণ পর্যন্ত, বরং আরও বহুগুণ লিখে রাখেন; আর যে কোনো মন্দ কাজের নিয়ত করে অতঃপর তা না করে, আল্লাহ তা তাঁর নিকট একটি পূর্ণ নেকি লিখে রাখেন; আর যদি সে তার নিয়ত করে ও তা করে, আল্লাহ তা তাঁর নিকট কেবল একটি গুনাহ লিখে রাখেন।',
  'an Ibni ʿAbbas (radhiallahu ʿanhuma), daripada Rasulullah (sallallahu ʿalaihi wa sallam) tentang apa yang baginda riwayatkan daripada Tuhannya Tabaraka wa Taʿala, bahawa Dia berfirman: sesungguhnya Allah Taʿala telah menetapkan kebaikan dan keburukan, kemudian Dia menjelaskannya: sesiapa yang berniat melakukan kebaikan lalu tidak mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu kebaikan yang sempurna; jika dia berniat lalu mengerjakannya, Allah menulisnya di sisi-Nya sepuluh kebaikan hingga tujuh ratus kali ganda sehingga berganda-ganda banyaknya; dan sesiapa yang berniat melakukan keburukan lalu tidak mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu kebaikan yang sempurna; jika dia berniat lalu mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu keburukan sahaja.',
  'От Ибн Аббаса (да будет доволен Аллах ими обоими), от Посланника Аллаха ﷺ, в том, что он передаёт от своего Господа, Благословенного и Всевышнего, что Он сказал: поистине, Аллах Всевышний записал добрые и дурные деяния, затем разъяснил это: кто вознамерился совершить доброе деяние, но не совершил его, тому Аллах записывает у Себя полное доброе деяние; а если он вознамерился и совершил его, Аллах записывает у Себя от десяти до семисот добрых деяний и до многократно большего; а кто вознамерился совершить дурное деяние, но не совершил его, тому Аллах записывает у Себя полное доброе деяние; а если он вознамерился и совершил его, Аллах записывает у Себя одно дурное деяние.',
  -- translation
  'On the authority of Ibn ʿAbbas (may Allah be pleased with them both), from the Messenger of Allah ﷺ, in what he related from his Lord, Blessed and Exalted, that He said: "Indeed Allah, the Exalted, has recorded the good deeds and the evil deeds, then He explained that: whoever intends a good deed but does not do it, Allah records it with Him as a complete good deed; and if he intends it and does it, Allah records it with Him as ten good deeds up to seven hundred times, and even many times more. And whoever intends an evil deed but does not do it, Allah records it with Him as a complete good deed; and if he intends it and does it, Allah records it with Him as a single evil deed."',
  'D''après Ibn ʿAbbâs (qu''Allah les agrée tous deux), l''Envoyé d''Allah ﷺ, rapportant les paroles de son Seigneur, Béni et Très-Haut, a dit : « Certes Allah le Très-Haut a inscrit les bonnes actions et les mauvaises, puis Il a expliqué cela : quiconque décide d''accomplir une bonne action mais ne la fait pas, Allah la lui inscrit auprès de Lui comme une bonne action complète ; et s''il la décide et l''accomplit, Allah la lui inscrit de dix à sept cents fois sa valeur, et même bien davantage. Quiconque décide de faire une mauvaise action mais ne la fait pas, Allah la lui inscrit auprès de Lui comme une bonne action complète ; et s''il la décide et la fait, Allah la lui inscrit comme une seule mauvaise action. »',
  'Nach Ibn ʿAbbas (möge Allah mit beiden zufrieden sein), vom Gesandten Allahs ﷺ, in dem, was er von seinem Herrn, dem Gesegneten und Erhabenen, überliefert, dass Er sagte: „Wahrlich, Allah, der Erhabene, hat die guten und die schlechten Taten aufgezeichnet, dann erklärte Er das: wer eine gute Tat beabsichtigt, sie aber nicht tut, dem schreibt Allah sie bei Sich als eine vollständige gute Tat an; und wenn er sie beabsichtigt und tut, schreibt Allah sie bei Sich als zehn gute Taten bis zum Siebenhundertfachen und sogar vielfach mehr an. Und wer eine schlechte Tat beabsichtigt, sie aber nicht tut, dem schreibt Allah sie bei Sich als eine vollständige gute Tat an; und wenn er sie beabsichtigt und tut, schreibt Allah sie bei Sich als eine einzige schlechte Tat an."',
  'Op gezag van Ibn ʿAbbas (moge Allah tevreden met hen beiden zijn), van de Boodschapper van Allah ﷺ, in wat hij overlevert van zijn Heer, de Gezegende en Verhevene, dat Hij zei: „Voorwaar, Allah, de Verhevene, heeft de goede en de slechte daden opgetekend, daarna verklaarde Hij dat: wie een goede daad beoogt maar haar niet verricht, hem schrijft Allah haar bij Zich als een volledige goede daad toe; en als hij haar beoogt en verricht, schrijft Allah haar bij Zich als tien goede daden tot zevenhonderdvoud en zelfs veelvoudig meer toe. En wie een slechte daad beoogt maar haar niet verricht, hem schrijft Allah haar bij Zich als een volledige goede daad toe; en als hij haar beoogt en verricht, schrijft Allah haar bij Zich als één enkele slechte daad toe."',
  'İbn Abbâs''tan (Allah her ikisinden de razı olsun), Resûlullah''ın ﷺ Rabbi Tebâreke ve Teâlâ''dan rivayet ettiğine göre buyurdu: „Şüphesiz Allah Teâlâ iyilikleri ve kötülükleri yazdı, sonra bunu açıkladı: kim bir iyiliğe niyetlenir de onu yapmazsa, Allah onu katında tam bir iyilik olarak yazar; eğer niyetlenip de onu yaparsa, Allah onu katında on iyilikten yedi yüz kata, hatta kat kat fazlasına kadar yazar. Kim bir kötülüğe niyetlenir de onu yapmazsa, Allah onu katında tam bir iyilik olarak yazar; eğer niyetlenip de onu yaparsa, Allah onu katında bir tek kötülük olarak yazar."',
  'Dari Ibnu ʿAbbas (semoga Allah meridhai keduanya), dari Rasulullah ﷺ tentang apa yang beliau riwayatkan dari Rabbnya Tabaraka wa Taʿala, bahwa Dia berfirman: "Sesungguhnya Allah Taʿala telah menetapkan kebaikan dan keburukan, kemudian Dia menjelaskannya: barangsiapa berniat melakukan kebaikan lalu tidak mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu kebaikan yang sempurna; jika ia berniat lalu mengerjakannya, Allah menulisnya di sisi-Nya sepuluh kebaikan hingga tujuh ratus kali lipat sampai berlipat-lipat banyaknya. Dan barangsiapa berniat melakukan keburukan lalu tidak mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu kebaikan yang sempurna; jika ia berniat lalu mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu keburukan saja."',
  'ابن عباس رضی اللہ عنہما سے، رسول اللہ ﷺ سے روایت ہے، اس میں جو آپ اپنے رب تبارک و تعالیٰ سے روایت کرتے ہیں کہ اس نے فرمایا: ”بے شک اللہ تعالیٰ نے نیکیاں اور برائیاں لکھ دیں، پھر اسے واضح کیا: جو کسی نیکی کا ارادہ کرے پھر اسے نہ کرے، اللہ اسے اپنے ہاں ایک مکمل نیکی لکھ دیتا ہے؛ اور اگر اس کا ارادہ کرے اور اسے کر لے تو اللہ اسے اپنے ہاں دس نیکیوں سے سات سو گنا تک، بلکہ اس سے بھی کئی گنا زیادہ لکھ دیتا ہے۔ اور جو کسی برائی کا ارادہ کرے پھر اسے نہ کرے، اللہ اسے اپنے ہاں ایک مکمل نیکی لکھ دیتا ہے؛ اور اگر اس کا ارادہ کرے اور اسے کر لے تو اللہ اسے اپنے ہاں صرف ایک برائی لکھتا ہے۔“',
  'ইবনে আব্বাস (রাদিয়াল্লাহু আনহুমা) থেকে, রাসূলুল্লাহ ﷺ থেকে বর্ণিত, তিনি যা তাঁর রব তাবারাকা ওয়া তাআলা থেকে বর্ণনা করেন যে তিনি বলেছেন: "নিশ্চয়ই আল্লাহ তাআলা ভালো ও মন্দ কাজসমূহ লিখে রেখেছেন, অতঃপর তা স্পষ্ট করেছেন: যে কোনো ভালো কাজের নিয়ত করে অতঃপর তা না করে, আল্লাহ তা তাঁর নিকট একটি পূর্ণ নেকি লিখে রাখেন; আর যদি সে তার নিয়ত করে ও তা করে, আল্লাহ তা তাঁর নিকট দশ নেকি থেকে সাতশ গুণ পর্যন্ত, বরং আরও বহুগুণ লিখে রাখেন। আর যে কোনো মন্দ কাজের নিয়ত করে অতঃপর তা না করে, আল্লাহ তা তাঁর নিকট একটি পূর্ণ নেকি লিখে রাখেন; আর যদি সে তার নিয়ত করে ও তা করে, আল্লাহ তা তাঁর নিকট কেবল একটি গুনাহ লিখে রাখেন।"',
  'Daripada Ibnu ʿAbbas (semoga Allah meredai keduanya), daripada Rasulullah ﷺ tentang apa yang baginda riwayatkan daripada Tuhannya Tabaraka wa Taʿala, bahawa Dia berfirman: "Sesungguhnya Allah Taʿala telah menetapkan kebaikan dan keburukan, kemudian Dia menjelaskannya: sesiapa yang berniat melakukan kebaikan lalu tidak mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu kebaikan yang sempurna; jika dia berniat lalu mengerjakannya, Allah menulisnya di sisi-Nya sepuluh kebaikan hingga tujuh ratus kali ganda sehingga berganda-ganda banyaknya. Dan sesiapa yang berniat melakukan keburukan lalu tidak mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu kebaikan yang sempurna; jika dia berniat lalu mengerjakannya, Allah menulisnya di sisi-Nya sebagai satu keburukan sahaja."',
  'От Ибн Аббаса (да будет доволен Аллах ими обоими), от Посланника Аллаха ﷺ, в том, что он передаёт от своего Господа, Благословенного и Всевышнего, что Он сказал: «Поистине, Аллах Всевышний записал добрые и дурные деяния, затем разъяснил это: кто вознамерился совершить доброе деяние, но не совершил его, тому Аллах записывает у Себя полное доброе деяние; а если он вознамерился и совершил его, Аллах записывает у Себя от десяти до семисот добрых деяний и даже многократно больше. А кто вознамерился совершить дурное деяние, но не совершил его, тому Аллах записывает у Себя полное доброе деяние; а если он вознамерился и совершил его, Аллах записывает у Себя одно дурное деяние».',
  -- reference
  'Sahih — reported by Al-Bukhari (no. 6491) and Muslim (no. 131), with these very words; also Ahmad (1/310, 360-361) and others',
  'Hadith authentique rapporté par Al-Bukhari (n°6491) et Muslim (n°131), avec ces mêmes mots ; également Ahmad (1/310, 360-361) et d''autres',
  'حديث صحيح، رواه البخاري (رقم ٦٤٩١) ومسلم (رقم ١٣١) بهذه الحروف، وأحمد (١/٣١٠، ٣٦٠-٣٦١) وغيرهم',
  'Sahih — überliefert von Al-Bukhari (Nr. 6491) und Muslim (Nr. 131) mit eben diesen Worten; auch Ahmad (1/310, 360-361) und andere',
  'Sahih — overgeleverd door Al-Bukhari (nr. 6491) en Muslim (nr. 131) met deze exacte woorden; ook Ahmad (1/310, 360-361) en anderen',
  'Sahih — Buhârî (no. 6491) ve Müslim (no. 131) bu lafızlarla rivayet etmiştir; ayrıca Ahmed (1/310, 360-361) ve diğerleri',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (no. 6491) dan Muslim (no. 131) dengan lafal ini; juga Ahmad (1/310, 360-361) dan lainnya',
  'صحیح حدیث، اسے بخاری (نمبر ۶۴۹۱) اور مسلم (نمبر ۱۳۱) نے انہی الفاظ کے ساتھ روایت کیا؛ نیز احمد (۱/۳۱۰، ۳۶۰-۳۶۱) وغیرہ',
  'সহীহ হাদীস — বুখারী (নং ৬৪৯১) ও মুসলিম (নং ১৩১) এই শব্দেই বর্ণনা করেছেন; আরও আহমাদ (১/৩১০, ৩৬০-৩৬১) প্রমুখ',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (no. 6491) dan Muslim (no. 131) dengan lafaz ini; juga Ahmad (1/310, 360-361) dan lain-lain',
  'Достоверный хадис, передали аль-Бухари (№ 6491) и Муслим (№ 131) этими самыми словами; также Ахмад (1/310, 360-361) и другие',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-37-Nawawi-Psalmodie-Arabe.mp3',
  5,
  37
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 37
);
