-- =============================================================================
-- 40 Hadith Nawawi — Hadith 1: "Actions are by intentions"
-- Target collection: public.hadith_collections.id = 2
--
-- Idempotent: guarded by WHERE NOT EXISTS on (collection, position) so re-runs
-- do not create duplicates. Fills all 11 content languages
-- (en, fr, ar, de, nl, tr, id, ur, bn, ms, ru).
-- transcription_ar / translation_ar intentionally absent (Arabic source lives
-- in arabic_text). description_* left NULL by design.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Actions are by intentions',
  'Les actes ne valent que par les intentions',
  'إنما الأعمال بالنيات',
  'Die Taten zählen nur entsprechend den Absichten',
  'Daden worden slechts beoordeeld naar de intenties',
  'Ameller niyetlere göredir',
  'Setiap amal tergantung pada niatnya',
  'اعمال کا دارومدار نیتوں پر ہے',
  'কাজের ফলাফল নিয়তের উপর নির্ভরশীল',
  'Setiap amalan bergantung pada niat',
  'Дела оцениваются по намерениям',
  -- arabic_text (duplicated narration line removed)
  'عَنْ أَمِيرِ الْمُؤْمِنِينَ أَبِي حَفْصٍ عُمَرَ بْنِ الْخَطَّابِ رَضِيَ اللَّهُ عَنْهُ قَالَ: سَمِعْتُ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يَقُولُ: «إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى، فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ فَهِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ، وَمَنْ كَانَتْ هِجْرَتُهُ لِدُنْيَا يُصِيبُهَا أَوِ امْرَأَةٍ يَنْكِحُهَا فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ»',
  -- transcription
  'On amīri l-muʾminīna Abī Ḥafṣin ʿUmara bni l-Khaṭṭābi raḍiya Llāhu ʿanhu qāla: samiʿtu Rasūla Llāhi ṣalla Llāhu ʿalayhi wa-sallama yaqūlu: innama l-aʿmālu bi-n-niyyāt, wa-innamā li-kulli mriʾin mā nawā, fa-man kānat hijratuhu ilā Llāhi wa-Rasūlihi fa-hijratuhu ilā Llāhi wa-Rasūlih, wa-man kānat hijratuhu li-dunyā yuṣībuhā awi mraʾatin yankiḥuhā fa-hijratuhu ilā mā hājara ilayh.',
  'ʿAn amîri l-mouʾminîna Abî Hafs ʿOumar ibn al-Khattâb (radia Llâhou ʿanhou) qâla : samiʿtou Rassôla Llâhi (salla Llâhou ʿalayhi wa sallam) yaqôlou : innama l-aʿmâlou bi-n-niyyât, wa innamâ li-koulli mriʾin mâ nawâ, fa-man kânat hijratouhou ilâ Llâhi wa Rassôlihi fa-hijratouhou ilâ Llâhi wa Rassôlih, wa man kânat hijratouhou li-dounyâ yousîbouhâ awi mraʾatin yankihouhâ fa-hijratouhou ilâ mâ hâjara ilayh.',
  'ʿAn amīri l-muʾminīna Abī Hafs ʿUmar ibn al-Chattāb (radiya Llāhu ʿanhu) qāla: samiʿtu Rasūla Llāhi (salla Llāhu ʿalaihi wa-sallam) yaqūlu: innama l-aʿmālu bi-n-nijjāt, wa-innamā li-kulli mriʾin mā nawā, fa-man kānat hidschratuhu ilā Llāhi wa-Rasūlihi fa-hidschratuhu ilā Llāhi wa-Rasūlih, wa-man kānat hidschratuhu li-dunyā yusībuhā awi mraʾatin jankihuhā fa-hidschratuhu ilā mā hādschara ilaih.',
  'ʿAn amieri l-moeʾminiena Abie Hafs ʿOemar ibn al-Chattaab (radia Llaahoe ʿanhoe) qaala: samiʿtoe Rasoela Llaahi (salla Llaahoe ʿalaihi wa-sallam) jaqoeloe: innama l-aʿmaaloe bi-n-nijjaat, wa-innamaa li-koelli mriʾin maa nawaa, fa-man kaanat hidzjratoehoe ilaa Llaahi wa-Rasoelihi fa-hidzjratoehoe ilaa Llaahi wa-Rasoelih, wa-man kaanat hidzjratoehoe li-doenjaa joesieboehaa awi mraʾatin jankihoehaa fa-hidzjratoehoe ilaa maa haadzjara ilaih.',
  'Mü''minlerin emiri Ebû Hafs Ömer ibn el-Hattâb (r.a.) dedi ki: Resûlullah''ın (s.a.v.) şöyle dediğini işittim: innema''l-aʿmâlü bi''n-niyyât, ve innemâ li-külli''mriin mâ nevâ, fe-men kânet hicretühû ilâ''llâhi ve resûlihî fe-hicretühû ilâ''llâhi ve resûlih, ve men kânet hicretühû li-dünyâ yusîbühâ evi''mraetin yenkihuhâ fe-hicretühû ilâ mâ hâcera ileyh.',
  'ʿAn amīri l-muʾminīna Abī Ḥafṣ ʿUmar ibn al-Khaṭṭāb (raḍiyallāhu ʿanhu) qāla: samiʿtu Rasūlallāhi (ṣallallāhu ʿalaihi wa sallam) yaqūlu: innamal-aʿmālu bin-niyyāt, wa innamā li-kullimriʾin mā nawā, fa man kānat hijratuhu ilallāhi wa rasūlihi fa hijratuhu ilallāhi wa rasūlih, wa man kānat hijratuhu li-dunyā yuṣībuhā awimraʾatin yankiḥuhā fa hijratuhu ilā mā hājara ilaih.',
  'عَن اَمِیرُالمُومِنِین اَبُو حَفص عُمَر بِن الخطّاب رَضِی اللہ عَنہُ نے فرمایا: میں نے رسول اللہ صلی اللہ علیہ وسلم کو فرماتے سنا: اِنَّمَا الاَعمالُ بِالنِّیّات، وَاِنَّمَا لِکُلِّ امرِئٍ مَا نَوٰی، فَمَن کَانَت ہِجرَتُہُ اِلَی اللہِ وَرَسُولِہِ فَہِجرَتُہُ اِلَی اللہِ وَرَسُولِہِ، وَمَن کَانَت ہِجرَتُہُ لِدُنیَا یُصِیبُہَا اَوِ امرَأَۃٍ یَنکِحُہَا فَہِجرَتُہُ اِلَی مَا ہَاجَرَ اِلَیہِ۔',
  'আন আমীরিল মুমিনীন আবী হাফস উমার ইবনুল খাত্তাব (রাদিয়াল্লাহু আনহু) বলেন: আমি রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম)-কে বলতে শুনেছি: ইন্নামাল আমালু বিন্নিয়্যাত, ওয়া ইন্নামা লিকুল্লিম রিইম মা নাওয়া, ফামান কানাত হিজরাতুহু ইলাল্লাহি ওয়া রাসূলিহি ফাহিজরাতুহু ইলাল্লাহি ওয়া রাসূলিহ, ওয়া মান কানাত হিজরাতুহু লিদুনইয়া ইউসীবুহা আউইম রাআতিন ইয়ানকিহুহা ফাহিজরাতুহু ইলা মা হাজারা ইলাইহ।',
  'ʿAn amiri l-muʾminina Abi Hafs ʿUmar ibn al-Khattab (radiyallahu ʿanhu) berkata: aku mendengar Rasulullah (sallallahu ʿalaihi wa sallam) bersabda: innamal-aʿmalu bin-niyyat, wa innama li-kullimriʾin ma nawa, fa man kanat hijratuhu ilallahi wa rasulihi fa hijratuhu ilallahi wa rasulih, wa man kanat hijratuhu li-dunya yusibuha awimraʾatin yankihuha fa hijratuhu ila ma hajara ilaih.',
  'Ан амири ль-муʾминина Аби Хафс ʿУмара ибн аль-Хаттаб (да будет доволен им Аллах) сказал: я слышал, как Посланник Аллаха (ﷺ) говорил: иннама ль-аʿмалу би-н-ниййат, ва иннама ли-кулли мриʾин ма нава, фа-ман канат хиджратуху иля Ллахи ва-Расулихи фа-хиджратуху иля Ллахи ва-Расулих, ва-ман канат хиджратуху ли-дунья юсибуха ави мраʾатин янкихуха фа-хиджратуху иля ма хаджара иляйх.',
  -- translation
  'The Commander of the Faithful, Abu Hafs ʿUmar ibn al-Khattab (may Allah be pleased with him), reported: I heard the Messenger of Allah ﷺ say: "Actions are but by intentions, and every person will have only what they intended. So whoever''s emigration was for Allah and His Messenger, his emigration is for Allah and His Messenger; and whoever''s emigration was to attain some worldly gain or to marry a woman, his emigration is for that to which he emigrated."',
  'Le prince des croyants Abou Hafs ʿOumar ibn al-Khattâb (qu''Allah l''agrée) rapporte : « J''ai entendu l''Envoyé d''Allah (qu''Allah prie sur lui et le salue) dire : "Les actes ne valent que par les intentions, et à chacun selon son intention. Celui qui émigre pour Allah et Son Messager, son émigration lui sera comptée comme étant pour Allah et Son Messager. Tandis que celui dont l''émigration a pour but d''acquérir des biens de ce bas-monde ou d''épouser une femme, son émigration ne sera comptée que pour ce vers quoi il a émigré." »',
  'Der Befehlshaber der Gläubigen, Abu Hafs ʿUmar ibn al-Khattab (möge Allah mit ihm zufrieden sein), berichtete: Ich hörte den Gesandten Allahs ﷺ sagen: „Die Taten zählen nur entsprechend den Absichten, und jedem Menschen wird nur das zuteil, was er beabsichtigt hat. Wessen Auswanderung für Allah und Seinen Gesandten war, dessen Auswanderung ist für Allah und Seinen Gesandten; und wessen Auswanderung darauf abzielte, weltlichen Gewinn zu erlangen oder eine Frau zu heiraten, dessen Auswanderung ist für das, wozu er ausgewandert ist."',
  'De leider der gelovigen, Abu Hafs ʿUmar ibn al-Khattab (moge Allah tevreden met hem zijn), verhaalde: Ik hoorde de Boodschapper van Allah ﷺ zeggen: „Daden worden slechts beoordeeld naar de intenties, en ieder mens krijgt slechts dat wat hij heeft beoogd. Wiens uittocht (hijra) voor Allah en Zijn Boodschapper was, diens uittocht is voor Allah en Zijn Boodschapper; en wiens uittocht bedoeld was om werelds gewin te verkrijgen of om met een vrouw te trouwen, diens uittocht is voor datgene waarheen hij is uitgeweken."',
  'Mü''minlerin emîri Ebû Hafs Ömer ibn el-Hattâb (Allah ondan razı olsun) şöyle dedi: Resûlullah''ın ﷺ şöyle buyurduğunu işittim: „Ameller ancak niyetlere göredir ve herkese ancak niyet ettiği şey vardır. Kimin hicreti Allah''a ve Resûlü''ne ise, onun hicreti Allah''a ve Resûlü''nedir; kimin hicreti elde edeceği bir dünyalık ya da evleneceği bir kadın için ise, onun hicreti de hicret ettiği şeyedir."',
  'Pemimpin kaum mukminin, Abu Hafs Umar bin al-Khattab (semoga Allah meridhainya), meriwayatkan: Aku mendengar Rasulullah ﷺ bersabda: "Sesungguhnya setiap amal itu tergantung pada niatnya, dan setiap orang hanya memperoleh sesuai apa yang ia niatkan. Maka barangsiapa hijrahnya karena Allah dan Rasul-Nya, maka hijrahnya untuk Allah dan Rasul-Nya; dan barangsiapa hijrahnya karena dunia yang ingin diraihnya atau wanita yang ingin dinikahinya, maka hijrahnya untuk apa yang ia tuju."',
  'امیر المومنین ابو حفص عمر بن الخطاب رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: میں نے رسول اللہ صلی اللہ علیہ وسلم کو فرماتے ہوئے سنا: ”اعمال کا دارومدار نیتوں پر ہے، اور ہر شخص کے لیے وہی کچھ ہے جس کی اس نے نیت کی۔ پس جس کی ہجرت اللہ اور اس کے رسول کی طرف ہو، تو اس کی ہجرت اللہ اور اس کے رسول ہی کی طرف ہے؛ اور جس کی ہجرت دنیا کے کسی فائدے کے لیے ہو جسے وہ حاصل کرنا چاہتا ہو، یا کسی عورت کے لیے ہو جس سے وہ نکاح کرنا چاہتا ہو، تو اس کی ہجرت اسی چیز کی طرف ہے جس کی طرف اس نے ہجرت کی۔“',
  'আমীরুল মুমিনীন আবু হাফস উমার ইবনুল খাত্তাব (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: আমি রাসূলুল্লাহ ﷺ-কে বলতে শুনেছি: "নিশ্চয়ই সমস্ত কাজ নিয়তের উপর নির্ভরশীল, এবং প্রত্যেক ব্যক্তি তা-ই পাবে যা সে নিয়ত করেছে। সুতরাং যার হিজরত আল্লাহ ও তাঁর রাসূলের উদ্দেশ্যে, তার হিজরত আল্লাহ ও তাঁর রাসূলের উদ্দেশ্যেই গণ্য হবে; আর যার হিজরত দুনিয়া অর্জনের জন্য কিংবা কোনো নারীকে বিবাহ করার জন্য, তার হিজরত সেটিরই উদ্দেশ্যে গণ্য হবে যার দিকে সে হিজরত করেছে।"',
  'Pemimpin orang beriman, Abu Hafs Umar bin al-Khattab (semoga Allah meredainya), meriwayatkan: Aku mendengar Rasulullah ﷺ bersabda: "Sesungguhnya setiap amalan itu bergantung pada niat, dan setiap orang hanya memperoleh apa yang diniatkannya. Maka sesiapa yang hijrahnya kerana Allah dan Rasul-Nya, maka hijrahnya adalah untuk Allah dan Rasul-Nya; dan sesiapa yang hijrahnya kerana dunia yang ingin diperolehnya atau wanita yang ingin dinikahinya, maka hijrahnya adalah untuk apa yang ditujuinya."',
  'Повелитель верующих Абу Хафс Умар ибн аль-Хаттаб (да будет доволен им Аллах) передал: Я слышал, как Посланник Аллаха ﷺ сказал: «Поистине, дела оцениваются по намерениям, и каждому человеку достанется лишь то, что он намеревался обрести. Чьё переселение (хиджра) было ради Аллаха и Его Посланника, того переселение — ради Аллаха и Его Посланника; а чьё переселение было ради мирской выгоды, которую он хотел приобрести, или женщины, на которой он хотел жениться, того переселение — ради того, ради чего он переселился».',
  -- reference
  'Sahih — reported by Al-Bukhari (1/9, no. 1) and Muslim (3/1515)',
  'Hadith authentique rapporté par Al-Bukhari (1/9, n°1) et Muslim (3/1515)',
  'حديث صحيح، رواه البخاري (١/٩) (رقم ١) ومسلم (٣/١٥١٥)',
  'Sahih — überliefert von Al-Bukhari (1/9, Nr. 1) und Muslim (3/1515)',
  'Sahih — overgeleverd door Al-Bukhari (1/9, nr. 1) en Muslim (3/1515)',
  'Sahih — Buhârî (1/9, no. 1) ve Müslim (3/1515) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (1/9, no. 1) dan Muslim (3/1515)',
  'صحیح حدیث، اسے بخاری (۱/۹، نمبر ۱) اور مسلم (۳/۱۵۱۵) نے روایت کیا',
  'সহীহ হাদীস — বুখারী (১/৯, নং ১) ও মুসলিম (৩/১৫১৫) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (1/9, no. 1) dan Muslim (3/1515)',
  'Достоверный хадис, передали аль-Бухари (1/9, № 1) и Муслим (3/1515)',
  -- tafsir (Sheikh Ibn al-ʿUthaymin, cleaned)
  'This explanation is that of Shaykh Ibn al-ʿUthaymin. This hadith is a fundamental basis concerning the actions of the heart, for intention is itself an action of the heart. The scholars said that this hadith pertains to half of worship, as it is the scale for inward deeds (aʿmal batina); while the hadith reported by ʿAisha (may Allah be pleased with her) — "Whoever introduces into this affair of ours (Islam) what is not part of it, his innovation is rejected" (and in another version: "Whoever performs a deed not in accordance with our affair, his deed is rejected") — pertains to the other half of the religion, as it is the scale for outward deeds. From the Prophet''s words ﷺ "Actions are but by intentions" we deduce that there is no deed without an intention. Indeed, every rational person, free in his decision, cannot perform a deed without an intention; some scholars went so far as to say: "If Allah were to impose upon us a deed without intention, it would be imposing upon us what we are incapable of." In this deduction lies the answer to those afflicted by scrupulous doubts (waswas), who repeat the same act of worship several times in a row while Shaytan whispers to them: "You have not yet formed the intention." We answer them: "No — you cannot perform a deed without an intention; so relax and abandon these whisperings."',
  'Cette explication est celle du Cheikh Ibn al-ʿUthaymîn. Ce hadith est une base fondamentale concernant les actes du cœur, car l''intention fait partie des actes du cœur. Les savants ont dit que ce hadith concerne la moitié des adorations, car il est la balance des actes intérieurs (aʿmâl bâtina) ; quant au hadith rapporté par ʿÂïcha (qu''Allah l''agrée) — « Celui qui invente dans notre affaire (l''Islam) ce qui n''en fait pas partie, son invention est à rejeter » (et dans une autre version : « Celui qui accomplit un acte qui n''est pas conforme à notre affaire verra son acte rejeté ») —, il concerne l''autre moitié de la religion, car il est la balance des actes apparents. On déduit des paroles du Prophète ﷺ « Les actes ne valent que par les intentions » qu''il n''y a pas d''acte sans intention. En effet, tout homme doté de raison et libre de sa décision ne peut accomplir d''acte sans intention ; certains savants sont allés jusqu''à dire : « Si Allah nous imposait un acte sans intention, ce serait nous imposer ce dont nous sommes incapables. » Dans cette déduction se trouve la réponse à ceux qui sont harcelés par des doutes scrupuleux (waswâs) et qui refont le même acte d''adoration plusieurs fois de suite, tandis que le Chaytân leur chuchote : « Tu n''as pas encore formulé l''intention. » Nous leur répondons : « Non, vous ne pouvez pas accomplir d''acte sans intention ; détendez-vous donc et abandonnez ces suggestions. »',
  'هذا الشرح للشيخ ابن عثيمين. هذا الحديث أصل عظيم في أعمال القلوب، فإن النية من أعمال القلوب. قال العلماء إن هذا الحديث يتعلق بنصف العبادة، لأنه ميزان الأعمال الباطنة؛ وأما حديث عائشة رضي الله عنها: «من أحدث في أمرنا هذا ما ليس منه فهو رد» (وفي رواية: «من عمل عملاً ليس عليه أمرنا فهو رد») فيتعلق بالنصف الآخر من الدين، لأنه ميزان الأعمال الظاهرة. ويُستفاد من قوله صلى الله عليه وسلم «إنما الأعمال بالنيات» أنه لا عمل إلا بنية. فإن كل إنسان عاقل مختار لا يمكن أن يفعل عملاً بلا نية، حتى قال بعض العلماء: «لو كلّفنا الله عملاً بلا نية لكان تكليفاً بما لا يُطاق». وفي هذا الاستنباط الرد على الموسوسين الذين يكررون العبادة الواحدة مراراً، ويوسوس لهم الشيطان: «إنك لم تنوِ بعد». فنقول لهم: «لا، لا يمكن أن تعمل عملاً بلا نية، فاطمئن ودع عنك هذه الوساوس».',
  'Diese Erläuterung stammt von Scheich Ibn al-ʿUthaimin. Dieser Hadith ist eine grundlegende Basis für die Taten des Herzens, denn die Absicht gehört zu den Taten des Herzens. Die Gelehrten sagten, dass dieser Hadith die Hälfte der Gottesdienste betrifft, da er die Waage der inneren Taten (aʿmal batina) ist; während der von ʿAischa (möge Allah mit ihr zufrieden sein) überlieferte Hadith — „Wer in diese unsere Angelegenheit (den Islam) etwas einführt, das nicht dazugehört, dessen Neuerung wird zurückgewiesen" (und in einer anderen Version: „Wer eine Tat verrichtet, die nicht unserer Angelegenheit entspricht, dessen Tat wird zurückgewiesen") — die andere Hälfte der Religion betrifft, da er die Waage der äußeren Taten ist. Aus den Worten des Propheten ﷺ „Die Taten zählen nur entsprechend den Absichten" leiten wir ab, dass es keine Tat ohne Absicht gibt. Tatsächlich kann kein vernünftiger, frei entscheidender Mensch eine Tat ohne Absicht verrichten; manche Gelehrte gingen so weit zu sagen: „Würde Allah uns eine Tat ohne Absicht auferlegen, so wäre dies eine Auferlegung dessen, wozu wir nicht imstande sind." In dieser Ableitung liegt die Antwort an jene, die von zwanghaften Zweifeln (Waswas) geplagt werden und denselben Gottesdienst mehrmals hintereinander wiederholen, während Schaitan ihnen einflüstert: „Du hast die Absicht noch nicht gefasst." Wir antworten ihnen: „Nein — du kannst keine Tat ohne Absicht verrichten; sei also ruhig und lass von diesen Einflüsterungen ab."',
  'Deze uitleg is van Sjeik Ibn al-ʿUthaymin. Deze hadith is een fundamentele basis voor de daden van het hart, want de intentie behoort tot de daden van het hart. De geleerden zeiden dat deze hadith de helft van de aanbidding betreft, omdat hij de weegschaal van de innerlijke daden (aʿmal batina) is; terwijl de hadith overgeleverd door ʿAisha (moge Allah tevreden met haar zijn) — „Wie in deze zaak van ons (de islam) iets invoert dat er geen deel van uitmaakt, diens innovatie wordt verworpen" (en in een andere versie: „Wie een daad verricht die niet in overeenstemming is met onze zaak, diens daad wordt verworpen") — de andere helft van de religie betreft, omdat hij de weegschaal van de uiterlijke daden is. Uit de woorden van de Profeet ﷺ „Daden worden slechts beoordeeld naar de intenties" leiden wij af dat er geen daad is zonder intentie. Immers, geen enkel verstandig mens die vrij is in zijn beslissing kan een daad verrichten zonder intentie; sommige geleerden gingen zelfs zo ver te zeggen: „Als Allah ons een daad zonder intentie zou opleggen, zou dat ons iets opleggen waartoe wij niet in staat zijn." In deze afleiding ligt het antwoord op hen die geplaagd worden door dwangmatige twijfels (waswas) en dezelfde aanbidding meerdere keren achter elkaar herhalen, terwijl Sjaytan hun influistert: „Je hebt de intentie nog niet gevormd." Wij antwoorden hun: „Nee — je kunt geen daad verrichten zonder intentie; wees dus gerust en laat deze influisteringen los."',
  'Bu açıklama Şeyh İbn Useymîn''e aittir. Bu hadis, kalbin amelleri konusunda temel bir esastır; zira niyet, kalbin amellerindendir. Âlimler, bu hadisin ibadetin yarısını ilgilendirdiğini söylemişlerdir, çünkü o, bâtınî amellerin (aʿmâl bâtına) ölçüsüdür; Âişe''den (Allah ondan razı olsun) rivayet edilen „Kim bizim bu işimizde (İslâm''da) ondan olmayan bir şey ortaya çıkarırsa, o reddedilir" (bir başka rivayette: „Kim bizim işimize uygun olmayan bir amel işlerse, o reddedilir") hadisi ise dinin diğer yarısını ilgilendirir, çünkü o, zâhirî amellerin ölçüsüdür. Peygamber''in ﷺ „Ameller ancak niyetlere göredir" sözünden, niyetsiz amel olmayacağı çıkarılır. Zira akıl sahibi, kararında özgür hiçbir insan niyetsiz bir amel işleyemez; hatta bazı âlimler şöyle demiştir: „Allah bize niyetsiz bir amel yükleseydi, bu bize güç yetiremeyeceğimiz bir şeyi yüklemek olurdu." Bu çıkarımda, vesveseye (vesvâs) tutulup aynı ibadeti arka arkaya birkaç kez tekrarlayan ve Şeytan''ın kendilerine „Henüz niyet etmedin" diye fısıldadığı kimselere cevap vardır. Onlara deriz ki: „Hayır — niyetsiz bir amel işleyemezsin; öyleyse rahatla ve bu vesveseleri bırak."',
  'Penjelasan ini berasal dari Syaikh Ibnu Utsaimin. Hadis ini merupakan dasar yang fundamental tentang amalan hati, karena niat termasuk amalan hati. Para ulama mengatakan bahwa hadis ini berkaitan dengan separuh ibadah, karena ia adalah timbangan amalan batin (aʿmal batina); sedangkan hadis yang diriwayatkan oleh Aisyah (semoga Allah meridhainya) — "Barangsiapa mengada-adakan dalam urusan kami ini (Islam) sesuatu yang bukan darinya, maka itu tertolak" (dalam riwayat lain: "Barangsiapa melakukan suatu amal yang tidak sesuai dengan urusan kami, maka itu tertolak") — berkaitan dengan separuh agama yang lain, karena ia adalah timbangan amalan lahir. Dari sabda Nabi ﷺ "Sesungguhnya setiap amal tergantung pada niatnya" disimpulkan bahwa tidak ada amal tanpa niat. Sesungguhnya setiap orang yang berakal dan bebas dalam keputusannya tidak mungkin melakukan suatu amal tanpa niat; sebagian ulama bahkan berkata: "Seandainya Allah membebani kita suatu amal tanpa niat, niscaya itu membebani kita dengan sesuatu yang tidak sanggup kita lakukan." Dalam kesimpulan ini terdapat jawaban bagi mereka yang dilanda keraguan berlebihan (waswas), yang mengulang-ulang ibadah yang sama beberapa kali, sementara setan membisikkan kepada mereka: "Engkau belum berniat." Kami menjawab mereka: "Tidak — engkau tidak mungkin melakukan amal tanpa niat; maka tenanglah dan tinggalkan bisikan-bisikan ini."',
  'یہ شرح شیخ ابن عثیمین کی ہے۔ یہ حدیث اعمالِ قلب کے بارے میں ایک بنیادی اصول ہے، کیونکہ نیت قلبی اعمال میں سے ہے۔ علماء نے کہا ہے کہ یہ حدیث عبادت کے نصف حصے سے متعلق ہے، کیونکہ یہ باطنی اعمال کی میزان ہے؛ جبکہ عائشہ رضی اللہ عنہا سے مروی حدیث — ”جس نے ہمارے اس دین میں کوئی ایسی نئی چیز ایجاد کی جو اس میں سے نہیں، تو وہ مردود ہے“ (اور ایک روایت میں: ”جس نے کوئی ایسا عمل کیا جس پر ہمارا حکم نہیں، تو وہ مردود ہے“) — دین کے دوسرے نصف حصے سے متعلق ہے، کیونکہ یہ ظاہری اعمال کی میزان ہے۔ نبی ﷺ کے فرمان ”اعمال کا دارومدار نیتوں پر ہے“ سے یہ اخذ کیا جاتا ہے کہ نیت کے بغیر کوئی عمل نہیں۔ درحقیقت ہر عقل مند اور اپنے فیصلے میں آزاد انسان نیت کے بغیر کوئی عمل نہیں کر سکتا؛ بعض علماء تو یہاں تک کہہ گئے: ”اگر اللہ ہمیں نیت کے بغیر کسی عمل کا مکلف بناتا تو یہ ہمیں اس چیز کا مکلف بنانا ہوتا جس کی ہم میں طاقت نہیں۔“ اس استنباط میں ان لوگوں کا جواب ہے جو وسوسوں میں مبتلا ہیں اور ایک ہی عبادت کو بار بار دہراتے ہیں، جبکہ شیطان انہیں وسوسہ دیتا ہے: ”تم نے ابھی نیت نہیں کی۔“ ہم انہیں کہتے ہیں: ”نہیں، تم نیت کے بغیر کوئی عمل کر ہی نہیں سکتے؛ لہٰذا مطمئن رہو اور ان وسوسوں کو چھوڑ دو۔“',
  'এই ব্যাখ্যাটি শায়খ ইবনু উসাইমীনের। এই হাদীসটি অন্তরের আমল সম্পর্কে একটি মৌলিক ভিত্তি, কারণ নিয়ত অন্তরের আমলের অন্তর্ভুক্ত। আলেমগণ বলেছেন যে এই হাদীসটি ইবাদতের অর্ধেকের সাথে সম্পর্কিত, কারণ এটি অভ্যন্তরীণ আমলের (আমালে বাতিনা) মানদণ্ড; আর আয়েশা (রাদিয়াল্লাহু আনহা) থেকে বর্ণিত হাদীস — "যে ব্যক্তি আমাদের এই দ্বীনের মধ্যে এমন কিছু নতুন উদ্ভাবন করে যা তার অন্তর্ভুক্ত নয়, তা প্রত্যাখ্যাত" (অন্য বর্ণনায়: "যে ব্যক্তি এমন আমল করে যা আমাদের নির্দেশের অনুরূপ নয়, তা প্রত্যাখ্যাত") — দ্বীনের অপর অর্ধেকের সাথে সম্পর্কিত, কারণ এটি প্রকাশ্য আমলের মানদণ্ড। নবী ﷺ-এর বাণী "কাজের ফলাফল নিয়তের উপর নির্ভরশীল" থেকে অনুমান করা যায় যে নিয়ত ছাড়া কোনো আমল নেই। প্রকৃতপক্ষে, প্রতিটি বুদ্ধিমান ও স্বাধীন সিদ্ধান্তের অধিকারী মানুষ নিয়ত ছাড়া কোনো আমল করতে পারে না; কিছু আলেম এমনকি বলেছেন: "যদি আল্লাহ আমাদের উপর নিয়ত ছাড়া কোনো আমল ফরজ করতেন, তবে তা আমাদের সাধ্যের বাইরে কিছু চাপিয়ে দেওয়া হতো।" এই সিদ্ধান্তের মধ্যে রয়েছে তাদের জবাব যারা ওয়াসওয়াসায় (অতিরিক্ত সন্দেহে) আক্রান্ত এবং একই ইবাদত বারবার পুনরাবৃত্তি করে, যখন শয়তান তাদের কুমন্ত্রণা দেয়: "তুমি এখনও নিয়ত করোনি।" আমরা তাদের বলি: "না — তুমি নিয়ত ছাড়া কোনো আমল করতেই পারো না; সুতরাং নিশ্চিন্ত থাকো এবং এই কুমন্ত্রণাগুলো ত্যাগ করো।"',
  'Penjelasan ini adalah daripada Syeikh Ibnu Uthaimin. Hadis ini merupakan asas yang fundamental tentang amalan hati, kerana niat termasuk dalam amalan hati. Para ulama menyatakan bahawa hadis ini berkaitan dengan separuh ibadah, kerana ia adalah neraca amalan batin (aʿmal batina); manakala hadis yang diriwayatkan oleh Aisyah (semoga Allah meredainya) — "Sesiapa yang mengada-adakan dalam urusan kami ini (Islam) sesuatu yang bukan daripadanya, maka ia tertolak" (dalam riwayat lain: "Sesiapa yang melakukan sesuatu amalan yang tidak menepati urusan kami, maka ia tertolak") — berkaitan dengan separuh agama yang lain, kerana ia adalah neraca amalan zahir. Daripada sabda Nabi ﷺ "Sesungguhnya setiap amalan bergantung pada niat" disimpulkan bahawa tiada amalan tanpa niat. Sesungguhnya setiap orang yang berakal dan bebas dalam keputusannya tidak mungkin melakukan sesuatu amalan tanpa niat; sebahagian ulama bahkan berkata: "Sekiranya Allah membebankan kita suatu amalan tanpa niat, nescaya itu membebankan kita dengan sesuatu yang tidak terdaya kita lakukan." Dalam kesimpulan ini terdapat jawapan bagi mereka yang dilanda was-was, yang mengulangi ibadah yang sama beberapa kali, sementara syaitan membisikkan kepada mereka: "Engkau belum berniat." Kami menjawab mereka: "Tidak — engkau tidak mungkin melakukan amalan tanpa niat; maka bertenanglah dan tinggalkan bisikan-bisikan ini."',
  'Это толкование принадлежит шейху Ибн аль-Усаймину. Этот хадис является фундаментальной основой для деяний сердца, ведь намерение относится к деяниям сердца. Учёные сказали, что этот хадис касается половины поклонения, поскольку он — мера внутренних деяний (аʿмаль батина); тогда как хадис, переданный Аишей (да будет доволен ею Аллах) — «Кто внесёт в это наше дело (Ислам) то, что не относится к нему, нововведение его отвергается» (а в другой версии: «Кто совершит деяние, не соответствующее нашему делу, оно будет отвергнуто») — касается другой половины религии, ибо он — мера внешних деяний. Из слов Пророка ﷺ «Поистине, дела оцениваются по намерениям» выводится, что нет деяния без намерения. Ведь ни один разумный человек, свободный в своём решении, не может совершить деяние без намерения; некоторые учёные дошли до того, что сказали: «Если бы Аллах возложил на нас деяние без намерения, это было бы возложением того, что нам не под силу». В этом выводе — ответ тем, кого одолевают наваждения сомнений (васвас) и кто повторяет одно и то же поклонение несколько раз подряд, в то время как Шайтан нашёптывает им: «Ты ещё не вознамерился». Мы отвечаем им: «Нет — ты не можешь совершить деяние без намерения; так успокойся же и оставь эти наваждения».',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-1-Nawawi-Psalmodie-Arabe.mp3',
  5,
  1
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 1
);
