-- =============================================================================
-- 40 Hadith Nawawi — Hadith 25: "The broad meaning of charity (sadaqah)"
-- Target collection: public.hadith_collections.id = 2  /  position = 25
-- Idempotent guard on (collection, position). All 11 content languages.
-- Arabic cleaned: وفي بعض أحد كم -> وفي بُضْعِ أحدكم.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'The broad meaning of charity',
  'Le sens large de l''aumône',
  'سعة معنى الصدقة',
  'Die weite Bedeutung der Wohltätigkeit',
  'De ruime betekenis van liefdadigheid',
  'Sadakanın geniş manası',
  'Luasnya makna sedekah',
  'صدقے کا وسیع مفہوم',
  'সদকার ব্যাপক অর্থ',
  'Luasnya makna sedekah',
  'Широкий смысл милостыни',
  -- arabic_text (cleaned)
  'عَنْ أَبِي ذَرٍّ رَضِيَ اللَّهُ عَنْهُ أَيْضًا أَنَّ نَاسًا مِنْ أَصْحَابِ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالُوا لِلنَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: يَا رَسُولَ اللَّهِ، ذَهَبَ أَهْلُ الدُّثُورِ بِالْأُجُورِ، يُصَلُّونَ كَمَا نُصَلِّي، وَيَصُومُونَ كَمَا نَصُومُ، وَيَتَصَدَّقُونَ بِفُضُولِ أَمْوَالِهِمْ. قَالَ: «أَوَلَيْسَ قَدْ جَعَلَ اللَّهُ لَكُمْ مَا تَصَّدَّقُونَ؟ إِنَّ بِكُلِّ تَسْبِيحَةٍ صَدَقَةً، وَكُلِّ تَكْبِيرَةٍ صَدَقَةً، وَكُلِّ تَحْمِيدَةٍ صَدَقَةً، وَكُلِّ تَهْلِيلَةٍ صَدَقَةً، وَأَمْرٌ بِالْمَعْرُوفِ صَدَقَةٌ، وَنَهْيٌ عَنِ الْمُنْكَرِ صَدَقَةٌ، وَفِي بُضْعِ أَحَدِكُمْ صَدَقَةٌ». قَالُوا: يَا رَسُولَ اللَّهِ، أَيَأْتِي أَحَدُنَا شَهْوَتَهُ وَيَكُونُ لَهُ فِيهَا أَجْرٌ؟ قَالَ: «أَرَأَيْتُمْ لَوْ وَضَعَهَا فِي حَرَامٍ أَكَانَ عَلَيْهِ وِزْرٌ؟ فَكَذَلِكَ إِذَا وَضَعَهَا فِي الْحَلَالِ كَانَ لَهُ أَجْرٌ»',
  -- transcription
  'ʿan Abī Dharrin raḍiya Llāhu ʿanhu ayḍan anna nāsan min aṣḥābi Rasūli Llāhi ṣalla Llāhu ʿalayhi wa-sallama qālū li-n-Nabiyyi ṣalla Llāhu ʿalayhi wa-sallama: yā Rasūla Llāhi, dhahaba ahlu d-duthūri bi-l-ujūri, yuṣallūna kamā nuṣallī, wa-yaṣūmūna kamā naṣūmu, wa-yataṣaddaqūna bi-fuḍūli amwālihim. qāla: a-wa-laysa qad jaʿala Llāhu lakum mā taṣṣaddaqūna? inna bi-kulli tasbīḥatin ṣadaqatan, wa-kulli takbīratin ṣadaqatan, wa-kulli taḥmīdatin ṣadaqatan, wa-kulli tahlīlatin ṣadaqatan, wa-amrun bi-l-maʿrūfi ṣadaqatun, wa-nahyun ʿani l-munkari ṣadaqatun, wa-fī buḍʿi aḥadikum ṣadaqatun. qālū: yā Rasūla Llāhi, a-yaʾtī aḥadunā shahwatahu wa-yakūnu lahu fīhā ajrun? qāla: a-raʾaytum law waḍaʿahā fī ḥarāmin a-kāna ʿalayhi wizrun? fa-ka-dhālika idhā waḍaʿahā fi l-ḥalāli kāna lahu ajrun.',
  'ʿan Abî Dharrin (radia Llâhou ʿanhou) aydan anna nâsan min ashâbi Rassôli Llâhi (salla Llâhou ʿalayhi wa sallam) qâlô li-n-Nabiyyi (salla Llâhou ʿalayhi wa sallam) : yâ Rassôla Llâhi, dhahaba ahlou d-douthôuri bi-l-oujôuri, yousallôuna kamâ nousallî, wa yasôumôuna kamâ nasôumou, wa yatasaddaqôuna bi-foudôuli amwâlihim. qâla : a-wa-laysa qad jaʿala Llâhou lakoum mâ tassaddaqôuna ? inna bi-koulli tasbîhatin sadaqatan, wa koulli takbîratin sadaqatan, wa koulli tahmîdatin sadaqatan, wa koulli tahlîlatin sadaqatan, wa amroun bi-l-maʿrôufi sadaqatoun, wa nahyoun ʿani l-mounkari sadaqatoun, wa fî boudʿi ahadikoum sadaqatoun. qâlô : yâ Rassôla Llâhi, a-yaʾtî ahadounâ chahwatahou wa yakôunou lahou fîhâ ajroun ? qâla : a-raʾaytoum law wadaʿahâ fî harâmin a-kâna ʿalayhi wizroun ? fa-ka-dhâlika idhâ wadaʿahâ fi l-halâli kâna lahou ajroun.',
  'ʿan Abī Dharrin (radiya Llāhu ʿanhu) aidan anna nāsan min ashābi Rasūli Llāhi (salla Llāhu ʿalaihi wa-sallam) qālū li-n-Nabijji (salla Llāhu ʿalaihi wa-sallam): jā Rasūla Llāhi, dhahaba ahlu d-duthūri bi-l-udschūri, jusallūna kamā nusallī, wa-jasūmūna kamā nasūmu, wa-jatasaddaqūna bi-fudūli amwālihim. qāla: a-wa-laisa qad dschaʿala Llāhu lakum mā tassaddaqūna? inna bi-kulli tasbīhatin sadaqatan, wa-kulli takbīratin sadaqatan, wa-kulli tahmīdatin sadaqatan, wa-kulli tahlīlatin sadaqatan, wa-amrun bi-l-maʿrūfi sadaqatun, wa-nahjun ʿani l-munkari sadaqatun, wa-fī budʿi ahadikum sadaqatun. qālū: jā Rasūla Llāhi, a-jaʾtī ahadunā schahwatahu wa-jakūnu lahu fīhā adschrun? qāla: a-raʾaitum law wadaʿahā fī harāmin a-kāna ʿalaihi wizrun? fa-ka-dhālika idhā wadaʿahā fi l-halāli kāna lahu adschrun.',
  'ʿan Abie Dharrin (radia Llaahoe ʿanhoe) aidan anna naasan min ashaabi Rasoeli Llaahi (salla Llaahoe ʿalaihi wa-sallam) qaaloe li-n-Nabijji (salla Llaahoe ʿalaihi wa-sallam): jaa Rasoela Llaahi, dhahaba ahloe d-doethoeri bi-l-oedzjoeri, joesalloena kamaa noesallie, wa-jasoemoena kamaa nasoemoe, wa-jatasaddaqoena bi-foedoeli amwaalihim. qaala: a-wa-laisa qad dzjaʿala Llaahoe lakoem maa tassaddaqoena? inna bi-koelli tasbiehatin sadaqatan, wa-koelli takbieratin sadaqatan, wa-koelli tahmiedatin sadaqatan, wa-koelli tahlielatin sadaqatan, wa-amroen bi-l-maʿroefi sadaqatoen, wa-nahjoen ʿani l-moenkari sadaqatoen, wa-fie boedʿi ahadikoem sadaqatoen. qaaloe: jaa Rasoela Llaahi, a-jaʾtie ahadoenaa sjahwatahoe wa-jakoenoe lahoe fiehaa adzjroen? qaala: a-raʾaitoem law wadaʿahaa fie haraamin a-kaana ʿalaihi wizroen? fa-ka-dhaalika idhaa wadaʿahaa fi l-halaali kaana lahoe adzjroen.',
  'an Ebî Zer''den (radıyallâhu anh) yine rivayetle, Resûlullah''ın (s.a.v.) ashabından bazı kimseler Nebî''ye (s.a.v.) dediler ki: yâ Resûlallah, servet sahipleri ecirleri alıp götürdüler; bizim kıldığımız gibi namaz kılıyor, bizim tuttuğumuz gibi oruç tutuyor ve mallarının fazlasından sadaka veriyorlar. Buyurdu: Allah size de sadaka verebileceğiniz şeyler kılmadı mı? Her tesbih bir sadakadır, her tekbir bir sadakadır, her tahmid bir sadakadır, her tehlil bir sadakadır, marufu emretmek bir sadakadır, münkerden nehyetmek bir sadakadır, hatta birinizin eşiyle münasebetinde de bir sadaka vardır. Dediler ki: yâ Resûlallah, birimiz şehvetini giderir de bunda ona ecir mi olur? Buyurdu: ne dersiniz, onu harama koysa günah olmaz mıydı? İşte onu helale koyduğunda da ona ecir olur.',
  'an Abi Dzarrin (radhiyallahu ʿanhu) juga, bahwa beberapa orang dari sahabat Rasulullah (shallallahu ʿalaihi wa sallam) berkata kepada Nabi (shallallahu ʿalaihi wa sallam): wahai Rasulullah, orang-orang kaya telah memborong pahala; mereka shalat sebagaimana kami shalat, berpuasa sebagaimana kami berpuasa, dan bersedekah dengan kelebihan harta mereka. Beliau bersabda: bukankah Allah telah menjadikan bagi kalian sesuatu yang dapat kalian sedekahkan? Sesungguhnya setiap tasbih adalah sedekah, setiap takbir adalah sedekah, setiap tahmid adalah sedekah, setiap tahlil adalah sedekah, menyuruh kepada kebaikan adalah sedekah, mencegah kemungkaran adalah sedekah, dan pada hubungan suami-istri salah seorang dari kalian pun ada sedekah. Mereka berkata: wahai Rasulullah, apakah salah seorang dari kami menunaikan syahwatnya lalu ia mendapat pahala padanya? Beliau bersabda: bagaimana pendapat kalian, seandainya ia meletakkannya pada yang haram, bukankah ia berdosa? Maka demikian pula apabila ia meletakkannya pada yang halal, ia mendapat pahala.',
  'ابو ذر رضی اللہ عنہ سے بھی روایت ہے کہ رسول اللہ صلی اللہ علیہ وسلم کے کچھ صحابہ نے نبی صلی اللہ علیہ وسلم سے کہا: یا رسول اللہ! مالدار لوگ اجر و ثواب لے گئے؛ وہ نماز پڑھتے ہیں جیسے ہم پڑھتے ہیں، روزے رکھتے ہیں جیسے ہم رکھتے ہیں، اور اپنے مال کی زیادتی سے صدقہ بھی کرتے ہیں۔ آپ نے فرمایا: کیا اللہ نے تمہارے لیے بھی ایسی چیزیں نہیں رکھیں جن سے تم صدقہ کر سکو؟ ہر تسبیح صدقہ ہے، ہر تکبیر صدقہ ہے، ہر تحمید صدقہ ہے، ہر تہلیل صدقہ ہے، نیکی کا حکم دینا صدقہ ہے، برائی سے روکنا صدقہ ہے، اور تم میں سے کسی کے اپنی بیوی سے ہمبستری میں بھی صدقہ ہے۔ انہوں نے کہا: یا رسول اللہ! کیا ہم میں سے کوئی اپنی شہوت پوری کرے اور اس میں بھی اسے اجر ملے؟ فرمایا: بتاؤ، اگر وہ اسے حرام میں رکھتا تو کیا اس پر گناہ نہ ہوتا؟ پس اسی طرح جب وہ اسے حلال میں رکھتا ہے تو اسے اجر ملتا ہے۔',
  'আবু যার (রাদিয়াল্লাহু আনহু) থেকে আরও বর্ণিত যে রাসূলুল্লাহ ﷺ-এর কিছু সাহাবী নবী ﷺ-কে বললেন: হে আল্লাহর রাসূল! ধনী লোকেরা সওয়াব নিয়ে গেল; তারা আমাদের মতো সালাত আদায় করে, আমাদের মতো সিয়াম পালন করে, এবং তাদের সম্পদের উদ্বৃত্ত থেকে সদকাও করে। তিনি বললেন: আল্লাহ কি তোমাদের জন্যও এমন কিছু রাখেননি যা দিয়ে তোমরা সদকা করতে পারো? প্রতিটি তাসবীহ সদকা, প্রতিটি তাকবীর সদকা, প্রতিটি তাহমীদ সদকা, প্রতিটি তাহলীল সদকা, ভালো কাজের আদেশ সদকা, মন্দ কাজ থেকে নিষেধ সদকা, এবং তোমাদের কারো স্ত্রীর সাথে সহবাসেও সদকা রয়েছে। তারা বললেন: হে আল্লাহর রাসূল! আমাদের কেউ কি তার কামনা পূর্ণ করবে আর তাতেও তার সওয়াব হবে? তিনি বললেন: বলো তো, যদি সে তা হারামে স্থাপন করত তবে কি তার গুনাহ হতো না? সুতরাং অনুরূপভাবে যখন সে তা হালালে স্থাপন করে তখন তার সওয়াব হয়।',
  'an Abi Dzarrin (radhiallahu ʿanhu) juga, bahawa beberapa orang daripada sahabat Rasulullah (sallallahu ʿalaihi wa sallam) berkata kepada Nabi (sallallahu ʿalaihi wa sallam): wahai Rasulullah, orang-orang kaya telah memborong pahala; mereka solat sebagaimana kami solat, berpuasa sebagaimana kami berpuasa, dan bersedekah dengan lebihan harta mereka. Baginda bersabda: bukankah Allah telah menjadikan bagi kamu sesuatu yang boleh kamu sedekahkan? Sesungguhnya setiap tasbih adalah sedekah, setiap takbir adalah sedekah, setiap tahmid adalah sedekah, setiap tahlil adalah sedekah, menyuruh kepada kebaikan adalah sedekah, mencegah kemungkaran adalah sedekah, dan pada hubungan suami-isteri seseorang daripada kamu pun ada sedekah. Mereka berkata: wahai Rasulullah, adakah seseorang daripada kami menunaikan syahwatnya lalu dia mendapat pahala padanya? Baginda bersabda: bagaimana pendapat kamu, seandainya dia meletakkannya pada yang haram, bukankah dia berdosa? Maka demikian jugalah apabila dia meletakkannya pada yang halal, dia mendapat pahala.',
  'От Аби Зарра (да будет доволен им Аллах) также передаётся, что некоторые из сподвижников Посланника Аллаха ﷺ сказали Пророку ﷺ: о Посланник Аллаха, обладатели богатства унесли награды; они молятся, как молимся мы, постятся, как постимся мы, и сверх того раздают милостыню из излишка своего имущества. Он сказал: разве Аллах не сделал и для вас то, чем вы можете давать милостыню? Поистине, каждое прославление (тасбих) — милостыня, каждое возвеличивание (такбир) — милостыня, каждая хвала (тахмид) — милостыня, каждое свидетельство единобожия (тахлиль) — милостыня, повеление одобряемого — милостыня, удержание от порицаемого — милостыня, и в близости одного из вас (с супругой) — милостыня. Они сказали: о Посланник Аллаха, неужели один из нас удовлетворяет свою страсть и получает за это награду? Он сказал: скажите, если бы он поместил её в запретное, был бы на нём грех? Так же и когда он помещает её в дозволенное, ему за это награда.',
  -- translation
  'On the authority of Abu Dharr (may Allah be pleased with him) also: Some of the Companions of the Messenger of Allah ﷺ said to the Prophet ﷺ: "O Messenger of Allah, the wealthy have taken away the rewards; they pray as we pray, they fast as we fast, and they give charity from the surplus of their wealth." He said: "Has Allah not given you that with which you can give charity? Every glorification (tasbih) is a charity, every magnification (takbir) is a charity, every praise (tahmid) is a charity, every declaration of Allah''s oneness (tahlil) is a charity, enjoining good is a charity, forbidding evil is a charity, and in the intimate relation of one of you (with his spouse) there is a charity." They said: "O Messenger of Allah, does one of us satisfy his desire and have a reward for it?" He said: "Do you not see that if he were to put it in the unlawful, he would bear a sin? So likewise, when he puts it in the lawful, he has a reward."',
  'D''après Abû Dharr (qu''Allah l''agrée) également : Quelques compagnons de l''Envoyé d''Allah ﷺ dirent au Prophète ﷺ : « Ô Envoyé d''Allah, les gens riches ont emporté les récompenses ; ils prient comme nous prions, jeûnent comme nous jeûnons, et font en plus l''aumône du surplus de leurs richesses. » Il dit : « Allah n''a-t-Il pas mis à votre portée de quoi faire l''aumône ? Chaque glorification (tasbîh) est une aumône, chaque magnification (takbîr) est une aumône, chaque louange (tahmîd) est une aumône, chaque attestation de l''unicité (tahlîl) est une aumône, ordonner le convenable est une aumône, interdire le blâmable est une aumône, et dans l''union intime de l''un de vous (avec son épouse) il y a une aumône. » Ils dirent : « Ô Envoyé d''Allah, l''un de nous satisfait son désir et en reçoit en plus un salaire ? » Il dit : « Ne voyez-vous pas que s''il le plaçait dans l''illicite, il commettrait un péché ? De même, lorsqu''il le place dans le licite, il en reçoit un salaire. »',
  'Nach Abu Dharr (möge Allah mit ihm zufrieden sein) ebenfalls: Einige der Gefährten des Gesandten Allahs ﷺ sagten zum Propheten ﷺ: „O Gesandter Allahs, die Wohlhabenden haben die Belohnungen davongetragen; sie beten, wie wir beten, fasten, wie wir fasten, und geben darüber hinaus Almosen vom Überschuss ihres Vermögens." Er sagte: „Hat Allah euch nicht das gegeben, womit ihr Almosen geben könnt? Jede Lobpreisung (Tasbih) ist ein Almosen, jede Größpreisung (Takbir) ist ein Almosen, jedes Lob (Tahmid) ist ein Almosen, jedes Bekenntnis der Einheit (Tahlil) ist ein Almosen, das Gebieten des Guten ist ein Almosen, das Verbieten des Schlechten ist ein Almosen, und im ehelichen Beiwohnen eines von euch ist ein Almosen." Sie sagten: „O Gesandter Allahs, befriedigt einer von uns sein Verlangen und hat dafür auch noch eine Belohnung?" Er sagte: „Seht ihr nicht, dass er, wenn er es ins Verbotene legte, eine Sünde auf sich lüde? Ebenso, wenn er es ins Erlaubte legt, hat er eine Belohnung."',
  'Op gezag van Abu Dharr (moge Allah tevreden met hem zijn) eveneens: Enkele van de metgezellen van de Boodschapper van Allah ﷺ zeiden tegen de Profeet ﷺ: „O Boodschapper van Allah, de welgestelden hebben de beloningen weggedragen; zij bidden zoals wij bidden, vasten zoals wij vasten, en geven bovendien aalmoezen van het overschot van hun rijkdom." Hij zei: „Heeft Allah jullie niet gegeven waarmee jullie aalmoezen kunnen geven? Elke verheerlijking (tasbih) is een aalmoes, elke vergroting (takbir) is een aalmoes, elke lofprijzing (tahmid) is een aalmoes, elke verklaring van Allahs eenheid (tahlil) is een aalmoes, het goede gebieden is een aalmoes, het slechte verbieden is een aalmoes, en in de intieme omgang van een van jullie (met zijn echtgenote) is een aalmoes." Zij zeiden: „O Boodschapper van Allah, bevredigt een van ons zijn verlangen en heeft hij daar ook nog een beloning voor?" Hij zei: „Zien jullie niet dat hij, als hij het in het verbodene zou plaatsen, een zonde zou dragen? Zo ook, wanneer hij het in het toegestane plaatst, heeft hij een beloning."',
  'Ebû Zer''den (Allah ondan razı olsun) yine: Resûlullah''ın ﷺ ashabından bazıları Peygamber''e ﷺ dediler ki: „Yâ Resûlallah, servet sahipleri ecirleri alıp götürdüler; bizim kıldığımız gibi namaz kılıyor, bizim tuttuğumuz gibi oruç tutuyor ve mallarının fazlasından sadaka veriyorlar." Buyurdu: „Allah size de sadaka verebileceğiniz şeyler kılmadı mı? Her tesbih bir sadakadır, her tekbir bir sadakadır, her tahmid bir sadakadır, her tehlil bir sadakadır, marufu emretmek bir sadakadır, münkerden nehyetmek bir sadakadır ve birinizin eşiyle münasebetinde de bir sadaka vardır." Dediler ki: „Yâ Resûlallah, birimiz şehvetini giderir de bunda ona ecir mi olur?" Buyurdu: „Ne dersiniz, onu harama koysa günah olmaz mıydı? İşte onu helale koyduğunda da ona ecir olur."',
  'Dari Abu Dzarr (semoga Allah meridhainya) juga: Beberapa orang dari sahabat Rasulullah ﷺ berkata kepada Nabi ﷺ: "Wahai Rasulullah, orang-orang kaya telah memborong pahala; mereka shalat sebagaimana kami shalat, berpuasa sebagaimana kami berpuasa, dan bersedekah dengan kelebihan harta mereka." Beliau bersabda: "Bukankah Allah telah menjadikan bagi kalian sesuatu yang dapat kalian sedekahkan? Sesungguhnya setiap tasbih adalah sedekah, setiap takbir adalah sedekah, setiap tahmid adalah sedekah, setiap tahlil adalah sedekah, menyuruh kepada kebaikan adalah sedekah, mencegah kemungkaran adalah sedekah, dan pada hubungan suami-istri salah seorang dari kalian pun ada sedekah." Mereka berkata: "Wahai Rasulullah, apakah salah seorang dari kami menunaikan syahwatnya lalu ia mendapat pahala padanya?" Beliau bersabda: "Bagaimana pendapat kalian, seandainya ia meletakkannya pada yang haram, bukankah ia berdosa? Maka demikian pula apabila ia meletakkannya pada yang halal, ia mendapat pahala."',
  'ابو ذر رضی اللہ عنہ سے بھی روایت ہے: رسول اللہ ﷺ کے کچھ صحابہ نے نبی ﷺ سے کہا: ”یا رسول اللہ! مالدار لوگ اجر و ثواب لے گئے؛ وہ نماز پڑھتے ہیں جیسے ہم پڑھتے ہیں، روزے رکھتے ہیں جیسے ہم رکھتے ہیں، اور اپنے مال کی زیادتی سے صدقہ بھی کرتے ہیں۔“ آپ نے فرمایا: ”کیا اللہ نے تمہارے لیے بھی ایسی چیزیں نہیں رکھیں جن سے تم صدقہ کر سکو؟ ہر تسبیح صدقہ ہے، ہر تکبیر صدقہ ہے، ہر تحمید صدقہ ہے، ہر تہلیل صدقہ ہے، نیکی کا حکم دینا صدقہ ہے، برائی سے روکنا صدقہ ہے، اور تم میں سے کسی کے اپنی بیوی سے ہمبستری میں بھی صدقہ ہے۔“ انہوں نے کہا: ”یا رسول اللہ! کیا ہم میں سے کوئی اپنی شہوت پوری کرے اور اس میں بھی اسے اجر ملے؟“ فرمایا: ”بتاؤ، اگر وہ اسے حرام میں رکھتا تو کیا اس پر گناہ نہ ہوتا؟ پس اسی طرح جب وہ اسے حلال میں رکھتا ہے تو اسے اجر ملتا ہے۔“',
  'আবু যার (রাদিয়াল্লাহু আনহু) থেকে আরও বর্ণিত: রাসূলুল্লাহ ﷺ-এর কিছু সাহাবী নবী ﷺ-কে বললেন: "হে আল্লাহর রাসূল! ধনী লোকেরা সওয়াব নিয়ে গেল; তারা আমাদের মতো সালাত আদায় করে, আমাদের মতো সিয়াম পালন করে, এবং তাদের সম্পদের উদ্বৃত্ত থেকে সদকাও করে।" তিনি বললেন: "আল্লাহ কি তোমাদের জন্যও এমন কিছু রাখেননি যা দিয়ে তোমরা সদকা করতে পারো? প্রতিটি তাসবীহ সদকা, প্রতিটি তাকবীর সদকা, প্রতিটি তাহমীদ সদকা, প্রতিটি তাহলীল সদকা, ভালো কাজের আদেশ সদকা, মন্দ কাজ থেকে নিষেধ সদকা, এবং তোমাদের কারো স্ত্রীর সাথে সহবাসেও সদকা রয়েছে।" তারা বললেন: "হে আল্লাহর রাসূল! আমাদের কেউ কি তার কামনা পূর্ণ করবে আর তাতেও তার সওয়াব হবে?" তিনি বললেন: "বলো তো, যদি সে তা হারামে স্থাপন করত তবে কি তার গুনাহ হতো না? সুতরাং অনুরূপভাবে যখন সে তা হালালে স্থাপন করে তখন তার সওয়াব হয়।"',
  'Daripada Abu Dzarr (semoga Allah meredainya) juga: Beberapa orang daripada sahabat Rasulullah ﷺ berkata kepada Nabi ﷺ: "Wahai Rasulullah, orang-orang kaya telah memborong pahala; mereka solat sebagaimana kami solat, berpuasa sebagaimana kami berpuasa, dan bersedekah dengan lebihan harta mereka." Baginda bersabda: "Bukankah Allah telah menjadikan bagi kamu sesuatu yang boleh kamu sedekahkan? Sesungguhnya setiap tasbih adalah sedekah, setiap takbir adalah sedekah, setiap tahmid adalah sedekah, setiap tahlil adalah sedekah, menyuruh kepada kebaikan adalah sedekah, mencegah kemungkaran adalah sedekah, dan pada hubungan suami-isteri seseorang daripada kamu pun ada sedekah." Mereka berkata: "Wahai Rasulullah, adakah seseorang daripada kami menunaikan syahwatnya lalu dia mendapat pahala padanya?" Baginda bersabda: "Bagaimana pendapat kamu, seandainya dia meletakkannya pada yang haram, bukankah dia berdosa? Maka demikian jugalah apabila dia meletakkannya pada yang halal, dia mendapat pahala."',
  'От Абу Зарра (да будет доволен им Аллах) также: Некоторые из сподвижников Посланника Аллаха ﷺ сказали Пророку ﷺ: «О Посланник Аллаха, обладатели богатства унесли награды; они молятся, как молимся мы, постятся, как постимся мы, и сверх того раздают милостыню из излишка своего имущества». Он сказал: «Разве Аллах не сделал и для вас то, чем вы можете давать милостыню? Поистине, каждое прославление (тасбих) — милостыня, каждое возвеличивание (такбир) — милостыня, каждая хвала (тахмид) — милостыня, каждое свидетельство единобожия (тахлиль) — милостыня, повеление одобряемого — милостыня, удержание от порицаемого — милостыня, и в близости одного из вас (с супругой) — милостыня». Они сказали: «О Посланник Аллаха, неужели один из нас удовлетворяет своё желание и получает за это награду?» Он сказал: «Скажите, если бы он поместил это в запретное, был бы на нём грех? Так же и когда он помещает это в дозволенное, ему за это награда».',
  -- reference
  'Sahih — reported by Muslim (no. 1006), al-Bayhaqi in al-Kubra (4/188), and Ahmad (5/167)',
  'Hadith authentique rapporté par Muslim (n°1006), al-Bayhaqî dans al-Kubrâ (4/188) et Ahmad (5/167)',
  'حديث صحيح، رواه مسلم (رقم ١٠٠٦) والبيهقي في الكبرى (٤/١٨٨) وأحمد (٥/١٦٧)',
  'Sahih — überliefert von Muslim (Nr. 1006), al-Bayhaqi in al-Kubra (4/188) und Ahmad (5/167)',
  'Sahih — overgeleverd door Muslim (nr. 1006), al-Bayhaqi in al-Kubra (4/188) en Ahmad (5/167)',
  'Sahih — Müslim (no. 1006), Beyhakî el-Kübrâ''da (4/188) ve Ahmed (5/167) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 1006), al-Baihaqi dalam al-Kubra (4/188), dan Ahmad (5/167)',
  'صحیح حدیث، اسے مسلم (نمبر ۱۰۰۶)، بیہقی نے الکبریٰ میں (۴/۱۸۸) اور احمد (۵/۱۶۷) نے روایت کیا',
  'সহীহ হাদীস — মুসলিম (নং ১০০৬), বায়হাকী আল-কুবরায় (৪/১৮৮) ও আহমাদ (৫/১৬৭) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 1006), al-Baihaqi dalam al-Kubra (4/188), dan Ahmad (5/167)',
  'Достоверный хадис, передали Муслим (№ 1006), аль-Байхаки в «аль-Кубра» (4/188) и Ахмад (5/167)',
  -- tafsir
  '• The persistence with which the Companions vied in good deeds.\n• When someone uses an ambiguous expression, he should clarify it afterwards: when the Companions said "the wealthy have taken away the rewards," they clarified it by saying that the wealthy pray and fast as they do, and in addition give charity from the surplus of their wealth.\n• Every word that brings one closer to Allah, the Exalted, is a charity — such as saying "Subhan Allah," "Alhamdu lillah," "Allahu Akbar," "La ilaha illa Allah," enjoining good, and forbidding evil.\n• An incitement to abundant remembrance of Allah, for every word of these remembrances is a charity that brings the servant closer to Allah.\n• Contenting oneself with the lawful so as to dispense with the unlawful makes the lawful a means of drawing near to Allah and a charity; the Prophet ﷺ said: "And in the intimate relation of one of you there is a charity."\n• It is permissible to verify a piece of information even if it comes from a truthful person; the Companions asked the question to confirm: "O Messenger of Allah, does one of us satisfy his desire and have a reward for it?"\n• The excellent teaching method of the Prophet ﷺ, using an interrogative style so that the listener is convinced of the answer and his heart is at peace. In the same way, when the Prophet ﷺ was asked about selling fresh dates for dried dates, he said: "Do they decrease in size when they become dry?" and when they said "Yes," he forbade that sale.',
  '• L''insistance avec laquelle les compagnons rivalisent dans les bonnes œuvres.\n• Quand quelqu''un emploie une expression équivoque, il doit l''expliciter ensuite : quand les compagnons ont dit « les gens riches ont emporté les récompenses », ils l''ont explicité en disant qu''ils prient et jeûnent comme eux, et qu''en plus ils font l''aumône du surplus de leurs fortunes.\n• Toute parole qui rapproche d''Allah, le Très-Haut, est une aumône, comme dire « Subhân Allah », « Al-hamdu lillah », « Allahu Akbar », « Lâ ilâha illâ Allah », ordonner le convenable et interdire le blâmable.\n• Une incitation à multiplier les évocations d''Allah, car chaque mot de ces évocations est une aumône qui rapproche le serviteur d''Allah.\n• Se contenter du licite pour se passer de l''illicite fait du licite un moyen de se rapprocher d''Allah et une aumône ; le Prophète ﷺ a dit : « Dans l''union intime de l''un de vous il y a une aumône. »\n• Il est permis de vérifier une information même si elle provient de quelqu''un de véridique ; les compagnons ont posé la question pour s''assurer : « Ô Envoyé d''Allah, l''un de nous satisfait son désir et en reçoit un salaire ? »\n• La bonne manière d''enseigner du Prophète ﷺ, en utilisant un style interrogatif pour que l''interlocuteur soit convaincu de la réponse et que son cœur soit tranquille. De même, quand le Prophète ﷺ fut interrogé sur la vente de dattes fraîches contre des dattes sèches, il dit : « Diminuent-elles de taille en séchant ? » ; quand ils dirent « Oui », il interdit cette vente.',
  '• إلحاح الصحابة في التنافس على الأعمال الصالحة.\n• إذا ذكر أحد عبارة مجملة فعليه أن يبيّنها بعد ذلك: فلما قال الصحابة «ذهب أهل الدثور بالأجور» بيّنوا ذلك بقولهم إنهم يصلون ويصومون كما يصلون ويصومون، ويتصدقون فوق ذلك بفضول أموالهم.\n• كل كلمة تقرّب من الله تعالى فهي صدقة، كقول «سبحان الله» و«الحمد لله» و«الله أكبر» و«لا إله إلا الله»، والأمر بالمعروف، والنهي عن المنكر.\n• الحث على الإكثار من ذكر الله تعالى، فإن كل كلمة من هذا الذكر صدقة تقرّب العبد من الله.\n• الاكتفاء بالحلال عن الحرام يجعل الحلال وسيلة للتقرب إلى الله وصدقة، قال النبي صلى الله عليه وسلم: «وفي بضع أحدكم صدقة».\n• يجوز التثبت من الخبر وإن جاء من صادق، فقد سأل الصحابة ليتثبتوا: «يا رسول الله، أيأتي أحدنا شهوته ويكون له فيها أجر؟».\n• حسن طريقة النبي صلى الله عليه وسلم في التعليم باستخدام الأسلوب الاستفهامي ليقتنع المخاطب بالجواب ويطمئن قلبه. وكذلك لما سُئل النبي صلى الله عليه وسلم عن بيع الرطب بالتمر قال: «أينقص الرطب إذا يبس؟» فلما قالوا: «نعم» نهى عن ذلك البيع.',
  '• Die Beharrlichkeit, mit der die Gefährten in guten Taten wetteiferten.\n• Wenn jemand einen mehrdeutigen Ausdruck gebraucht, sollte er ihn danach klären: als die Gefährten sagten „die Wohlhabenden haben die Belohnungen davongetragen", klärten sie es, indem sie sagten, dass jene beten und fasten wie sie und darüber hinaus Almosen vom Überschuss ihres Vermögens geben.\n• Jedes Wort, das Allah, dem Erhabenen, näherbringt, ist ein Almosen, wie das Sagen von „Subhan Allah", „Alhamdu lillah", „Allahu Akbar", „La ilaha illa Allah", das Gebieten des Guten und das Verbieten des Schlechten.\n• Ein Ansporn zum häufigen Gedenken Allahs, denn jedes Wort dieses Gedenkens ist ein Almosen, das den Diener Allah näherbringt.\n• Sich mit dem Erlaubten zu begnügen, um auf das Verbotene zu verzichten, macht das Erlaubte zu einem Mittel der Annäherung an Allah und zu einem Almosen; der Prophet ﷺ sagte: „Im ehelichen Beiwohnen eines von euch ist ein Almosen."\n• Es ist erlaubt, eine Information zu überprüfen, auch wenn sie von einem Wahrhaftigen kommt; die Gefährten stellten die Frage zur Vergewisserung: „O Gesandter Allahs, befriedigt einer von uns sein Verlangen und hat dafür eine Belohnung?"\n• Die vortreffliche Lehrmethode des Propheten ﷺ durch einen fragenden Stil, damit der Zuhörer von der Antwort überzeugt ist und sein Herz ruhig wird. Ebenso, als der Prophet ﷺ über den Verkauf frischer Datteln gegen getrocknete Datteln gefragt wurde, sagte er: „Nehmen sie an Größe ab, wenn sie trocken werden?" Als sie „Ja" sagten, verbot er diesen Verkauf.',
  '• De volharding waarmee de metgezellen wedijverden in goede daden.\n• Wanneer iemand een dubbelzinnige uitdrukking gebruikt, moet hij die daarna verduidelijken: toen de metgezellen zeiden „de welgestelden hebben de beloningen weggedragen", verduidelijkten zij het door te zeggen dat zij bidden en vasten zoals zij, en daarbovenop aalmoezen geven van het overschot van hun rijkdom.\n• Elk woord dat dichter bij Allah, de Verhevene, brengt, is een aalmoes, zoals het zeggen van „Subhan Allah", „Alhamdoe lillah", „Allahoe Akbar", „La ilaha illa Allah", het goede gebieden en het slechte verbieden.\n• Een aansporing tot veelvuldig gedenken van Allah, want elk woord van dit gedenken is een aalmoes die de dienaar dichter bij Allah brengt.\n• Zich tevredenstellen met het toegestane om het verbodene te vermijden, maakt het toegestane tot een middel om Allah te naderen en tot een aalmoes; de Profeet ﷺ zei: „In de intieme omgang van een van jullie is een aalmoes."\n• Het is toegestaan een bericht te verifiëren, ook als het van een waarachtige komt; de metgezellen stelden de vraag ter bevestiging: „O Boodschapper van Allah, bevredigt een van ons zijn verlangen en heeft hij daar een beloning voor?"\n• De voortreffelijke onderwijsmethode van de Profeet ﷺ, met een vragende stijl zodat de toehoorder overtuigd is van het antwoord en zijn hart gerust is. Evenzo, toen de Profeet ﷺ werd gevraagd over het verkopen van verse dadels voor gedroogde dadels, zei hij: „Nemen ze af in omvang wanneer ze droog worden?" Toen zij „Ja" zeiden, verbood hij die verkoop.',
  '• Ashabın salih amellerde yarışmadaki ısrarı.\n• Kişi kapalı bir ifade kullanırsa, sonradan onu açıklamalıdır: ashab „servet sahipleri ecirleri alıp götürdüler" dediklerinde, bunu, onların kendileri gibi namaz kılıp oruç tuttuklarını ve ayrıca mallarının fazlasından sadaka verdiklerini söyleyerek açıkladılar.\n• Allah''a yaklaştıran her söz bir sadakadır; „Sübhânallah", „Elhamdülillah", „Allâhu ekber", „Lâ ilâhe illallah" demek, marufu emretmek ve münkerden nehyetmek gibi.\n• Allah''ı çokça zikretmeye teşvik; zira bu zikrin her kelimesi, kulu Allah''a yaklaştıran bir sadakadır.\n• Haramdan müstağni olmak için helalle yetinmek, helali Allah''a yaklaşma vesilesi ve sadaka kılar; Peygamber ﷺ: „Birinizin eşiyle münasebetinde de bir sadaka vardır" buyurdu.\n• Bir haber doğru kimseden gelse bile teyit etmek caizdir; ashab teyit için sordu: „Yâ Resûlallah, birimiz şehvetini giderir de bunda ona ecir mi olur?"\n• Peygamber''in ﷺ öğretimdeki güzel yöntemi: muhatabın cevaba kanaat getirmesi ve kalbinin mutmain olması için soru üslubunu kullanması. Nitekim Peygamber''e ﷺ yaş hurmanın kuru hurma karşılığında satışı sorulduğunda: „Yaş hurma kuruyunca eksilir mi?" buyurdu; „Evet" dediklerinde bu satışı yasakladı.',
  '• Kesungguhan para sahabat dalam berlomba-lomba pada amal saleh.\n• Apabila seseorang menyebut ungkapan yang samar, hendaklah ia menjelaskannya setelah itu: ketika para sahabat berkata "orang-orang kaya telah memborong pahala," mereka menjelaskannya dengan mengatakan bahwa mereka shalat dan berpuasa sebagaimana para sahabat, dan ditambah bersedekah dengan kelebihan harta mereka.\n• Setiap kata yang mendekatkan diri kepada Allah Taʿala adalah sedekah, seperti ucapan "Subhanallah", "Alhamdulillah", "Allahu Akbar", "La ilaha illallah", menyuruh kepada kebaikan, dan mencegah kemungkaran.\n• Anjuran memperbanyak zikir kepada Allah Taʿala, karena setiap kata dari zikir ini adalah sedekah yang mendekatkan hamba kepada Allah.\n• Mencukupkan diri dengan yang halal agar terhindar dari yang haram menjadikan yang halal sebagai sarana mendekatkan diri kepada Allah dan sedekah; Nabi ﷺ bersabda: "Dan pada hubungan suami-istri salah seorang dari kalian ada sedekah."\n• Boleh memastikan suatu kabar meskipun datang dari orang yang jujur; para sahabat mengajukan pertanyaan untuk memastikan: "Wahai Rasulullah, apakah salah seorang dari kami menunaikan syahwatnya lalu ia mendapat pahala padanya?"\n• Metode pengajaran Nabi ﷺ yang baik dengan menggunakan gaya bertanya agar lawan bicara yakin dengan jawaban dan hatinya tenang. Demikian pula ketika Nabi ﷺ ditanya tentang menjual kurma basah dengan kurma kering, beliau bersabda: "Apakah ia berkurang ukurannya apabila kering?" Ketika mereka menjawab "Ya," beliau melarang jual beli itu.',
  '• صحابہ کا نیک اعمال میں مقابلے کا اصرار۔\n• جب کوئی شخص مجمل عبارت کہے تو اسے بعد میں اس کی وضاحت کرنی چاہیے: جب صحابہ نے کہا ”مالدار لوگ اجر لے گئے“ تو انہوں نے اس کی وضاحت یہ کہہ کر کی کہ وہ نماز اور روزہ انہی کی طرح رکھتے ہیں، اور اس کے علاوہ اپنے مال کی زیادتی سے صدقہ بھی کرتے ہیں۔\n• ہر وہ کلمہ جو اللہ تعالیٰ کے قریب کرے وہ صدقہ ہے، جیسے ”سبحان اللہ“، ”الحمد للہ“، ”اللہ اکبر“، ”لا الٰہ الا اللہ“ کہنا، نیکی کا حکم دینا اور برائی سے روکنا۔\n• اللہ تعالیٰ کے ذکر کی کثرت کی ترغیب، کیونکہ اس ذکر کا ہر کلمہ ایک صدقہ ہے جو بندے کو اللہ کے قریب کرتا ہے۔\n• حرام سے بچنے کے لیے حلال پر اکتفا کرنا، حلال کو اللہ کے تقرب کا ذریعہ اور صدقہ بنا دیتا ہے؛ نبی ﷺ نے فرمایا: ”تم میں سے کسی کی (اپنی بیوی سے) ہمبستری میں بھی صدقہ ہے۔“\n• کسی سچے شخص سے آنے والی خبر کی بھی تصدیق و تثبت جائز ہے؛ صحابہ نے تثبت کے لیے سوال کیا: ”یا رسول اللہ! کیا ہم میں سے کوئی اپنی شہوت پوری کرے اور اس میں بھی اسے اجر ملے؟“\n• نبی ﷺ کا تعلیم کا بہترین طریقہ، استفہامی اسلوب کے ذریعے تاکہ مخاطب جواب پر مطمئن ہو جائے اور اس کا دل سکون پائے۔ اسی طرح جب نبی ﷺ سے تازہ کھجور کو خشک کھجور کے بدلے بیچنے کے بارے میں پوچھا گیا تو فرمایا: ”کیا خشک ہونے پر یہ کم ہو جاتی ہے؟“ جب انہوں نے کہا ”ہاں“ تو آپ نے اس بیع سے منع فرما دیا۔',
  '• সাহাবীগণের সৎকর্মে প্রতিযোগিতার আগ্রহ।\n• কেউ যদি অস্পষ্ট কথা বলে, তবে তার উচিত পরে তা স্পষ্ট করা: সাহাবীগণ যখন বললেন "ধনীরা সওয়াব নিয়ে গেল," তখন তারা তা স্পষ্ট করলেন এই বলে যে তারা তাদের মতোই সালাত ও সিয়াম পালন করে, এবং তার উপর সম্পদের উদ্বৃত্ত থেকে সদকাও করে।\n• যে কথা আল্লাহ তাআলার নিকটবর্তী করে তা-ই সদকা, যেমন "সুবহানাল্লাহ", "আলহামদুলিল্লাহ", "আল্লাহু আকবার", "লা ইলাহা ইল্লাল্লাহ" বলা, ভালো কাজের আদেশ ও মন্দ কাজ থেকে নিষেধ।\n• আল্লাহ তাআলার অধিক যিকরের প্রতি উৎসাহ, কারণ এই যিকরের প্রতিটি শব্দ একটি সদকা যা বান্দাকে আল্লাহর নিকটবর্তী করে।\n• হারাম থেকে বাঁচতে হালালে সন্তুষ্ট থাকা হালালকে আল্লাহর নৈকট্যের মাধ্যম ও সদকা বানিয়ে দেয়; নবী ﷺ বলেছেন: "তোমাদের কারো (স্ত্রীর সাথে) সহবাসেও সদকা রয়েছে।"\n• সত্যবাদীর কাছ থেকে আসা সংবাদও যাচাই করা জায়েজ; সাহাবীগণ নিশ্চিত হওয়ার জন্য প্রশ্ন করলেন: "হে আল্লাহর রাসূল! আমাদের কেউ কি তার কামনা পূর্ণ করবে আর তাতেও তার সওয়াব হবে?"\n• নবী ﷺ-এর শিক্ষাদানের উত্তম পদ্ধতি, প্রশ্নবোধক রীতি ব্যবহার করে যাতে শ্রোতা উত্তরে নিশ্চিত হয় ও তার অন্তর প্রশান্ত হয়। অনুরূপভাবে নবী ﷺ-কে যখন তাজা খেজুরের বদলে শুকনো খেজুর বিক্রি সম্পর্কে জিজ্ঞাসা করা হলো, তিনি বললেন: "শুকিয়ে গেলে কি তা কমে যায়?" তারা যখন বলল "হ্যাঁ," তিনি সেই বেচাকেনা নিষেধ করলেন।',
  '• Kesungguhan para sahabat dalam berlumba-lumba pada amal soleh.\n• Apabila seseorang menyebut ungkapan yang samar, hendaklah dia menjelaskannya selepas itu: ketika para sahabat berkata "orang-orang kaya telah memborong pahala," mereka menjelaskannya dengan mengatakan bahawa mereka solat dan berpuasa sebagaimana para sahabat, dan ditambah bersedekah dengan lebihan harta mereka.\n• Setiap kata yang mendekatkan diri kepada Allah Taʿala adalah sedekah, seperti ucapan "Subhanallah", "Alhamdulillah", "Allahu Akbar", "La ilaha illallah", menyuruh kepada kebaikan, dan mencegah kemungkaran.\n• Galakan memperbanyak zikir kepada Allah Taʿala, kerana setiap kata daripada zikir ini adalah sedekah yang mendekatkan hamba kepada Allah.\n• Mencukupkan diri dengan yang halal agar terhindar daripada yang haram menjadikan yang halal sebagai wasilah mendekatkan diri kepada Allah dan sedekah; Nabi ﷺ bersabda: "Dan pada hubungan suami-isteri seseorang daripada kamu ada sedekah."\n• Harus memastikan sesuatu khabar walaupun datang daripada orang yang jujur; para sahabat mengajukan soalan untuk memastikan: "Wahai Rasulullah, adakah seseorang daripada kami menunaikan syahwatnya lalu dia mendapat pahala padanya?"\n• Kaedah pengajaran Nabi ﷺ yang baik dengan menggunakan gaya bertanya agar lawan bicara yakin dengan jawapan dan hatinya tenang. Demikian juga ketika Nabi ﷺ ditanya tentang menjual kurma basah dengan kurma kering, baginda bersabda: "Adakah ia berkurang ukurannya apabila kering?" Ketika mereka menjawab "Ya," baginda melarang jual beli itu.',
  '• Настойчивость, с которой сподвижники состязались в благих делах.\n• Когда кто-то употребляет неясное выражение, он должен затем разъяснить его: когда сподвижники сказали «обладатели богатства унесли награды», они разъяснили это, сказав, что те молятся и постятся, как они, и вдобавок раздают милостыню из излишка своего имущества.\n• Всякое слово, приближающее к Аллаху Всевышнему, — милостыня, как произнесение «Субхана Ллах», «Альхамду лиллях», «Аллаху акбар», «Ля иляха илля Ллах», повеление одобряемого и запрет порицаемого.\n• Побуждение к обильному поминанию Аллаха Всевышнего, ибо каждое слово этого поминания — милостыня, приближающая раба к Аллаху.\n• Довольствование дозволенным, чтобы обойтись без запретного, делает дозволенное средством приближения к Аллаху и милостыней; Пророк ﷺ сказал: «И в близости одного из вас — милостыня».\n• Дозволено проверять сообщение, даже если оно исходит от правдивого; сподвижники задали вопрос для уверенности: «О Посланник Аллаха, неужели один из нас удовлетворяет своё желание и получает за это награду?»\n• Прекрасный метод обучения Пророка ﷺ через вопросительный стиль, чтобы собеседник убедился в ответе и его сердце успокоилось. Так же, когда Пророка ﷺ спросили о продаже свежих фиников за сушёные, он сказал: «Уменьшаются ли они в размере, когда высыхают?» Когда они сказали «Да», он запретил эту сделку.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2023/01/Hadith-25-Nawawi-Psalmodie-Arabe.mp3',
  5,
  25
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 25
);
