-- =============================================================================
-- Quiz questions :: seed batch (10 questions, trilingual EN/FR/AR)
-- correct_option_index is 1-based (1..4)
-- =============================================================================

insert into public.quiz_questions
  (level,
   question_en, question_fr, question_ar,
   arabic_text, transcription_en, transcription_fr,
   subtitle_en, subtitle_fr, subtitle_ar,
   option_a_en, option_a_fr, option_a_ar,
   option_b_en, option_b_fr, option_b_ar,
   option_c_en, option_c_fr, option_c_ar,
   option_d_en, option_d_fr, option_d_ar,
   congratulation_en, congratulation_fr, congratulation_ar,
   correct_option_index, ajr, bonus_ajr)
values
  ('begining',
   'How many pillars does Islam have?', 'Combien de piliers compte l''Islam ?', 'كم عدد أركان الإسلام؟',
   null, null, null, null, null, null,
   'Three', 'Trois', 'ثلاثة',
   'Four', 'Quatre', 'أربعة',
   'Five', 'Cinq', 'خمسة',
   'Six', 'Six', 'ستة',
   'Correct! Islam has five pillars.', 'Bravo ! L''Islam a cinq piliers.', 'أحسنت! للإسلام خمسة أركان.',
   3, 5, 2),

  ('begining',
   'What is the first month of the Islamic calendar?', 'Quel est le premier mois du calendrier islamique ?', 'ما هو أول شهر في التقويم الهجري؟',
   null, null, null, null, null, null,
   'Ramadan', 'Ramadan', 'رمضان',
   'Muharram', 'Mouharram', 'محرم',
   'Shawwal', 'Chawwal', 'شوال',
   'Rajab', 'Rajab', 'رجب',
   'Correct! The year begins with Muharram.', 'Bravo ! L''année commence par Mouharram.', 'أحسنت! تبدأ السنة بشهر محرم.',
   2, 5, 2),

  ('begining',
   'Which prophet built the Kaaba with his son?', 'Quel prophète a bâti la Kaaba avec son fils ?', 'أي نبي بنى الكعبة مع ابنه؟',
   null, null, null, null, null, null,
   'Musa (Moses)', 'Moussa (Moïse)', 'موسى',
   'Nuh (Noah)', 'Nouh (Noé)', 'نوح',
   'Ibrahim (Abraham)', 'Ibrahim (Abraham)', 'إبراهيم',
   'Isa (Jesus)', 'Issa (Jésus)', 'عيسى',
   'Correct! Ibrahim built it with his son Ismail.', 'Bravo ! Ibrahim l''a bâtie avec son fils Ismaïl.', 'أحسنت! بناها إبراهيم مع ابنه إسماعيل.',
   3, 5, 2),

  ('growing',
   'How many rak''ahs are in the obligatory Fajr prayer?', 'Combien de rak''ahs compte la prière obligatoire du Fajr ?', 'كم عدد ركعات صلاة الفجر المفروضة؟',
   null, null, null, null, null, null,
   'Two', 'Deux', 'ركعتان',
   'Three', 'Trois', 'ثلاث',
   'Four', 'Quatre', 'أربع',
   'One', 'Une', 'ركعة واحدة',
   'Correct! Fajr is two rak''ahs.', 'Bravo ! Le Fajr est de deux rak''ahs.', 'أحسنت! الفجر ركعتان.',
   1, 5, 2),

  ('growing',
   'Which surah is known as the heart of the Quran?', 'Quelle sourate est appelée le cœur du Coran ?', 'أي سورة تُعرف بقلب القرآن؟',
   null, null, null, null, null, null,
   'Al-Baqarah', 'Al-Baqara', 'البقرة',
   'Ya-Sin', 'Ya-Sin', 'يس',
   'Al-Kahf', 'Al-Kahf', 'الكهف',
   'Al-Mulk', 'Al-Mulk', 'الملك',
   'Correct! Ya-Sin is called the heart of the Quran.', 'Bravo ! Ya-Sin est appelée le cœur du Coran.', 'أحسنت! يس تُسمى قلب القرآن.',
   2, 5, 2),

  ('growing',
   'In which month does Laylat al-Qadr occur?', 'Durant quel mois a lieu Laylat al-Qadr ?', 'في أي شهر تكون ليلة القدر؟',
   null, null, null, null, null, null,
   'Shaban', 'Chaabane', 'شعبان',
   'Ramadan', 'Ramadan', 'رمضان',
   'Dhul-Hijjah', 'Dhou al-Hijja', 'ذو الحجة',
   'Rajab', 'Rajab', 'رجب',
   'Correct! It falls in the last ten nights of Ramadan.', 'Bravo ! Elle a lieu dans les dix dernières nuits du Ramadan.', 'أحسنت! تكون في العشر الأواخر من رمضان.',
   2, 5, 2),

  ('established',
   'How many verses are in Surah Al-Fatiha?', 'Combien de versets compte la sourate Al-Fatiha ?', 'كم عدد آيات سورة الفاتحة؟',
   null, null, null, null, null, null,
   'Five', 'Cinq', 'خمس',
   'Six', 'Six', 'ست',
   'Seven', 'Sept', 'سبع',
   'Ten', 'Dix', 'عشر',
   'Correct! Al-Fatiha has seven verses.', 'Bravo ! Al-Fatiha compte sept versets.', 'أحسنت! الفاتحة سبع آيات.',
   3, 5, 2),

  ('established',
   'Which was the first major battle in Islamic history?', 'Quelle fut la première grande bataille de l''histoire de l''Islam ?', 'ما هي أول معركة كبرى في تاريخ الإسلام؟',
   null, null, null, null, null, null,
   'Uhud', 'Ouhoud', 'أحد',
   'Khandaq', 'Khandaq', 'الخندق',
   'Badr', 'Badr', 'بدر',
   'Hunayn', 'Hounayn', 'حنين',
   'Correct! The Battle of Badr came first.', 'Bravo ! La bataille de Badr fut la première.', 'أحسنت! كانت معركة بدر الأولى.',
   3, 5, 2),

  ('returning',
   'How many obligatory prayers are there each day?', 'Combien de prières obligatoires y a-t-il chaque jour ?', 'كم عدد الصلوات المفروضة في اليوم؟',
   null, null, null, null, null, null,
   'Three', 'Trois', 'ثلاث',
   'Five', 'Cinq', 'خمس',
   'Seven', 'Sept', 'سبع',
   'Two', 'Deux', 'اثنتان',
   'Correct! There are five daily prayers.', 'Bravo ! Il y a cinq prières quotidiennes.', 'أحسنت! هناك خمس صلوات يومية.',
   2, 5, 2),

  ('returning',
   'What is the Arabic term for fasting?', 'Quel est le terme arabe pour le jeûne ?', 'ما هو المصطلح العربي للصيام؟',
   null, null, null, null, null, null,
   'Zakat', 'Zakat', 'الزكاة',
   'Hajj', 'Hajj', 'الحج',
   'Sawm', 'Sawm', 'الصوم',
   'Salah', 'Salat', 'الصلاة',
   'Correct! Fasting is called Sawm.', 'Bravo ! Le jeûne s''appelle Sawm.', 'أحسنت! الصيام يُسمى الصوم.',
   3, 5, 2);
