-- =============================================================================
-- 40 Hadith Nawawi — Hadith 6: "The lawful is clear and the unlawful is clear"
-- Target collection: public.hadith_collections.id = 2  /  position = 6
-- Idempotent guard on (collection, position). All 11 content languages.
-- Arabic source cleaned: restored truncated ending (ألا وهي القلب),
-- fixed مَحَارِ مُهُ -> مَحَارِمُهُ.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'The lawful and the unlawful',
  'Le licite et l''illicite',
  'الحلال بيّن والحرام بيّن',
  'Das Erlaubte und das Verbotene',
  'Het toegestane en het verbodene',
  'Helal ve haram',
  'Yang halal dan yang haram',
  'حلال اور حرام',
  'হালাল ও হারাম',
  'Yang halal dan yang haram',
  'Дозволенное и запретное',
  -- arabic_text (cleaned)
  'عَنْ أَبِي عَبْدِ اللَّهِ النُّعْمَانِ بْنِ بَشِيرٍ رَضِيَ اللَّهُ عَنْهُمَا قَالَ: سَمِعْتُ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يَقُولُ: «إِنَّ الْحَلَالَ بَيِّنٌ وَإِنَّ الْحَرَامَ بَيِّنٌ، وَبَيْنَهُمَا أُمُورٌ مُشْتَبِهَاتٌ لَا يَعْلَمُهُنَّ كَثِيرٌ مِنَ النَّاسِ، فَمَنِ اتَّقَى الشُّبُهَاتِ فَقَدِ اسْتَبْرَأَ لِدِينِهِ وَعِرْضِهِ، وَمَنْ وَقَعَ فِي الشُّبُهَاتِ وَقَعَ فِي الْحَرَامِ، كَالرَّاعِي يَرْعَى حَوْلَ الْحِمَى يُوشِكُ أَنْ يَرْتَعَ فِيهِ، أَلَا وَإِنَّ لِكُلِّ مَلِكٍ حِمًى، أَلَا وَإِنَّ حِمَى اللَّهِ مَحَارِمُهُ، أَلَا وَإِنَّ فِي الْجَسَدِ مُضْغَةً إِذَا صَلَحَتْ صَلَحَ الْجَسَدُ كُلُّهُ، وَإِذَا فَسَدَتْ فَسَدَ الْجَسَدُ كُلُّهُ، أَلَا وَهِيَ الْقَلْبُ»',
  -- transcription
  'ʿan Abī ʿAbdi Llāhi n-Nuʿmāni bni Bashīrin raḍiya Llāhu ʿanhumā qāla: samiʿtu Rasūla Llāhi ṣalla Llāhu ʿalayhi wa-sallama yaqūlu: inna l-ḥalāla bayyinun wa-inna l-ḥarāma bayyinun, wa-baynahumā umūrun mushtabihātun lā yaʿlamuhunna kathīrun mina n-nās, fa-mani ttaqa sh-shubuhāti fa-qadi stabraʾa li-dīnihi wa-ʿirḍihi, wa-man waqaʿa fi sh-shubuhāti waqaʿa fi l-ḥarām, ka-r-rāʿī yarʿā ḥawla l-ḥimā yūshiku an yartaʿa fīh, alā wa-inna li-kulli malikin ḥiman, alā wa-inna ḥima Llāhi maḥārimuhu, alā wa-inna fi l-jasadi muḍghatan idhā ṣalaḥat ṣalaḥa l-jasadu kulluhu, wa-idhā fasadat fasada l-jasadu kulluhu, alā wa-hiya l-qalb.',
  'ʿan Abî ʿAbdi Llâhi n-Nouʿmâni bni Bachîrin (radia Llâhou ʿanhoumâ) qâla : samiʿtou Rassôla Llâhi (salla Llâhou ʿalayhi wa sallam) yaqôlou : inna l-halâla bayyinoun wa inna l-harâma bayyinoun, wa baynahoumâ oumôuroun mouchtabihâtoun lâ yaʿlamouhounna kathîroun mina n-nâs, fa-mani ttaqa ch-choubouhâti fa-qadi stabraʾa li-dînihi wa ʿirdihi, wa man waqaʿa fi ch-choubouhâti waqaʿa fi l-harâm, ka-r-râʿî yarʿâ hawla l-himâ yôuchikou an yartaʿa fîh, alâ wa inna li-koulli malikin himan, alâ wa inna hima Llâhi mahârimouhou, alâ wa inna fi l-jasadi moudghatan idhâ salahat salaha l-jasadou koullouhou, wa idhâ fasadat fasada l-jasadou koullouhou, alâ wa hiya l-qalb.',
  'ʿan Abī ʿAbdi Llāhi n-Nuʿmāni bni Baschīrin (radiya Llāhu ʿanhumā) qāla: samiʿtu Rasūla Llāhi (salla Llāhu ʿalaihi wa-sallam) jaqūlu: inna l-halāla bajjinun wa-inna l-harāma bajjinun, wa-bainahumā umūrun muschtabihātun lā jaʿlamuhunna kathīrun mina n-nās, fa-mani ttaqa sch-schubuhāti fa-qadi stabraʾa li-dīnihi wa-ʿirdihi, wa-man waqaʿa fi sch-schubuhāti waqaʿa fi l-harām, ka-r-rāʿī jarʿā haula l-himā jūschiku an jartaʿa fīh, alā wa-inna li-kulli malikin himan, alā wa-inna hima Llāhi mahārimuhu, alā wa-inna fi l-dschasadi mudghatan idhā salahat salaha l-dschasadu kulluhu, wa-idhā fasadat fasada l-dschasadu kulluhu, alā wa-hija l-qalb.',
  'ʿan Abie ʿAbdi Llaahi n-Noeʿmaani bni Basjierin (radia Llaahoe ʿanhoemaa) qaala: samiʿtoe Rasoela Llaahi (salla Llaahoe ʿalaihi wa-sallam) jaqoeloe: inna l-halaaloe bajjinoen wa-inna l-haraamoe bajjinoen, wa-bainahoemaa oemoeroen moesjtabihaatoen laa jaʿlamoehoenna kathieroen mina n-naas, fa-mani ttaqa sj-sjoeboehaati fa-qadi stabraʾa li-dienihi wa-ʿirdihi, wa-man waqaʿa fi sj-sjoeboehaati waqaʿa fi l-haraam, ka-r-raaʿie jarʿaa haula l-himaa joesjikoe an jartaʿa fieh, alaa wa-inna li-koelli malikin himan, alaa wa-inna hima Llaahi mahaarimoehoe, alaa wa-inna fi l-dzjasadi moedghatan idhaa salahat salaha l-dzjasadoe koelloehoe, wa-idhaa fasadat fasada l-dzjasadoe koelloehoe, alaa wa-hija l-qalb.',
  'an Ebû Abdillâh Nuʿmân ibn Beşîr''den (radıyallâhu anhümâ) rivayetle dedi ki: Resûlullah''ın (s.a.v.) şöyle dediğini işittim: helal bellidir, haram da bellidir; ikisi arasında ise birçok insanın bilmediği şüpheli işler vardır. Kim şüpheli şeylerden sakınırsa dinini ve ırzını korumuş olur; kim de şüpheli şeylere düşerse harama düşer; tıpkı korunun çevresinde sürü otlatan çoban gibi, neredeyse içine girecektir. Dikkat edin, her hükümdarın bir korusu vardır; dikkat edin, Allah''ın korusu da haram kıldıklarıdır. Dikkat edin, bedende bir et parçası vardır ki o iyi olursa bütün beden iyi olur, o bozulursa bütün beden bozulur; dikkat edin, o kalptir.',
  'ʿan Abī ʿAbdillāh an-Nuʿmān bin Basyīr (radhiyallāhu ʿanhumā) berkata: aku mendengar Rasulullah (shallallāhu ʿalaihi wa sallam) bersabda: innal-halāla bayyinun wa innal-harāma bayyinun, wa bainahumā umūrun musytabihātun lā yaʿlamuhunna katsīrun minan-nās, faman ittaqasy-syubuhāti faqadistabraʾa li-dīnihi wa ʿirdhihi, wa man waqaʿa fisy-syubuhāti waqaʿa fil-harām, kar-rāʿī yarʿā haulal-himā yūsyiku an yartaʿa fīh, alā wa inna li-kulli malikin himan, alā wa inna himallāhi mahārimuh, alā wa inna fil-jasadi mudghatan idzā shalahat shalahal-jasadu kulluhu, wa idzā fasadat fasadal-jasadu kulluhu, alā wa hiyal-qalb.',
  'ابو عبد اللہ نعمان بن بشیر رضی اللہ عنہما سے روایت ہے، انہوں نے کہا: میں نے رسول اللہ صلی اللہ علیہ وسلم کو فرماتے سنا: اِنَّ الحَلالَ بَیِّنٌ وَاِنَّ الحَرامَ بَیِّنٌ، وَبَینَہُما اُمُورٌ مُشتَبِہاتٌ لا یَعلَمُہُنَّ کَثِیرٌ مِنَ النّاس، فَمَنِ اتَّقَی الشُّبُہاتِ فَقَدِ استَبرَأَ لِدِینِہِ وَعِرضِہِ، وَمَن وَقَعَ فِی الشُّبُہاتِ وَقَعَ فِی الحَرام، کَالرّاعِی یَرعٰی حَولَ الحِمٰی یُوشِکُ اَن یَرتَعَ فِیہِ، اَلا وَاِنَّ لِکُلِّ مَلِکٍ حِمًی، اَلا وَاِنَّ حِمَی اللہِ مَحارِمُہُ، اَلا وَاِنَّ فِی الجَسَدِ مُضغَۃً اِذا صَلَحَت صَلَحَ الجَسَدُ کُلُّہُ، وَاِذا فَسَدَت فَسَدَ الجَسَدُ کُلُّہُ، اَلا وَہِیَ القَلب۔',
  'আবু আবদিল্লাহ নুমান ইবনে বাশীর (রাদিয়াল্লাহু আনহুমা) থেকে বর্ণিত, তিনি বলেন: আমি রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম)-কে বলতে শুনেছি: ইন্নাল হালালা বায়্যিন, ওয়া ইন্নাল হারামা বায়্যিন, ওয়া বাইনাহুমা উমূরুম মুশতাবিহাতুল লা ইয়ালামুহুন্না কাসীরুম মিনান নাস, ফামানিত তাকাশ শুবুহাতি ফাকাদিস তাবরাআ লিদীনিহি ওয়া ইরদিহি, ওয়া মান ওয়াকাআ ফিশ শুবুহাতি ওয়াকাআ ফিল হারাম, কার রাঈ ইয়ারআ হাওলাল হিমা ইউশিকু আন ইয়ারতাআ ফীহ, আলা ওয়া ইন্না লিকুল্লি মালিকিন হিমা, আলা ওয়া ইন্না হিমাল্লাহি মাহারিমুহ, আলা ওয়া ইন্না ফিল জাসাদি মুদগাতান ইযা সালাহাত সালাহাল জাসাদু কুল্লুহু, ওয়া ইযা ফাসাদাত ফাসাদাল জাসাদু কুল্লুহু, আলা ওয়া হিয়াল কালব।',
  'ʿan Abī ʿAbdillāh an-Nuʿmān bin Basyīr (radhiallāhu ʿanhumā) berkata: aku mendengar Rasulullah (sallallāhu ʿalaihi wa sallam) bersabda: innal-halālu bayyinun wa innal-harāmu bayyinun, wa bainahumā umūrun musytabihātun lā yaʿlamuhunna katsīrun minan-nās, faman ittaqasy-syubuhāti faqadistabraʾa li-dīnihi wa ʿirdhihi, wa man waqaʿa fisy-syubuhāti waqaʿa fil-harām, kar-rāʿī yarʿā haulal-himā yūsyiku an yartaʿa fīh, alā wa inna li-kulli malikin himan, alā wa inna himallāhi mahārimuh, alā wa inna fil-jasadi mudghatan idzā solahat solahal-jasadu kulluhu, wa idzā fasadat fasadal-jasadu kulluhu, alā wa hiyal-qalb.',
  'Ан Аби Абдиллях ан-Нуман ибн Башир (да будет доволен Аллах ими обоими) сказал: я слышал, как Посланник Аллаха ﷺ говорил: иннал-халяля баййин, ва иннал-харама баййин, ва байнахума умурун муштабихатун ля яʿлямухунна касирун мина н-нас, фамани-ттака ш-шубухати фа-кади-стабраа ли-динихи ва ирдихи, ва ман вакаа фи ш-шубухати вакаа фи ль-харам, ка-р-раʿи ярʿа хауля ль-хима юшику ан яртаʿа фих, аля ва инна ли-кулли маликин химан, аля ва инна хима Ллахи махаримуху, аля ва инна фи ль-джасади мудгатан иза салахат салаха ль-джасаду куллюху, ва иза фасадат фасада ль-джасаду куллюху, аля ва хия ль-кальб.',
  -- translation
  'On the authority of Abu ʿAbd Allah an-Nuʿman ibn Bashir (may Allah be pleased with them both), I heard the Messenger of Allah ﷺ say: "The lawful is clear and the unlawful is clear, and between them are doubtful matters which many people do not know. So whoever guards against the doubtful matters has protected his religion and his honour; and whoever falls into the doubtful matters falls into the unlawful, like a shepherd who grazes around a sanctuary, all but grazing within it. Indeed, every king has a sanctuary, and the sanctuary of Allah is His prohibitions. Indeed, in the body there is a morsel of flesh which, if sound, the whole body is sound, and if corrupt, the whole body is corrupt. Indeed, it is the heart."',
  'D''après Abû ʿAbd Allah an-Nuʿmân ibn Bashîr (qu''Allah les agrée tous deux) : J''ai entendu l''Envoyé d''Allah ﷺ dire : « Le licite est bien évident et l''illicite est bien évident, et entre les deux il y a des choses équivoques que beaucoup de gens ignorent. Ainsi, quiconque se met à l''abri des choses équivoques préserve sa religion et son honneur ; et quiconque tombe dans les choses équivoques tombe dans l''illicite, tel le berger qui fait paître son troupeau autour d''un enclos réservé, risquant à tout moment d''y empiéter. Or, chaque souverain a un domaine réservé : celui d''Allah, ce sont Ses interdits. N''y a-t-il pas dans le corps un morceau de chair qui, s''il est sain, tout le corps l''est, et s''il est corrompu, tout le corps l''est ? N''est-ce pas le cœur ? »',
  'Nach Abu ʿAbd Allah an-Nuʿman ibn Baschir (möge Allah mit beiden zufrieden sein): Ich hörte den Gesandten Allahs ﷺ sagen: „Das Erlaubte ist klar und das Verbotene ist klar, und zwischen beiden liegen zweifelhafte Dinge, die viele Menschen nicht kennen. Wer sich vor den zweifelhaften Dingen hütet, hat seine Religion und seine Ehre bewahrt; und wer in die zweifelhaften Dinge fällt, fällt ins Verbotene, wie ein Hirte, der um ein Schutzgebiet herum weidet und beinahe darin weidet. Wahrlich, jeder König hat ein Schutzgebiet, und das Schutzgebiet Allahs sind Seine Verbote. Wahrlich, im Körper ist ein Stück Fleisch: ist es gesund, so ist der ganze Körper gesund, und ist es verdorben, so ist der ganze Körper verdorben. Wahrlich, es ist das Herz."',
  'Op gezag van Abu ʿAbd Allah an-Nuʿman ibn Bashir (moge Allah tevreden met hen beiden zijn): Ik hoorde de Boodschapper van Allah ﷺ zeggen: „Het toegestane is duidelijk en het verbodene is duidelijk, en daartussen liggen twijfelachtige zaken die veel mensen niet kennen. Wie zich voor de twijfelachtige zaken hoedt, heeft zijn religie en zijn eer beschermd; en wie in de twijfelachtige zaken vervalt, vervalt in het verbodene, als een herder die rond een beschermd gebied weidt en bijna erin weidt. Voorwaar, elke koning heeft een beschermd gebied, en het beschermde gebied van Allah zijn Zijn verboden. Voorwaar, in het lichaam is een stukje vlees: als het gezond is, is het hele lichaam gezond, en als het bedorven is, is het hele lichaam bedorven. Voorwaar, het is het hart."',
  'Ebû Abdillâh Nuʿmân ibn Beşîr''den (Allah her ikisinden de razı olsun): Resûlullah''ın ﷺ şöyle buyurduğunu işittim: „Helal bellidir, haram da bellidir; ikisi arasında ise birçok insanın bilmediği şüpheli işler vardır. Kim şüpheli şeylerden sakınırsa dinini ve ırzını korumuş olur; kim de şüpheli şeylere düşerse harama düşer; tıpkı korunun çevresinde sürü otlatan, neredeyse içinde otlatacak olan çoban gibi. Dikkat edin, her hükümdarın bir korusu vardır; dikkat edin, Allah''ın korusu da haram kıldıklarıdır. Dikkat edin, bedende bir et parçası vardır: o iyi olursa bütün beden iyi olur, o bozulursa bütün beden bozulur. Dikkat edin, o kalptir."',
  'Dari Abu Abdullah an-Nuʿman bin Basyir (semoga Allah meridhai keduanya): Aku mendengar Rasulullah ﷺ bersabda: "Yang halal itu jelas dan yang haram itu jelas, dan di antara keduanya ada perkara-perkara samar (syubhat) yang tidak diketahui oleh kebanyakan manusia. Maka barangsiapa menjaga diri dari perkara-perkara samar, sungguh ia telah membersihkan agama dan kehormatannya; dan barangsiapa terjerumus ke dalam perkara samar, ia terjerumus ke dalam yang haram, seperti penggembala yang menggembala di sekitar daerah terlarang, hampir-hampir ia menggembala di dalamnya. Ketahuilah, setiap raja memiliki daerah terlarang, dan ketahuilah daerah terlarang Allah adalah perkara-perkara yang Dia haramkan. Ketahuilah, di dalam tubuh ada segumpal daging: jika ia baik, baiklah seluruh tubuh, dan jika ia rusak, rusaklah seluruh tubuh. Ketahuilah, ia adalah hati."',
  'ابو عبد اللہ نعمان بن بشیر رضی اللہ عنہما سے روایت ہے: میں نے رسول اللہ ﷺ کو فرماتے سنا: ”حلال واضح ہے اور حرام واضح ہے، اور ان دونوں کے درمیان کچھ مشتبہ چیزیں ہیں جنہیں بہت سے لوگ نہیں جانتے۔ پس جو شخص مشتبہ چیزوں سے بچ گیا اس نے اپنے دین اور اپنی عزت کو محفوظ کر لیا؛ اور جو مشتبہ چیزوں میں پڑ گیا وہ حرام میں جا پڑا، اس چرواہے کی طرح جو کسی محفوظ چراگاہ کے گرد جانور چراتا ہے، قریب ہے کہ وہ اسی میں چرانے لگے۔ خبردار! ہر بادشاہ کی ایک محفوظ چراگاہ ہوتی ہے، اور خبردار! اللہ کی محفوظ چراگاہ اس کی حرام کردہ چیزیں ہیں۔ خبردار! جسم میں ایک گوشت کا لوتھڑا ہے، جب وہ درست ہو تو سارا جسم درست ہو جاتا ہے، اور جب وہ بگڑ جائے تو سارا جسم بگڑ جاتا ہے۔ خبردار! وہ دل ہے۔“',
  'আবু আবদিল্লাহ নুমান ইবনে বাশীর (রাদিয়াল্লাহু আনহুমা) থেকে বর্ণিত: আমি রাসূলুল্লাহ ﷺ-কে বলতে শুনেছি: "হালাল সুস্পষ্ট এবং হারাম সুস্পষ্ট, আর এ দুইয়ের মাঝে রয়েছে কিছু সন্দেহজনক বিষয় যা অনেক মানুষ জানে না। সুতরাং যে ব্যক্তি সন্দেহজনক বিষয়গুলো থেকে বেঁচে থাকল, সে তার দ্বীন ও সম্মান রক্ষা করল; আর যে সন্দেহজনক বিষয়ে পতিত হলো, সে হারামে পতিত হলো, ঐ রাখালের মতো যে সংরক্ষিত চারণভূমির আশেপাশে পশু চরায়, অচিরেই সে তার ভেতরে চরাবে। জেনে রাখো, প্রত্যেক রাজার একটি সংরক্ষিত এলাকা থাকে, আর জেনে রাখো আল্লাহর সংরক্ষিত এলাকা হলো তাঁর হারামকৃত বিষয়সমূহ। জেনে রাখো, দেহের মধ্যে একটি মাংসপিণ্ড আছে, তা ভালো হলে সমস্ত দেহ ভালো হয়, আর তা নষ্ট হলে সমস্ত দেহ নষ্ট হয়। জেনে রাখো, তা হলো হৃদয় (কলব)।"',
  'Daripada Abu Abdullah an-Nuʿman bin Basyir (semoga Allah meredai keduanya): Aku mendengar Rasulullah ﷺ bersabda: "Yang halal itu jelas dan yang haram itu jelas, dan antara keduanya ada perkara-perkara yang samar (syubhat) yang tidak diketahui oleh kebanyakan manusia. Maka sesiapa yang menjaga diri daripada perkara-perkara samar, sungguh dia telah membersihkan agama dan maruahnya; dan sesiapa yang terjerumus ke dalam perkara samar, dia terjerumus ke dalam yang haram, seperti pengembala yang mengembala di sekitar kawasan larangan, hampir-hampir dia mengembala di dalamnya. Ketahuilah, setiap raja mempunyai kawasan larangan, dan ketahuilah kawasan larangan Allah ialah perkara-perkara yang diharamkan-Nya. Ketahuilah, di dalam tubuh ada seketul daging: jika ia baik, baiklah seluruh tubuh, dan jika ia rosak, rosaklah seluruh tubuh. Ketahuilah, ia ialah hati."',
  'Со слов Абу ʿАбдиллаха ан-Нуʿмана ибн Башира (да будет доволен Аллах ими обоими): Я слышал, как Посланник Аллаха ﷺ сказал: «Дозволенное ясно и запретное ясно, а между ними — сомнительные вещи, которых не знают многие люди. Кто остерегается сомнительного, тот оберегает свою религию и свою честь; а кто впадает в сомнительное, тот впадает в запретное, подобно пастуху, который пасёт стадо вокруг заповедника и вот-вот станет пасти в нём. Поистине, у каждого правителя есть заповедник, и заповедник Аллаха — это то, что Он запретил. Поистине, в теле есть кусочек плоти: если он здоров, то здорово всё тело, а если он испорчен, то испорчено всё тело. Поистине, это — сердце».',
  -- reference
  'Sahih — reported by Al-Bukhari (no. 52), Muslim (no. 1599), Abu Dawud (no. 3329), at-Tirmidhi (no. 1205), an-Nasaʾi (7/241)',
  'Hadith authentique rapporté par Al-Bukhari (n°52), Muslim (n°1599), Abû Dâwûd (n°3329), at-Tirmidhî (n°1205), an-Nasâʾî (7/241)',
  'حديث صحيح، رواه البخاري (رقم ٥٢) ومسلم (رقم ١٥٩٩) وأبو داود (رقم ٣٣٢٩) والترمذي (رقم ١٢٠٥) والنسائي (٧/٢٤١)',
  'Sahih — überliefert von Al-Bukhari (Nr. 52), Muslim (Nr. 1599), Abu Dawud (Nr. 3329), at-Tirmidhi (Nr. 1205), an-Nasaʾi (7/241)',
  'Sahih — overgeleverd door Al-Bukhari (nr. 52), Muslim (nr. 1599), Abu Dawud (nr. 3329), at-Tirmidhi (nr. 1205), an-Nasaʾi (7/241)',
  'Sahih — Buhârî (no. 52), Müslim (no. 1599), Ebû Dâvûd (no. 3329), Tirmizî (no. 1205), Nesâî (7/241) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (no. 52), Muslim (no. 1599), Abu Dawud (no. 3329), at-Tirmidzi (no. 1205), an-Nasaʾi (7/241)',
  'صحیح حدیث، اسے بخاری (نمبر ۵۲)، مسلم (نمبر ۱۵۹۹)، ابو داود (نمبر ۳۳۲۹)، ترمذی (نمبر ۱۲۰۵) اور نسائی (۷/۲۴۱) نے روایت کیا',
  'সহীহ হাদীস — বুখারী (নং ৫২), মুসলিম (নং ১৫৯৯), আবু দাউদ (নং ৩৩২৯), তিরমিযী (নং ১২০৫), নাসাঈ (৭/২৪১) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Al-Bukhari (no. 52), Muslim (no. 1599), Abu Dawud (no. 3329), at-Tirmizi (no. 1205), an-Nasaʾi (7/241)',
  'Достоверный хадис, передали аль-Бухари (№ 52), Муслим (№ 1599), Абу Давуд (№ 3329), ат-Тирмизи (№ 1205), ан-Насаи (7/241)',
  -- tafsir
  'In this hadith the Prophet ﷺ classified things into three categories:\n• The category of things lawful in an evident, unambiguous way, such as the permission to eat the livestock of the flock.\n• The category of things unlawful in an evident, unambiguous way, such as the prohibition of wine.\n• The third category is that of doubtful matters which leave the ruling uncertain: do they belong to the lawful or to the unlawful? Many people do not know the status of these matters, though it may be known to others.\nConcerning this category, the Messenger of Allah ﷺ stressed that avoiding such things is part of scrupulous piety, saying: "So whoever guards against the doubtful matters has protected his religion and his honour." He protects his religion in what is between Allah and him, and protects his honour in what is between people and him, so that they do not say that so-and-so fell into the unlawful — since they know its status, while to him the matter is confusing.',
  'Dans ce hadith, le Prophète ﷺ a classé les choses en trois catégories :\n• La catégorie des choses licites de façon évidente et sans ambiguïté, comme l''autorisation de manger la bête du troupeau.\n• La catégorie des choses illicites de façon évidente et sans ambiguïté, comme l''interdiction du vin.\n• La troisième catégorie est celle des choses équivoques qui laissent le jugement hésitant : font-elles partie du licite ou de l''illicite ? Beaucoup de gens ignorent le statut de ces choses, même s''il est connu chez d''autres.\nConcernant cette catégorie, l''Envoyé d''Allah ﷺ a souligné qu''éviter ces choses relève de la piété scrupuleuse, en disant : « Ainsi, quiconque se met à l''abri des choses équivoques préserve sa religion et son honneur. » Il préserve sa religion pour ce qui est entre Allah et lui, et préserve son honneur pour ce qui est entre les gens et lui, afin qu''ils ne disent pas qu''untel est tombé dans l''illicite — puisqu''ils en connaissent le statut, alors qu''à ses yeux la chose prête à confusion.',
  'في هذا الحديث قسّم النبي صلى الله عليه وسلم الأشياء إلى ثلاثة أقسام:\n• قسم الحلال البيّن الذي لا اشتباه فيه، كإباحة أكل بهيمة الأنعام.\n• قسم الحرام البيّن الذي لا اشتباه فيه، كتحريم الخمر.\n• والقسم الثالث هو المشتبهات التي يتردد فيها الحكم: هل هي من الحلال أم من الحرام؟ يجهل كثير من الناس حكمها وإن كان معلوماً عند غيرهم.\nوفي هذا القسم بيّن رسول الله صلى الله عليه وسلم أن اجتناب هذه الأمور من الورع، فقال: «فمن اتقى الشبهات فقد استبرأ لدينه وعرضه»، فيستبرئ لدينه فيما بينه وبين الله، ويستبرئ لعرضه فيما بينه وبين الناس، حتى لا يتحدثوا أن فلاناً وقع في الحرام، لكونهم يعلمون حكمه، بينما هو عنده مشتبه.',
  'In diesem Hadith teilte der Prophet ﷺ die Dinge in drei Kategorien ein:\n• Die Kategorie des offenkundig und unzweideutig Erlaubten, wie die Erlaubnis, das Vieh der Herde zu essen.\n• Die Kategorie des offenkundig und unzweideutig Verbotenen, wie das Verbot des Weins.\n• Die dritte Kategorie sind die zweifelhaften Dinge, bei denen das Urteil unsicher bleibt: gehören sie zum Erlaubten oder zum Verbotenen? Viele Menschen kennen ihren Status nicht, auch wenn er anderen bekannt sein mag.\nIn Bezug auf diese Kategorie betonte der Gesandte Allahs ﷺ, dass das Meiden solcher Dinge zur gewissenhaften Frömmigkeit gehört, indem er sagte: „Wer sich vor den zweifelhaften Dingen hütet, hat seine Religion und seine Ehre bewahrt." Er bewahrt seine Religion in dem, was zwischen Allah und ihm ist, und bewahrt seine Ehre in dem, was zwischen den Menschen und ihm ist, damit sie nicht sagen, dass der und der ins Verbotene gefallen sei — denn sie kennen dessen Status, während die Sache für ihn unklar ist.',
  'In deze hadith verdeelde de Profeet ﷺ de dingen in drie categorieën:\n• De categorie van het op duidelijke, ondubbelzinnige wijze toegestane, zoals de toestemming om het vee van de kudde te eten.\n• De categorie van het op duidelijke, ondubbelzinnige wijze verbodene, zoals het verbod op wijn.\n• De derde categorie is die van de twijfelachtige zaken waarbij het oordeel onzeker blijft: behoren ze tot het toegestane of tot het verbodene? Veel mensen kennen de status ervan niet, ook al is die wellicht bij anderen bekend.\nWat deze categorie betreft, benadrukte de Boodschapper van Allah ﷺ dat het vermijden van zulke zaken tot nauwgezette vroomheid behoort, door te zeggen: „Wie zich voor de twijfelachtige zaken hoedt, heeft zijn religie en zijn eer beschermd." Hij beschermt zijn religie in wat tussen Allah en hem is, en beschermt zijn eer in wat tussen de mensen en hem is, zodat zij niet zeggen dat die-en-die in het verbodene is vervallen — aangezien zij de status ervan kennen, terwijl de zaak voor hem verwarrend is.',
  'Bu hadiste Peygamber ﷺ şeyleri üç kısma ayırdı:\n• Şüphe bulunmayan, açıkça helal olan şeyler kısmı; mesela davar etini yemenin mubah olması gibi.\n• Şüphe bulunmayan, açıkça haram olan şeyler kısmı; mesela şarabın haram kılınması gibi.\n• Üçüncü kısım, hükmü tereddütlü olan şüpheli şeylerdir: helalden mi yoksa haramdan mı sayılırlar? Birçok insan bunların hükmünü bilmez, başkalarınca biliniyor olsa da.\nBu kısımla ilgili olarak Resûlullah ﷺ, bu tür şeylerden kaçınmanın veradan olduğunu vurguladı ve şöyle dedi: „Kim şüpheli şeylerden sakınırsa dinini ve ırzını korumuş olur." Allah ile kendisi arasındaki konuda dinini korur, insanlarla kendisi arasındaki konuda ise ırzını korur; ta ki insanlar — hükmünü bildikleri için — falanca harama düştü demesinler, hâlbuki o iş kendisi için şüphelidir.',
  'Dalam hadis ini, Nabi ﷺ membagi segala sesuatu menjadi tiga kategori:\n• Kategori yang halal secara jelas tanpa keraguan, seperti dibolehkannya memakan hewan ternak.\n• Kategori yang haram secara jelas tanpa keraguan, seperti diharamkannya khamar.\n• Kategori ketiga adalah perkara-perkara samar yang membuat hukumnya ragu: apakah termasuk yang halal atau yang haram? Banyak orang tidak mengetahui hukumnya, meskipun mungkin diketahui oleh sebagian yang lain.\nMengenai kategori ini, Rasulullah ﷺ menegaskan bahwa menjauhi perkara-perkara tersebut termasuk wara (kehati-hatian), dengan bersabda: "Maka barangsiapa menjaga diri dari perkara-perkara samar, sungguh ia telah membersihkan agama dan kehormatannya." Ia membersihkan agamanya dalam hal yang antara dirinya dan Allah, dan membersihkan kehormatannya dalam hal yang antara dirinya dan manusia, agar mereka tidak mengatakan bahwa si fulan terjerumus ke dalam yang haram — karena mereka mengetahui hukumnya, sementara bagi dirinya perkara itu samar.',
  'اس حدیث میں نبی ﷺ نے چیزوں کو تین اقسام میں تقسیم فرمایا:\n• وہ قسم جو واضح اور بلا اشتباہ حلال ہے، جیسے مویشی کا گوشت کھانے کی اجازت۔\n• وہ قسم جو واضح اور بلا اشتباہ حرام ہے، جیسے شراب کی حرمت۔\n• تیسری قسم وہ مشتبہ چیزیں ہیں جن میں حکم متردد رہتا ہے: کیا یہ حلال میں سے ہیں یا حرام میں سے؟ بہت سے لوگ ان کا حکم نہیں جانتے، اگرچہ دوسروں کے ہاں معلوم ہو۔\nاس قسم کے بارے میں رسول اللہ ﷺ نے واضح فرمایا کہ ان چیزوں سے بچنا ورع میں سے ہے، فرمایا: ”پس جو مشتبہ چیزوں سے بچ گیا اس نے اپنے دین اور اپنی عزت کو محفوظ کر لیا۔“ وہ اپنے دین کو اس معاملے میں محفوظ کرتا ہے جو اس کے اور اللہ کے درمیان ہے، اور اپنی عزت کو اس معاملے میں محفوظ کرتا ہے جو اس کے اور لوگوں کے درمیان ہے، تاکہ لوگ یہ نہ کہیں کہ فلاں حرام میں جا پڑا — کیونکہ وہ اس کا حکم جانتے ہیں، جبکہ اس کے نزدیک وہ چیز مشتبہ ہے۔',
  'এই হাদীসে নবী ﷺ বিষয়গুলোকে তিন ভাগে ভাগ করেছেন:\n• সুস্পষ্ট ও সন্দেহমুক্তভাবে হালাল বিষয়, যেমন গবাদিপশুর গোশত খাওয়ার অনুমতি।\n• সুস্পষ্ট ও সন্দেহমুক্তভাবে হারাম বিষয়, যেমন মদের নিষেধাজ্ঞা।\n• তৃতীয় ভাগ হলো সন্দেহজনক বিষয়, যেগুলোতে বিধান অনিশ্চিত থাকে: এগুলো কি হালালের অন্তর্ভুক্ত নাকি হারামের? অনেক মানুষ এগুলোর বিধান জানে না, যদিও অন্যদের কাছে তা জানা থাকতে পারে।\nএই ভাগ সম্পর্কে রাসূলুল্লাহ ﷺ স্পষ্ট করেছেন যে এসব বিষয় এড়িয়ে চলা তাকওয়া (সতর্কতা)-র অন্তর্ভুক্ত, তিনি বলেছেন: "সুতরাং যে সন্দেহজনক বিষয়গুলো থেকে বেঁচে থাকল, সে তার দ্বীন ও সম্মান রক্ষা করল।" সে তার দ্বীন রক্ষা করে যা তার ও আল্লাহর মধ্যে, আর তার সম্মান রক্ষা করে যা তার ও মানুষের মধ্যে, যাতে তারা না বলে যে অমুক হারামে পতিত হয়েছে — কারণ তারা এর বিধান জানে, অথচ তার কাছে বিষয়টি সন্দেহজনক।',
  'Dalam hadis ini, Nabi ﷺ membahagikan segala sesuatu kepada tiga kategori:\n• Kategori yang halal secara jelas tanpa kesamaran, seperti dibolehkannya memakan haiwan ternakan.\n• Kategori yang haram secara jelas tanpa kesamaran, seperti diharamkannya arak.\n• Kategori ketiga ialah perkara-perkara samar yang membuat hukumnya ragu: adakah ia termasuk yang halal atau yang haram? Ramai orang tidak mengetahui hukumnya, walaupun mungkin diketahui oleh sebahagian yang lain.\nMengenai kategori ini, Rasulullah ﷺ menegaskan bahawa menjauhi perkara-perkara tersebut termasuk warak (kehati-hatian), dengan bersabda: "Maka sesiapa yang menjaga diri daripada perkara-perkara samar, sungguh dia telah membersihkan agama dan maruahnya." Dia membersihkan agamanya dalam perkara yang antara dirinya dan Allah, dan membersihkan maruahnya dalam perkara yang antara dirinya dan manusia, agar mereka tidak mengatakan bahawa si fulan terjerumus ke dalam yang haram — kerana mereka mengetahui hukumnya, sedangkan bagi dirinya perkara itu samar.',
  'В этом хадисе Пророк ﷺ разделил вещи на три категории:\n• Категория явно и недвусмысленно дозволенного, как, например, разрешение есть мясо скота.\n• Категория явно и недвусмысленно запретного, как, например, запрет вина.\n• Третья категория — это сомнительные вещи, в отношении которых суждение колеблется: относятся ли они к дозволенному или к запретному? Многие люди не знают их положения, хотя оно может быть известно другим.\nОтносительно этой категории Посланник Аллаха ﷺ подчеркнул, что избегание подобных вещей относится к богобоязненной осторожности (вараʿ), сказав: «Кто остерегается сомнительного, тот оберегает свою религию и свою честь». Он оберегает свою религию в том, что между ним и Аллахом, и оберегает свою честь в том, что между ним и людьми, чтобы они не говорили, что такой-то впал в запретное — ведь они знают его положение, тогда как для него самого дело является сомнительным.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-6-Nawawi-Psalmodie-Arabe.mp3',
  5,
  6
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 6
);
