-- =============================================================================
-- 40 Hadith Nawawi — Hadith 21: "Say: I believe in Allah, then be upright"
-- Target collection: public.hadith_collections.id = 2  /  position = 21
-- Idempotent guard on (collection, position). All 11 content languages.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'Say: I believe in Allah, then be upright',
  'Dis : « J''ai foi en Allah », puis suis la voie droite',
  'قل آمنت بالله ثم استقم',
  'Sprich: Ich glaube an Allah, dann sei aufrichtig',
  'Zeg: Ik geloof in Allah, wees dan standvastig',
  'De ki: Allah''a iman ettim, sonra dosdoğru ol',
  'Katakanlah: Aku beriman kepada Allah, lalu istiqamahlah',
  'کہو: میں اللہ پر ایمان لایا، پھر استقامت اختیار کرو',
  'বলো: আমি আল্লাহর প্রতি ঈমান এনেছি, অতঃপর অবিচল থাকো',
  'Katakanlah: Aku beriman kepada Allah, lalu beristiqamahlah',
  'Скажи: «Я уверовал в Аллаха», затем будь стойким',
  -- arabic_text
  'عَنْ أَبِي عَمْرٍو، وَقِيلَ أَبِي عَمْرَةَ، سُفْيَانَ بْنِ عَبْدِ اللَّهِ رَضِيَ اللَّهُ عَنْهُ قَالَ: قُلْتُ: يَا رَسُولَ اللَّهِ، قُلْ لِي فِي الْإِسْلَامِ قَوْلًا لَا أَسْأَلُ عَنْهُ أَحَدًا غَيْرَكَ. قَالَ: «قُلْ: آمَنْتُ بِاللَّهِ، ثُمَّ اسْتَقِمْ»',
  -- transcription
  'ʿan Abī ʿAmrin, wa-qīla Abī ʿAmrata, Sufyāna bni ʿAbdi Llāhi raḍiya Llāhu ʿanhu qāla: qultu: yā Rasūla Llāhi, qul lī fi l-islāmi qawlan lā asʾalu ʿanhu aḥadan ghayraka. qāla: qul: āmantu bi-Llāhi, thumma staqim.',
  'ʿan Abî ʿAmrin, wa qîla Abî ʿAmrata, Soufyâna bni ʿAbdi Llâhi (radia Llâhou ʿanhou) qâla : qoultou : yâ Rassôla Llâhi, qoul lî fi l-islâmi qawlan lâ asʾalou ʿanhou ahadan ghayraka. qâla : qoul : âmantou bi-Llâhi, thoumma staqim.',
  'ʿan Abī ʿAmrin, wa-qīla Abī ʿAmrata, Sufjāna bni ʿAbdi Llāhi (radiya Llāhu ʿanhu) qāla: qultu: jā Rasūla Llāhi, qul lī fi l-islāmi qaulan lā asʾalu ʿanhu ahadan ghairaka. qāla: qul: āmantu bi-Llāhi, thumma staqim.',
  'ʿan Abie ʿAmrin, wa-qiela Abie ʿAmrata, Soefjaana bni ʿAbdi Llaahi (radia Llaahoe ʿanhoe) qaala: qoeltoe: jaa Rasoela Llaahi, qoel lie fi l-islaami qaulan laa asʾaloe ʿanhoe ahadan ghairaka. qaala: qoel: aamantoe bi-Llaahi, thoemma staqim.',
  'an Ebû Amr — Ebû Amra da denir — Süfyân ibn Abdillâh''tan (radıyallâhu anh) rivayetle dedi ki: dedim ki: yâ Resûlallah, bana İslâm hakkında, senden başkasına sormayacağım bir söz söyle. Buyurdu: kul: âmentu bi''llâhi, summe''stekım (de ki: Allah''a iman ettim, sonra dosdoğru ol).',
  'ʿan Abī ʿAmr — disebut juga Abī ʿAmrah — Sufyan bin ʿAbdillah (radhiyallāhu ʿanhu) berkata: aku berkata: wahai Rasulullah, katakanlah kepadaku tentang Islam suatu perkataan yang aku tidak akan menanyakannya kepada seorang pun selainmu. Beliau bersabda: qul: āmantu billāhi, tsummastaqim (katakanlah: aku beriman kepada Allah, lalu istiqamahlah).',
  'ابو عمرو — اور کہا گیا ابو عمرہ — سفیان بن عبد اللہ رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: میں نے عرض کیا: یا رسول اللہ! مجھے اسلام کے بارے میں کوئی ایسی بات بتائیے جس کے بارے میں آپ کے سوا کسی سے نہ پوچھوں۔ آپ نے فرمایا: قُل: آمَنتُ بِاللہِ، ثُمَّ استَقِم (کہو: میں اللہ پر ایمان لایا، پھر استقامت اختیار کرو)۔',
  'আবু আমর — আবু আমরাও বলা হয় — সুফিয়ান ইবনে আবদিল্লাহ (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: আমি বললাম: হে আল্লাহর রাসূল! আমাকে ইসলাম সম্পর্কে এমন কথা বলুন যা সম্পর্কে আপনি ছাড়া আর কাউকে জিজ্ঞাসা করব না। তিনি বললেন: কুল: আমানতু বিল্লাহি, সুম্মাসতাকিম (বলো: আমি আল্লাহর প্রতি ঈমান এনেছি, অতঃপর অবিচল থাকো)।',
  'ʿan Abī ʿAmr — disebut juga Abī ʿAmrah — Sufyan bin ʿAbdillah (radhiallāhu ʿanhu) berkata: aku berkata: wahai Rasulullah, katakanlah kepadaku tentang Islam suatu perkataan yang aku tidak akan menanyakannya kepada sesiapa pun selainmu. Baginda bersabda: qul: āmantu billāhi, tsummastaqim (katakanlah: aku beriman kepada Allah, lalu beristiqamahlah).',
  'Ан Аби Амр — также говорят Аби Амра — Суфьян ибн Абдиллях (да будет доволен им Аллах) сказал: я сказал: о Посланник Аллаха, скажи мне об исламе такое слово, о котором я не спрошу никого, кроме тебя. Он сказал: куль: аманту би-Лляхи, сумма-стаким (скажи: я уверовал в Аллаха, затем будь стойким).',
  -- translation
  'On the authority of Abu ʿAmr — also said Abu ʿAmra — Sufyan ibn ʿAbd Allah (may Allah be pleased with him), who said: I said: "O Messenger of Allah, tell me something about Islam which I will not ask anyone but you about." He said: "Say: ''I believe in Allah,'' then be upright (remain steadfast)."',
  'D''après Abû ʿAmr — on dit aussi Abû ʿAmra — Sufyân ibn ʿAbd Allah (qu''Allah l''agrée), qui a dit : Je dis : « Ô Envoyé d''Allah, dis-moi sur l''Islam une parole sur laquelle je n''interrogerai personne d''autre que toi. » Il dit : « Dis : "J''ai cru en Allah", puis maintiens-toi droit (reste constant). »',
  'Nach Abu ʿAmr — auch Abu ʿAmra genannt — Sufyan ibn ʿAbd Allah (möge Allah mit ihm zufrieden sein), der sagte: Ich sagte: „O Gesandter Allahs, sage mir über den Islam ein Wort, nach dem ich niemanden außer dir fragen werde." Er sagte: „Sprich: ''Ich glaube an Allah'', dann sei aufrichtig (bleibe standhaft)."',
  'Op gezag van Abu ʿAmr — ook Abu ʿAmra genoemd — Sufyan ibn ʿAbd Allah (moge Allah tevreden met hem zijn), die zei: Ik zei: „O Boodschapper van Allah, zeg mij over de islam een woord waarover ik niemand anders dan u zal vragen." Hij zei: „Zeg: ''Ik geloof in Allah'', wees dan standvastig (blijf volhardend)."',
  'Ebû Amr — Ebû Amra da denilir — Süfyân ibn Abdillâh''tan (Allah ondan razı olsun) rivayet edildiğine göre şöyle dedi: Dedim ki: „Ey Allah''ın Resûlü, bana İslâm hakkında, senden başkasına sormayacağım bir söz söyle." Buyurdu: „De ki: ''Allah''a iman ettim'', sonra dosdoğru ol (sebat et)."',
  'Dari Abu ʿAmr — disebut juga Abu ʿAmrah — Sufyan bin ʿAbdullah (semoga Allah meridhainya), yang berkata: Aku berkata: "Wahai Rasulullah, katakanlah kepadaku tentang Islam suatu perkataan yang tidak akan kutanyakan kepada siapa pun selainmu." Beliau bersabda: "Katakanlah: ''Aku beriman kepada Allah'', lalu istiqamahlah (teguhlah)."',
  'ابو عمرو — اور ابو عمرہ بھی کہا گیا ہے — سفیان بن عبد اللہ رضی اللہ عنہ سے روایت ہے، انہوں نے کہا: میں نے عرض کیا: ”یا رسول اللہ! مجھے اسلام کے بارے میں ایسی بات بتائیے جس کے بارے میں آپ کے سوا کسی سے نہ پوچھوں۔“ آپ نے فرمایا: ”کہو: ''میں اللہ پر ایمان لایا''، پھر استقامت اختیار کرو (ثابت قدم رہو)۔“',
  'আবু আমর — আবু আমরাও বলা হয় — সুফিয়ান ইবনে আবদিল্লাহ (রাদিয়াল্লাহু আনহু) থেকে বর্ণিত, তিনি বলেন: আমি বললাম: "হে আল্লাহর রাসূল! আমাকে ইসলাম সম্পর্কে এমন কথা বলুন যা সম্পর্কে আপনি ছাড়া আর কাউকে জিজ্ঞাসা করব না।" তিনি বললেন: "বলো: ''আমি আল্লাহর প্রতি ঈমান এনেছি'', অতঃপর অবিচল থাকো (দৃঢ় থাকো)।"',
  'Daripada Abu ʿAmr — disebut juga Abu ʿAmrah — Sufyan bin ʿAbdullah (semoga Allah meredainya), yang berkata: Aku berkata: "Wahai Rasulullah, katakanlah kepadaku tentang Islam suatu perkataan yang tidak akan kutanyakan kepada sesiapa pun selainmu." Baginda bersabda: "Katakanlah: ''Aku beriman kepada Allah'', lalu beristiqamahlah (teguhlah)."',
  'Со слов Абу ʿАмра — также называют Абу ʿАмра — Суфьяна ибн ʿАбдиллаха (да будет доволен им Аллах), который сказал: Я сказал: «О Посланник Аллаха, скажи мне об исламе такое слово, о котором я не спрошу никого, кроме тебя». Он сказал: «Скажи: ''Я уверовал в Аллаха'', затем будь стойким (придерживайся прямоты)».',
  -- reference
  'Sahih — reported by Muslim (1/65, no. 38), Ahmad (3/385), at-Tirmidhi (no. 2410), and Ibn Majah (no. 3972)',
  'Hadith authentique rapporté par Muslim (1/65, n°38), Ahmad (3/385), at-Tirmidhî (n°2410) et Ibn Mâja (n°3972)',
  'حديث صحيح، رواه مسلم (١/٦٥) (رقم ٣٨) وأحمد (٣/٣٨٥) والترمذي (رقم ٢٤١٠) وابن ماجه (رقم ٣٩٧٢)',
  'Sahih — überliefert von Muslim (1/65, Nr. 38), Ahmad (3/385), at-Tirmidhi (Nr. 2410) und Ibn Madscha (Nr. 3972)',
  'Sahih — overgeleverd door Muslim (1/65, nr. 38), Ahmad (3/385), at-Tirmidhi (nr. 2410) en Ibn Madja (nr. 3972)',
  'Sahih — Müslim (1/65, no. 38), Ahmed (3/385), Tirmizî (no. 2410) ve İbn Mâce (no. 3972) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Muslim (1/65, no. 38), Ahmad (3/385), at-Tirmidzi (no. 2410), dan Ibnu Majah (no. 3972)',
  'صحیح حدیث، اسے مسلم (۱/۶۵، نمبر ۳۸)، احمد (۳/۳۸۵)، ترمذی (نمبر ۲۴۱۰) اور ابن ماجہ (نمبر ۳۹۷۲) نے روایت کیا',
  'সহীহ হাদীস — মুসলিম (১/৬৫, নং ৩৮), আহমাদ (৩/৩৮৫), তিরমিযী (নং ২৪১০) ও ইবনে মাজাহ (নং ৩৯৭২) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Muslim (1/65, no. 38), Ahmad (3/385), at-Tirmizi (no. 2410), dan Ibnu Majah (no. 3972)',
  'Достоверный хадис, передали Муслим (1/65, № 38), Ахмад (3/385), ат-Тирмизи (№ 2410) и Ибн Маджа (№ 3972)',
  -- tafsir
  'This Companion asked the Prophet ﷺ to tell him about Islam something concise about which he would ask no one else — that is, words that are comprehensive, clear and explicit. The Prophet ﷺ answered: "Say: ''I believe in Allah,'' then be upright." Belief in Allah is by the heart, and uprightness is by the limbs. The Prophet ﷺ gave him words encompassing the whole religion:\n— "I believe in Allah": this is belief in everything Allah has informed us of — about His noble Self, the Last Day, His messengers, the purpose of their mission, and so forth.\n— The second statement concerns submission and compliance (inqiyad), the second foundation of the religion: "then be upright" — a command built upon belief; hence he used the conjunction "then" (thumma), which denotes order in succession.\nTo be upright (istiqama) means to remain permanently on the path of rectitude, the path of those Allah has favoured: the prophets, the truthful, the martyrs, and the righteous. When a person builds his life on these two principles, he will live happily in this world and in the Hereafter.',
  'Ce compagnon a demandé au Prophète ﷺ de lui dire sur l''Islam une parole sur laquelle il n''interrogerait personne d''autre que lui — c''est-à-dire des paroles synthétiques, claires et explicites. Le Prophète ﷺ a répondu : « Dis : "J''ai cru en Allah", puis maintiens-toi droit. » La croyance en Allah se fait par le cœur, et la rectitude par les membres. Le Prophète ﷺ lui a donné des paroles qui englobent toute la religion :\n— « J''ai cru en Allah » : c''est la croyance en toutes les informations données par Allah — sur Sa noble Personne, le Jour Dernier, Ses Envoyés, l''objet de leur mission, etc.\n— La seconde parole concerne la docilité (inqiyâd), le second fondement de la religion : « puis maintiens-toi droit » — une injonction bâtie sur la croyance ; il a donc employé la conjonction « puis » (thumma), qui signifie l''ordre dans la succession.\nSe maintenir droit (istiqâma) signifie demeurer en permanence sur la voie de rectitude, voie de ceux qu''Allah a gratifiés : les prophètes, les véridiques, les martyrs et les vertueux. Quand l''homme fonde sa vie sur ces deux principes, il vivra heureux ici-bas et dans l''au-delà.',
  'سأل هذا الصحابي النبي صلى الله عليه وسلم أن يقول له في الإسلام قولاً لا يسأل عنه أحداً غيره، أي كلمات جامعة واضحة صريحة. فأجابه النبي صلى الله عليه وسلم: «قل: آمنت بالله، ثم استقم». فالإيمان بالله يكون بالقلب، والاستقامة تكون بالجوارح. وقد أعطاه النبي صلى الله عليه وسلم كلمات تشمل الدين كله:\n— «آمنت بالله»: وهو الإيمان بكل ما أخبر به الله — عن ذاته الكريمة، واليوم الآخر، ورسله، والغاية من رسالتهم، ونحو ذلك.\n— والكلمة الثانية تتعلق بالانقياد (الأصل الثاني من الدين): «ثم استقم» — وهو أمر مبني على الإيمان، فلذلك أتى بحرف «ثم» الذي يفيد الترتيب مع التراخي.\nوالاستقامة تعني الثبات الدائم على طريق الاستقامة، طريق الذين أنعم الله عليهم: النبيين والصديقين والشهداء والصالحين. فإذا بنى الإنسان حياته على هذين الأصلين عاش سعيداً في الدنيا والآخرة.',
  'Dieser Gefährte bat den Propheten ﷺ, ihm über den Islam etwas Knappes zu sagen, wonach er niemanden außer ihm fragen würde — das heißt umfassende, klare und deutliche Worte. Der Prophet ﷺ antwortete: „Sprich: ''Ich glaube an Allah'', dann sei aufrichtig." Der Glaube an Allah geschieht durch das Herz, und die Aufrichtigkeit durch die Glieder. Der Prophet ﷺ gab ihm Worte, die die ganze Religion umfassen:\n— „Ich glaube an Allah": das ist der Glaube an alles, was Allah uns mitgeteilt hat — über Sein edles Selbst, den Jüngsten Tag, Seine Gesandten, den Zweck ihrer Sendung usw.\n— Die zweite Aussage betrifft die Fügsamkeit (Inqiyad), die zweite Grundlage der Religion: „dann sei aufrichtig" — ein Gebot, das auf dem Glauben aufbaut; deshalb gebrauchte er die Konjunktion „dann" (thumma), die die Reihenfolge in der Abfolge bezeichnet.\nAufrichtig zu sein (Istiqama) bedeutet, dauerhaft auf dem Weg der Geradheit zu verbleiben, dem Weg derer, denen Allah Gnade erwiesen hat: den Propheten, den Wahrhaftigen, den Märtyrern und den Rechtschaffenen. Wenn der Mensch sein Leben auf diese beiden Grundsätze gründet, wird er glücklich in dieser Welt und im Jenseits leben.',
  'Deze metgezel vroeg de Profeet ﷺ om hem over de islam iets beknopts te zeggen waarover hij niemand anders zou vragen — dat wil zeggen omvattende, heldere en duidelijke woorden. De Profeet ﷺ antwoordde: „Zeg: ''Ik geloof in Allah'', wees dan standvastig." Het geloof in Allah geschiedt door het hart, en de standvastigheid door de ledematen. De Profeet ﷺ gaf hem woorden die de hele religie omvatten:\n— „Ik geloof in Allah": dat is het geloof in alles waarvan Allah ons heeft bericht — over Zijn edele Zelf, de Laatste Dag, Zijn boodschappers, het doel van hun zending, enzovoort.\n— De tweede uitspraak betreft de onderwerping (inqiyad), de tweede grondslag van de religie: „wees dan standvastig" — een gebod dat op het geloof is gebouwd; daarom gebruikte hij het voegwoord „dan" (thumma), dat de volgorde in opeenvolging aanduidt.\nStandvastig zijn (istiqama) betekent permanent op het pad van oprechtheid te blijven, het pad van hen die Allah heeft begunstigd: de profeten, de waarachtigen, de martelaren en de rechtschapenen. Wanneer de mens zijn leven op deze twee beginselen bouwt, zal hij gelukkig leven in deze wereld en in het Hiernamaals.',
  'Bu sahâbî, Peygamber''den ﷺ İslâm hakkında, kendisinden başkasına sormayacağı özlü bir söz söylemesini istedi — yani kapsamlı, açık ve net sözler. Peygamber ﷺ şöyle cevap verdi: „De ki: ''Allah''a iman ettim'', sonra dosdoğru ol." Allah''a iman kalple, istikamet ise organlarla olur. Peygamber ﷺ ona bütün dini kapsayan sözler verdi:\n— „Allah''a iman ettim": bu, Allah''ın haber verdiği her şeye imandır — yüce zâtı, âhiret günü, resulleri, onların gönderiliş gayesi vb. hakkında.\n— İkinci söz, dinin ikinci temeli olan boyun eğmeyle (inkıyâd) ilgilidir: „sonra dosdoğru ol" — imana dayanan bir emirdir; bu yüzden, sıralamada gevşeklikle birlikte tertibi ifade eden „sonra" (sümme) edatını kullanmıştır.\nİstikamet, dosdoğruluk yolunda — Allah''ın nimet verdiği peygamberler, sıddıklar, şehitler ve sâlihlerin yolunda — sürekli sebat etmek demektir. İnsan hayatını bu iki esas üzerine kurduğunda, dünyada ve âhirette mutlu yaşar.',
  'Sahabat ini meminta Nabi ﷺ untuk mengatakan kepadanya tentang Islam suatu perkataan yang tidak akan ia tanyakan kepada siapa pun selainnya — yaitu kata-kata yang ringkas, jelas, dan tegas. Nabi ﷺ menjawab: "Katakanlah: ''Aku beriman kepada Allah'', lalu istiqamahlah." Iman kepada Allah dengan hati, dan istiqamah dengan anggota badan. Nabi ﷺ memberinya kata-kata yang mencakup seluruh agama:\n— "Aku beriman kepada Allah": yaitu beriman kepada segala yang Allah kabarkan — tentang Zat-Nya yang mulia, hari akhir, para rasul-Nya, tujuan risalah mereka, dan sebagainya.\n— Kalimat kedua berkaitan dengan ketundukan (inqiyad), dasar kedua agama: "lalu istiqamahlah" — perintah yang dibangun di atas iman; karena itu beliau menggunakan kata sambung "lalu" (tsumma), yang menunjukkan urutan dengan tenggang.\nIstiqamah berarti tetap teguh selamanya di atas jalan kelurusan, jalan orang-orang yang Allah beri nikmat: para nabi, orang-orang yang jujur (shiddiqin), para syuhada, dan orang-orang saleh. Apabila seseorang membangun hidupnya di atas dua prinsip ini, ia akan hidup bahagia di dunia dan akhirat.',
  'اس صحابی نے نبی ﷺ سے درخواست کی کہ آپ اسے اسلام کے بارے میں کوئی ایسی بات بتائیں جس کے بارے میں وہ آپ کے سوا کسی سے نہ پوچھے — یعنی جامع، واضح اور صریح کلمات۔ نبی ﷺ نے فرمایا: ”کہو: ''میں اللہ پر ایمان لایا''، پھر استقامت اختیار کرو۔“ اللہ پر ایمان دل سے ہوتا ہے اور استقامت اعضاء سے۔ نبی ﷺ نے اسے ایسے کلمات دیے جو پورے دین کو شامل ہیں:\n— ''میں اللہ پر ایمان لایا'': یہ ان تمام باتوں پر ایمان ہے جن کی اللہ نے خبر دی — اس کی ذاتِ کریمہ، یومِ آخرت، اس کے رسولوں اور ان کی بعثت کے مقصد وغیرہ کے بارے میں۔\n— دوسرا کلمہ انقیاد (دین کی دوسری بنیاد) سے متعلق ہے: ''پھر استقامت اختیار کرو'' — یہ ایمان پر مبنی ایک حکم ہے؛ اسی لیے آپ نے ''ثم'' کا حرف استعمال کیا جو ترتیب کے ساتھ تاخیر کا فائدہ دیتا ہے۔\nاستقامت کا مطلب ہے سیدھے راستے پر ہمیشہ ثابت قدم رہنا، ان لوگوں کا راستہ جن پر اللہ نے انعام کیا: انبیاء، صدیقین، شہداء اور صالحین۔ جب انسان اپنی زندگی ان دو اصولوں پر قائم کرے تو وہ دنیا و آخرت میں خوش و خرم زندگی گزارے گا۔',
  'এই সাহাবী নবী ﷺ-এর কাছে ইসলাম সম্পর্কে এমন সংক্ষিপ্ত কথা জানতে চাইলেন যা সম্পর্কে তিনি আর কাউকে জিজ্ঞাসা করবেন না — অর্থাৎ ব্যাপক, স্পষ্ট ও সুস্পষ্ট কথা। নবী ﷺ উত্তর দিলেন: "বলো: ''আমি আল্লাহর প্রতি ঈমান এনেছি'', অতঃপর অবিচল থাকো।" আল্লাহর প্রতি ঈমান অন্তর দিয়ে হয়, আর অবিচলতা অঙ্গপ্রত্যঙ্গ দিয়ে। নবী ﷺ তাঁকে এমন কথা দিলেন যা সমগ্র দ্বীনকে অন্তর্ভুক্ত করে:\n— ''আমি আল্লাহর প্রতি ঈমান এনেছি'': এটি আল্লাহ যা কিছু জানিয়েছেন তার সবকিছুর প্রতি ঈমান — তাঁর সম্মানিত সত্তা, শেষ দিবস, তাঁর রাসূলগণ, তাঁদের রিসালাতের উদ্দেশ্য ইত্যাদি সম্পর্কে।\n— দ্বিতীয় কথাটি আনুগত্যের (ইনকিয়াদ, দ্বীনের দ্বিতীয় ভিত্তি) সাথে সম্পর্কিত: ''অতঃপর অবিচল থাকো'' — এটি ঈমানের উপর প্রতিষ্ঠিত একটি আদেশ; এজন্যই তিনি ''সুম্মা'' শব্দটি ব্যবহার করেছেন যা ক্রম ও বিলম্ব নির্দেশ করে।\nইস্তিকামত (অবিচলতা) অর্থ সরল পথে স্থায়ীভাবে অবিচল থাকা, সেই পথ যাদের আল্লাহ অনুগ্রহ করেছেন: নবীগণ, সিদ্দীকগণ, শহীদগণ ও সৎকর্মশীলগণ। মানুষ যখন তার জীবন এই দুই মূলনীতির উপর গড়ে, তখন সে দুনিয়া ও আখিরাতে সুখী জীবনযাপন করবে।',
  'Sahabat ini meminta Nabi ﷺ untuk mengatakan kepadanya tentang Islam suatu perkataan yang tidak akan dia tanyakan kepada sesiapa pun selainnya — iaitu kata-kata yang ringkas, jelas, dan tegas. Nabi ﷺ menjawab: "Katakanlah: ''Aku beriman kepada Allah'', lalu beristiqamahlah." Iman kepada Allah dengan hati, dan istiqamah dengan anggota badan. Nabi ﷺ memberinya kata-kata yang merangkumi seluruh agama:\n— "Aku beriman kepada Allah": iaitu beriman kepada segala yang Allah khabarkan — tentang Zat-Nya yang mulia, hari akhir, para rasul-Nya, tujuan risalah mereka, dan sebagainya.\n— Kalimat kedua berkaitan dengan ketundukan (inqiyad), asas kedua agama: "lalu beristiqamahlah" — perintah yang dibina di atas iman; kerana itu baginda menggunakan kata sambung "lalu" (tsumma), yang menunjukkan urutan dengan tenggang.\nIstiqamah bermaksud tetap teguh selama-lamanya di atas jalan kelurusan, jalan orang-orang yang Allah beri nikmat: para nabi, orang-orang yang benar (siddiqin), para syuhada, dan orang-orang soleh. Apabila seseorang membina hidupnya di atas dua prinsip ini, dia akan hidup bahagia di dunia dan akhirat.',
  'Этот сподвижник попросил Пророка ﷺ сказать ему об исламе нечто краткое, о чём он не спросит никого, кроме него, — то есть слова всеобъемлющие, ясные и недвусмысленные. Пророк ﷺ ответил: «Скажи: ''Я уверовал в Аллаха'', затем будь стойким». Вера в Аллаха совершается сердцем, а стойкость (прямота) — органами тела. Пророк ﷺ дал ему слова, охватывающие всю религию:\n— «Я уверовал в Аллаха»: это вера во всё, о чём сообщил Аллах — о Своей благородной Сущности, Последнем дне, Своих посланниках, цели их послания и так далее.\n— Второе выражение касается покорности (инкияд), второй основы религии: «затем будь стойким» — повеление, построенное на вере; поэтому он употребил союз «затем» (сумма), указывающий на порядок с отсрочкой.\nСтойкость (истикама) означает постоянное пребывание на пути прямоты, пути тех, кого облагодетельствовал Аллах: пророков, правдивых, павших мучеников и праведников. Когда человек строит свою жизнь на этих двух основах, он будет жить счастливо в этом мире и в будущем.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-21-Nawawi-Psalmodie-Arabe.mp3',
  5,
  21
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 21
);
