-- =============================================================================
-- 40 Hadith Nawawi — Hadith 22: "The ease of the religion (entering Paradise)"
-- Target collection: public.hadith_collections.id = 2  /  position = 22
-- Idempotent guard on (collection, position). All 11 content languages.
-- NOTE: source tafsir opened with a stray sentence belonging to Hadith 17
-- (ihsan/slaughter); it has been omitted as a paste error.
-- =============================================================================

insert into public.hadiths (
  hadith_collection_id,
  title_en, title_fr, title_ar, title_de, title_nl, title_tr, title_id, title_ur, title_bn, title_ms, title_ru,
  arabic_text,
  transcription_en, transcription_fr, transcription_de, transcription_nl, transcription_tr,
  transcription_id, transcription_ur, transcription_bn, transcription_ms, transcription_ru,
  translation_en, translation_fr, translation_de, translation_nl, translation_tr,
  translation_id, translation_ur, translation_bn, translation_ms, translation_ru,
  reference_en, reference_fr, reference_ar, reference_de, reference_nl, reference_tr,
  reference_id, reference_ur, reference_bn, reference_ms, reference_ru,
  tafsir_en, tafsir_fr, tafsir_ar, tafsir_de, tafsir_nl, tafsir_tr,
  tafsir_id, tafsir_ur, tafsir_bn, tafsir_ms, tafsir_ru,
  audio_url, ajr, position
)
select
  2,
  -- title
  'The ease of the religion',
  'La facilité de la religion',
  'يسر الدين',
  'Die Leichtigkeit der Religion',
  'Het gemak van de religie',
  'Dinin kolaylığı',
  'Kemudahan agama',
  'دین کی آسانی',
  'দ্বীনের সহজতা',
  'Kemudahan agama',
  'Лёгкость религии',
  -- arabic_text
  'عَنْ أَبِي عَبْدِ اللَّهِ جَابِرِ بْنِ عَبْدِ اللَّهِ الْأَنْصَارِيِّ رَضِيَ اللَّهُ عَنْهُمَا أَنَّ رَجُلًا سَأَلَ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَقَالَ: أَرَأَيْتَ إِذَا صَلَّيْتُ الْمَكْتُوبَاتِ، وَصُمْتُ رَمَضَانَ، وَأَحْلَلْتُ الْحَلَالَ، وَحَرَّمْتُ الْحَرَامَ، وَلَمْ أَزِدْ عَلَى ذَلِكَ شَيْئًا، أَأَدْخُلُ الْجَنَّةَ؟ قَالَ: «نَعَمْ»',
  -- transcription
  'ʿan Abī ʿAbdi Llāhi Jābiri bni ʿAbdi Llāhi l-Anṣāriyyi raḍiya Llāhu ʿanhumā anna rajulan saʾala Rasūla Llāhi ṣalla Llāhu ʿalayhi wa-sallama fa-qāla: araʾayta idhā ṣallaytu l-maktūbāti, wa-ṣumtu Ramaḍāna, wa-aḥlaltu l-ḥalāla, wa-ḥarramtu l-ḥarāma, wa-lam azid ʿalā dhālika shayʾan, a-adkhulu l-jannata? qāla: naʿam.',
  'ʿan Abî ʿAbdi Llâhi Jâbiri bni ʿAbdi Llâhi l-Ansâriyyi (radia Llâhou ʿanhoumâ) anna rajoulan saʾala Rassôla Llâhi (salla Llâhou ʿalayhi wa sallam) fa-qâla : araʾayta idhâ sallaytou l-maktôubâti, wa soumtou Ramadâna, wa ahlaltou l-halâla, wa harramtou l-harâma, wa lam azid ʿalâ dhâlika chayʾan, a-adkhoulou l-jannata ? qâla : naʿam.',
  'ʿan Abī ʿAbdi Llāhi Dschābiri bni ʿAbdi Llāhi l-Ansārijji (radiya Llāhu ʿanhumā) anna radschulan saʾala Rasūla Llāhi (salla Llāhu ʿalaihi wa-sallam) fa-qāla: araʾaita idhā sallaitu l-maktūbāti, wa-sumtu Ramadāna, wa-ahlaltu l-halāla, wa-harramtu l-harāma, wa-lam azid ʿalā dhālika schaiʾan, a-adchulu l-dschannata? qāla: naʿam.',
  'ʿan Abie ʿAbdi Llaahi Dzjaabiri bni ʿAbdi Llaahi l-Ansaarijji (radia Llaahoe ʿanhoemaa) anna radzjoelan saʾala Rasoela Llaahi (salla Llaahoe ʿalaihi wa-sallam) fa-qaala: araʾaita idhaa sallaitoe l-maktoebaati, wa-soemtoe Ramadaana, wa-ahlaltoe l-halaala, wa-harramtoe l-haraama, wa-lam azid ʿalaa dhaalika sjaiʾan, a-adchoeloe l-dzjannata? qaala: naʿam.',
  'an Ebû Abdillâh Câbir ibn Abdillâh el-Ensârî''den (radıyallâhu anhümâ): bir adam Resûlullah''a (s.a.v.) sordu ve dedi ki: ne dersin, farz namazları kılsam, Ramazan orucunu tutsam, helali helal sayıp haramı haram bilsem ve buna hiçbir şey eklemesem, cennete girer miyim? Buyurdu: evet.',
  'ʿan Abī ʿAbdillah Jabir bin ʿAbdillah al-Anshari (radhiyallāhu ʿanhumā) bahwa seorang lelaki bertanya kepada Rasulullah (shallallāhu ʿalaihi wa sallam) lalu berkata: bagaimana pendapatmu jika aku mengerjakan shalat-shalat fardhu, berpuasa Ramadhan, menghalalkan yang halal, mengharamkan yang haram, dan aku tidak menambah atas itu sedikit pun, apakah aku masuk surga? Beliau menjawab: ya.',
  'ابو عبد اللہ جابر بن عبد اللہ الانصاری رضی اللہ عنہما سے روایت ہے کہ ایک شخص نے رسول اللہ صلی اللہ علیہ وسلم سے پوچھا: بتائیے، اگر میں فرض نمازیں پڑھوں، رمضان کے روزے رکھوں، حلال کو حلال اور حرام کو حرام جانوں، اور اس پر کچھ زیادہ نہ کروں، تو کیا میں جنت میں داخل ہو جاؤں گا؟ آپ نے فرمایا: ہاں۔',
  'আবু আবদিল্লাহ জাবির ইবনে আবদিল্লাহ আল-আনসারী (রাদিয়াল্লাহু আনহুমা) থেকে বর্ণিত যে এক ব্যক্তি রাসূলুল্লাহ (সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম)-কে জিজ্ঞাসা করল: বলুন তো, যদি আমি ফরজ সালাতসমূহ আদায় করি, রমজানের সিয়াম পালন করি, হালালকে হালাল ও হারামকে হারাম জানি, এবং এর উপর কিছু না বাড়াই, তবে কি আমি জান্নাতে প্রবেশ করব? তিনি বললেন: হ্যাঁ।',
  'ʿan Abī ʿAbdillah Jabir bin ʿAbdillah al-Ansari (radhiallāhu ʿanhumā) bahawa seorang lelaki bertanya kepada Rasulullah (sallallāhu ʿalaihi wa sallam) lalu berkata: bagaimana pendapatmu jika aku mengerjakan solat-solat fardu, berpuasa Ramadan, menghalalkan yang halal, mengharamkan yang haram, dan aku tidak menambah atas itu sedikit pun, adakah aku masuk syurga? Baginda menjawab: ya.',
  'Ан Аби Абдиллях Джабир ибн Абдиллях аль-Ансари (да будет доволен Аллах ими обоими), что один человек спросил Посланника Аллаха ﷺ и сказал: скажи мне, если я буду совершать предписанные молитвы, поститься в Рамадан, считать дозволенным дозволенное и запретным запретное и ничего к этому не прибавлю, войду ли я в Рай? Он сказал: да.',
  -- translation
  'On the authority of Abu ʿAbd Allah Jabir ibn ʿAbd Allah al-Ansari (may Allah be pleased with them both): A man asked the Messenger of Allah ﷺ and said: "Do you think that if I perform the obligatory prayers, fast Ramadan, treat the lawful as lawful and the unlawful as unlawful, and add nothing to that, I will enter Paradise?" He said: "Yes."',
  'D''après Abû ʿAbd Allah Jâbir ibn ʿAbd Allah al-Ansârî (qu''Allah les agrée tous deux) : Un homme interrogea l''Envoyé d''Allah ﷺ et dit : « Vois-tu, si j''accomplis les prières prescrites, si je jeûne le Ramadan, si je rends licite ce qui est licite et illicite ce qui est illicite, sans rien ajouter à cela, entrerai-je au Paradis ? » Il répondit : « Oui. »',
  'Nach Abu ʿAbd Allah Jabir ibn ʿAbd Allah al-Ansari (möge Allah mit beiden zufrieden sein): Ein Mann fragte den Gesandten Allahs ﷺ und sagte: „Meinst du, wenn ich die Pflichtgebete verrichte, im Ramadan faste, das Erlaubte für erlaubt und das Verbotene für verboten halte und nichts darüber hinaus hinzufüge, werde ich ins Paradies eintreten?" Er sagte: „Ja."',
  'Op gezag van Abu ʿAbd Allah Jabir ibn ʿAbd Allah al-Ansari (moge Allah tevreden met hen beiden zijn): Een man vroeg de Boodschapper van Allah ﷺ en zei: „Denk je dat, als ik de verplichte gebeden verricht, in de Ramadan vast, het toegestane als toegestaan en het verbodene als verboden behandel, en daar niets aan toevoeg, ik het Paradijs zal binnengaan?" Hij zei: „Ja."',
  'Ebû Abdillâh Câbir ibn Abdillâh el-Ensârî''den (Allah her ikisinden de razı olsun): Bir adam Resûlullah''a ﷺ sordu ve dedi ki: „Ne dersin, farz namazları kılsam, Ramazan orucunu tutsam, helali helal sayıp haramı haram bilsem ve buna hiçbir şey eklemesem, cennete girer miyim?" Buyurdu: „Evet."',
  'Dari Abu ʿAbdullah Jabir bin ʿAbdullah al-Anshari (semoga Allah meridhai keduanya): Seorang lelaki bertanya kepada Rasulullah ﷺ dan berkata: "Bagaimana pendapatmu jika aku mengerjakan shalat-shalat fardhu, berpuasa Ramadhan, menghalalkan yang halal dan mengharamkan yang haram, serta tidak menambah sedikit pun atas itu, apakah aku akan masuk surga?" Beliau menjawab: "Ya."',
  'ابو عبد اللہ جابر بن عبد اللہ الانصاری رضی اللہ عنہما سے روایت ہے: ایک شخص نے رسول اللہ ﷺ سے پوچھا: ”بتائیے، اگر میں فرض نمازیں پڑھوں، رمضان کے روزے رکھوں، حلال کو حلال اور حرام کو حرام سمجھوں، اور اس پر کچھ زیادہ نہ کروں، تو کیا میں جنت میں داخل ہو جاؤں گا؟“ آپ نے فرمایا: ”ہاں۔“',
  'আবু আবদিল্লাহ জাবির ইবনে আবদিল্লাহ আল-আনসারী (রাদিয়াল্লাহু আনহুমা) থেকে বর্ণিত: এক ব্যক্তি রাসূলুল্লাহ ﷺ-কে জিজ্ঞাসা করল: "বলুন তো, যদি আমি ফরজ সালাতসমূহ আদায় করি, রমজানের সিয়াম পালন করি, হালালকে হালাল ও হারামকে হারাম গণ্য করি, এবং এর উপর কিছু না বাড়াই, তবে কি আমি জান্নাতে প্রবেশ করব?" তিনি বললেন: "হ্যাঁ।"',
  'Daripada Abu ʿAbdullah Jabir bin ʿAbdullah al-Ansari (semoga Allah meredai keduanya): Seorang lelaki bertanya kepada Rasulullah ﷺ dan berkata: "Bagaimana pendapatmu jika aku mengerjakan solat-solat fardu, berpuasa Ramadan, menghalalkan yang halal dan mengharamkan yang haram, serta tidak menambah sedikit pun atas itu, adakah aku akan masuk syurga?" Baginda menjawab: "Ya."',
  'Со слов Абу ʿАбдиллаха Джабира ибн ʿАбдиллаха аль-Ансари (да будет доволен Аллах ими обоими): Один человек спросил Посланника Аллаха ﷺ и сказал: «Скажи мне, если я буду совершать предписанные молитвы, поститься в Рамадан, считать дозволенным дозволенное и запретным запретное и ничего к этому не прибавлю, войду ли я в Рай?» Он сказал: «Да».',
  -- reference
  'Sahih — reported by Muslim (no. 15)',
  'Hadith authentique rapporté par Muslim (n°15)',
  'حديث صحيح، رواه مسلم (رقم ١٥)',
  'Sahih — überliefert von Muslim (Nr. 15)',
  'Sahih — overgeleverd door Muslim (nr. 15)',
  'Sahih — Müslim (no. 15) rivayet etmiştir',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 15)',
  'صحیح حدیث، اسے مسلم (نمبر ۱۵) نے روایت کیا',
  'সহীহ হাদীস — মুসলিম (নং ১৫) বর্ণনা করেছেন',
  'Hadis sahih, diriwayatkan oleh Muslim (no. 15)',
  'Достоверный хадис, передал Муслим (№ 15)',
  -- tafsir
  '"Do you think that if I perform the obligatory prayers": the obligatory prayers are the five daily prayers and the Friday prayer. "…and fast Ramadan": Ramadan is the month between Shaʿban and Shawwal. "…treat the lawful as lawful" — that is, doing it with the conviction that it is lawful in the Sacred Law. "…and the unlawful as unlawful" — that is, avoiding it with the conviction that it is religiously unlawful.\nIn this hadith, the zakat and the pilgrimage (Hajj) were not mentioned. This may have two explanations:\n— It may be supposed that these two obligations are included in his words "treat the unlawful as unlawful," for abandoning the pilgrimage is unlawful and refusing to give the zakat is also unlawful.\n— It may also be said, regarding the pilgrimage, that perhaps this hadith occurred before the pilgrimage was prescribed; and regarding the zakat, perhaps the Prophet ﷺ knew that this man was poor and not among those liable to pay zakat, so he gave him answers suited to his situation.',
  '« Vois-tu, si j''accomplis les prières prescrites » : les prières prescrites sont les cinq prières quotidiennes et la prière du Vendredi. « …si je jeûne le Ramadan » : le Ramadan est le mois situé entre Shaʿbân et Shawwâl. « …si je rends licite ce qui est licite » : c''est-à-dire le faire en ayant la conviction que c''est licite selon la Loi. « …et illicite ce qui est illicite » : c''est-à-dire l''éviter en ayant la conviction que c''est illicite selon la religion.\nDans ce hadith, l''aumône (Zakât) et le pèlerinage (Hajj) n''ont pas été cités. Cela peut avoir deux explications :\n— On peut supposer que ces deux obligations entrent dans sa parole « je rends illicite ce qui est illicite », car l''abandon du pèlerinage est illicite et refuser de donner l''aumône est aussi illicite.\n— On peut dire aussi, concernant le pèlerinage, que peut-être ce hadith a eu lieu avant la prescription du pèlerinage ; et concernant l''aumône légale, peut-être que le Prophète ﷺ savait que cet homme était pauvre, n''entrant pas dans la catégorie des gens assujettis à la Zakât, et il lui a donné des réponses adaptées à sa situation.',
  '«أرأيت إذا صليت المكتوبات»: المكتوبات هي الصلوات الخمس وصلاة الجمعة. «وصمت رمضان»: ورمضان هو الشهر الواقع بين شعبان وشوال. «وأحللت الحلال»: أي فعله معتقداً أنه حلال شرعاً. «وحرمت الحرام»: أي اجتنابه معتقداً أنه حرام شرعاً.\nوفي هذا الحديث لم تُذكر الزكاة ولا الحج. ولهذا تفسيران:\n— يمكن أن يُفترض دخول هاتين الفريضتين في قوله «وحرمت الحرام»، فإن ترك الحج حرام، والامتناع عن الزكاة حرام أيضاً.\n— ويمكن أن يقال أيضاً في الحج: لعل هذا الحديث كان قبل فرض الحج؛ وأما الزكاة، فلعل النبي صلى الله عليه وسلم علم أن هذا الرجل فقير لا يدخل في عداد المكلفين بالزكاة، فأعطاه أجوبة تناسب حاله.',
  '„Meinst du, wenn ich die Pflichtgebete verrichte": die Pflichtgebete sind die fünf täglichen Gebete und das Freitagsgebet. „…und im Ramadan faste": der Ramadan ist der Monat zwischen Schaʿban und Schawwal. „…das Erlaubte für erlaubt halte" — das heißt, es zu tun mit der Überzeugung, dass es im Gesetz erlaubt ist. „…und das Verbotene für verboten" — das heißt, es zu meiden mit der Überzeugung, dass es religiös verboten ist.\nIn diesem Hadith wurden die Zakat und die Pilgerfahrt (Hadsch) nicht erwähnt. Dafür gibt es zwei Erklärungen:\n— Man kann annehmen, dass diese beiden Pflichten in seinen Worten „das Verbotene für verboten halte" enthalten sind, denn das Unterlassen der Pilgerfahrt ist verboten und die Verweigerung der Zakat ist ebenfalls verboten.\n— Man kann auch sagen, hinsichtlich der Pilgerfahrt: vielleicht ereignete sich dieser Hadith vor der Vorschreibung der Pilgerfahrt; und hinsichtlich der Zakat: vielleicht wusste der Prophet ﷺ, dass dieser Mann arm war und nicht zu den Zakat-Pflichtigen gehörte, und gab ihm daher Antworten, die seiner Lage entsprachen.',
  '„Denk je dat, als ik de verplichte gebeden verricht": de verplichte gebeden zijn de vijf dagelijkse gebeden en het vrijdaggebed. „…en in de Ramadan vast": de Ramadan is de maand tussen Sjaʿban en Sjawwal. „…het toegestane als toegestaan behandel" — dat wil zeggen het doen met de overtuiging dat het volgens de Wet toegestaan is. „…en het verbodene als verboden" — dat wil zeggen het mijden met de overtuiging dat het religieus verboden is.\nIn deze hadith werden de zakat en de bedevaart (Hadj) niet genoemd. Hiervoor zijn twee verklaringen:\n— Men kan aannemen dat deze twee verplichtingen besloten liggen in zijn woorden „het verbodene als verboden behandel," want het nalaten van de bedevaart is verboden en het weigeren van de zakat is eveneens verboden.\n— Men kan ook zeggen, wat de bedevaart betreft: misschien vond deze hadith plaats vóór het voorschrijven van de bedevaart; en wat de zakat betreft: misschien wist de Profeet ﷺ dat deze man arm was en niet behoorde tot hen die zakat verschuldigd zijn, en gaf hij hem daarom antwoorden die bij zijn situatie pasten.',
  '„Ne dersin, farz namazları kılsam": farz namazlar, beş vakit namaz ile cuma namazıdır. „Ramazan orucunu tutsam": Ramazan, Şaban ile Şevval arasındaki aydır. „Helali helal saysam" — yani onu, şer''an helal olduğuna inanarak yapmak. „Haramı haram bilsem" — yani onu, dinen haram olduğuna inanarak terk etmek.\nBu hadiste zekât ve hac zikredilmemiştir. Bunun iki açıklaması olabilir:\n— Bu iki farzın, onun „haramı haram bilsem" sözüne dahil olduğu varsayılabilir; zira haccı terk etmek haramdır, zekât vermekten kaçınmak da haramdır.\n— Hac hakkında şöyle de denilebilir: belki bu hadis, haccın farz kılınmasından önceydi; zekâta gelince, belki Peygamber ﷺ bu adamın fakir olduğunu, zekâtla yükümlü olanlar arasına girmediğini biliyordu da ona durumuna uygun cevaplar verdi.',
  '"Bagaimana pendapatmu jika aku mengerjakan shalat-shalat fardhu": shalat-shalat fardhu adalah shalat lima waktu dan shalat Jumat. "Dan berpuasa Ramadhan": Ramadhan adalah bulan yang terletak antara Syaʿban dan Syawal. "Menghalalkan yang halal" — yaitu melakukannya dengan keyakinan bahwa itu halal secara syariat. "Dan mengharamkan yang haram" — yaitu menjauhinya dengan keyakinan bahwa itu haram secara agama.\nDalam hadis ini, zakat dan haji tidak disebutkan. Hal ini memiliki dua penjelasan:\n— Dapat diandaikan bahwa kedua kewajiban ini termasuk dalam ucapannya "mengharamkan yang haram," karena meninggalkan haji adalah haram, dan enggan menunaikan zakat juga haram.\n— Dapat pula dikatakan, mengenai haji: mungkin hadis ini terjadi sebelum haji diwajibkan; dan mengenai zakat: mungkin Nabi ﷺ mengetahui bahwa orang ini fakir, tidak termasuk golongan yang wajib zakat, sehingga beliau memberinya jawaban yang sesuai dengan keadaannya.',
  '”بتائیے، اگر میں فرض نمازیں پڑھوں“: فرض نمازیں پانچ وقت کی نمازیں اور جمعہ کی نماز ہیں۔ ”اور رمضان کے روزے رکھوں“: رمضان شعبان اور شوال کے درمیان کا مہینہ ہے۔ ”اور حلال کو حلال جانوں“: یعنی اسے اس یقین کے ساتھ کرنا کہ یہ شرعاً حلال ہے۔ ”اور حرام کو حرام جانوں“: یعنی اس سے اس یقین کے ساتھ بچنا کہ یہ شرعاً حرام ہے۔\nاس حدیث میں زکوٰۃ اور حج کا ذکر نہیں۔ اس کی دو توجیہیں ہو سکتی ہیں:\n— یہ فرض کیا جا سکتا ہے کہ یہ دونوں فرائض اس کے قول ”حرام کو حرام جانوں“ میں شامل ہیں، کیونکہ حج کا ترک حرام ہے اور زکوٰۃ سے انکار بھی حرام ہے۔\n— حج کے بارے میں یہ بھی کہا جا سکتا ہے کہ شاید یہ حدیث حج کی فرضیت سے پہلے کی ہو؛ اور زکوٰۃ کے بارے میں شاید نبی ﷺ کو معلوم تھا کہ یہ شخص فقیر ہے، زکوٰۃ کے مکلفین میں شامل نہیں، اس لیے آپ نے اسے اس کے حال کے مطابق جواب دیے۔',
  '"বলুন তো, যদি আমি ফরজ সালাতসমূহ আদায় করি": ফরজ সালাত হলো পাঁচ ওয়াক্ত সালাত ও জুমার সালাত। "এবং রমজানের সিয়াম পালন করি": রমজান হলো শাবান ও শাওয়ালের মধ্যবর্তী মাস। "হালালকে হালাল গণ্য করি" — অর্থাৎ এই বিশ্বাসসহ তা করা যে এটি শরীয়তসম্মতভাবে হালাল। "এবং হারামকে হারাম গণ্য করি" — অর্থাৎ এই বিশ্বাসসহ তা এড়িয়ে চলা যে এটি ধর্মীয়ভাবে হারাম।\nএই হাদীসে যাকাত ও হজের উল্লেখ নেই। এর দুটি ব্যাখ্যা হতে পারে:\n— ধরা যেতে পারে যে এই দুটি ফরজ তার "হারামকে হারাম গণ্য করি" কথার মধ্যে অন্তর্ভুক্ত, কারণ হজ ত্যাগ করা হারাম এবং যাকাত দিতে অস্বীকার করাও হারাম।\n— হজের ব্যাপারে এও বলা যায় যে সম্ভবত এই হাদীস হজ ফরজ হওয়ার আগের; আর যাকাতের ব্যাপারে সম্ভবত নবী ﷺ জানতেন যে এই ব্যক্তি দরিদ্র, যাকাতের মুকাল্লাফদের অন্তর্ভুক্ত নয়, তাই তিনি তাকে তার অবস্থার উপযোগী উত্তর দিয়েছেন।',
  '"Bagaimana pendapatmu jika aku mengerjakan solat-solat fardu": solat-solat fardu ialah solat lima waktu dan solat Jumaat. "Dan berpuasa Ramadan": Ramadan ialah bulan yang terletak antara Syaʿban dan Syawal. "Menghalalkan yang halal" — iaitu melakukannya dengan keyakinan bahawa ia halal secara syariat. "Dan mengharamkan yang haram" — iaitu menjauhinya dengan keyakinan bahawa ia haram secara agama.\nDalam hadis ini, zakat dan haji tidak disebut. Hal ini mempunyai dua penjelasan:\n— Boleh diandaikan bahawa kedua-dua kewajipan ini termasuk dalam ucapannya "mengharamkan yang haram," kerana meninggalkan haji adalah haram, dan enggan menunaikan zakat juga haram.\n— Boleh juga dikatakan, mengenai haji: mungkin hadis ini berlaku sebelum haji diwajibkan; dan mengenai zakat: mungkin Nabi ﷺ mengetahui bahawa orang ini fakir, tidak termasuk golongan yang wajib zakat, lalu baginda memberinya jawapan yang sesuai dengan keadaannya.',
  '«Скажи мне, если я буду совершать предписанные молитвы»: предписанные молитвы — это пять ежедневных молитв и пятничная молитва. «И поститься в Рамадан»: Рамадан — это месяц между Шаабаном и Шаввалем. «Считать дозволенным дозволенное» — то есть совершать его с убеждением, что оно дозволено по Шариату. «И запретным запретное» — то есть избегать его с убеждением, что оно запретно по религии.\nВ этом хадисе не упомянуты закят и хадж. Этому есть два объяснения:\n— Можно предположить, что эти две обязанности входят в его слова «считать запретным запретное», ибо оставление хаджа запретно, и отказ от выплаты закята также запретен.\n— Можно также сказать относительно хаджа: возможно, этот хадис был до предписания хаджа; а относительно закята: возможно, Пророк ﷺ знал, что этот человек беден и не относится к обязанным выплачивать закят, и потому дал ему ответы, соответствующие его положению.',
  -- audio_url, ajr, position
  'https://www.40-hadith-nawawi.com/wp-content/uploads/2022/08/Hadith-22-Nawawi-Psalmodie-Arabe.mp3',
  5,
  22
where not exists (
  select 1 from public.hadiths
  where hadith_collection_id = 2 and position = 22
);
