// =============================================================================
// Donation attestation — neutral proof of gift, available in EVERY country.
//
// This is NOT a tax document and says so, in a bordered disclaimer, in its own
// locale. It exists so that a mosque outside a supported tax regime still has
// something useful to hand a donor instead of a dead button, without Nour
// producing a document that could be mistaken for a tax receipt.
// =============================================================================

import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";
import type { ReceiptContext, Renderer } from "./types.ts";
import { Cursor, formatDate, formatMoney, INK, MUTED, PAGE, winAnsi, winAnsiOr } from "./pdf_kit.ts";

interface Strings {
  title: string;
  issuer: string;
  donor: string;
  gifts: string;
  received: string;
  period: string;
  date: string;
  detail: string;
  disclaimer: string;
  issuedOn: string;
  footer: (name: string) => string;
  number: string;
}

const STRINGS: Record<string, Strings> = {
  fr: {
    title: "ATTESTATION DE DON",
    issuer: "Bénéficiaire",
    donor: "Donateur",
    gifts: "Versements",
    received: "Le bénéficiaire reconnaît avoir reçu la somme de :",
    period: "Période : année",
    date: "Date du versement :",
    detail: "Détail des versements",
    disclaimer:
      "Ce document est une simple attestation de don. Il n'ouvre droit à aucune réduction d'impôt " +
      "et ne constitue pas un reçu fiscal.",
    issuedOn: "Fait le",
    footer: (n) => `Document généré par Nour pour le compte de ${n}.`,
    number: "Numéro",
  },
  en: {
    title: "DONATION ATTESTATION",
    issuer: "Recipient",
    donor: "Donor",
    gifts: "Payments",
    received: "The recipient acknowledges having received the amount of:",
    period: "Period: year",
    date: "Date of payment:",
    detail: "Payment details",
    disclaimer:
      "This document is a simple proof of donation. It does not give right to any tax relief and " +
      "is not a tax receipt.",
    issuedOn: "Issued on",
    footer: (n) => `Document generated by Nour on behalf of ${n}.`,
    number: "Number",
  },
  de: {
    title: "SPENDENBESTÄTIGUNG (INFORMELL)",
    issuer: "Empfänger",
    donor: "Spender",
    gifts: "Zahlungen",
    received: "Der Empfänger bestätigt den Erhalt des Betrags von:",
    period: "Zeitraum: Jahr",
    date: "Zahlungsdatum:",
    detail: "Einzelne Zahlungen",
    disclaimer:
      "Dieses Dokument ist eine einfache Spendenbestätigung. Es ist KEINE Zuwendungsbestätigung im " +
      "Sinne des § 50 EStDV und berechtigt nicht zum Spendenabzug.",
    issuedOn: "Ausgestellt am",
    footer: (n) => `Von Nour im Auftrag von ${n} erstellt.`,
    number: "Nummer",
  },
  nl: {
    title: "DONATIEBEVESTIGING",
    issuer: "Ontvanger",
    donor: "Donateur",
    gifts: "Betalingen",
    received: "De ontvanger bevestigt het bedrag te hebben ontvangen van:",
    period: "Periode: jaar",
    date: "Datum van betaling:",
    detail: "Details van de betalingen",
    disclaimer:
      "Dit document is een eenvoudige donatiebevestiging. Het geeft geen recht op belastingaftrek " +
      "en is geen fiscaal ontvangstbewijs.",
    issuedOn: "Afgegeven op",
    footer: (n) => `Document gegenereerd door Nour namens ${n}.`,
    number: "Nummer",
  },
};

function strings(locale: string): Strings {
  return STRINGS[locale.slice(0, 2).toLowerCase()] ?? STRINGS.en;
}

export const attestation: Renderer = {
  templateKey: "generic-attestation",
  templateVersion: "1",

  validate(ctx: ReceiptContext): string[] {
    const missing: string[] = [];
    if (!winAnsi(ctx.issuer.legalName ?? ctx.issuer.name)) missing.push("issuer:legal_name");
    if (!winAnsi(ctx.donor.name)) missing.push("donor:full_name");
    return missing;
  },

  async render(ctx: ReceiptContext): Promise<Uint8Array> {
    const s = strings(ctx.locale);
    const intl = ctx.locale || "en";
    const pdf = await PDFDocument.create();
    const page = pdf.addPage([PAGE.width, PAGE.height]);
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
    const c = new Cursor(page, font, bold);

    pdf.setTitle(`${s.title} ${ctx.number}`);
    pdf.setProducer("Nour");
    pdf.setCreationDate(ctx.issuedAt);

    const i = ctx.issuer;
    const issuerName = winAnsiOr(i.legalName ?? i.name, `Organisation ${i.id}`);

    c.text(s.title, { size: 16, bold: true, gap: 4 });
    c.rule();
    c.text(`${s.number} : ${ctx.number}`, { size: 10.5, bold: true });
    c.space(2);

    c.section(s.issuer);
    c.text(issuerName, { size: 11, bold: true });
    const address = [i.addressLine, [i.postalCode, i.city].filter(Boolean).join(" ")]
      .filter(Boolean)
      .join(", ");
    if (address) c.text(address);
    for (const [key, value] of Object.entries(i.registrations)) {
      if (value) c.text(`${key.toUpperCase()} : ${value}`, { size: 9, color: MUTED, gap: 3 });
    }

    c.section(s.donor);
    c.text(winAnsiOr(ctx.donor.name, "-"), { size: 11, bold: true });
    const donorAddress = [ctx.donor.addressLine, [ctx.donor.postalCode, ctx.donor.city].filter(Boolean).join(" ")]
      .filter(Boolean)
      .join(", ");
    if (donorAddress) c.text(donorAddress);
    if (ctx.donor.email) c.text(ctx.donor.email, { size: 9, color: MUTED });

    c.section(s.gifts);
    c.text(s.received, { size: 9.5 });
    c.space(2);
    c.text(formatMoney(ctx.total, ctx.currency, intl), { size: 15, bold: true, gap: 4 });
    c.text(
      ctx.single
        ? `${s.date} ${formatDate(ctx.gifts[0].date, intl)}`
        : `${s.period} ${ctx.year} (${ctx.gifts.length})`,
      { size: 9.5 },
    );

    if (!ctx.single && ctx.gifts.length > 1) {
      c.space(6);
      c.text(s.detail, { size: 9.5, bold: true, gap: 4 });
      for (const g of ctx.gifts.slice(0, 24)) {
        c.text(`${formatDate(g.date, intl)}    ${formatMoney(g.amount, ctx.currency, intl)}`, {
          size: 8.5,
          color: MUTED,
          gap: 2,
        });
      }
    }

    // Disclaimer box — the whole point of this document being safe.
    c.space(14);
    const boxTop = c.y;
    const boxHeight = 52;
    page.drawRectangle({
      x: PAGE.margin,
      y: boxTop - boxHeight,
      width: PAGE.width - PAGE.margin * 2,
      height: boxHeight,
      borderColor: rgb(0.75, 0.3, 0.2),
      borderWidth: 1,
      color: rgb(0.99, 0.96, 0.94),
    });
    c.y = boxTop - 18;
    const inner = new Cursor(page, font, bold, c.y);
    inner.paragraph(s.disclaimer, { size: 9, color: rgb(0.55, 0.18, 0.1), width: PAGE.width - PAGE.margin * 2 - 24 });
    c.y = boxTop - boxHeight - 20;

    c.text(`${s.issuedOn} ${formatDate(ctx.issuedAt, intl)}`, { size: 9, color: INK });

    page.drawText(winAnsi(s.footer(issuerName)), {
      x: PAGE.margin,
      y: 50,
      size: 7.5,
      font,
      color: MUTED,
    });
    return await pdf.save();
  },
};
